<?php
/**
 * YAWIK
 *
 * @filesource
 * @license MIT
 * @copyright  2013 - 2018 Cross Solution <http://cross-solution.de>
 */

$user = $this->auth()->getUser();

if (!$user) { return; }

$productWrapper = $user->getAttachedEntity(\Gastro24\Entity\UserProduct::class);

if (!$productWrapper) { return; }

$product = $productWrapper->getProduct();
// HINT: currently only 1 package
//$name    = str_replace('Gastro24\Entity\Product\\', '', get_class($product));
$name = 'Flatrate für 12 Monate (CHF 595.-)';
$jobDraftsCount = $this->gastroJobDraftsCount($user);
$inactiveJobCount = $product->getInactiveJobCount();
$activeJobCount = $product->getJobCount();
?>
<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Ihr gewähltes Produkt: <?=$name?></h3>
    </div>

    <table class="table table-striped">
        <tbody>
        <tr>
            <td>
                Start:
            </td>
            <td>
                <?=$this->dateFormat($product->getStartDate(), IntlDateFormatter::MEDIUM, IntlDateFormatter::NONE)?>
            </td>
        </tr>
        <tr>
            <td>
                Läuft ab am:
            </td>
            <td>
                <?=$this->dateFormat($product->getEndDate(),IntlDateFormatter::MEDIUM, IntlDateFormatter::NONE)?>
            </td>
        </tr>
        <tr>
            <td>geschaltete Anzeigen:</td>
            <td>
                Sie haben
                <a style="text-decoration: underline" href="<?= $this->url('lang/jobs', array(), array(), true)?>">
                    <?=$activeJobCount?>
                    <?php if ($limit = $product->getAvailableJobAmount()): ?> von <?=$limit?><?php endif ?> Jobs
                </a> inseriert
                <?php if ($jobDraftsCount && $product->getInactiveJobCount()) {
                    if ($jobDraftsCount == 1) {
                        echo '(davon ' . $inactiveJobCount . ' inaktiv, ' . $jobDraftsCount . ' Entwurf)';
                    }
                    else {
                        echo '(davon ' . $inactiveJobCount . ' inaktiv, ' . $jobDraftsCount . ' Entwürfe)';
                    }
                }
                ?>
                <?php if ($jobDraftsCount && !$inactiveJobCount) {
                    if ($jobDraftsCount == 1) {
                        echo '(' . $jobDraftsCount . ' Entwurf)';
                    }
                    else {
                        echo '(' . $jobDraftsCount . ' Entwürfe)';
                    }
                }
                ?>
                <?php if (!$jobDraftsCount && $inactiveJobCount): ?>
                    (davon <?=$inactiveJobCount?> inaktiv)
                <?php endif ?>
            </td>
        </tr>
        </tbody>
    </table>
</div>

