<script type="application/ld+json">
    {
        "@context": "https://schema.org",
        "@type": "Organization",
        "name": "Gastrojob24",
        "url": "https://www.gastrojob24.ch",
        "logo": "https://www.gastrojob24.ch/modules/Gastro24/gastrojob24_blue.svg",
        "foundingDate": "2008",
        "founders": [
            {
                "@type": "Person",
                "name": "Marc Bösch"
            }
        ],
        "address": {
            "@type": "PostalAddress",
            "streetAddress": "Weidlistrasse 49",
            "addressLocality": "Ettenhausen",
            "addressRegion": "Thurgau",
            "postalCode": "8356",
            "addressCountry": "Switzerland"
        },
        "contactPoint": {
            "@type": "ContactPoint",
            "contactType": "customer support",
            "telephone": "+41 77 484 03 78",
            "email": "info@gastrojob24.ch"
        },
        "sameAs": [
            "https://www.facebook.com/gastrojob24.ch/"
        ]}
</script>

<script type="application/ld+json">
    {
        "@context": "http://schema.org",
        "@type": "WebSite",
        "url": "https://www.gastrojob24.ch",
        "potentialAction": {
            "@type": "SearchAction",
            "target": "https://www.gastrojob24.ch/de/jobs?q={search_term_string}",
            "query-input": "required name=search_term_string"
        }
    }
</script>