<?php echo $this->doctype(); ?>
<html lang="<?php echo $this->params('lang') ?>">

<head prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# website: http://ogp.me/ns/website#">
   <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="<?= $this->basePath('dist/css/core.min.css') ?>">
    <link rel="stylesheet" type="text/css" href="<?= $this->basePath($this->asset('dist/css/jquery-ui-1-12.min.css')) ?>">
    <link rel="stylesheet" type="text/css" href="<?= $this->basePath($this->asset('modules/Gastro24/Gastro24.css')) ?>">

    <style>
    @media (min-width: 1200px) {
        .container {
            width: 1200px;
        }
    }

media (min-width: 992px) {

.col-md-3 {
    padding-left:8px;
    padding-right:8px;
}

}


    </style>


    <title>Jobs inserieren wo Fachkräfte sind - Gastrojob24</title>
    <meta name="description" content="Jobs inserieren bei Gastrojob24. Mit einem Klick tausende Jobsuchende aus Hotel und Gastronomie erreichen. Jetzt inserieren!">


 <meta name="msvalidate.01" content="2A03FA2A5360A355DD3ECEB3DF29DFA3" />
    <script>
        var lang = "de";
        var basePath = "";
    </script>
    <link rel="dns-prefetch" href="https://www.google.com">
    <link rel="dns-prefetch" href="https://www.googletagmanager.com">
    <link rel="dns-prefetch" href="https://www.google-analytics.com">

    <!-- Google Tag Manager -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-125791873-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];

        function gtag() {
            dataLayer.push(arguments);
        }
        gtag('js', new Date());
        gtag('config', 'UA-125791873-1');
        gtag('config', 'AW-980688466');
    </script>

    <!-- End Google Tag Manager -->


    <script type="text/javascript">
        window.GUMLET_CONFIG = {
            hosts: [{
                current: "gastrojob24.ch",
                gumlet: "gastrojob24.gumlet.io"
            }],
            lazy_load: true,
            srcset: true,
            auto_webp: true
        };
        (function() {
            d = document;
            s = d.createElement("script");
            s.src = "https://cdn.gumlet.com/gumlet.js/2.0/gumlet.min.js";
            s.async = 1;
            d.getElementsByTagName("head")[0].appendChild(s);
        })();
    </script>





<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-125791873-1');
  gtag('config', 'AW-980688466');

</script>
    <!-- End Google Tag Manager -->


<script type=application/ld+json>
    {
        "@context": "https://schema.org",
        "@type": "FAQPage",
        "mainEntity": [{
            "@type": "Question",
            "name": "Wieso ist Gastrojob24 so günstig?",
            "acceptedAnswer": {
                "@type": "Answer",
                "text": "<p>Unsere Kunden sprechen uns oft auf die günstigen Inserate-Preise an. Unsere Mission ist es, alle Unternehmen mit einem transparenten Full-Service rund um die Rekrutierung von geeigneten Fachkräften zu unterstützen - ohne Abstriche in der Leistung und Reichweite machen zu müssen. Darum können wir so günstig sein:</p> \t\t\t  <ol> \t\t\t\t<li>Job-Boostings können auf Wunsch optional dazu gebucht werden - das reduziert den Basispreis.</li> \t\t\t\t<li>Schlanke und hocheffiziente Prozesse reduzieren unseren Administrations- und Personalaufwand.</li> \t\t\t\t<li>Wir setzen auf organisches Wachstum und geben wenig Geld für zusätzliche Werbung aus - zufriedene Kunden sind daher unser Motor.</li> \t\t\t\t<li>Unsere Jobportal ist für Branchen-Fachkräfte - das bedeutet kein Streuverlust sondern konzentriertes Targeting.</li>   </ol>"
            }
        }, {
            "@type": "Question",
            "name": "Erscheint mein Job-Inserat auf Google for Jobs?",
            "acceptedAnswer": {
                "@type": "Answer",
                "text": "<p>Ja. Ihr Stelleninserat ist automatisch so optimiert, dass es bei Google Jobs möglichst weit oben gelistet wird. Wir gehen aber noch einen Schritt weiter: um sicherzustellen, dass Ihr Stelleninserat auch wirklich mit den richtigen Keywords von Bewerbern gefunden wird, überprüfen und optimieren wir individuell jedes Einzelinserat («Premium») von einem SEO-Experten mit Expertise im Bereich Recruiting. Das ist schweizweit einzigartig.</p>"
            }
        },{
            "@type": "Question",
            "name": "Gibt es ein Job Flatrate-Abonnement?",
            "acceptedAnswer": {
                "@type": "Answer",
                "text": "<p>Ja. Wir bieten Job-Flatrate-Abonnements für 12 Monate zu sehr attraktiven Konditionen an. Mit diesem können Sie so viele Stellen inserieren, wie Sie möchten. Interessiert? <a href='https://www.gastrojob24.ch/de/contact.html'>Kontaktieren Sie uns</a> oder rufen Sie uns an: +41 77 484 03 78. </p>"
            }
        }, {
            "@type": "Question",
            "name": "Gibt es Angebote für Personalvermittler?",
            "acceptedAnswer": {
                "@type": "Answer",
                "text": "<p>Ja. Für Personalvermittler oder Unternehmen mit vielen Stellen, bieten wir einen <a href=\"/de/crawler\">Job-Crawler</a> an. Nehmen Sie Kontakt mit auf. Wir finden garantiert die optimale Lösung.</p>"
            }
        }, {
            "@type": "Question",
            "name": "Kann ich Gastrojob24 testen?",
            "acceptedAnswer": {
                "@type": "Answer",
                "text": "<p>Ja. Sie können unser Abonnement 30 Tage lang <b>eingeschränkt</b> testen. Wenn Sie nicht zufrieden sind, können Sie ohne Wenn und Aber vom Vertrag zurücktreten.</p>"
            }
        
        }]
    }
</script>
</head>
<body class="landingpage gastro24-controller-redirectexternaljobs-index" id="top">

<header id="header" role="banner">
        <div class="container-fluid">
            <div class="row">
                <div class="navbar-header col-md-2 hidden-xs">
                    <a class="logo" title="Gastrojob24" href="/de">
                        <img src="https://www.gastrojob24.ch/modules/Gastro24/gastrojob24_dark_blue.svg" alt="Gastrojob24">
                    </a>
                </div>
               <a class="visible-xs navbar-brand" href="/">
                        <img src="/modules/Gastro24/gastrojob24_dark_blue.svg" alt="Gastrojob24" class="menu-logo">
                </a>




                <div class="col-md-10 hidden-xs">
                    <ul class="pull-right navbar-nav nav-recruiting">

                        <li class="nav-item">
                            <a title="Jobs" href="/de/jobs?clear=1" class="navigation-link-norm text-white">Jobs suchen</a>
                        </li>
                       
                        <li class="nav-item dropdown">
                            <a title="Anmelden" href="/de/login" class="login-link nav-link text-decoration-none"><i class="login-icon-top"></i>
                                <span>Login</span>
                            </a>
                            
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </header>



<main id="content" class="insert">
    <div class="container">


        <div class="sub-navigation-wrapper"></div>

        <div class="row">




            <h1 class="price-title text-center">Jobs inserieren wo Fachkräfte sind</h1>
            <div class="row-eq-height">


            <div class="col-md-3">
                    <div class="stand-alone-card">
                        <div class="info-card">

                            <h3 class="productlist-h3">Einzelinserat «Free»</h3>

                            <p class="price-productlist">
                                <strong>CHF 0.-&nbsp;</strong>
                                <span class="price-sub-productlist"></span>
                            </p>

                            <p class="text--grey-dark">

                                <br><br>
                            </p>

                            <a href="/de/job/free" class="btn price-btn">Gratis inserieren</a>

                            <hr />

                            <ul class="price-list-check">
                                <li>30 Tage Laufzeit</li>
                        

                                <li>Text-Inserat</li>

                                <li>E-Mail-Versand an Jobmail-Abonnenten</li>

                                <li>Job-Boostings optional dazu buchbar</li>
                 

                            </ul>


                        </div>
                    </div>
                </div>

                <div class="col-md-3">
                    <div class="stand-alone-card">
                        <div class="info-card">

                            <h3 class="productlist-h3">Einzelinserat «Pro»</h3>

                            <p class="price-productlist">
                                <strong>CHF 95.-&nbsp;</strong>
                                <span class="price-sub-productlist"></span>
                            </p>

                            <p class="text--grey-dark">

                                <br><br>
                            </p>

                            <a href="/de/job/single" class="btn price-btn">Jetzt starten</a>

                            <hr />

                            <ul class="price-list-check">
                                <li>30 Tage Laufzeit</li>
                                <li>Aufschaltdatum frei wählbar</li>
                                <li>Datumsaktualisierung nach 15 Tagen</li>
                                <li>Veröffentlichung im <a href="/de/publikationsnetzwerk.html">Publikationsnetzwerk</a></li>

                                <li> PDF- oder Text-Inserat</li>

                                <li> E-Mail-Versand an Jobmail-Abonnenten</li>

                                <li>Job-Boostings optional dazu buchbar</li>
                                 <li>Support via Mail</li>

                            </ul>


                        </div>
                    </div>
                </div>

                <div class="col-md-3">

                    <div class="stand-alone-card top-product">




                        <div class="info-card">
                           
                            <h3 class="productlist-h3">10er Abonnement</h3>

                            <p class="price-productlist">
                                <strong>CHF 895.-&nbsp;</strong>
                                <span class="price-sub-productlist"> </span>
                            </p>
                            <p class="text--grey-dark">
                            Top Preis-Leistung!
                                
                                <br><br>
                            </p>
                            <a href="/de/auth/register" class="btn price-btn">Jetzt starten</a>



                            <p class="neukunden-info"><b>Jetzt für Neukunden!</b><br />
                                30 Tage <a href="/de/geld-zurueck-garantie.html">Geld-zurück-Garantie</a>
                            </p>




                            <hr />

                            <ul class="price-list-check">
                                <li>Laufzeit 12 Monate</li>
                                <li>Datumsaktualisierung nach 15 Tagen</li>
                                <li>Inserate jederzeit änderbar</li>


                                <li>Veröffentlichung im <a href="/de/publikationsnetzwerk.html">Publikationsnetzwerk</a></li>

                                <li> PDF-, Text-Inserate oder iFrame-Weiterleitung</li>

                                <li> E-Mail-Versand an Jobmail-Abonnenten</li>

                                <li>Job-Boostings optional dazu buchbar</li>
                                
                                <li>Persönlicher Support via Mail und Telefon</li>
                            </ul>

                            <br /><br /><br />
                            <hr />


                            <ul class="price-list-check">
                                <li><strong>Firmenprofil</strong></li>
                                <li><strong>Logo-Platzierung auf der Startseite</strong></li>




                            </ul>


                        </div>
                    </div>
                </div>


                <div class="col-md-3">
                    <div class="stand-alone-card">
                        <div class="info-card">

                            <h3 class="productlist-h3">Einzelinserat «Premium»</h3>

                            <p class="price-productlist">
                                <strong>ab CHF 1'295.-&nbsp;</strong>
                                <span class="price-sub-productlist"></span>
                            </p>
                            <p class="text--grey-dark">

                                Für schwierig zu besetzende Stellen
                                <br><br>
                            </p>
                            <a href="/de/premium-job-ads.html" class="btn price-btn">Kontaktieren Sie uns</a>

                            <hr />

                            <ul class="price-list-check">
                                <li>120 Tage Laufzeit</li>
                                <li>Datumsaktualisierung nach 15 Tagen</li>
                                <li>Anzeigenüberprüfung und SEO-Optimierung durch Experte</li>

                                <li>Veröffentlichung im <a href="/de/publikationsnetzwerk.html">Publikationsnetzwerk</a></li>

                                <li>HTML-Template in Ihrem Corporate Design - auf Wunsch mit Video oder Bildergalerie</li>

                                <li> E-Mail-Versand an Jobmail-Abonnenten</li>

                                <li>Google Displaynetzwerk Re-Marketing</li>
                                <li>Facebook und Instagram Re-Marketing</li>
                                <li>Top-Listing Suche und Hervorhebung</li>
                                <li>Top-Listing Startseite</li>
                                <li>Persönlicher Support via Mail und Telefon</li>

                            </ul>


                            <hr />


                            <ul class="price-list-check">


                                <li><strong>Logo-Platzierung auf der Startseite</strong></li>





                            </ul>



                        </div>
                    </div>
                </div>


            </div>





        </div>


        <p class="hint">Keine versteckten Kosten. Keine automatische Abo-Verlängerung. Bezahlung per Rechnung.</p>


        <div class="row">
    
    
    
  <div class="col-md-4">  
      <h3>Job-Erfassungsservice</h3>
      <p>
Sofern wir die Aufschaltung für Sie übernehmen dürfen, kümmert sich das Team von Gastrojob24 um die korrekte Inserierung Ihrer Stellen.</p>

 <p><a style="text-decoration:underline;" href="mailto:info@gastrojob24.ch?Subject=Anfrage zu Erfassungsservice">Jetzt Kontakt aufnehmen</a></p>
      
    </div>
      <div class="col-md-4">  
      <h3>Job-Flatrates</h3>
      <p>
Bereits ab 10 Inseraten pro Jahr bieten wir Ihnen attraktive Flatrate-Modelle. Gerne beraten wir Sie persönlich über die Möglichkeiten.</p>

 <p><a style="text-decoration:underline;" href="mailto:info@gastrojob24.ch?Subject=Anfrage zu Flatrate">Jetzt Kontakt aufnehmen</a></p>
      
    </div>
    
      <div class="col-md-4">  
      <h3>Branding-Optionen</h3>
      <p>
Sie möchten Ihre Stellen speziell hervorheben oder platzieren? Für alle speziellen Wünsche stehen wir Ihnen ebenfalls zur Verfügung.</p>

 <p><a style="text-decoration:underline;" href="mailto:info@gastrojob24.ch?Subject=Anfrage zu Branding-Optionen">Jetzt Kontakt aufnehmen</a></p>
      
    </div></div>


    
        <div class="hidden-xs brands">
            <img src="https://gastrojob24.gumlet.net/modules/Gastro24/images/coop-grey.png" alt="Coop Logo">
            <img src="https://gastrojob24.gumlet.net/modules/Gastro24/images/adecco-grey.png" alt="Adecco Schweiz Logo">
            <img src="https://gastrojob24.gumlet.net/modules/Gastro24/images/mcdonalds-grey.png" alt="McDonalds Schweiz Logo">
            <img src="https://gastrojob24.gumlet.net/modules/Gastro24/images/spruengli-grey.png" alt="Sprüngli Logo">
            <img src="https://gastrojob24.gumlet.net/modules/Gastro24/images/jaegerhof-grey.png" alt="Jägerhof St.Gallen Logo">
            <img src="https://gastrojob24.gumlet.net/modules/Gastro24/images/hiltl-grey.png" alt="Hiltl Logo">
        </div>


        <div class="row">
    <div class="col-md-6 col-xs-12">

        <blockquote>
            <p>
                <strong>Neue Bewerbungen umgehend erhalten</strong>
                <em>«Ein Inserat auf Gastrojob24.ch, und schon erreichten uns Bewerbungen zahlreicher Kandidaten. Die Job-Plattform können wir definitiv weiterempfehlen.»</em> - <strong style="display:inline;">Gastro-Personalvermittler aus Zürich</strong>
            </p>

             <div id="full-stars">
            <div class="rating-group">
                <label aria-label="1 star" class="rating__label" for="rating-1"><i class="rating__icon rating__icon--star fa fa-star"></i></label>
                <input class="rating__input" name="rating" id="rating-1" value="1" type="radio">
                <label aria-label="2 stars" class="rating__label" for="rating-2"><i class="rating__icon rating__icon--star fa fa-star"></i></label>
                <input class="rating__input" name="rating" id="rating-2" value="2" type="radio">
                <label aria-label="3 stars" class="rating__label" for="rating-3"><i class="rating__icon rating__icon--star fa fa-star"></i></label>
                <input class="rating__input" name="rating" id="rating-3" value="3" type="radio" checked="">
                <label aria-label="4 stars" class="rating__label" for="rating-4"><i class="rating__icon rating__icon--star fa fa-star"></i></label>
                <input class="rating__input" name="rating" id="rating-4" value="4" type="radio" checked="">
                <label aria-label="5 stars" class="rating__label" for="rating-5"><i class="rating__icon rating__icon--star fa fa-star"></i></label>
                <input class="rating__input" name="rating" id="rating-5" value="5" type="radio" checked="">


            </div>

        </div>
        </blockquote>

       


    </div>

    <div class="col-md-6 col-xs-12">

        <blockquote>
            <p><strong>Jobsuchmaschine die funktioniert</strong>
                <em>«Beratung und Betreuung durch Herrn Bösch. Absolut zu empfehlen - kompetent und freundlich. Vielen Dank dafür!»</em> - <strong style="display:inline;">Hotelleiterin, Zürich</strong>
            </p><br><br>

               <div id="full-stars">
            <div class="rating-group">


                <label aria-label="1 star" class="rating__label" for="rating-1"><i class="rating__icon rating__icon--star fa fa-star"></i></label>
                <input class="rating__input" name="rating" id="rating-1" value="1" type="radio">
                <label aria-label="2 stars" class="rating__label" for="rating-2"><i class="rating__icon rating__icon--star fa fa-star"></i></label>
                <input class="rating__input" name="rating" id="rating-2" value="2" type="radio">
                <label aria-label="3 stars" class="rating__label" for="rating-3"><i class="rating__icon rating__icon--star fa fa-star"></i></label>
                <input class="rating__input" name="rating" id="rating-3" value="3" type="radio" checked="">
                <label aria-label="4 stars" class="rating__label" for="rating-4"><i class="rating__icon rating__icon--star fa fa-star"></i></label>
                <input class="rating__input" name="rating" id="rating-4" value="4" type="radio">
                <label aria-label="5 stars" class="rating__label" for="rating-5"><i class="rating__icon rating__icon--star fa fa-star"></i></label>
                <input class="rating__input" name="rating" id="rating-5" value="5" type="radio" checked="">


            </div>

        </div>
        </blockquote>

     

    </div>
</div>



    </div>


</main>

<div id="additional-content" class="accordion-section extra-content">
    <div class="container">


        <h2 class="text-center">Häufige Fragen und Antworten</h2>




        <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
            <div class="panel panel-default">
                <div class="panel-heading p-3 mb-3" role="tab" id="heading0">
                    <h3 class="panel-title">
                        <a class="collapsed" role="button" title="" data-toggle="collapse" data-parent="#accordion" href="#collapse0" aria-expanded="true" aria-controls="collapse0">
                            Warum ist Gastrojob24 so günstig?
                        </a>
                    </h3>
                </div>
                <div id="collapse0" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="heading0">
                    <div class="panel-body px-3 mb-4">
                        <p>Unsere Kunden sprechen uns oft auf die günstigen Inserate-Preise an. Unsere Mission ist es, alle Unternehmen mit einem transparenten Full-Service rund um die Rekrutierung von geeigneten Fachkräften zu unterstützen - ohne Abstriche in der Leistung und Reichweite machen zu müssen. Darum können wir so günstig sein:</p>
                        <ol>
                            <li>Job-Boostings können auf Wunsch optional dazu gebucht werden - das reduziert den Basispreis.</li>
                            <li>Schlanke und hocheffiziente Prozesse reduzieren unseren Administrations- und Personalaufwand.</li>
                            <li>Wir setzen auf organisches Wachstum und geben wenig Geld für zusätzliche Werbung aus - zufriedene Kunden sind daher unser Motor.</li>
                            <li>Unsere Jobportal ist für Branchen-Fachkräfte - das bedeutet kein Streuverlust sondern konzentriertes Targeting.</li>


                        </ol>


                    </div>
                </div>
            </div>
             

             <div class="panel panel-default">
                <div class="panel-heading p-3 mb-3" role="tab" id="heading1">
                    <h3 class="panel-title">
                        <a class="collapsed" role="button" title="" data-toggle="collapse" data-parent="#accordion" href="#collapse1" aria-expanded="true" aria-controls="collapse1">
                            Erscheint mein Job-Inserat auf Google for Jobs?
                        </a>
                    </h3>
                </div>
                <div id="collapse1" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading1">
                    <div class="panel-body px-3 mb-4">
                        <p>Ja. Ihr Stelleninserat ist automatisch so optimiert, dass es bei Google for Jobs möglichst weit oben gelistet wird. Wir gehen aber noch einen Schritt weiter: um sicherzustellen, dass Ihr Stelleninserat auch wirklich mit den richtigen Keywords von Bewerbern gefunden wird, überprüfen und optimieren wir individuell jedes Einzelinserat («Premium») von einem SEO-Experten mit Expertise im Bereich Recruiting. Das ist schweizweit einzigartig.</p>
                    </div>
                </div>
            </div>



            <div class="panel panel-default">
                <div class="panel-heading p-3 mb-3" role="tab" id="heading1">
                    <h3 class="panel-title">
                        <a class="collapsed" role="button" title="" data-toggle="collapse" data-parent="#accordion" href="#collapse2" aria-expanded="true" aria-controls="collapse2">
                            Gibt es ein Job Flatrate-Abonnement?
                        </a>
                    </h3>
                </div>
                <div id="collapse2" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading1">
                    <div class="panel-body px-3 mb-4">
                        <p>Ja. Wir bieten Job-Flatrate-Abonnements für 12 Monate zu sehr attraktiven Konditionen an. Mit diesem können Sie so viele Stellen inserieren, wie Sie möchten. Interessiert? <a href="https://www.gastrojob24.ch/de/contact.html">Kontaktieren Sie uns</a> oder rufen Sie uns an: +41 77 484 03 78. </p>
                    </div>
                </div>
            </div>

            <div class="panel panel-default">
                <div class="panel-heading p-3 mb-3" role="tab" id="heading2">
                    <h3 class="panel-title">
                        <a class="collapsed" role="button" title="" data-toggle="collapse" data-parent="#accordion" href="#collapse3" aria-expanded="true" aria-controls="collapse3">
                            Gibt es Angebote für Personalvermittler?
                        </a>
                    </h3>
                </div>
                <div id="collapse3" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading2">
                    <div class="panel-body px-3 mb-4">
                        <p>Ja. Für Personalvermittler oder Unternehmen mit vielen Stellen, bieten wir einen <a href="/de/crawler">Job-Crawler</a> an. Nehmen Sie Kontakt mit uns auf. Wir finden garantiert die optimale Lösung.</p>
                    </div>
                </div>
            </div>

            <div class="panel panel-default">
                <div class="panel-heading p-3 mb-3" role="tab" id="heading3">
                    <h3 class="panel-title">
                        <a class="collapsed" role="button" title="" data-toggle="collapse" data-parent="#accordion" href="#collapse4" aria-expanded="true" aria-controls="collapse4">
                            Kann ich Gastrojob24 testen?
                        </a>
                    </h3>
                </div>
                <div id="collapse4" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading3">
                    <div class="panel-body px-3 mb-4">
                        <p>Ja. Sie können unser Abonnement 30 Tage lang <b>eingeschränkt</b> testen. Wenn Sie nicht zufrieden sind, können Sie ohne Wenn und Aber vom Vertrag zurücktreten.</p>
                    </div>
                </div>
            </div>
        </div>


        <hr />

        <p class="text-center">Sie wünschen eine individuelle Beratung oder möchten mehr über uns erfahren?</p>

        <h2 class="text-center ">Rufen Sie uns an: +41 77 484 03 78</h3>
            <p class="text-center">oder</p>
            <h2 class="text-center ">Nehmen Sie <a style="text-decoration:underline" href="/de/contact.html">Kontakt</a> mit uns auf</h3>





    </div>
</div>





<?php echo $this->partial("footer") ?>
<script type="text/javascript" src="<?= $this->basepath($this->asset('dist/js/core.min.js')) ?>"></script>

</body>

</html>
