<?php echo $this->doctype(); ?>
<html lang="<?php echo $this->params('lang') ?>">

<head prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# website: http://ogp.me/ns/website#">
    <link rel="icon" type="image/png" sizes="32x32" href="/modules/Gastro24/favicons/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/modules/Gastro24/favicons/favicon-16x16.png">
    <link rel="shortcut icon" type="image/ico" href="/modules/Gastro24/favicons/favicon.ico">
    <meta name="msapplication-TileColor" content="#2e5b93">
    <meta name="theme-color" content="#2e5b93">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">


    <link rel="stylesheet" type="text/css" href="<?= $this->basePath('dist/css/core.min.css') ?>">
    <link rel="stylesheet" type="text/css" href="<?= $this->basePath($this->asset('dist/css/jquery-ui-1-12.min.css')) ?>">
    <link rel="stylesheet" type="text/css" href="<?= $this->basePath($this->asset('modules/Gastro24/Gastro24.css')) ?>">


    <title>Gastro Stellen kostenlos inserieren | Gastrojob24</title>
    <meta name="description" content="Gastro Job inserieren bei Gastrojob24. Mit einem Klick tausende Jobsuchende erreichen. Jetzt Stelleninserate schalten: kostenlos - einfach - effizient!">

    <link rel="preconnect" href="https://www.google.com" crossorigin>
    <link rel="dns-prefetch" href="https://www.google.com">
    <link rel="preconnect" href="https://www.googletagmanager.com" crossorigin>
    <link rel="dns-prefetch" href="https://www.googletagmanager.com">
    <link rel="preconnect" href="https://www.google-analytics.com" crossorigin>
    <link rel="dns-prefetch" href="https://www.google-analytics.com">

    <!-- Google Tag Manager -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-125791873-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-125791873-1');
  gtag('config', 'AW-980688466');

</script>
    <!-- End Google Tag Manager -->



</head>
<style>

html {
   scroll-behavior: smooth;
    
}

body {
    background-color: #f2f2f2;
}

.where-your-are {
    margin-top: 0;
    background-repeat: no-repeat;
    background-position: 50%;
    background-size: cover;
    height: 550px;
    display: -webkit-box;
    display: -ms-flexbox;
    display: flex;
    -webkit-box-orient: vertical;
    -webkit-box-direction: normal;
    -ms-flex-direction: column;
    flex-direction: column;
    -webkit-box-pack: center;
    -ms-flex-pack: center;
    justify-content: center;
}

.where-your-are h1 {
    text-align: left;
    color: #fff;
    font-size: 60px;
    font-weight: 700;
    line-height: 75px;
    max-width: 589px;
    margin: 0;
}

.where-your-are h2 {
    margin: 0;
    color: #fff;
    font-size: 40px;
    padding-top: 15px;
}

.navbar {
    position: relative;
    height: 52px;
    margin-bottom: 0;
    border: none;
}

.help-opportunities {
    margin: 30px auto 0;
    max-width: 50%;
    font-size: 16px;
    text-align: center
}

.help-opportunities i {
    display: block;
    margin-bottom: 12px;
    font-size: 32px;
}

.help-header {
    line-height: 52px;
    height: 52px;
    padding-right: 10px;
    padding-left: 10px;
    display: inline-block;
    color: #fff;
}

.help-header a {
    color: #fff;
    text-decoration: underline;
}

.containerHeader {
    padding-top: 40px;
    padding-bottom: 40px;
}

.brands {
    display: -webkit-box;
    display: -ms-flexbox;
    display: flex;
    -webkit-box-pack: center;
    -ms-flex-pack: center;
    justify-content: center;
    -ms-flex-wrap: wrap;
    flex-wrap: wrap;
}

.back-button {
    padding: 8px 16px !important;
    margin-top: 2px;
}

.brands img {
    height: 35px;
    margin: 36px;
}

.brands img {
    width: auto;
}

.reasonWhyPostJob {
    font-size: 16px;
    line-height: 24px;
    color: #fff;
    font-weight: 700;
}

.reasonWhyPostJob i {
    display: block;
    font-size: 32px;
    color: #fff;
    margin-bottom: 5px;
}

.reasonWhyPostJob h2 {
    font-size: 24px;
    color: #fff;
    font-weight: bold;
}

.reasonWhyPostJob .usp i {
    display: block;
    width: 24px;
    margin-right: 20px;
    position: relative;
    top: -3px;
    float: left;
}

.reasonWhyPostJob ul.usp {
    margin: 0;
    padding: 0;
    list-style: none;
    display: flex;
    flex-direction: row;
}

.reasonWhyPostJob ul.usp li {
    margin: 0;
    color: #fff;
    font-size: 17px;
    line-height: 25px;
    font-weight: bold;
    position: relative;
    padding-right: 50px;
    text-align: left;
    display: flex;
}

.postJobScrollButton {
    min-width: 194px;
    border-radius: 8px;
    box-shadow: 0 22px 23px -19px rgba(0, 0, 0, .2);
    font-size: 20px;
    font-weight: 600;
    margin: 20px 0;
    font-weight: 600;
    padding: 12px 24px;
    outline: none;
    cursor: pointer;
    transition: background .2s ease-in-out;
}

button:focus {
    outline: none !important
}

#testimonials {
    background-color: #f2f2f2;
    padding: 20px 0 30px 0;
}

#promote-abos {
    background-color: #fff;
}

#promote-abos hr {
    background-color: #bac4da;
    height: 1px;
    margin: 60px auto;
}

#post-job-help {
    padding: 0 0 20px 0;
}

#promote-abos h3 {
    margin-top: 0px;
    font-size: 22px;
    font-weight: 300;
}
.ecom--sh-productlist strong {
    font-size:18px;
}
.ecom-list {
    position: relative;
    list-style: none inside;
    padding: 0;
}

.ecom-list__item--checked {
    position: relative;
    padding-left: 19px;
}

.ecom-list__item--checked::before {
    content: '\f00c';
    display: block;
    font: normal normal normal 14px/1 FontAwesome;
    font-size: inherit;
    text-rendering: auto;
    -webkit-font-smoothing: antialiased;
    position: absolute;
    margin-left: -20px;
    color: #7aae1a;
    top: 3px;
    font-weight: 100;
}

.subTextMarginBottom {
    margin-bottom: 90px;
}

.full-width-titles h2 {
    margin-bottom: 10px;
    text-align: center;
    color: #0b2235;
    font-size: 24px;
    line-height: 30px;
    font-weight: bold;
}

.link-inverted-post {
    display: inline-block;
    background-color: #ffffff;
    border: 1px solid #243b84;
    color: #243b84;
    font-size: 16px;
    font-weight: 300;
    margin-top: 15px;
    padding: 10px 15px;
}

.link-inverted-post:hover {
    background-color: #19295c;
    color: #ffffff;
    text-decoration: none
}

#why-we {
    padding: 60px 0;
    text-align: center;
}

#why-we h2 {
    margin-top: 0px
}

#why-we p {
    font-size: 16px;
    color: #333;
    line-height: 1.5;
}

#why-we p a {
    text-decoration: underline
}

#why-we img {
    width: 50px;
    margin-bottom: 20px;
    margin-top: 20px;
}

footer {
    padding: 50px 0;
    background-color: #0b2235
}

footer .footer-link {
    padding: 0;
    text-align: center;
    margin: 25px 0;
}

footer .footer-link li {
    display: inline;
    margin: 0 10px;
    color: #fff;
}

footer .footer-link li a {
    color: #fff;
    text-decoration: underline
}

footer .facebook {
    display: block;
    color: #fff;
    font-size: 30px;
    font-weight: 300;
    border: 1px solid #fff;
    width: 50px;
    height: 50px;
    margin: 0 auto;
    line-height: 50px;
}

.dropdown-backdrop {
    background-color: rgba(0, 0, 0, 0.5);
}

.logo {
    margin: 15px 0;
    display: block;
    width: 200px;
}

.logo img {
    width: 100%;
}

#navbar-home-site-links ul {
    list-style-type: none;
    float: left;
    padding-left: 0;
    margin: 0;
}

#navbar-home-site-links ul li {
    display: inline-block;
}

#navbar-home-site-links .navbar-item-anchor {
    line-height: 52px;
    height: 52px;
    padding-right: 10px;
    padding-left: 10px;
    display: inline-block;
    color: #fff;
}

#navbar-home-site-links li:hover {
    background: #0b2235;
}

#navbar-home-site-links li a:hover {
    text-decoration: none;
}

.login-link {
    text-align: center;
    padding: 0 !important;
    display: block;
    height: 38px;
    line-height: 38px !important;
    width: 29px;
    margin: 0;
    font-size: 18px;
    border: none;
    margin-left: 19px;
}

.dropdown-menu-right {
    padding: 0;
}

.yamm-content #login-form-buttons .btn {
    width: 100%;
}

.yamm-content .controls-row.form-group:nth-child(2) {
    margin-bottom: 0px;
}

.nav-recruiting>li>.dropdown-menu {
    margin-top: 15px;
}

.nav-recruiting {
    margin-top: 12px;
    padding: 0;
    list-style: none;
}

.nav-recruiting .btn-danger {
    padding-top: 8px;
    padding-bottom: 8px;
    padding-left: 16px;
    padding-right: 16px;
}

.favorite-icon .link__saved-jobs {
    color: #A5B0BB;
    font-size: 16px;
    display: block;
    height: 52px;
    line-height: 52px;
    width: 50px;
    text-align: center;
}

.favorite-icon {
    margin-right: -15px;
}


.search-form-container {
    padding: 0;
}

.bg-white {
    background: #ffffff !important;
}

.full-background {
    background-size: cover;
    width: 100%;
}

.container-search {
    padding: 50px 0 40px 0;
    float: left;
    width: 100%
}

.tagline-container h1 {
    font-size: 72px;
    line-height: 85px;
    color: #fff;
    max-width: 72%;
    margin-top: 20px;
    font-weight: 600;
}

@media (min-width: 768px) {
    .promote-container {
        max-width: 780px;
       padding: 40px 0 80px 0;
    }
}

@media (max-width: 768px) {
    .reasonWhyPostJob ul.usp li {
        float: left;
        margin-bottom: 15px;
    }
    .reasonWhyPostJob ul.usp {
        display: block;
    }
    .where-your-are h1 {
        font-size: 48px;
        line-height: 52px;
    }
    .where-your-are h2 {
        font-size: 20px;
    }
    .navbar-nav2 {
        left: 0;
        margin: 0;
        position: absolute;
    }
    .navbar-collapse {
        padding-right: 0;
        padding-left: 0;
        float: left;
        border-top: none;
        box-shadow: none;
    }
    .icon-bar {
        background-color: #fff
    }
    .icon-bar {
        display: block;
        margin-bottom: 3px;
        width: 22px;
        height: 2px;
        margin-left: 12px;
        border-radius: 1px;
        -webkit-transition-duration: .35s;
        -moz-transition-duration: .35s;
        -o-transition-duration: .35s;
        transition-duration: .35s
    }
    .middle-bar {
        opacity: 1
    }
    #meta-navigation .open.dropdown-submenu {
        padding: 0;
        border: none;
        border-radius: 0;
        box-shadow: none;
        background: #0b2235 !important
    }
    #meta-navigation .navbar-nav2>.dropdown.open>.dropdown-toggle .middle-bar {
        opacity: 0;
        margin-top: 2px
    }
    #meta-navigation .navbar-nav2>.dropdown.open>.dropdown-toggle .top-bar {
        -ms-transform: rotate(45deg);
        -ms-transform-origin: 15% 10%;
        -webkit-transform: rotate(45deg);
        -webkit-transform-origin: 15% 10%;
        transform: rotate(45deg);
        transform-origin: 15% 10%;
        -webkit-transition-duration: .35s;
        -moz-transition-duration: .35s;
        -o-transition-duration: .35s;
        transition-duration: .35s;
        margin-left: 15px
    }
    #meta-navigation .navbar-nav2>.dropdown.open>.dropdown-toggle .bottom-bar {
        -webkit-transform: rotate(-45deg);
        -webkit-transform-origin: 15% 90%;
        -ms-transform: rotate(-45deg);
        -ms-transform-origin: 15% 90%;
        transform: rotate(-45deg);
        transform-origin: 15% 90%;
        -webkit-transition-duration: .35s;
        -moz-transition-duration: .35s;
        -o-transition-duration: .35s;
        transition-duration: .35s;
        margin-top: 2px;
        margin-left: 15px
    }
    #meta-navigation .navbar-nav2>.dropdown {
        display: table;
    }
    #meta-navigation .navbar-nav2>.dropdown>.dropdown-toggle {
        padding: 0 !important;
        height: 52px;
        width: 48px;
        display: table-cell;
        vertical-align: middle;
    }
    .dropdown-menu>li>a:focus,
    .dropdown-menu>li>a:hover {
        background: #e5e5e5;
        color: #0b2235 !important;
    }
    #meta-navigation .navbar-nav2>li>.dropdown-menu {
        margin-top: 0px;
        border: none;
        min-width: 200px;
        background-color: #0b2235;
        position: absolute;
        left: 0;
        padding: 0;
        border-radius: 0px;
        -webkit-border-radius: 0px;
    }
    #meta-navigation .dropdown-menu>li>a {
        display: block;
        width: 100%;
        padding: 10px 12px 12px;
        color: #fff;
    }
    .navbar-nav2>.dropdown>.dropdown-toggle:hover {
        background-color: #0b2235
    }
    .navbar-nav2>.dropdown.open>.dropdown-toggle {
        background-color: #0b2235
    }
    #meta-navigation .dropdown-submenu:not(.open)>a:focus,
    #meta-navigation .dropdown-submenu:not(.open)>a:hover {
        background: #e5e5e5;
        color: #0b2235 !important
    }
    .icon-bar {
        display: block;
        margin-bottom: 3px;
        width: 22px;
        height: 2px;
        margin-left: 12px;
        border-radius: 1px;
        -webkit-transition-duration: .35s;
        -moz-transition-duration: .35s;
        -o-transition-duration: .35s;
        transition-duration: .35s;
        background-color: #fff;
    }
    .envelope-icon {
        width: 46px;
        position: absolute;
        right: 0;
        height: 52px;
        text-align: center;
        line-height: 52px;
    }
    .envelope-icon a {
        color: #A5B0BB;
        font-size: 18px;
        display: block;
        height: 52px;
        line-height: 52px;
        cursor: pointer;
    }
    .envelope-icon a:hover {
        color: #fff;
    }
}

@media (max-width: 468px) {
    #menu {
        padding-left: 0px!important
    }
    a.facebook {
        text-align: center;
    }
    #why-we {
        padding: 20px 12px;
    }
    .reasonWhyPostJob ul.usp li {
        padding-right: 0;
    }
    .reasonWhyPostJob .usp i {
        top: 0;
        float: none
    }
    .brands img {
        height: 25px;
        margin: 25px;
    }
    .subTextMarginBottom {
        margin-bottom: 30px;
    }
    .text-center,
    .full-width-titles h2 {
        text-align: left;
    }
    .full-width-titles h2 {
        font-size: 21px;
    }
    .where-your-are h1 {
        text-align: left;
        font-size: 26px;
        line-height: 28px;
    }
    .where-your-are h2 {
        font-size: 16px;
    }
    .where-your-are {
        height: 300px;
    }
    .postJobScrollButton {
        border-radius: 4px;
        font-size: 14px;
        margin-bottom: 0px;
    }
    .link-inverted-post {
        display: block
    }
    footer .footer-link li {
        display: block;
        margin: 10px;
    }
}


</style>


<body class="">
    <header id="header" role="banner" class="hidden-xs">
        <div class="container">
            <div class="row">
                <div class="navbar-header col-md-4">
                    <a class="logo" title="Gastrojob24" href="/">
                        <img src="https://www.gastrojob24.ch/modules/Gastro24/gastrojob24_blue.svg" alt="Gastrojob24 Logo">
                    </a>
                </div>



                <div class="col-md-8">

                    <ul class="pull-right navbar-nav nav-recruiting">

                        <li class="nav-item">
                            <a title="Alle Gastro Jobs" href="/de/jobs?clear=1" class="back-button btn btn-default nav-link text-white text-decoration-none">Auf Jobsuche?</a>
                        </li>


                    </ul>

                </div>
            </div>
        </div>
    </header>
    <nav class="navbar-home navbar search-form-container">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="navbar-collapse visible-xs" id="meta-navigation">
                        <ul id="menu" class="nav navbar-nav2">
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <span class="icon-bar top-bar"></span>
                                    <span class="icon-bar middle-bar"></span>
                                    <span class="icon-bar bottom-bar"></span>
                                </a>

                                <ul class="dropdown-menu">


                                    <li>
                                        <a class="navbar-item-anchor" href="#promote-abos">Job-Pakete & Features</a>
                                    </li>
                                    <!--<li>
                                        <a class="navbar-item-anchor" href="#why-we">Darum Gastrojob24</a>
                                    </li>-->



                                </ul>
                            </li>
                            <ul>
                    </div>
                    <a class="visible-xs navbar-brand" href="/">
                        <img src="https://www.gastrojob24.ch/modules/Gastro24/gastrojob24_white.svg" alt="Gastrojob24 Schweiz" class="menu-logo">
                    </a>

                    <!-- menu --->
                    <div id="navbar-home-site-links" class="hidden-xs">
                        <ul>



                            <li>
                                <a class="navbar-item-anchor" href="#promote-abos">Job-Pakete & Features</a>
                            </li>
                           <!-- <li>
                                <a class="navbar-item-anchor" href="#why-we">Darum Gastrojob24</a>
                            </li>-->
                        </ul>
                    </div>
                    <div class="help-header pull-right hidden-xs">
                        <span>Fragen? <a href="mailto:info@gastrojob24.ch">Kontaktieren</a> Sie uns!</span>


                    </div>




                    <div class="envelope-icon pull-right visible-xs">
                        <a href="mailto:info@gastrojob24.ch" class="fa fa-envelope"></a>
                    </div>




                </div>
            </div>
        </div>
    </nav>


    <div class="where-your-are" style="background-image: url('/modules/Gastro24/images/collage3.jpg');">

        <div class="container">

            <div class="row">
                <div class="col-md-12">
                    <h1>Inserieren wo Fachkräfte sind</h1>
                    <h2>Mit einem Klick tausende Job-Suchende erreichen</h2>

                    <a href="/de/job/single" class="postJobScrollButton btn-danger btn btn-default">Gratis Einzelinserat schalten</a>

                </div>
            </div>

        </div>

    </div>
    <div style="background-color:#0b2235">
        <div class="container text-center containerHeader">




            <div class="row reasonWhyPostJob">




                <div class="col-md-12">





                    <ul class="usp">
                        <li>
                            <i>
                                <svg fill="#fff" viewBox="0 0 128 128" width="32px" height="32px">
                                    <path d="M114.156 15.188l-5.469 5.844L43.781 89.97 19.593 66.282l-5.719-5.594L2.686 72.126l5.719 5.594 30.031 29.406 5.844 5.688 5.594-5.938 70.438-74.906 5.5-5.813-11.656-10.969z">
                                    </path>
                                </svg></i>
                            <span>Publizieren Sie kostenlos Stelleninserate für 30 Tage</span>
                        </li>
                        <li>
                            <i>
                                <svg fill="#fff" viewBox="0 0 128 128" width="32px" height="32px">
                                    <path d="M114.156 15.188l-5.469 5.844L43.781 89.97 19.593 66.282l-5.719-5.594L2.686 72.126l5.719 5.594 30.031 29.406 5.844 5.688 5.594-5.938 70.438-74.906 5.5-5.813-11.656-10.969z">
                                    </path>
                                </svg></i>
                            <span>Beste Platzierungen in den Ergebnissen der Google Job Suche</span></span>
                        </li>
                        <li>
                            <i>
                                <svg fill="#fff" viewBox="0 0 128 128" width="32px" height="32px">
                                    <path d="M114.156 15.188l-5.469 5.844L43.781 89.97 19.593 66.282l-5.719-5.594L2.686 72.126l5.719 5.594 30.031 29.406 5.844 5.688 5.594-5.938 70.438-74.906 5.5-5.813-11.656-10.969z">
                                    </path>
                                </svg></i>
                            <span>Seit 2008 beliebt bei Schweizer und internationalen Fachkräften</span>
                        </li>
                    </ul>





                </div>
            </div>

        </div>
    </div>


    <div id="testimonials">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="full-width-titles">
                        <h2 class="full-width-titles text-center">Gastrojob24 besetzt Vakanzen bekannter Marken mit den richtigen Personen</h2>
                        <div class="brands">
                            <img src="<?= $this->basePath('modules/Gastro24/images/coop-grey.png') ?>" alt="Coop Logo">
                            <img src="<?= $this->basePath('modules/Gastro24/images/adecco-grey.png') ?>" alt="Adecco Schweiz Logo">
                            <img src="<?= $this->basePath('modules/Gastro24/images/mcdonalds-grey.png') ?>" alt="McDonalds Schweiz Logo">
                            <img src="<?= $this->basePath('modules/Gastro24/images/coople-grey.png') ?>" alt="Coople Schweiz Logo">
                            <img src="<?= $this->basePath('modules/Gastro24/images/spruengli-grey.png') ?>" alt="Sprüngli Logo">
                            <img src="<?= $this->basePath('modules/Gastro24/images/jaegerhof-grey.png') ?>" alt="Jägerhof St.Gallen Logo">
                            <img src="<?= $this->basePath('modules/Gastro24/images/hiltl-grey.png') ?>" alt="Hiltl Logo">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>



    <div id="promote-abos">
        <div class="promote-container container">
            <div class="row">
                <div class="col-md-12">

                    <div class="text-center subTextMarginBottom full-width-titles">
                        <h2>Job-Pakete und Features für mehr Sichtbarkeit</h2>

                        <p class="postJobSubTitle">Publizieren Sie schnell und unkompliziert Ihre Stellenanzeigen und erreichen Sie gezeilt Fachkräfte aus Gastronomie und Hotellerie -
                            am richtigen Ort und im richtigen Moment. Mit monatlich über 10'000 Inserate-Klicks sprechen wir Stellensuchende aus der Gastronomie-Branche gezielt an.
                            Wählen Sie jetzt das für Sie passende Angebot.
                        </p>

                    </div>
                    <div class="row">

                        <div class="col-md-7 col-sm-7 col-xs-12">
                            <h3>Arbeitgeber Jahres-Job-Flatrate</h3>
                            <p>Für alle, die alles möchten - ohne Kompromisse eingehen zu müssen. 
                            Die Job-Flatrate für 12 Monate ist exklusiv unseren registrierten Arbeitgebern vorbehalten und beinhaltet unter anderem:</p>


                            <ul class="ecom-list">
                                <li class="ecom-list__item ecom-list__item--checked">Unlimitierte Anzahl Jobs schalten</li>
                                <li class="ecom-list__item ecom-list__item--checked">Bewerbermanagement mit Dashboard und Verwaltung</li>
                                <li class="ecom-list__item ecom-list__item--checked">Individuelle Inserate-Laufzeit</li>
                                <li class="ecom-list__item ecom-list__item--checked">Einzelne Jobs direkt von Ihrer Webseite einbinden</li>
                                <li class="ecom-list__item ecom-list__item--checked">Permanente Logopräsenz auf der Startseite</li>
                            </ul>

                            <p class="ecom--sh-productlist">

                                nur <strong>CHF 595.–</strong>
                            </p>

                            <a title="Jahres-Job-Flatrate" href="/de/auth/register?pt=plus" class="link-inverted-post">
                                Jetzt registrieren für Jahres-Job-Flatrate
                            </a>


                        </div>




                        <div class="col-md-5 col-sm-5 col-xs-12">
                            <img class="img-responsive" src="<?= $this->basePath('modules/Gastro24/images/position.png') ?>" class="pull-right" alt="Job-Flatrate 12 Monate ">

                        </div>





                    </div>

                    <hr />


                    <div class="row">


                        <div class="col-md-5 col-sm-5 col-xs-12">
                            <img class="img-responsive" src="<?= $this->basePath('modules/Gastro24/images/crawler.png') ?>" class="pull-left" alt="Job Crawler">

                        </div>
                        <div class="col-md-7 col-sm-7 col-xs-12">
                            <h3>Job-Crawler</h3>

                            <p>Verfügt Ihre Website über eine grössere Anzahl an Stellenanzeigen und möchten Sie diese in Ihrem individuellen Design automatisch bei Gastrojob24 integrieren?
                                Dann ist unser Job-Crawler die richtige Lösung für Sie.</p>



                            <ul class="ecom-list">
                                <li class="ecom-list__item ecom-list__item--checked">Keine Extra-Programmierung notwendig</li>
                                <li class="ecom-list__item ecom-list__item--checked">Bilder und Logos gemäss Ihren CD/CI-Vorgaben</li>
                                <li class="ecom-list__item ecom-list__item--checked">Individuelles HTML-Template nach Ihren Wünschen</li>
                            </ul>


                            <a href="/de/crawler" class="link-inverted-post">
                                Jetzt anfragen
                            </a>

                        </div>





                    </div>


                    <hr />


                    <div class="row">



                        <div class="col-md-7 col-sm-7 col-xs-12">
                            <h3>Branding & Job-Boostings</h3>
                            <p>Sie möchten Fachkräfte noch schneller auf Ihre Stellenanzeigen, Dienstleistungen oder Produkte aufmerksam machen? Nutzen Sie
                                jetzt unsere diversen Online-Werbeflächen und Services für mehr Aufmerksamkeit und Klicks.</p>



                            <a href="/de/branding.html" class="link-inverted-post">
                                Mehr erfahren
                            </a>

                        </div>

                        <div class="col-md-5 col-sm-5 col-xs-12">
                            <img class="img-responsive" src="<?= $this->basePath('modules/Gastro24/images/rocket.png') ?>" class="pull-right" alt="Job Branding Pakete">

                        </div>




                    </div>




                </div>
            </div>
        </div>
    </div>


  <!--<div id="why-we">
        <div class="container">
            <div class="row">
                <div class="col-md-12">



                    <div class="row">
                        <div class="full-width-titles">
                            <h2>Drei sehr gute Gründe, die für uns sprechen</h2>

                            <div style="max-width:65%;margin:0 auto;">

                                <div class="col-md-4 col-sm-6 col-xs-12">

                                    <img alt="Zahlung mit Rechnung" src="<?= $this->basePath('modules/Gastro24/images/rechnung.png') ?>" />

                                    <p>Zahlung einfach & bequem mit Rechnung</p>
                                </div>
                                <div class="col-md-4 col-sm-6 col-xs-12">
                                    <img src="<?= $this->basePath('modules/Gastro24/images/geld-zurueck-garantie.png') ?>" alt="60 Tage Geld-zurück-Garantie" />
                                    <p>60 Tage <a href="/de/geld-zurueck-garantie.html" href="">Geld-zurück-Garantie*</a>
									<small style="display: block;font-size:10px;">*nur für Job-Flatrate</small></p>

                                </div>

                                <div class="col-md-4 col-sm-6 col-xs-12">
                                    <img src="<?= $this->basePath('modules/Gastro24/images/support.png') ?>" alt="Persönlicher Support" />
                                    <p>Persönlicher Support per E-Mail oder Telefon</p>
                                </div>

                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>-->





    <footer>
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <a class="text-center facebook" title="Gastrojob24.ch bei Facebook" href="https://www.facebook.com/gastrojob24.ch/" target="_blank" rel="ugc"><i class="fa fa-facebook"></i></a>


                </div>
                <div class="col-md-12">


                    <ul class="footer-link">

                        <li><a title="Kontakt" href="/de/contact.html">Kontakt</a></li>
                        <li><a title="Impressum" href="/de/impressum.html">Impressum</a></li>
                        <li><a title="Datenschutz" href="/de/datenschutz.html">Datenschutz</a></li>
                        <li><a title="AGB" href="/de/agb.html">AGB</a></li>
                        <li>&copy; 2020 Alle Rechte vorbehalten</li>


                    </ul>

                </div>





            </div>



        </div>
    </footer>

	    <script type="text/javascript" src="<?= $this->basepath($this->asset('dist/js/core.min.js')) ?>"></script>

</body>

</html>