<?php echo $this->doctype(); ?>
<html lang="<?php echo $this->params('lang') ?>">

<head prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# website: http://ogp.me/ns/website#">
   <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="<?= $this->basePath('dist/css/core.min.css') ?>">
    <link rel="stylesheet" type="text/css" href="<?= $this->basePath($this->asset('dist/css/jquery-ui-1-12.min.css')) ?>">
    <link rel="stylesheet" type="text/css" href="<?= $this->basePath($this->asset('modules/Gastro24/Gastro24.css')) ?>">


    <title>Jobs inserieren wo Fachkräfte sind - Gastrojob24</title>
    <meta name="description" content="Jobs schalten bei Gastrojob24. Mit einem Klick tausende Jobsuchende aus Hotel und Gastronomie erreichen. Jetzt inserieren!">


 <meta name="msvalidate.01" content="2A03FA2A5360A355DD3ECEB3DF29DFA3" />
    <script>
        var lang = "de";
        var basePath = "";
    </script>
    <link rel="dns-prefetch" href="https://www.google.com">
    <link rel="dns-prefetch" href="https://www.googletagmanager.com">
    <link rel="dns-prefetch" href="https://www.google-analytics.com">

    <!-- Google Tag Manager -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-125791873-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];

        function gtag() {
            dataLayer.push(arguments);
        }
        gtag('js', new Date());
        gtag('config', 'UA-125791873-1');
        gtag('config', 'AW-980688466');
    </script>

    <!-- End Google Tag Manager -->


    <script type="text/javascript">
        window.GUMLET_CONFIG = {
            hosts: [{
                current: "gastrojob24.ch",
                gumlet: "gastrojob24.gumlet.io"
            }],
            lazy_load: true,
            srcset: true,
            auto_webp: true
        };
        (function() {
            d = document;
            s = d.createElement("script");
            s.src = "https://cdn.gumlet.com/gumlet.js/2.0/gumlet.min.js";
            s.async = 1;
            d.getElementsByTagName("head")[0].appendChild(s);
        })();
    </script>





<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-125791873-1');
  gtag('config', 'AW-980688466');

</script>
    <!-- End Google Tag Manager -->


<script type=application/ld+json>
    {
        "@context": "https://schema.org",
        "@type": "FAQPage",
        "mainEntity": [{
            "@type": "Question",
            "name": "Wieso kann Gastrojob24 so günstig sein?",
            "acceptedAnswer": {
                "@type": "Answer",
                "text": "<p>Unsere Kunden sprechen uns oft auf die günstigen Inseratepreise an. Unsere Mission ist es, alle Unternehmen mit einem transparenten Full-Service rund um die Rekrutierung von geeigneten Fachkräften zu unterstützen - ohne Abstriche in der Leistung und Reichweite machen zu müssen. Darum können wir so günstig sein:</p> \t\t\t  <ol> \t\t\t\t<li>Job-Boostings können auf Wunsch optional dazu gebucht werden - das reduziert den Basispreis.</li> \t\t\t\t<li>Schlanke und hocheffiziente Prozesse reduzieren unseren Administrations- und Personalaufwand.</li> \t\t\t\t<li>Wir setzen auf organisches Wachstum und geben wenig Geld für zusätzliche Werbung aus - zufriedene Kunden sind daher unser Motor.</li> \t\t\t\t<li>Unsere Jobportal ist für Branchen-Fachkräfte - das bedeutet kein Streuverlust bei Ihrer Zielgruppe sondern konzentriertes Targeting.</li>   </ol>"
            }
        }, {
            "@type": "Question",
            "name": "Erscheint mein Job-Inserat auch auf Google Jobs?",
            "acceptedAnswer": {
                "@type": "Answer",
                "text": "<p>Ja. Ihr Stelleninserat wird automatisch so optimiert, dass es bei Google Jobs möglichst weit oben gelistet wird. Wir gehen aber noch einen Schritt weiter: um sicherzustellen, dass Ihr Stelleninserat auch wirklich mit den richtigen Keywords von Bewerbern gefunden wird, überpüfen und optimieren wir jedes Einzelinserat («Premium») von einem SEO-Experten mit Expertise im Bereich Recruiting. Das ist schweizweit einzigartig.</p>"
            }
        }, {
            "@type": "Question",
            "name": "Gibt es Angebote für Personalvermittler?",
            "acceptedAnswer": {
                "@type": "Answer",
                "text": "<p>Ja. Für Personalvermittler oder Unternehmen mit vielen Stellen, bieten wir einen <a href=\"/de/crawler\">Job-Crawler</a> an. Nehmen Sie Kontakt mit auf. Wir finden garantiert die optimale Lösung.</p>"
            }
        }, {
            "@type": "Question",
            "name": "Kann ich Gastrojob24 testen?",
            "acceptedAnswer": {
                "@type": "Answer",
                "text": "<p>Ja. Sie können unser Flatrate-Abonnement 60 Tage lang <b>uneingeschränkt</b> testen. Wenn Sie nicht zufrieden sind, können Sie einfach vom Vertrag zurücktreten. Wir stellen keine Fragen!</p>"
            }
        
        }]
    }
</script>
</head>
<body class="landingpage gastro24-controller-redirectexternaljobs-index" id="top">

<header id="header" role="banner">
        <div class="container-fluid">
            <div class="row">
                <div class="navbar-header col-md-2 hidden-xs">
                    <a class="logo" title="Gastrojob24" href="/de">
                        <img src="https://www.gastrojob24.ch/modules/Gastro24/gastrojob24_dark_blue.svg" alt="Gastrojob24">
                    </a>
                </div>
               <a class="visible-xs navbar-brand" href="/">
                        <img src="/modules/Gastro24/gastrojob24_dark_blue.svg" alt="Gastrojob24" class="menu-logo">
                </a>




                <div class="col-md-10 hidden-xs">
                    <ul class="pull-right navbar-nav nav-recruiting">

                        <li class="nav-item">
                            <a title="Jobs" href="/de/jobs?clear=1" class="navigation-link-norm text-white">Jobs suchen</a>
                        </li>
                       
                        <li class="nav-item dropdown">
                            <a title="Anmelden" href="#" class="login-link nav-link text-reset _dropdown-toggle text-decoration-none" data-toggle="dropdown" aria-expanded="false"><i class="login-icon-top"></i>
                                <span>Login</span>
                            </a>
                            <ul class="dropdown-menu dropdown-menu-right">
                                <li class="nav-item">

                                    <div class="yamm-content login-form-desktop">
                                        <div class="row">
                                            <div class="col-md-12">
                                                <strong class="reveal-form-title"><i class="fa fa-lock"></i> Arbeitgeber-Login</strong>
                                                <div id="form-login-form" class="form-container">
                                                    <div class="form-content">
                                                        <form method="POST" name="login-form" data-handle-by="native" class="&#x20;form-horizontal" action="&#x2F;de&#x2F;login&#x3F;ref&#x3D;&#x25;252Fde&#x25;252Fdashboard&amp;0&#x3D;1" id="login-form">
                                                            <fieldset id="login-form-login-form-credentials">
                                                                <div class="fieldset-content">
                                                                    <div class="controls controls-row form-group">
                                                                        <div class="col-md-12"><input name="credentials&#x5B;login&#x5D;" data-placeholder="E-Mail&#x20;Adresse" placeholder="E-Mail&#x20;Adresse" id="credentials-login" class="&#x20;form-control&#x20;" type="text" value="">
                                                                            <div id="credentials-login-errors" class="errors"></div>
                                                                        </div>
                                                                    </div>
                                                                    <div class="controls controls-row form-group">
                                                                        <div class="col-md-12"><input type="password" name="credentials&#x5B;credential&#x5D;" data-placeholder="Passwort" placeholder="Passwort" id="credentials-credential" class="&#x20;form-control&#x20;" value="">
                                                                            <div id="credentials-credential-errors" class="errors"></div>
                                                                        </div>
                                                                    </div>
                                                                    <div class="controls controls-row form-group">
                                                                        <div class="col-md-12"><input type="hidden" name="credentials&#x5B;csrf&#x5D;" id="credentials-csrf" class="&#x20;form-control&#x20;" value="37cf931d735584567dc466a2c1b41679-d9c007831b17fa3f9706d9091535279e">
                                                                            <div id="credentials-csrf-errors" class="errors"></div>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                            </fieldset>
                                                            <div id="login-form-buttons" class="buttons-bar&#x20;form-group">
                                                                <div class="col-md-offset-3 col-md-9">

                                                                    <input type="submit" name="buttons&#x5B;button&#x5D;" id="submit" class="btn&#x20;btn-primary&#x20;btn-login" value="Einloggen">
                                                                    <div id="submit-errors" class="errors"></div>
                                                                </div>
                                                            </div>

                                                        </form>
                                                    </div>
                                                </div>
                                                <p>
                                                    <a class="link--reset-password" href="#" title="Passwort vergessen?">
                                                        Passwort vergessen? </a>
                                                    <br>Noch kein Konto? <a title="Als Arbeitgeber registrieren" href="/de/auth/register?pt=plus">Registrieren</a>
                                                </p>
                                            </div>
                                        </div>
                                    </div>


                                    <div class="yamm-content reset-form-desktop" style="display: none;">
                                        <div class="row">
                                            <div class="col-md-12">
                                                <strong class="reveal-form-title"><i class="fa fa-lock"></i> Passwort vergessen</strong>
                                                <style>
                                                    #form-forgot-password #forgot-password-identity {
                                                        margin-bottom: 15px;
                                                    }

                                                    .yamm-content .btn-reset {
                                                        color: #fff;
                                                        background-color: #97979D;
                                                        border-color: #97979D;
                                                        width: 100% !important;
                                                    }

                                                    @media only screen and (max-width: 768px) {
                                                        .yamm-content .btn-reset {
                                                            margin-left: 0;
                                                        }
                                                    }

                                                    @media (max-width: 768px) {
                                                        .yamm-content .btn-reset {
                                                            display: block;
                                                            width: 100%;
                                                            height: 34px;
                                                            padding: 6px 12px;
                                                            font-size: 14px;
                                                            line-height: 1.42857143;
                                                        }
                                                    }
                                                </style>

                                                <div id="form-forgot-password" class="form-container">
                                                    <div class="daf-form-container row">
                                                        <div class="daf-form col-md-12">
                                                            <div class="panel panel-default">
                                                                <div class="panel-body">
                                                                    <form method="POST" name="forgot-password" data-handle-by="native" class="&#x20;" action="&#x2F;de&#x2F;forgot-password" id="forgot-password">
                                                                        <div class="controls controls-row row">
                                                                            <div class="col-md-12"><input type="text" name="identity" data-placeholder="Username&#x20;or&#x20;email" placeholder="Benutzername&#x20;oder&#x20;E-Mail" id="forgot-password-identity" class="&#x20;form-control&#x20;" value="">
                                                                                <div id="forgot-password-identity-errors" class="errors"></div>
                                                                            </div>
                                                                        </div>
                                                                        <div class="controls controls-row row">
                                                                            <div class="col-md-12"><input type="hidden" name="csrf" id="forgot-password-csrf" class="&#x20;form-control&#x20;" value="1491777dee5bed0602e587896279600a-0190a452a94a156608ddb6560422b387">
                                                                                <div id="forgot-password-csrf-errors" class="errors"></div>
                                                                            </div>
                                                                        </div>
                                                                        <div class="buttons-bar&#x20;form-group&#x20;row" id="forgot-password-buttons">
                                                                            <div class="col-md-offset-3 col-md-9">

                                                                                <input type="submit" name="buttons&#x5B;button&#x5D;" id="submit" class="btn&#x20;btn-primary&#x20;btn-reset" value="Kennwort&#x20;zur&#xFC;cksetzen">
                                                                                <div id="submit-errors" class="errors"></div>
                                                                            </div>
                                                                        </div>

                                                                    </form>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="daf-desc col-md-12">
                                                            <div class="daf-desc-content alert alert-info">Bitte geben Sie Ihren Benutzernamen oder Ihre E-mail Adresse ein. Sie erhalten per Mail einen Link, um Ihr Kennwort zurückzusetzen</div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>


                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </header>









<main id="content" class="insert">
    <div class="container">


        <div class="sub-navigation-wrapper"></div>

        <div class="row">




            <h1 class="price-title text-center">Jobs schalten wo Fachkräfte sind</h1>
            <div class="row-eq-height">

                <div class="col-md-4">
                    <div class="stand-alone-card">
                        <div class="info-card">

                            <h3 class="productlist-h3">Einzelinserat «Simple»</h3>

                            <p class="price-productlist">
                                <strong>CHF 29.-&nbsp;</strong>
                                <span class="price-sub-productlist">zzgl. MwSt</span>
                            </p>

                            <p class="text--grey-dark">

                                <br><br>
                            </p>

                            <a href="/de/job/single" class="btn price-btn">Inserat schalten</a>

                            <hr />

                            <ul class="price-list-check">
                                <li>30 Tage Laufzeit</li>

                                <li>Datumsaktualisierung nach 15 Tagen</li>
                                <li>Veröffentlichung im <a href="/de/publikationsnetzwerk.html">Publikationsnetzwerk</a></li>

                                <li> PDF- oder HTML-Inserat</li>

                                <li> E-Mail-Versand an >20'000 Jobmail-Abonnenten</li>

                                <li>Job-Boostings optional dazu buchbar</li>

                            </ul>


                        </div>
                    </div>
                </div>

                <div class="col-md-4">

                    <div class="stand-alone-card top-product">




                        <div class="info-card topseller">
                            <span class="span-topseller-default">
                                <b>
                                    BELIEBT
                                </b>
                            </span>
                            <h3 class="productlist-h3">Flatrate-Abonnement «Self»</h3>

                            <p class="price-productlist">
                                <strong>CHF 895.-&nbsp;</strong>
                                <span class="price-sub-productlist">zzgl. MwSt</span>
                            </p>
                            <p class="text--grey-dark">

                                12 Monate unlimitiert Inserate schalten
                                <br><br>
                            </p>
                            <a href="/de/auth/register" class="btn price-btn">Inserat schalten</a>



                            <p class="neukunden-info"><b>Jetzt für Neukunden!</b><br />
                                60 Tage <a href="/de/geld-zurueck-garantie.html">Geld-zurück-Garantie</a>
                            </p>




                            <hr />

                            <ul class="price-list-check">
                                <li>Keine Laufzeit-Beschränkung</li>
                                <li>Datumsaktualisierung nach 15 Tagen</li>



                                <li>Veröffentlichung im <a href="/de/publikationsnetzwerk.html">Publikationsnetzwerk</a></li>

                                <li> PDF- oder HTML-Inserat</li>

                                <li> E-Mail-Versand an >20'000 Jobmail-Abonnenten</li>

                                <li>Job-Boostings optional dazu buchbar</li>

                            </ul>

                            <br /><br /><br />
                            <hr />


                            <ul class="price-list-check">
                                <li><strong>Firmenprofil</strong></li>
                                <li><strong>Logo-Platzierung auf der Startseite</strong></li>




                            </ul>


                        </div>
                    </div>
                </div>


                <div class="col-md-4">
                    <div class="stand-alone-card">
                        <div class="info-card">

                            <h3 class="productlist-h3">Einzelinserat «Premium»</h3>

                            <p class="price-productlist">
                                <strong>CHF 1'295.-&nbsp;</strong>
                                <span class="price-sub-productlist">zzgl. MwSt</span>
                            </p>
                            <p class="text--grey-dark">

                                Für schwierig zu besetzende Stellen
                                <br><br>
                            </p>
                            <a href="/de/job/premium-job-ads.html" class="btn price-btn">Inserat schalten</a>

                            <hr />

                            <ul class="price-list-check">
                                <li>120 Tage Laufzeit</li>
                                <li>Datumsaktualisierung nach 15 Tagen</li>
                                <li>Anzeigenüberprüfung und SEO-Optimierung durch Experte</li>

                                <li>Veröffentlichung im <a href="/de/publikationsnetzwerk.html">Publikationsnetzwerk</a></li>

                                <li>HTML-Template in Ihrem Corporate Design - auf Wunsch mit Video oder Bildergalerie</li>

                                <li> E-Mail-Versand an >20'000 Jobmail-Abonnenten</li>

                                <li>Google Displaynetzwerk Re-Marketing</li>
                                <li>Facebook und Instagram Re-Marketing</li>
                                <li>Top-Listing Suche und Hervorhebung</li>
                                <li>Top-Listing Startseite</li>

                            </ul>


                            <hr />


                            <ul class="price-list-check">


                                <li><strong>Logo-Platzierung auf der Startseite</strong></li>





                            </ul>



                        </div>
                    </div>
                </div>


            </div>





        </div>


        <p class="hint">Keine versteckten Kosten. Keine automatische Abo-Verlängerung.</p>



        <div class="brands">
            <img src="https://gastrojob24.gumlet.net/modules/Gastro24/images/coop-grey.png" alt="Coop Logo">
            <img src="https://gastrojob24.gumlet.net/modules/Gastro24/images/adecco-grey.png" alt="Adecco Schweiz Logo">
            <img src="https://gastrojob24.gumlet.net/modules/Gastro24/images/mcdonalds-grey.png" alt="McDonalds Schweiz Logo">
            <img src="https://gastrojob24.gumlet.net/modules/Gastro24/images/spruengli-grey.png" alt="Sprüngli Logo">
            <img src="https://gastrojob24.gumlet.net/modules/Gastro24/images/jaegerhof-grey.png" alt="Jägerhof St.Gallen Logo">
            <img src="https://gastrojob24.gumlet.net/modules/Gastro24/images/hiltl-grey.png" alt="Hiltl Logo">
        </div>

    </div>
</main>

<div id="additional-content" class="accordion-section extra-content">
    <div class="container">


        <h2 class="text-center">Häufige Fragen und Antworten</h2>




        <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
            <div class="panel panel-default">
                <div class="panel-heading p-3 mb-3" role="tab" id="heading0">
                    <h3 class="panel-title">
                        <a class="collapsed" role="button" title="" data-toggle="collapse" data-parent="#accordion" href="#collapse0" aria-expanded="true" aria-controls="collapse0">
                            Wieso kann Gastrojob24 so günstig sein?
                        </a>
                    </h3>
                </div>
                <div id="collapse0" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="heading0">
                    <div class="panel-body px-3 mb-4">
                        <p>Unsere Kunden sprechen uns oft auf die günstigen Inseratepreise an. Unsere Mission ist es, alle Unternehmen mit einem transparenten Full-Service rund um die Rekrutierung von geeigneten Fachkräften zu unterstützen - ohne Abstriche in der Leistung und Reichweite machen zu müssen. Darum können wir so günstig sein:</p>
                        <ol>
                            <li>Job-Boostings können auf Wunsch optional dazu gebucht werden - das reduziert den Basispreis.</li>
                            <li>Schlanke und hocheffiziente Prozesse reduzieren unseren Administrations- und Personalaufwand.</li>
                            <li>Wir setzen auf organisches Wachstum und geben wenig Geld für zusätzliche Werbung aus - zufriedene Kunden sind daher unser Motor.</li>
                            <li>Unsere Jobportal ist für Branchen-Fachkräfte - das bedeutet kein Streuverlust bei Ihrer Zielgruppe sondern konzentriertes Targeting.</li>


                        </ol>


                    </div>
                </div>
            </div>

            <div class="panel panel-default">
                <div class="panel-heading p-3 mb-3" role="tab" id="heading1">
                    <h3 class="panel-title">
                        <a class="collapsed" role="button" title="" data-toggle="collapse" data-parent="#accordion" href="#collapse1" aria-expanded="true" aria-controls="collapse1">
                            Erscheint mein Job-Inserat auch auf Google Jobs?
                        </a>
                    </h3>
                </div>
                <div id="collapse1" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading1">
                    <div class="panel-body px-3 mb-4">
                        <p>Ja. Ihr Stelleninserat wird automatisch so optimiert, dass es bei Google Jobs möglichst weit oben gelistet wird. Wir gehen aber noch einen Schritt weiter: um sicherzustellen, dass Ihr Stelleninserat auch wirklich mit den richtigen Keywords von Bewerbern gefunden wird, überpüfen und optimieren wir jedes Einzelinserat («Premium») von einem SEO-Experten mit Expertise im Bereich Recruiting. Das ist schweizweit einzigartig.</p>
                    </div>
                </div>
            </div>

            <div class="panel panel-default">
                <div class="panel-heading p-3 mb-3" role="tab" id="heading2">
                    <h3 class="panel-title">
                        <a class="collapsed" role="button" title="" data-toggle="collapse" data-parent="#accordion" href="#collapse2" aria-expanded="true" aria-controls="collapse2">
                            Gibt es Angebote für Personalvermittler?
                        </a>
                    </h3>
                </div>
                <div id="collapse2" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading2">
                    <div class="panel-body px-3 mb-4">
                        <p>Ja. Für Personalvermittler oder Unternehmen mit vielen Stellen, bieten wir einen <a href="/de/crawler">Job-Crawler</a> an. Nehmen Sie Kontakt mit auf. Wir finden garantiert die optimale Lösung.</p>
                    </div>
                </div>
            </div>

            <div class="panel panel-default">
                <div class="panel-heading p-3 mb-3" role="tab" id="heading3">
                    <h3 class="panel-title">
                        <a class="collapsed" role="button" title="" data-toggle="collapse" data-parent="#accordion" href="#collapse3" aria-expanded="true" aria-controls="collapse3">
                            Kann ich Gastrojob24 testen?
                        </a>
                    </h3>
                </div>
                <div id="collapse3" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading3">
                    <div class="panel-body px-3 mb-4">
                        <p>Ja. Sie können unser Flatrate-Abonnement 60 Tage lang <b>uneingeschränkt</b> testen. Wenn Sie nicht zufrieden sind, können Sie einfach vom Vertrag zurücktreten. Wir stellen keine Fragen!</p>
                    </div>
                </div>
            </div>
        </div>


        <hr />

        <p class="text-center">Sie wünschen ein individuelle Beratung oder möchten mehr über uns erfahren?</p>

        <h2 class="text-center ">Rufen Sie uns an: +41 77 484 03 78</h3>
            <p class="text-center">oder</p>
            <h2 class="text-center ">Nehmen Sie <a style="text-decoration:underline" href="/de/contact.html">Kontakt</a> mit uns auf</h3>





    </div>
</div>





<?php echo $this->partial("footer") ?>
<script type="text/javascript" src="<?= $this->basepath($this->asset('dist/js/core.min.js')) ?>"></script>

</body>

</html>
