<ul class="<?= ($this->cssClass) ?? 'dropdown-menu pull-right' ?>">
    <li>
        <a href="<?=$this->url('lang/my', array('action' => 'profile', 'lang' => $lang, true)) ?>">
            <span class="yk-icon yk-icon-user fa-fw"></span> <?=$this->translate('My profile')?></a>
    </li>
    <li>
        <a href="<?=$this->url('lang/my', array('action' => 'password', 'lang' => $lang), true) ?>"><span class="yk-icon yk-icon-password fa-fw"></span> <?=$this->translate('Change password')?></a>
    </li>
    <?php if ($this->acl()->isRole(\Auth\Entity\User::ROLE_RECRUITER)): ?>
        <?php

        $user = $this->auth()->getUser(); /* @var $user \Auth\Entity\User */
        $org  = $user->getOrganization();
        if ($org): /* An Anonymous user does not have the OrganizationReference */
            if (!$org->hasAssociation() || $org->isOwner() ):?>
                <li>
                <a href="<?=$this->url('lang/my-organization', array('lang' => $lang)) ?>"><span class="yk-icon fa-building fa-fw"></span> <?php
                    if (!$org->hasAssociation()) {
                        echo $this->translate('Create my organization');
                    } else {
                        $orgName = $org->getOrganizationName();
                        echo sprintf($this->translate('Edit "%s"'), $orgName ? $orgName->getName() : '&lt;unnamed organization&gt;');
                    }
                    ?></a>
                </li><?php endif ?>
        <?php endif; ?>
    <?php endif ?>
    <?php
    if ($switchUserSession->isSwitchedUser): ?>
        <li class="divider"></li>
        <li><a id="su-clear-link" href="<?=$this->url(
                'lang/user-switch',
                [],
                ['query' => ['do' => 'clear']],
                true
            )?>"
               onclick="$.get($(this).attr('href'), function() { window.location.reload(); }); return false;">
                <?=$this->translate('Clear switched user')?></a>
        </li>
    <?php elseif ($this->acl()->isRole(\Auth\Entity\User::ROLE_ADMIN)): ?>
        <li class="divider"></li>
        <li><a id="su-switch-link" href="#switch-user">
                <?=$this->translate('Switch user')?> &hellip;
            </a>
        </li>
        <?php $this->headScript()->captureStart() ?>
        $(function() {
        $('#su-switch-link').click(function(e) {
        var $modal = $('#su-select-dialog');
        $modal.modal({backdrop:false});
        return false;
        }) ;
        });
        <?php $this->headScript()->captureEnd() ?>
    <?php endif ?>
    <li class="divider"></li>
    <li>
        <a href="<?php echo $this->url('auth-logout',array('lang' => $lang)) ?>"><span class="yk-icon yk-icon-logout fa-fw"></span><?php echo $this->translate('Logout')?></a>
    </li>
</ul>