<?php
$formElementManager = $this->services('FormElementManager');
/** @var \Auth\Form\ForgotPassword $form */
$form = $formElementManager->get('Gastro24\Form\ForgotPasswordPopup');
$form->setIsDescriptionsEnabled(true);
$form->setDescription($this->translate('Please enter your username or email address. You will receive a link to create a new password via email.'));
$form->setAttribute('action', $this->url('lang/forgot-password-startpage'));

$deviceCss = ($this->device) ?? 'mobile';
$style = ($this->style) ?? '';
?>


<div class="yamm-content reset-form-<?= $deviceCss ?>" style="<?= $style ?>">
    <div class="row">
        <div class="col-md-12">
            <strong class="reveal-form-title"><i class="fa fa-lock"></i> Passwort vergessen</strong>
            <style>
                #form-forgot-password #forgot-password-identity {
                    margin-bottom: 15px;
                }
                .yamm-content .btn-reset {
                    color: #fff;
                    background-color: #97979D;
                    border-color: #97979D;
                    width: 100%!important;
                }
                @media only screen and (max-width: 768px) {
                    .yamm-content .btn-reset {
                        margin-left: 0;
                    }
                }
                @media (max-width: 768px) {
                    .yamm-content .btn-reset {
                        display: block;
                        width: 100%;
                        height: 34px;
                        padding: 6px 12px;
                        font-size: 14px;
                        line-height: 1.42857143;
                    }
                }
            </style>

            <?php echo $this->popupForm($form, Core\Form\View\Helper\Form::LAYOUT_VERTICAL, [
                'colMd' => '12',
                'descColMd' => '12'
            ]); ?>
        </div>
    </div>
</div>


