<?php
$savedJobsContainer = new \Zend\Session\Container('gastro24_savedjobs');
$savedJobsCount = ($savedJobsContainer->jobs) ? count($savedJobsContainer->jobs) : 0;

if ($this->clear || !$this->filterForm) {
    $form = $this->services('forms.Jobs/JobboardSearch');
    // defines after which element the search button will be placed
    $form->setButtonElement(null);
    $form->setAttribute('data-handle-by', 'native');
    $form->setAttribute('action', $this->url('lang/jobboard', [], true));
}
else {
    $queryParams = $this->params()->fromQuery();

    if ($this->jobs) {
        foreach (array_keys($this->jobs->getFacets()->toArray()) as $facetName):
            if (isset($queryParams['__' . $facetName])) {
                $facetValues = explode('_', $queryParams['__' . $facetName]);
                $facetValues = array_fill_keys($facetValues, '1');
                $queryParams[$facetName] = $facetValues;
            }
            if (isset($queryParams[$facetName])):
                foreach (array_keys($queryParams[$facetName]) as $facetValue):
                    $this->filterForm->add(['type' => 'hidden', 'name' => $facetName . '[' . $facetValue . ']',
                        'attributes' => ['class' => 'facet-param', 'value' => 1]]);
                endforeach;
            endif;
        endforeach;
    }

    $this->filterForm->setButtonElement(null);
    $this->filterForm->setAttribute('data-handle-by', 'native');
    $this->filterForm->setAttribute('action', $this->url('lang/jobboard', [], true));
    $form = $this->filterForm;
}
?>
<?php $this->headScript()->captureStart();?>
    (function($) {
        // prevent duplicated forms
        if ($(window).width() > 767) {
            $('.navbar-search-container-mobile .search-form').remove();
        }
        if ($(window).width() < 767) {
            $('.search-form-container.search-form-container__header .container .search-form').remove();
        }
    })(jQuery);
<?php $this->headScript()->captureEnd();?>

<nav class="navbar yk-toolbar <?= $this->cssClass ?>" id="jobs-list-filter-wrapper">
    <div class="search-form-container search-form-container__header ">
        <div class="container">
            <div class="navbar-collapse" id="meta-navigation">
                
 <ul id="menu" class="nav navbar-nav2">
    <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <span class="icon-bar top-bar"></span>
            <span class="icon-bar middle-bar"></span>
            <span class="icon-bar bottom-bar"></span>
        </a>
        <ul class="dropdown-menu">
            <li class="hidden-sm hidden-md hidden-lg btn-danger"><a href="/lg/stellenanzeigen-schalten">Anzeige schalten</a></li>
            <li><a title="Jobs" href="/de/jobs?clear=1">Jobs</a></li>
            <li><a title="Kontakt" href="/de/contact.html">Kontakt</a></li>
            <li><a title="Über uns" href="/de/ueber-uns.html">Über uns</a></li>
            <li class="abstand dropdown dropdown-submenu">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown2">Beliebte Jobkategorien</a>
                <ul class="dropdown-menu">
                    <li><a href="/de/jobs/lehrstellen-gastronomie.html" title="Lehrstellen">Lehrstellen</a></li>
                    <li><a href="/de/jobs/marketing-sales.html" title="Marketing Jobs">Marketing Jobs</a></li>
                    <li><a href="/de/jobs/studenten.html" title="Studenten Jobs">Studenten Jobs</a></li>
                    <li><a href="/de/jobs/teilzeit.html" title="Teilzeit Jobs">Teilzeit Jobs</a></li>
                    <li><a href="/de/jobs/koch.html" title="Koch Jobs">Koch Jobs</a></li>
                    <li><a href="/de/jobs/kuechenhilfe.html" title="Küchenhilfe Jobs">Küchenhilfe Jobs</a></li>
                    <li><a href="/de/jobs/baecker.html" title="Bäcker Jobs">Bäcker Jobs</a></li>
                    <li><a href="/de/jobs/metzger.html" title="Metzger Jobs">Metzger Jobs</a></li>
                    <li><a href="/de/jobs/barkeeper.html" title="Barkeeper Jobs">Barkeeper Jobs</a></li>
                    <li><a href="/de/jobs/zimmermaedchen.html" title="Zimmermädchen Jobs">Zimmermädchen Jobs</a></li>
                    <li><a href="/de/jobs/restauration.html" title="Restauration Jobs">Restauration Jobs</a></li>
                    <li><a href="/de/jobs/kuechenchef.html" title="Küchenchef Jobs">Küchenchef Jobs</a></li>
                    <li><a href="/de/jobs/barista.html" title="Barista Jobs">Barista Jobs</a></li>
                    <li><a href="/de/jobs/filialleiter.html" title="Filialleiter Jobs">Filialleiter Jobs</a></li>
                    <li><a href="/de/jobs/catering.html" title="Catering Jobs">Catering Jobs</a></li>
                    <li><a href="/de/jobs/jungkoch.html" title="Jungkoch Jobs">Jungkoch Jobs</a></li>
                    <li><a href="/de/jobs/sous-chef.html" title="Sous-Chef Jobs">Sous-Chef Jobs</a></li>
                    <li><a href="/de/jobs/allrounder.html" title="Allrounder Jobs">Allrounder Jobs</a></li>
                </ul>
         </li>
      </li>
    </ul>
  </li>
</ul>
                
            </div><!-- /.navbar-collapse -->

            <a class="visible-xs navbar-brand" href="/">
                <img src="<?= $this->basepath('/modules/Gastro24/gastrojob24_white.svg') ?>" alt="Gastrojob24 Schweiz"
                     class="menu-logo">
            </a>

            <?= $this->searchForm($form, ['q' => 4, 'l' => 4, 'd' => 2]); ?>

            <div class="navbar-always-on collapsed pull-right navbar-item visible-xs search-icon"
                 style="position: absolute; right: 80px; top: 0">
                <span id="navbar-search-toggle" class="fa-search" style="
                cursor: pointer;
                display: block;
                font-weight: 300;
                font-size: 18px;
                color: #A5B0BB;
                height: 52px;
                text-align: center;
                width: 40px;
                padding-top: 13px;
                " data-target="#navbar-search-bar" data-toggle="collapse"></span>
            </div>

            <div class="favorite-icon" style="top: 11px; width: unset;">
                <?php
                $tooltip = ($savedJobsCount) ? (($savedJobsCount == 1) ? $this->translate('1 saved job') :
                    sprintf($this->translate('%s saved jobs'), $savedJobsCount)) : $this->translate('No saved jobs');
                ?>
                <a style="color: #A5B0BB;font-size: 16px;" class="link__saved-jobs empty"
                   href="<?= $this->url('lang/saved-jobs', [], true) ?>"
                   data-toggle="tooltip" data-placement="bottom" title="<?= $tooltip ?>">
                    <!-- <em style="font-style:normal" class="hidden-xs">Merkliste</em>--></a>
            </div>
            <div class="login-icon pull-right visible-xs" data-toggle="dropdown" aria-expanded="false">
                <span class="fa fa-user"></span>
            </div>
            <!-- login content mobile -->
            <div class="dropdown-menu dropdown-menu-mobile">
                <?php if ('guest' == $this->auth('role')): ?>
                    <?= $this->partial('partials/login-popup.phtml'); ?>
                    <?= $this->partial('partials/password-reset.phtml', [
                        'style' => 'display: none;'
                    ]) ?>
                <?php else: ?>
                    <div class="yamm-content logged-in">
                        <div class="row">
                            <div class="col-md-12">
                                <?= $this->partial('partials/logged-in-submenu.phtml', [
                                    'cssClass' => '',
                                    'lang' => $this->params('lang')
                                ]); ?>
                            </div>
                        </div>
                    </div>
                <?php endif; ?>
            </div>
            <!--end login content mobile -->
        </div>
    </div>
</nav>
<div class="container collapse navbar-collapse always-collapse tj-collapse-menu navbar-site-search-bar navbar-search-container navbar-search-container-mobile"
     id="navbar-search-bar">
  <div class="visible-xs">
    <?= $this->searchForm($form, ['q' => 4, 'l' => 4, 'd' => 2]); ?>
  </div>
</div>