<?php if ($this->searchTerm) { ?>
    <nav aria-label="breadcrumb">
        <ol class="hidden-xs breadcrumb" itemscope itemtype="http://schema.org/BreadcrumbList"
            style="background-color:#fff; margin-bottom:0px;border-radius:0;padding:0;font-size:13px">
            <li class="breadcrumb-item" itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">
                <a itemprop="item" href="/">
                    <span itemprop="name">Home</span>
                </a>
                <meta itemprop="position" content="1"/>
            </li>
            
    
            <li class="breadcrumb-item" itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">
                <a itemprop="item" href="/de/jobs?clear=1">
                    <span itemprop="name">Jobs</span>
                </a>
                <meta itemprop="position" content="2"/>
            </li>
            
            
     <?php if ($this->params()->fromRoute('isLandingPage')) : ?>
            <li class="breadcrumb-item active" itemprop="itemListElement" itemscope
                itemtype="http://schema.org/ListItem" aria-current="page">
                
                    <span itemprop="name"> <?= $this->searchTerm ?></span>
                <meta itemprop="position" content="3"/>
            </li>
        <?php endif; ?>
        </ol>
    </nav>
<?php } else if ($this->hasRegion) { ?>

    <nav aria-label="breadcrumb">
        <ol class="hidden-xs breadcrumb" itemscope itemtype="http://schema.org/BreadcrumbList"
            style="background-color:#fff; margin-bottom:0px;border-radius:0;padding:0;font-size:13px">
            <li class="breadcrumb-item" itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">
                <a itemprop="item" href="/">
                    <span itemprop="name">Home</span>
                </a>
                <meta itemprop="position" content="1"/>
            </li>
            <li class="breadcrumb-item" itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">
                <a itemprop="item" href="/de/jobs?clear=1">
                    <span itemprop="name">Jobs</span>
                </a>
                <meta itemprop="position" content="2"/>
            </li>

            <li class="breadcrumb-item active" itemprop="itemListElement" itemscope
                itemtype="http://schema.org/ListItem" aria-current="page">
             
                 <span itemprop="name"> <?= $this->wordpressTitle ?></span>
                
                <meta itemprop="position" content="3"/>
            </li>
        </ol>
    </nav>
    
<?php } else if ($this->hasCity) { ?>
    
    
     <nav aria-label="breadcrumb">
        <ol class="hidden-xs breadcrumb" itemscope itemtype="http://schema.org/BreadcrumbList"
            style="background-color:#fff; margin-bottom:0px;border-radius:0;padding:0;font-size:13px">
            <li class="breadcrumb-item" itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">
                <a itemprop="item" href="/">
                    <span itemprop="name">Home</span>
                </a>
                <meta itemprop="position" content="1"/>
            </li>
            <li class="breadcrumb-item" itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">
                <a itemprop="item" href="/de/jobs?clear=1">
                    <span itemprop="name">Jobs</span>
                </a>
                <meta itemprop="position" content="2"/>
            </li>

            <li class="breadcrumb-item active" itemprop="itemListElement" itemscope
                itemtype="http://schema.org/ListItem" aria-current="page">
             
                 <span itemprop="name"> <?= $this->wordpressTitle ?></span>
                
                <meta itemprop="position" content="3"/>
            </li>
        </ol>
    </nav>
    
    
    
<?php } else { ?>

    <nav aria-label="breadcrumb">
        <ol class="hidden-xs breadcrumb" itemscope itemtype="http://schema.org/BreadcrumbList"
           style="background-color:#fff; margin-bottom:0px;border-radius:0;padding:0;font-size:13px">
            <li class="breadcrumb-item" itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">
                <a itemprop="item" href="/">
                    <span itemprop="name">Home</span>
                </a>
                <meta itemprop="position" content="1"/>
            </li>
            <li class="breadcrumb-item" itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">
                 <span itemprop="name">Jobs</span>
                <meta itemprop="position" content="2"/>
            </li>
        </ol>
    </nav>
<?php }; ?>