<?php
 $location = $this->job->getLocations()->current();

    // no street available, get address from organization (only for abo jobs, single has street)
    // @see https://gitlab.cross-solution.de/YAWIK/Gastro24/-/issues/587
    $useCompanyAddress = false;
    if ($location && !$location->getStreetname()) {
        $useCompanyAddress = true;
    }
    if ($location === false) {
        $useCompanyAddress = true;
    }

    // google maps string
    $googleMapsString = '';
    if ($useCompanyAddress) {
        $googleMapsString .= !empty($this->organizationName) ? $this->organizationName : $this->orgName;
        $googleMapsString .= '+';
    }

    if ($location == '') {
        $googleMapsString .= 'Schweiz';
    }
    elseif ($useCompanyAddress && $this->job->getOrganization()) {
        $orgAddress = $this->job->getOrganization()->getContact();
        $googleMapsString .= $orgAddress->getStreet() . ' ' . $orgAddress->getHouseNumber() . '+' .
            $orgAddress->getCity() . '+' . $orgAddress->getPostalcode() . '+Schweiz';
    } elseif ($location->getCity() && $location->getStreetname() && $location->getPostalcode()) {
        $googleMapsString .= $location->getStreetname() . '+' . $location->getCity() . '+' . $location->getPostalcode() . '+Schweiz';
    } else {
        $googleMapsString .= preg_replace('~\(.*?\)$~', '', (string)$this->job->getLocation());
    }
?>

<div class="visible-xs visible-sm">
    <hr />
    <address>

        <strong>
            <?php
        
            if ($useCompanyAddress) {
                echo (!empty($this->organizationName)) ? $this->organizationName : $this->orgName . '<br>';
            } else {

               echo (!empty($this->organizationName)) ? $this->organizationName : $this->orgName . '<br>';

            }
        ?>
        </strong>
        <?php
           if ($location === false && !$useCompanyAddress) {
                echo $this->translate('Swiss');
            }
            elseif ($useCompanyAddress && $this->job->getOrganization()) {
                $orgAddress = $this->job->getOrganization()->getContact();
                echo $orgAddress->getStreet() . ' ' . $orgAddress->getHouseNumber() . '<br>';
                echo $orgAddress->getPostalcode() . ' ' . $orgAddress->getCity();
            } elseif ($location->getCity() && $location->getStreetname() && $location->getPostalcode()) {
                echo $location->getStreetname() . '<br>';
                echo $location->getPostalcode() . ' ' . $location->getCity();
            } elseif ($location === false) {
                echo $this->translate('Swiss');
            }
            else {
                echo preg_replace('~\(.*?\)$~', '', (string)$this->job->getLocation());
            }
        ?>
    </address>

    <?php if (!$this->preview && $this->job->getTemplateValues()->get('companyWebsite')) : ?>
    <div class="meta-adress">

        <a class="fa fa-angle-right" rel="nofollow" title="<?= $this->organizationName ?>" href="<?= $this->job->getTemplateValues()->get('companyWebsite') ?>"><span>zur Firmenwebsite</span></a>
    </div>

    <?php elseif ($useCompanyAddress && $this->job->getOrganization()) : ?>
<!-- -->
    <div class="meta-adress">
        <a href="tel:<?= $orgAddress->getPhone() ?>" rel="nofollow"><?= $orgAddress->getPhone() ?></a>
        <a class="fa fa-angle-right" href="<?= $orgAddress->getWebsite() ?>" rel="nofollow"><span>zur Firmenwebsite</span></a>
    </div>
    <?php endif ?>

  
  <!-- end visible-xs -->
  </div>

   
<!-- end info-card -->
</div>

<div class="visible-xs visible-sm">
    <div class="iframe-container" style="padding-bottom:50%;">
        <img style="position:absolute;" width="300" data-src="https://maps.googleapis.com/maps/api/staticmap?center=<?= $googleMapsString ?>&language=de&zoom=15&scale=2&size=300x150&maptype=roadmap&key=AIzaSyCoY42r_qqmRmnKdikLHnh3kPcAQePc-0w&format=jpg&visual_refresh=true&markers=size:mid%7Ccolor:0xd9534f%7Clabel:%7C<?= $googleMapsString ?>" alt="Google Map von <?= $googleMapsString ?>">
     <!-- end visible-xs -->
    </div>
  <!-- end iframe-container -->
   <div class="info-card meta-adress" style="margin-top:0px;background-color:#fff;">
     <a class="fa fa-car" style="display:inline;" target="_blank" rel="noopener nofollow"
            href="https://www.google.com/maps/dir//<?= $googleMapsString ?>/"><span>Anfahrtsweg berechnen</span></a>
    </div>
</div>
