<?php
$publishFacetsValues = $this->facets->toArray()['datePublishStart'];
$publishFacetsDayValues = [];
$showLast24Hours = false;
$showLast3Days = false;
$showLast7Days = false;
$showLast30Days = false;

// filter only date values
foreach ($publishFacetsValues as $facetDate => $dateCount) {
    array_push($publishFacetsDayValues, substr($facetDate, 0, strpos($facetDate, "T")));
}
$publishFacetsDayValues = array_unique($publishFacetsDayValues);

foreach ($publishFacetsDayValues as $facetPublishDay) {
    $minutes = abs(strtotime($facetPublishDay . ' ' . date('H:i:s')) - time()) / 60;

    if ($minutes <= 43200) {
        $showLast30Days = true;
    }
    if ($minutes <= 10080) {
        $showLast7Days = true;
    }
    if ($minutes <= 4320) {
        $showLast3Days = true;
    }
    if ($minutes <= 1440) {
        $showLast24Hours = true;
    }
}
?>

<select id="jobDateFilter" name="jobDateFilter" data-searchbox="-1" >
     <option class="date-filter-option" value="all" <?php if($this->dateFilterValue == '') echo 'selected'; ?>>Alle Daten</option>
    
    <?php if ($showLast24Hours): ?>
        <option class="date-filter-option" value="1440" <?php if($this->dateFilterValue == '1440') echo 'selected'; ?>>neuer als 24 h</option>
    <?php endif; ?>
    <?php if ($showLast3Days): ?>
        <option class="date-filter-option" value="4320" <?php if($this->dateFilterValue == '4320') echo 'selected'; ?>>neuer als 3 Tage</option>
    <?php endif; ?>
    <?php if ($showLast7Days): ?>
        <option class="date-filter-option" value="10080" <?php if($this->dateFilterValue == '10080') echo 'selected'; ?>>neuer als 7 Tage</option>
    <?php endif; ?>
    <?php if ($showLast30Days): ?>
        <option class="date-filter-option" value="43200" <?php if($this->dateFilterValue == '43200') echo 'selected'; ?>>neuer als 30 Tage</option>
    <?php endif; ?>
</select>