<?php
/** @var \Gastro24\Options\Landingpages $landingpagesOptions */
$landingpagesOptions = $this->services(\Gastro24\Options\Landingpages::class);
$landingPageCategories = $this->job->getTemplateValues()->get('categories');
$contentProperty = 3;
$locationString = ' ' . \Gastro24\View\Helper\Jobs\JobLocationHelper::getLocationStringForBreadcrumb($this->job);
?>
<div class="sub-navigation-wrapper">
   <nav class="hidden job-detail-breadcrumb-nav" aria-label="breadcrumb">
      <ol class="breadcrumb" itemscope="" itemtype="http://schema.org/BreadcrumbList">
                    <li class="breadcrumb-item" itemprop="itemListElement" itemscope="" itemtype="http://schema.org/ListItem">
                        <a itemprop="item" href="/"> <span itemprop="name">Home</span></a>
                        <meta itemprop="position" content="1">
                    </li>
                    <li class="breadcrumb-item" itemprop="itemListElement" itemscope="" itemtype="http://schema.org/ListItem">
                        <a itemprop="item" href="/de/jobs?clear=1"> <span itemprop="name">Jobs</span></a>
                        <meta itemprop="position" content="2">
                    </li>

                    <?php if ($landingPageCategories) : ?>
                        <!-- build parent breadcrumbs -->
                        <?php
                            foreach ($landingPageCategories as $category) {
                                $catText = $landingpagesOptions->getQueryParameters($category)['q'];

                                echo '<li class="breadcrumb-item" itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">' .
                                    '<a title="' . $catText . ' Jobs" itemprop="item" href="' . $this->url('lang/landingPage', ['q' => $category, 'format' => 'html' ], true) . '">' .
                                    '<span itemprop="name"> ' . $catText . '</span></a>' .
                                    '<meta itemprop="position" content="' . $contentProperty . '"/></li>';

                                $contentProperty++;
                            }
                        ?>
                    <?php endif; ?>
                    <li class="breadcrumb-item" itemprop="itemListElement" itemscope="" itemtype="http://schema.org/ListItem">
                        <span itemprop="name"><?=ucfirst($this->job->getTitle()) . $locationString ?></span>
                        <meta itemprop="position" content="<?= $contentProperty ?>">
                    </li>
                </ol>

  </nav>  

<ul class="pull-right job-pagination">
           <?php if($this->prevJob) : ?>
               <li><a class="navbar-item-anchor" title="<?= $this->prevJob->getTitle() ?>" href="<?= $this->jobUrl($this->prevJob, ['linkOnly' => true ]) ?>"><i class="fa fa-arrow-left"></i> <span class="hidden-xs">Vorherige</span></a></li>
            <?php endif; ?>
            <?php if($this->nextJob) : ?>
                <li><a class="navbar-item-anchor" title="<?= $this->nextJob->getTitle() ?>" href="<?= $this->jobUrl($this->nextJob, ['linkOnly' => true ]) ?>"><span class="hidden-xs">Nächste</span> <i class="fa fa-arrow-right"></i></a></li>
            <?php endif; ?>
        </ul>
 
</div>
