<!-- btn btn-default btn-block company-jobs-btn --->
<div class="job-navigation">
    <div class="" style="float:left;padding:0 15px">
        <?php if($this->hasSession) : ?>
            <a title="<?= $this->backTitle ?>"
               href="<?= $this->lastSearchQueryUrl ?>"
               class="">
                <i class="fa fa-chevron-left"></i> <?= $this->backTitle ?>
            </a>
        <?php else: ?>
            <a title="<?= $this->translate('Back to search') ?>"
               href="/de/jobs?clear=1"
               class="">
                <i class="fa fa-chevron-left"></i> <?= $this->backTitle ?>
            </a>
        <?php endif; ?>
    </div>
    <div class="" style="float:right;padding:0 15px">
        <span <?php if(!$this->prevJob || !$this->nextJob) echo 'class="reverse"' ?>>
            <?php if($this->prevJob) : ?>
                <a title="<?= $this->prevJob->getTitle() ?>"
                   href="<?= $this->jobUrl($this->prevJob, ['linkOnly' => true ]) ?>"
                   class="btn btn-default">
                <i class="fa fa-chevron-left"></i><span class="hidden-xs"><?= $this->translate('Previous Job') ?></span>
            </a>
            <?php endif; ?>

            <?php if($this->nextJob) : ?>
                <a title="<?= $this->nextJob->getTitle() ?>"
                   href="<?= $this->jobUrl($this->nextJob, ['linkOnly' => true ]) ?>"
                   class="btn btn-default">
           <span class="hidden-xs"> <?= $this->translate('Next Job') ?></span><i class="fa fa-chevron-right right-align"></i>
            </a>
            <?php endif; ?>
        </span>
    </div>
</div>