<?php
    $similarCompanyJobs = $this->similarCompanyJobs($this->job);
    $companyName = ($this->job->getCompany(false)) ? $this->job->getCompany(false) : $this->job->getCompany();
    $similarJobTitle = $this->translate('Weitere Jobs') . ' von ' . $companyName;
    $organizationImageCache = $this->services('Organizations\ImageFileCache\Manager');
    $savedJobsContainer = new \Laminas\Session\Container('gastro24_savedjobs');
?>
<?php if (count($similarCompanyJobs)) : ?>

<h2 style="margin-bottom:15px;"><?= $similarJobTitle ?></h2>


                <?php
                /* @var Solr\Entity\JobProxy $similarJob */
                foreach ($similarCompanyJobs as $index => $similarJob):  ?>

                    <?php
                        $defaultLogoUrl = $this->basePath('modules/Gastro24/images/no-company-logo.png');
                        /** @var \Gastro24\Entity\Template $template */
                        $template = $similarJob->getAttachedEntity('gastro24-template');
                        $orgName = $this->jobOrganizationName($similarJob);

                    // get org logo as default
                        $org = $similarJob->getOrganization();

                        if($org && $org->getImages()->notEmpty('images')) {
                            $defaultLogoUrl = $this->basePath($organizationImageCache->getUri($org->getImages()->get('thumbnail')));
                        }
                        $wrapperLogoUrl = $defaultLogoUrl;
                        if ($template && ($logo = $template->getLogo())) {
                            $wrapperLogoUrl = $this->basePath($logo->getUri());
                        }
                        else {
                            $wrapperLogoUrl = $defaultLogoUrl;
                        }
                    ?>
                    
            
       <div class="card box__job-favorite profile-detail">
            <a class="job-logo-link" title="<?=strip_tags($similarJob->getTitle())?>" href="<?= $this->jobUrl($similarJob, ['linkOnly' => true ]) ?>">
                <img class="job-logo" alt="<?= $orgName ?>" src="<?= $wrapperLogoUrl ?>" />
            </a>
            <div class="card__job-content box__action-buttons">
                <!-- favorite button -->
                <?php if (isset($savedJobsContainer->jobs[$similarJob->getId()])) : ?>
                    <button type="button" class="btn btn-default saved"
                            data-text-saved="<?=$this->translate('Marked')?>" data-text-save="<?=$this->translate('Mark')?>" data-job="<?= $similarJob->getId() ?>">
                        <span><?=$this->translate('Marked')?></span>
                    </button>
                <?php else : ?>
                    <button type="button" class="pull-right btn btn-default"
                            data-text-saved="<?=$this->translate('Marked')?>" data-text-save="<?=$this->translate('Mark')?>" data-job="<?= $similarJob->getId() ?>">
                        <span><?=$this->translate('Mark')?></span>
                    </button>
                <?php endif ?>
                <!-- end favorite button -->
                <h2>
                    <a title="<?=strip_tags($similarJob->getTitle())?>" href="<?= $this->jobUrl($similarJob, ['linkOnly' => true ]) ?>"><?=strip_tags($similarJob->getTitle())?></a>
                </h2>
                <div class="card__job-info">
                    <div class="card__job-empname-label"><?= $orgName ?></div>
                    <div class="card__job-location">
                      <?php
                            $location = $similarJob->getLocations()->last();
                            if ($location == '') {
                                echo $this->translate('Swiss');
                            }
                            elseif ($location) {
                                echo $location->getCity() ? $location->getPostalCode() . ' ' . $location->getCity() :
                                preg_replace('~\(.*?\)$~', '', (string) $similarJob->getLocation());
                            }
                            else {
                                echo (string) $similarJob->getLocation();
                            }
                          ?>
                    </div>
                </div>
                <div class="card__job-snippet-logo">
                    <p class="card__job-snippet" dir="auto">
                        <?php
                        $preview = null;
                        if ($similarJob->getTemplateValues()->getIntroduction()) {
                            $preview = substr(strip_tags($similarJob->getTemplateValues()->getIntroduction()), 0 , 215);
                        }
                        elseif($similarJob->getTemplateValues()->get('position')) {
                            $preview = $similarJob->getTemplateValues()->get('position');
                            $preview = str_replace(['<li>', '<strong>', '</strong>', '</u>', '</p>', '</h2>', '<b>', '<u>', '</b>', '<br>', '</h4>','</h3>','</span>','<span>','<div>'], ' ', $preview);
                            $preview = substr(strip_tags($preview), 0 , 215);
                        }
                        elseif ($similarJob->getTemplateValues()->getHtml()) {
                            $preview = $similarJob->getTemplateValues()->getHtml();
                            $preview = str_replace(['<li>', '<strong>', '</strong>', '</u>', '</p>', '</h2>', '<b>', '<u>', '</b>', '<br>', '</h4>','</h3>','</span>','<span>','<div>'], ' ', $preview);
                            $preview = substr(strip_tags($preview), 0 , 215);
                        }
                        if ($preview) {
                            $preview = str_replace('<p>', '', $preview);
                            $preview = str_replace('</p>', '', $preview);
                            $preview   = implode(' ', explode(' ', $preview, -1));
                            $preview .= ' ... ';
                        }
                        ?>
                        <?= $preview ?>
                    </p>
                </div>
                <div class="card_job-short-info">
                    <ul>
                        <li class="type"><?= $this->publishDateFormatter($similarJob) ?></li>
                        <li class="contract"><?php $typeOfContract = $similarJob->getClassifications()->getEmploymentTypes()->__toString() ?:'Vollzeit' ?>
                         <?=$typeOfContract; ?></li>
                    </ul>
                </div>
            </div>
          </div>
            
            
        
         <?php endforeach; ?>
<?php endif; ?>