<?php
    $similarJobs = $this->similarJobs($this->job);

        $location = $this->job->getLocations()->current();
        if ($location == '') {
            $similarJobTitle = $this->translate('Ähnliche Jobs');
        }
        elseif ($location) {
            $jobLocation = $location->getCity() ? $location->getCity() : preg_replace('~\(.*?\)$~', '', (string)$job->getLocation());
            $similarJobTitle = $this->translate('Ähnliche Jobs') . ' in ' . $jobLocation . ' und Umgebung';
        }
        else {
            $jobLocation = preg_replace('~\(.*?\)$~', '', (string)$job->getLocation());
            $similarJobTitle = $this->translate('Ähnliche Jobs') . ' in ' . $jobLocation . ' und Umgebung';
        }

?>
<?php if (count($similarJobs)) : ?>

<h2 style="margin-bottom:15px;"><?= $similarJobTitle ?></h2>
               <?php
                /* @var Solr\Entity\JobProxy $similarJob */
                foreach ($similarJobs as $index => $similarJob):  ?>
                    <?php
                        // check for job external redirect (i.e. coop)
                        $org = $similarJob->getOrganization();
                        $hasJobTemplate = $this->gastroJobTemplate($org);
                        $isIntern = (!$similarJob->getLink() || $hasJobTemplate);
                        $isEmbeddable = $this->gastroIsEmbeddable($similarJob->getLink());
                        $jobHasExternLink = (!$isIntern && !$isEmbeddable);

                        $jobHref = ($jobHasExternLink) ? $similarJob->getLink() : $this->jobUrl($similarJob, ['linkOnly' => true ]);
                    ?>
                    
                    
        <div class="card box__job-favorite profile-detail">
            <a class="job-logo-link" title="<?=strip_tags($similarJob->getTitle())?>" href="<?= $jobHref ?>">
                <img class="job-logo" alt="<?= $this->organizationName ?>" src="<?= $wrapperLogoUrl ?>"" />
            </a>
            <div class="card__job-content box__action-buttons">
            
            

                <h2>
                    <a title="<?=strip_tags($similarJob->getTitle())?>" href="<?= $jobHref ?>"><?=strip_tags($similarJob->getTitle())?></a>
                </h2>
                <div class="card__job-info">
                    <div class="card__job-empname-label"><?= $this->organizationName ?></div>
                    <div class="card__job-location">
                        
                                       <?php
                                            $location = $similarJob->getLocations()->last();
                                            if ($location == '') {
                                                echo $this->translate('Swiss');
                                            }
                                            elseif ($location) {
                                                echo $location->getCity() ? $location->getPostalCode() . ' ' . $location->getCity() :
                                                preg_replace('~\(.*?\)$~', '', (string) $similarJob->getLocation());
                                            }
                                            else {
                                                echo (string) $similarJob->getLocation();
                                            }
                                          ?>
                        
                    </div>
                </div>
                <div class="card__job-snippet-logo">
                    <p class="card__job-snippet" dir="auto">
                    </p>
                </div>
                <div class="card_job-short-info">
                    <ul>
                        <li class="type"><?= $this->publishDateFormatter($job) ?></li>
                        <li class="contract"><?php $typeOfContract = $similarJob->getClassifications()->getEmploymentTypes()->__toString() ?:'Vollzeit' ?>
                         <?=$typeOfContract; ?></li>
                    </ul>
                </div>
            </div>
        </div>
                    
   
 <?php endforeach; ?>
                  
<?php endif; ?>