<?php
    $similarCompanyJobs = $this->similarCompanyJobs($this->job);
    $companyName = ($this->job->getCompany(false)) ? $this->job->getCompany(false) : $this->job->getCompany();
    $similarJobTitle = $this->translate('Weitere Jobs') . ' von ' . $companyName;
?>
<?php if (count($similarCompanyJobs)) : ?>

<h2 style="margin-bottom:15px;"><?= $similarJobTitle ?></h2>


                <?php
                /* @var Solr\Entity\JobProxy $similarJob */
                foreach ($similarCompanyJobs as $index => $similarJob):  ?>
                    
            
       <div class="card box__job-favorite profile-detail">
            <a class="job-logo-link" title="<?=strip_tags($similarJob->getTitle())?>" href="<?= $this->jobUrl($similarJob, ['linkOnly' => true ]) ?>">
                <img class="job-logo" alt="<?= $this->organizationName ?>" src="<?= $wrapperLogoUrl ?>" />
            </a>
            <div class="card__job-content box__action-buttons">
            
            

                <h2>
                    <a title="<?=strip_tags($similarJob->getTitle())?>" href="<?= $this->jobUrl($similarJob, ['linkOnly' => true ]) ?>"><?=strip_tags($similarJob->getTitle())?></a>
                </h2>
                <div class="card__job-info">
                    <div class="card__job-empname-label"><?= $this->organizationName ?></div>
                    <div class="card__job-location">
                      <?php
                                            $location = $similarJob->getLocations()->last();
                                            if ($location == '') {
                                                echo $this->translate('Swiss');
                                            }
                                            elseif ($location) {
                                                echo $location->getCity() ? $location->getPostalCode() . ' ' . $location->getCity() :
                                                preg_replace('~\(.*?\)$~', '', (string) $similarJob->getLocation());
                                            }
                                            else {
                                                echo (string) $similarJob->getLocation();
                                            }
                          ?>
                    </div>
                </div>
                <div class="card__job-snippet-logo">
                    <p class="card__job-snippet" dir="auto">
                    </p>
                </div>
                <div class="card_job-short-info">
                    <ul>
                        <li class="type"><?= $this->publishDateFormatter($job) ?></li>
                        <li class="contract"><?php $typeOfContract = $similarJob->getClassifications()->getEmploymentTypes()->__toString() ?:'Vollzeit' ?>
                         <?=$typeOfContract; ?></li>
                    </ul>
                </div>
            </div>
          </div>
            
            
        
         <?php endforeach; ?>
<?php endif; ?>