<?php
    $similarJobs = $this->similarJobs($this->job);

    /* loop through locations to build similar jobs title */
//    $similarJobLocations = [];
//    foreach ($similarJobs as $index => $similarJob) {
//        $location = $similarJob->getLocations()->last();
//        if ($location == '') {
//            $similarJobLocations[] = $this->translate('Swiss');
//        }
//        elseif ($location && $location->getCity()) {
//            $similarJobLocations[] = $location->getCity();
//        }
//        else {
//            $similarJobLocations[] = (string) $similarJob->getLocation();
//        }
//    }
//    $similarJobLocations = array_unique($similarJobLocations);
//
//    if (count($similarJobLocations) == 1) {
//        $similarJobTitle = $this->translate('Ähnliche Jobs') . ' in ' . $similarJobLocations[0];
//    }
//    elseif (count($similarJobLocations) > 1) {
        $location = $this->job->getLocations()->current();
        if ($location == '') {
            $similarJobTitle = $this->translate('Ähnliche Jobs');
        }
        elseif ($location) {
            $jobLocation = $location->getCity() ? $location->getCity() : preg_replace('~\(.*?\)$~', '', (string)$job->getLocation());
            $similarJobTitle = $this->translate('Ähnliche Jobs') . ' in ' . $jobLocation . ' und Umgebung';
        }
        else {
            $jobLocation = preg_replace('~\(.*?\)$~', '', (string)$job->getLocation());
            $similarJobTitle = $this->translate('Ähnliche Jobs') . ' in ' . $jobLocation . ' und Umgebung';
        }
//    }
//    else {
//        $similarJobTitle = $this->translate('Ähnliche Jobs');
//    }
?>
<?php if (count($similarJobs)) : ?>
<div class="grey-description-container similar-jobs">
    <div class="content">
        <div class="headline"><h2 style="margin-top: 5px; margin-bottom: 20px;font-size: 20px;color: #000;"><?= $similarJobTitle ?></h2></div>
            <div class="row">
                <?php
                /* @var Solr\Entity\JobProxy $similarJob */
                foreach ($similarJobs as $index => $similarJob):  ?>
                    <?php
                        // check for job external redirect (i.e. coop)
                        $org = $similarJob->getOrganization();
                        $hasJobTemplate = $this->gastroJobTemplate($org);
                        $isIntern = (!$similarJob->getLink() || $hasJobTemplate);
                        $isEmbeddable = $this->gastroIsEmbeddable($similarJob->getLink());
                        $jobHasExternLink = (!$isIntern && !$isEmbeddable);

                        $jobHref = ($jobHasExternLink) ? $similarJob->getLink() : $this->jobUrl($similarJob, ['linkOnly' => true ]);
                    ?>
                    
                    <div class="col-md-4 col-sm-12 col-xs-12">
                        <div class="job-box">

                            <a title="<?=strip_tags($similarJob->getTitle())?>" href="<?= $jobHref ?>">
                                <?=strip_tags($similarJob->getTitle())?>
                            </a>

                            <div class="job-short-info">
                                <ul>
                                    <li class="location">
                                        <!-- location -->
                                        <?php
                                            $location = $similarJob->getLocations()->last();
                                            if ($location == '') {
                                                echo $this->translate('Swiss');
                                            }
                                            elseif ($location) {
                                                echo $location->getCity() ? $location->getPostalCode() . ' ' . $location->getCity() :
                                                preg_replace('~\(.*?\)$~', '', (string) $similarJob->getLocation());
                                            }
                                            else {
                                                echo (string) $similarJob->getLocation();
                                            }
                                         ?>
                                        <!-- end location -->
                                    </li>
                                    <li class="type">
                                        <!-- type of contract -->
                                        <?php
                                        $typeOfContract = $similarJob->getClassifications()->getEmploymentTypes()->__toString() ?:'Vollzeit' ?>
                                        <span class="yk-contract yk-<?=$typeOfContract?>"><?=$typeOfContract; ?></span>
                                        <!-- end type of contract -->
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>
    </div>
</div>
<?php endif; ?>