<?php 
/**
 * YAWIK
 * View template for 404 error pages
 * 
 * @copyright (c) 2013 - 2016 Cross Solution (http://cross-solution.de)
 * @license   MIT
 */
/**
 * {{rtd: File not found error page}}
 */
?>

<?php $this->headTitle('404') ?>
<h1><?php echo $this->translate('A 404 error occurred') ?></h1>
<hr/>
<p>Leider konnte die von Ihnen gesuchte Seite nicht gefunden werden. Finden Sie Ihren Traumjob in einer der unten stehenden Kategorien:</p>


<ul class="column">
<li><a href="/de/jobs/hilfskoch.html">Hilfskoch Jobs</a></li>
<li><a href="/de/jobs/alleinkoch.html">Alleinkoch Jobs</a></li>
<li><a href="/de/jobs/baecker.html">Bäcker Jobs</a></li>
<li><a href="/de/jobs/chef-de-rang.html">Chef de Rang Jobs</a></li>
<li><a href="/de/jobs/diaetkoch.html">Diätkoch Jobs</a></li>
<li><a href="/de/jobs/entremetier.html">Entremetier Jobs</a></li>
<li><a href="/de/jobs/filialleiter.html">Filialleiter Jobs</a></li>
<li><a href="/de/jobs/hotelfachmann.html">Hotelfachmann Jobs</a></li>
<li><a href="/de/jobs/jungkoch.html">Jungkoch Jobs</a></li>
<li><a href="/de/jobs/koch.html">Koch Jobs</a></li>
<li><a href="/de/jobs/lebensmitteltechnologe.html">Lebensmitteltechnologe Jobs</a></li>
<li><a href="/de/jobs/metzger.html">Metzger Jobs</a></li>
<li><a href="/de/jobs/office.html">Office Jobs</a></li>
<li><a href="/de/jobs/patissier.html">Patissier Jobs</a></li>
<li><a href="/de/jobs/restauration.html">Restauration Jobs</a></li>
<li><a href="/de/jobs/servicemitarbeiterin.html">Servicemitarbeiterin Jobs</a></li>
<li><a href="/de/jobs/zimmermaedchen.html">Zimmermädchen Jobs</a></li>
<li><a href="/de/jobs/sous-chef.html">Sous-chef Jobs</a></li>
<li><a href="/de/jobs/systemgastronomiefachmann.html">Systemgastronomiefachmann Jobs</a></li>
<li><a href="/de/jobs/chef-de-partie.html">Chef de Partie Jobs</a></li>
<li><a href="/de/jobs/garde-manger.html">Garde Manger Jobs</a></li>
<li><a href="/de/jobs/tournant.html">Tournant Jobs</a></li>
<li><a href="/de/jobs/kellner.html">Kellner Jobs</a></li>
<li><a href="/de/jobs/pizzaiolo.html">Pizzaiolo Jobs</a></li>
<li><a href="/de/jobs/rezeptionistin.html">Rezeptionistin Jobs</a></li>
<li><a href="/de/jobs/konditor-confiseur.html">Konditor Confiseur Jobs</a></li>
<li><a href="/de/jobs/restaurantmanager.html">Restaurant Manager Jobs</a></li>
<li><a href="/de/jobs/ernaehrungsberater.html">Ernährungsberater Jobs</a></li>
<li><a href="/de/jobs/barkeeper.html">Barkeeper Jobs</a></li>
<li><a href="/de/jobs/barista.html">Barista Jobs</a></li>
<li><a href="/de/jobs/sommelier.html">Sommelier Jobs</a></li>
<li><a href="/de/jobs/animation.html">Animateur Jobs</a></li>
<li><a href="/de/jobs/teilzeitverkaeuferin.html">Teilzeitverkäuferin Jobs</a></li>
<li><a href="/de/jobs/kosmetikerin.html">Kosmetikerin Jobs</a></li>
<li><a href="/de/jobs/lehrstellen-gastronomie.html">Lehrstellen</a></li>
<li><a href="/de/jobs/front-office.html">Front Office Jobs</a></li>
<li><a href="/de/jobs/general-manager.html">General Manager Jobs</a></li>
<li><a href="/de/jobs/chef-de-bar.html">Chef de Bar Jobs</a></li>
<li><a href="/de/jobs/studenten.html">Studenten Jobs</a></li>
<li><a href="/de/jobs/commis-de-cuisine.html">Commis de Cuisine Jobs</a></li>
<li><a href="/de/jobs/buffet-mitarbeiterin.html">Buffet Mitarbeiterin Jobs</a></li>
<li><a href="/de/jobs?clear=1">Alle Gastro Stellen</a></li>
</ul>


<!--<h2><?php echo $this->message ?></h2>

<?php if (isset($this->reason) && $this->reason): ?>

<?php
$reasonMessage= '';
switch ($this->reason) {
    case 'error-controller-cannot-dispatch':
        $reasonMessage = $this->translate('The requested controller was unable to dispatch the request.');
        break;
    case 'error-controller-not-found':
        $reasonMessage = $this->translate('The requested controller could not be mapped to an existing controller class.');
        break;
    case 'error-controller-invalid':
        $reasonMessage = $this->translate('The requested controller was not dispatchable.');
        break;
    case 'error-router-no-match':
        $reasonMessage = $this->translate('The requested URL could not be matched by routing.');
        break;
    default:
        $reasonMessage = $this->translate('We cannot determine at this time why a 404 was generated.');
        break;
}
?>

<p><?php echo $reasonMessage ?></p>

<?php endif ?>

<?php if (isset($this->controller) && $this->controller): ?>

<dl>
    <dt><?php echo $this->translate('Controller') ?>:</dt>
    <dd><?php echo $this->escapeHtml($this->controller) ?>
<?php
if (isset($this->controller_class)
    && $this->controller_class
    && $this->controller_class != $this->controller
) {
    echo '(' . sprintf($this->translate('resolves to %s'), $this->escapeHtml($this->controller_class)) . ')';
}
?>
</dd>
</dl>

<?php endif ?>

<?php if (isset($this->display_exceptions) && $this->display_exceptions): ?>

<?php if(isset($this->exception) && $this->exception instanceof Exception): ?>
<hr/>
<h2><?php echo $this->translate('Additional information') ?>:</h2>
<h3><?php echo get_class($this->exception); ?></h3>
<dl>
    <dt><?php echo $this->translate('File') ?>:</dt>
    <dd>
        <pre class="prettyprint linenums"><?php echo $this->exception->getFile() ?>:<?php echo $this->exception->getLine() ?></pre>
    </dd>
    <dt><?php echo $this->translate('Message') ?>:</dt>
    <dd>
        <pre class="prettyprint linenums"><?php echo $this->exception->getMessage() ?></pre>
    </dd>
    <dt><?php echo $this->translate('Stack trace') ?>:</dt>
    <dd>
        <pre class="prettyprint linenums"><?php echo $this->exception->getTraceAsString() ?></pre>
    </dd>
</dl>
<?php
    $e = $this->exception->getPrevious();
    if ($e) :
?>
<hr/>
<h2><?php echo $this->translate('Previous exceptions') ?>:</h2>
<ul class="unstyled">
    <?php while($e) : ?>
    <li>
        <h3><?php echo get_class($e); ?></h3>
        <dl>
            <dt><?php echo $this->translate('File') ?>:</dt>
            <dd>
                <pre class="prettyprint linenums"><?php echo $e->getFile() ?>:<?php echo $e->getLine() ?></pre>
            </dd>
            <dt><?php echo $this->translate('Message') ?>:</dt>
            <dd>
                <pre class="prettyprint linenums"><?php echo $e->getMessage() ?></pre>
            </dd>
            <dt><?php echo $this->translate('Stack trace') ?>:</dt>
            <dd>
                <pre class="prettyprint linenums"><?php echo $e->getTraceAsString() ?></pre>
            </dd>
        </dl>
    </li>
    <?php
        $e = $e->getPrevious();
        endwhile;
    ?>
</ul>
<?php endif; ?>

<?php else: ?>

<h3><?php echo $this->translate('No Exception available') ?></h3>-->

<?php endif ?>

<?php endif ?>
