<?php
$hasFacets = $jobs instanceof \Solr\FacetsProviderInterface;
$today = new DateTime();
$savedJobsContainer = new \Laminas\Session\Container('gastro24_savedjobs');
?>
<?php if ($hasFacets):?>
    <?php
    $facets = $jobs->getFacets();
    $activeFacets = $facets->getActiveValues();
    ?>

    <?php $this->headScript()->captureStart()?>
        $(document).on('click', '.facet-checkbox', function () {
        var $checkbox = $(this),
        $form = $('#jobs-list-filter'),
        name = $checkbox.attr('name');
        $form.find('input[name="' + name + '"]').remove();
        if ($checkbox.prop('checked')) {
        $form.append('<input type="hidden" class="facet-param" name="' + name + '">');
        }
        $form.submit();
        }).on('click', '.facet-active', function () {
        $('#jobs-list-filter').find('input[name="' + $(this).data('name') + '"]').remove()
        .end().submit();
        }).on('click', '.facet-reset', function () {
        var $form = $('#jobs-list-filter');
        $('#jobs-list-filter').find('.facet-param').remove()
        .end().submit();
        });
    <?php $this->headScript()->captureEnd() ?>

    <?php if ($activeFacets):?>
        <div class="well well-sm">
            <?=$this->translate('Active filters:')?>
            <?php foreach ($activeFacets as $facetName => $facetValues):?>
                <?php foreach ($facetValues as $facetValue):?>
                    <button type="button" class="btn btn-default btn-sm facet-active" data-name="<?=$this->escapeHtmlAttr($facetName)?>[<?=$this->escapeHtmlAttr($facetValue)?>]" title="<?=$this->translate('Remove filter')?>"><?=$facetValue?> <span>&times;</span></button>
                <?php endforeach;?>
            <?php endforeach;?>
            <button type="button" class="btn btn-link facet-reset"><?=$this->translate('Remove all filters')?></button>
        </div>
    <?php endif;?>

    <div class="row">
        <div class="col-md-3">
            <?php foreach ($facets as $facetName => $facetValues):?>
                <div class="panel panel-default">
                    <div class="panel-heading"><?=$this->translate($facets->getTitle($facetName))?></div>
                    <div class="panel-body">
                        <?php foreach ($facetValues as $facetValue => $facetValueCount):?>
                            <div>
                                <label>
                                    <input type="checkbox" name="<?=$this->escapeHtmlAttr($facetName)?>[<?=$this->escapeHtmlAttr($facetValue)?>]" class="facet-checkbox"<?php if ($facets->isValueActive($facetName, $facetValue)):?> checked<?php endif;?>>
                                    <?=$facetValue?> (<?=$facetValueCount?>)
                                </label>
                            </div>
                        <?php endforeach;?>
                    </div>
                </div>
            <?php endforeach;?>
        </div>
    </div>
<?php endif;?>

<?php if (count($jobs)):?>
     <?php foreach ($jobs as $job): /* @var \Jobs\Entity\Job $job */?>
         <?php
            $industries = $job->getClassifications()->getIndustries();
            $org = $job->getOrganization();
            $hasJobTemplate = $this->gastroJobTemplate($org);
            $isIntern = (!$job->getLink() || $hasJobTemplate);
            $isEmbeddable = $this->gastroIsEmbeddable($job->getLink());
            $jobHasExternLink = (!$isIntern && !$isEmbeddable);
            $template = $job->getAttachedEntity('gastro24-template');

             if (is_object($job->getOrganization()) && is_object($job->getOrganization()->getOrganizationName()) && $job->getOrganization()->getOrganizationName()->getName()) {
                 $orgName =  $job->getOrganization()->getOrganizationName()->getName();
             }

            $logoUrl = $this->basePath('modules/Gastro24/images/no-company-logo.png');
            if (is_object($org) && is_object($org->getImage()) && $org->getImage()->getUri()) {
                $logoUrl = $this->basePath($this->organizationImageCache->getUri($org->getImages()->get('thumbnail')));
            }
            if ($template && ($logo = $template->getLogo())) {
                $logoUrl = $this->basePath($logo->getUri());
            }
         ?>

        <?php

        ?>
         <!-- begin card -->
         <div class="card box__job-favorite profile-detail">
             <a class="job-logo-link" title="<?= $job->getTitle()?>" href="<?=$this->jobUrl($job, ['linkOnly' => true, 'absolute' => true]) ?>">
                 <img class="job-logo" alt="<?= $orgName ?>" src="<?= $logoUrl ?>">
             </a>
             <div class="card__job-content box__action-buttons">
                 <?php if(!$jobHasExternLink) : ?>
                     <!-- favorite button -->
                     <?php if (isset($savedJobsContainer->jobs[$job->getId()])) : ?>
                         <button type="button" class="btn btn-default saved"
                                 data-text-saved="<?=$this->translate('Marked')?>" data-text-save="<?=$this->translate('Mark')?>" data-job="<?= $job->getId() ?>">
                             <span><?=$this->translate('Marked')?></span>
                         </button>
                     <?php else : ?>
                         <button type="button" class="pull-right btn btn-default"
                                 data-text-saved="<?=$this->translate('Marked')?>" data-text-save="<?=$this->translate('Mark')?>" data-job="<?= $job->getId() ?>">
                             <span><?=$this->translate('Mark')?></span>
                         </button>
                     <?php endif ?>
                     <!-- end favorite button -->
                 <?php endif; ?>

                 <h2>
                     <a title="<?= $job->getTitle()?>"
                        href="<?=$this->jobUrl($job, ['linkOnly' => true, 'absolute' => true]) ?>"><?= ucfirst($job->getTitle())?></a>
                 </h2>
                 <div class="card__job-info">
                     <div class="card__job-empname-label"><?= $orgName ?></div>
                     <div class="card__job-location">
                         <?php //TODO: workaround to hide coordinates ?>
                         <?php
                            if(strpos($job->getLocation(), "(") !== false) {
                                $locationString = substr($job->getLocation(), 0, strpos($job->getLocation(), "("));
                            }
                            else {
                                $locationString = $job->getLocation();
                            }
                         ?>
                         <?= $locationString;  ?>
                     </div>
                 </div>
                 <div class="card__job-snippet-logo">
                     <p class="card__job-snippet" dir="auto">
                         <?php
                         $preview = null;
                         if ($job->getTemplateValues()->getIntroduction()) {
                             $preview = substr(strip_tags($job->getTemplateValues()->getIntroduction()), 0 , 215);
                         }
                         elseif($job->getTemplateValues()->get('position')) {
                             $preview = $job->getTemplateValues()->get('position');
                             $preview = str_replace(['<li>', '<strong>', '</strong>', '</u>', '</p>', '</h2>', '<b>', '<u>', '</b>', '<br>', '</h4>','</h3>','</span>','<span>','<div>'], ' ', $preview);
                             $preview = substr(strip_tags($preview), 0 , 215);
                         }
                         elseif ($job->getTemplateValues()->getHtml()) {
                             $preview = $job->getTemplateValues()->getHtml();
                             $preview = str_replace(['<li>', '<strong>', '</strong>', '</u>', '</p>', '</h2>', '<b>', '<u>', '</b>', '<br>', '</h4>','</h3>','</span>','<span>','<div>'], ' ', $preview);
                             $preview = substr(strip_tags($preview), 0 , 215);
                         }
                         if ($preview) {
                             $preview = str_replace('<p>', '', $preview);
                             $preview = str_replace('</p>', '', $preview);
                             $preview   = implode(' ', explode(' ', $preview, -1));
                             $preview .= ' ... ';
                         }
                         ?>
                         <?= $preview ?>
                     </p>
                 </div>
                 <div class="card_job-short-info">
                     <ul>
                         <?php
                         // check for newer than 24 hours
                         $jobDate = $job->getDatePublishStart() ?? $job->getDateCreated();
                         $dayDiff = $today->diff($jobDate);
                         if ($dayDiff->days < 1) {
                             echo '<li class="new">Neu</li>';
                         }
                         ?>
                         <li class="type"><?= $this->publishDateFormatter($job) ?></li>
                         <li class="contract"><?php $typeOfContract = $job->getClassifications()->getEmploymentTypes()->__toString() ?:'Vollzeit' ?>
                             <?=$typeOfContract; ?>
                         </li>
                         <!-- HINT: some jobs has invalid industries, therefore check for empty string -->
                         <?php if ($industries->getItems()->count() && !$this->isCrawlerJob($org) && $industries->__toString() != ""): ?>
                             <li class="industries">
                                 <?= $industries->__toString(); ?>
                             </li>
                         <?php endif; ?>
                     </ul>
                 </div>
             </div>
         </div>
         <!-- end card -->
     <?php endforeach?>

<?php
    $paginationControlRoute = is_null($paginationControlRoute) ? 'lang/jobboard':$paginationControlRoute;
?>
<?php echo $this->paginationControl($jobs, 'Sliding', 'pagination-control', array('lang' => $this->params('lang'), 'route' => $paginationControlRoute));?>

<?php endif ?>

