<?php
//$this->headTitle("Jobs ".$this->organization->getName());

$this->headTitle("Firmenprofil von ".$this->organization->getName() );
$this->headMeta()->setName('description', "Firmenprofil von ".$this->organization->getName()." mit aktuell ".$this->jobs->getTotalItemCount()." verfügbaren Jobs. Jetzt passende Stellenanzeige finden!" );

$this->headScript()->appendFile($this->basepath('/modules/Core/js/core.pagination-container.js'))
    ->appendFile($this->basePath('modules/Core/js/core.pagination-container.js'))
    ->appendFile($this->basePath($this->asset('modules/Gastro24/js/jobs.js')));

/* @var \Organizations\Entity\Organization $organization */
$contact = $organization->getContact();

// set canonical link
$queryGet = $this->params()->fromQuery();
if (isset($queryGet['clear'])) {
    $orgBaseUrl = $this->serverUrl() . $this->orgProfileUrl($organization);
    //$this->headLink()->headLink(array('rel' => 'canonical', 'href' => $orgBaseUrl), 'PREPEND');
    $clear = "?clear=1";
    $this->headLink()->headLink(array('rel' => 'canonical', 'href' => $orgBaseUrl.$clear) );
}
elseif (isset($queryGet['page']) && $queryGet['page'] > 1) {
    $this->headMeta()->setName('robots', 'noindex,follow');
}

// reset searchQuery in session
$container = new \Laminas\Session\Container('gastro24_jobboardcontainer');
$container->landingPageSearchQuery = null;
$container->fromCompanyProfile = true;
$container->companyName = $organization->getName();
$container->companyId = $organization->getId();

// get org logo
$logoUrl = $this->basePath('modules/Gastro24/images/no-company-logo.png');
if($organization->getImages()->notEmpty('images')) {
    $logoUrl = $this->basePath($this->organizationImageCache->getUri($organization->getImages()->get('thumbnail')));
}

$bannerUrl = $this->basePath('/modules/Gastro24/images/bg_placeholder_gray.svg');

$organizationAdditionalRepo = $this->services('repositories')
    ->get(\Gastro24\Entity\OrganizationAdditional::class);
/** @var \Gastro24\Entity\OrganizationAdditional $organizationAdditional */
$organizationAdditional = $organizationAdditionalRepo->findOneByOrganizationId($organization->getId());
if ($organizationAdditional && $organizationAdditional->getBanner()) {
    $bannerUrl = $this->basePath($organizationAdditional->getBanner()->getUri());
}

$jsonLdSocialsString = '';
if ($organizationAdditional && $organizationAdditional->getSocials()) {
    if ($organizationAdditional->getSocials()->getFacebook()) {
        $jsonLdSocialsString .= '"' . $organizationAdditional->getSocials()->getFacebook() . '",';
    }
    if ($organizationAdditional->getSocials()->getLinkedin()) {
        $jsonLdSocialsString .= '"' . $organizationAdditional->getSocials()->getLinkedin() . '",';
    }
    if ($organizationAdditional->getSocials()->getTwitter()) {
        $jsonLdSocialsString .= '"' . $organizationAdditional->getSocials()->getTwitter() . '",';
    }
    if ($organizationAdditional->getSocials()->getInstagram()) {
        $jsonLdSocialsString .= '"' . $organizationAdditional->getSocials()->getInstagram() . '",';
    }
    if ($organizationAdditional->getSocials()->getYoutube()) {
        $jsonLdSocialsString .= '"' . $organizationAdditional->getSocials()->getYoutube() . '",';
    }

    $jsonLdSocialsString = rtrim($jsonLdSocialsString, ',');
}
?>

<?php $this->headStyle()->captureStart() ?>
.company-bg-image:before {
background-image: url(https://gastrojob24.gumlet.net<?= $bannerUrl?>?mode=crop&width=1200&height=510&quality=25);
}
<?php $this->headStyle()->captureEnd() ?>

<script type="application/ld+json">
    {
        "@context": "https://schema.org",
        "@type": "Organization",
        "name": "<?= $organization->getName()?>",
        "url": "<?= $contact->getWebsite() ?>",
        "logo": "https://www.gastrojob24.ch<?= $logoUrl ?>",
        "description": "<?= $organization->getdescription()?>",
        "address": {
            "@type": "PostalAddress",
            "streetAddress": "<?= $contact->getStreet() ?> <?= $contact->getHouseNumber() ?>",
            "addressLocality": "<?= $contact->getCity() ?>",
            "postalCode": "<?= $contact->getPostalcode() ?>",
            "addressCountry": "<?= $contact->getCountry() ?>"
        },
        "contactPoint": {
            "@type": "ContactPoint",
            "contactType": "Human Resource",
            "telephone": "[<?= $contact->getPhone() ?>]"
        },
        "sameAs": [ <?= $jsonLdSocialsString ?> ]
    }
</script>


<!-- Begin Organization Profile -->
<div class="sub-navigation-wrapper">
    <nav aria-label="breadcrumb" class="job-detail-breadcrumb-nav">
        <ol class="breadcrumb" itemscope="" itemtype="http://schema.org/BreadcrumbList">
            <li class="breadcrumb-item" itemprop="itemListElement" itemscope="" itemtype="http://schema.org/ListItem">
                <a itemprop="item" href="/"> <span itemprop="name">Home</span>
                </a>
                <meta itemprop="position" content="1">
            </li>
            <li class="breadcrumb-item" itemprop="itemListElement" itemscope="" itemtype="http://schema.org/ListItem">
                <a itemprop="item" href="/de/jobs?clear=1"> <span itemprop="name">Jobs</span>
                </a>
                <meta itemprop="position" content="2">
            </li>
            <li class="breadcrumb-item" itemprop="itemListElement" itemscope="" itemtype="http://schema.org/ListItem">
                <a itemprop="item" href="/de/organizations/profile"> <span itemprop="name">Firmen</span>
                </a>
                <meta itemprop="position" content="3">
            </li>
            <li class="breadcrumb-item" itemprop="itemListElement" itemscope="" itemtype="http://schema.org/ListItem">
                <span itemprop="name">
                    <h1>Firmenprofil von <?= $organization->getName()?></h1></span>
                    <meta itemprop="position" content="4">
            </li>
        </ol>
    </nav>
</div>

<?php if ($organizationAdditional && $organizationAdditional->getBanner()): ?>
<div class="" style="position:relative;">
    <div class="company-bg-image"></div>
    <div class="company-profile-wrapper">
        <div class="jgArSS" 
        style="background-image: url(https://gastrojob24.gumlet.net<?= $bannerUrl?>?mode=crop&width=1200&height=510&quality=55);">
        </div>
    </div>
</div>
<?php endif; ?>

<div class="company-description-wrapper">
    <div class="row">
        <div class="col-md-9">
            <div class="stand-alone-card company-info">
                <div class="info-card">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-md-3">
                                <span class="job-logo-wrapper">
                                    <img class="job-logo" alt="Firmenlogo <?= $organization->getName()?>" data-gmlazy="false" src="<?= $logoUrl ?>">
                                </span>

                                <div class="social-media-company-profile">
                                    <?php if($organizationAdditional && $organizationAdditional->getSocials()) : ?>
                                    <?php if($organizationAdditional->getSocials()->getFacebook()) :?>
                                    <a href="<?= $organizationAdditional->getSocials()->getFacebook() ?>" target="_blank"> <i class="fa fa-facebook-square"></i></a>
                                    <?php endif; ?>
                                    <?php if($organizationAdditional->getSocials()->getLinkedin()) :?>
                                    <a href="<?= $organizationAdditional->getSocials()->getLinkedin() ?>" target="_blank"><i class="fa fa-linkedin-square"></i></a>
                                    <?php endif; ?>
                                    <?php if($organizationAdditional->getSocials()->getTwitter()) :?>
                                    <a href="<?= $organizationAdditional->getSocials()->getTwitter() ?>" target="_blank"> <i class="fa fa-twitter-square"></i></a>
                                    <?php endif; ?>
                                    <?php if($organizationAdditional->getSocials()->getInstagram()) :?>
                                    <a href="<?= $organizationAdditional->getSocials()->getInstagram() ?>" target="_blank"><i class="fa fa-instagram"></i></a>
                                    <?php endif; ?>
                                    <?php if($organizationAdditional->getSocials()->getYoutube()) :?>
                                    <a href="<?= $organizationAdditional->getSocials()->getYoutube() ?>" target="_blank"> <i class="fa fa-youtube-square"></i></a>
                                    <?php endif; ?>
                                    <?php endif; ?>
                                </div>
                            </div>
                            <div class="col-md-9">
                                <h2><?= $organization->getName()?></h2>
                                <?php if($organizationAdditional && ($organizationAdditional->getVideoLink() || $organization->getdescription())) : ?>
                                <div class="more">
                                    <?= nl2br($organization->getdescription()) ?>
                                </div>
                                <?php endif; ?>
                            </div>
                        </div>
                    </div>
                    <div class="visible-xs visible-sm">
                        <hr />

                        <address>
                            <strong><?= $organization->getName()?></strong>
                            <?= $contact->getStreet() ?> <?= $contact->getHouseNumber() ?> <br>
                            <?= $contact->getPostalcode() ?> <?= $contact->getCity() ?><br>
                            <?= $contact->getCountry() ?>
                        </address>

                        <div class="meta-adress">
                            <a href="tel:<?= $contact->getPhone() ?>" rel="nofollow"><?= $contact->getPhone() ?></a>
                            <a class="fa fa-angle-right" href="<?= $contact->getWebsite() ?>" rel="nofollow"><span>zur Firmenwebsite</span></a>
                        </div>

                    </div>
                </div>

                <div class="visible-xs visible-sm">
                    <div class="iframe-container" style="padding-bottom:50%;">
                        <img style="position:absolute;" width="300" data-src="https://maps.googleapis.com/maps/api/staticmap?center=<?php echo $organization->getName()?>+<?php echo $contact->getStreet()?>+<?php echo $contact->getHouseNumber()?>+<?php echo $contact->getCity()?>>+<?php echo $contact->getCountry()?>&language=de&zoom=15&scale=2&size=300x150&maptype=roadmap&key=AIzaSyCoY42r_qqmRmnKdikLHnh3kPcAQePc-0w&format=jpg&visual_refresh=true&markers=size:mid%7Ccolor:0xd9534f%7Clabel:%7C=<?php echo $organization->getName()?>+<?php echo $contact->getStreet()?>+<?php echo $contact->getHouseNumber()?>+<?php echo $contact->getCity()?>>+<?php echo $contact->getCountry()?>" alt="Google Map">
                    </div>

                </div>

            </div>

      <?php if($organizationAdditional && $organizationAdditional->getVideoLink()) : ?>

            <h2 style="margin-bottom:15px;font-weight:bold;">Firmenvideo</h2>

            <div class="stand-alone-card">

                <div class="info-card">
                    <div class="yt-video embed-responsive embed-responsive-16by9">
                        <iframe class="embed-responsive-item" src="<?= $organizationAdditional->getVideoLink() ?>" allowfullscreen=""></iframe>
                    </div>
                </div>

            </div>



            <?php endif; ?>

            <!-- active jobs -->
            <div class="tab-pane active" id="jobs">
                <div id="jobs-list-container" class="pagination-container">
                    <div class="pagination-content">
                        <?php echo $this->render('organizations/profile/detail.ajax')?>
                    </div>
                </div>
            </div>
            <!-- end active jobs -->
        </div>
        <div class="col-md-3  hidden-xs hidden-sm">
            <div class="stand-alone-card">
                <div class="info-card">
                    <address>
                        <strong><?= $organization->getName()?></strong>
                        <?= $contact->getStreet() ?> <?= $contact->getHouseNumber() ?> <br>
                        <?= $contact->getPostalcode() ?> <?= $contact->getCity() ?><br>
                        <?= $contact->getCountry() ?>
                    </address>

                    <div class="meta-adress">
                        <a href="tel:<?= $contact->getPhone() ?>" rel="nofollow"><?= $contact->getPhone() ?></a>
                        <a class="fa fa-angle-right" href="<?= $contact->getWebsite() ?>" rel="nofollow"><span>zur Firmenwebsite</span></a>
                    </div>

                </div>

                <div class="iframe-container" style="padding-bottom:50%;">
                    <img style="position:absolute;" width="300" data-src="https://maps.googleapis.com/maps/api/staticmap?center=<?php echo $organization->getName()?>+<?php echo $contact->getStreet()?>+<?php echo $contact->getHouseNumber()?>+<?php echo $contact->getCity()?>>+<?php echo $contact->getCountry()?>&language=de&zoom=15&scale=1&size=300x150&maptype=roadmap&key=AIzaSyCoY42r_qqmRmnKdikLHnh3kPcAQePc-0w&format=jpg&visual_refresh=true&markers=size:mid%7Ccolor:0xd9534f%7Clabel:%7C=<?php echo $organization->getName()?>+<?php echo $contact->getStreet()?>+<?php echo $contact->getHouseNumber()?>+<?php echo $contact->getCity()?>>+<?php echo $contact->getCountry()?>" alt="Google Map">


                </div>
            </div>
        </div>
    </div>
</div>
<!-- End Organization Profile -->
