<?php
/**
 * YAWIK
 *
 * @filesource
 * @copyright (c) 2013 - 2016 Cross Solution (http://cross-solution.de)
 * @license   MIT
 */
$hasFacets = $jobs instanceof \Solr\FacetsProviderInterface;

?>

<?php
//@TODO: [ZF3] the line below caused an error in ZF3
//$this->proxy('jobsByMailSubscriptionForm')->render($jobs)
?>
        
        
        
        

 <?php
// get date difference
 $today = new DateTime();
  ?>



<?php if (count($jobs)):?>

     <?php foreach ($jobs as $job): /* @var \Jobs\Entity\Job $job */?>
     
                     <!-- begin card -->
						<div class="card box__job-favorite">
							<a class="job-logo-link" title="" href="">
								<img class="job-logo" alt="" src="">
							</a>
							<div class="card__job-content box__action-buttons">
								<!-- favorite button -->
								<button type="button" class="pull-right btn btn-default" data-text-saved="Gemerkt" data-text-save="Merken"> <span>Merken</span>
								</button>
								<!-- end favorite button -->
								<h2><a title="" href=""></a></h2>
								<div class="card__job-info">
									<div class="card__job-empname-label"></div>
									<div class="card__job-location"></div>
								</div>
								<div class="card__job-snippet-logo">
									<p class="card__job-snippet" dir="auto">
									    
									    
		 <?php
          $preview = null;
          if ($job->getTemplateValues()->getIntroduction()) {
              $preview = substr(strip_tags($job->getTemplateValues()->getIntroduction()), 0 , 215);
          }
          elseif($job->getTemplateValues()->get('position')) {
              $preview = $job->getTemplateValues()->get('position');
              $preview = str_replace(['<li>', '<strong>', '</strong>', '</u>', '</p>', '</h2>', '<b>', '<u>', '</b>', '<br>', '</h4>','</h3>','</span>','<span>','<div>'], ' ', $preview);
              $preview = substr(strip_tags($preview), 0 , 215);
          }
          elseif ($job->getTemplateValues()->getHtml()) {
              $preview = $job->getTemplateValues()->getHtml();
              $preview = str_replace(['<li>', '<strong>', '</strong>', '</u>', '</p>', '</h2>', '<b>', '<u>', '</b>', '<br>', '</h4>','</h3>','</span>','<span>','<div>'], ' ', $preview);
              $preview = substr(strip_tags($preview), 0 , 215);
          }
          if ($preview) {
              $preview = str_replace('<p>', '', $preview);
              $preview = str_replace('</p>', '', $preview);
              $preview   = implode(' ', explode(' ', $preview, -1));
              $preview .= ' ... ';
          }
          ?>
        <?= $preview ?>

				</p>
								</div>
								<div class="card_job-short-info ">
									<ul>
										
										
		<?php
          // check for newer than 24 hours
          $jobDate = $job->getDatePublishStart() ?? $job->getDateCreated();
          $dayDiff = $today->diff($jobDate);
          if ($dayDiff->days < 1) {
              echo '<li class="new">Neu</li>';
          }
          ?>
        <li class="type"><?= $this->publishDateFormatter($job) ?></li>
        <li class="contract"><?php $typeOfContract = $job->getClassifications()->getEmploymentTypes()->__toString() ?:'Vollzeit' ?>
          <?=$typeOfContract; ?>
        </li>
        <!-- HINT: some jobs has invalid industries, therefore check for empty string -->
        <?php if ($industries->getItems()->count() && !$this->isCrawlerJob($org) && $industries->__toString() != ""): ?>
        <li class="industries">
          <?= $industries->__toString(); ?>
        </li>
        <?php endif; ?>

										
										
										
									</ul>
								</div>
							</div>
						</div>
						<!-- end card -->
 
  <?php endforeach?>
           

<?php endif;?>

