<?php
//$this->headTitle("Jobs ".$this->organization->getName());

$this->headTitle("Firmenprofil von ".$this->organization->getName() );
$this->headMeta()->setName('description', "Firmenprofil von ".$this->organization->getName()." mit aktuell ".$this->jobs->getTotalItemCount()." verfügbaren Jobs. Jetzt passende Stellenanzeige finden!" );

$this->headScript()->appendFile($this->basepath('/modules/Core/js/core.pagination-container.js'))
    ->appendFile($this->basePath('modules/Core/js/core.pagination-container.js'))
    ->appendFile($this->basePath($this->asset('modules/Gastro24/js/jobs.js')));

/* @var \Organizations\Entity\Organization $organization */
$contact = $organization->getContact();

// set canonical link
$queryGet = $this->params()->fromQuery();
if (isset($queryGet['clear'])) {
    $orgBaseUrl = $this->serverUrl() . $this->orgProfileUrl($organization);
    $this->headLink()->headLink(array('rel' => 'canonical', 'href' => $orgBaseUrl), 'PREPEND');
}
elseif (isset($queryGet['page']) && $queryGet['page'] > 1) {
    $this->headMeta()->setName('robots', 'noindex,follow');
}

// reset searchQuery in session
$container = new \Laminas\Session\Container('gastro24_jobboardcontainer');
$container->landingPageSearchQuery = null;
$container->fromCompanyProfile = true;
$container->companyName = $organization->getName();
$container->companyId = $organization->getId();

// get org logo
$logoUrl = $this->basePath('modules/Gastro24/images/no-company-logo.png');
if($organization->getImages()->notEmpty('images')) {
    $logoUrl = $this->basePath($this->organizationImageCache->getUri($organization->getImages()->get('thumbnail')));
}

$bannerUrl = $this->basePath('/modules/Gastro24/images/bg_placeholder_gray.svg');

$organizationAdditionalRepo = $this->services('repositories')
    ->get(\Gastro24\Entity\OrganizationAdditional::class);
/** @var \Gastro24\Entity\OrganizationAdditional $organizationAdditional */
$organizationAdditional = $organizationAdditionalRepo->findOneByOrganizationId($organization->getId());
if ($organizationAdditional && $organizationAdditional->getBanner()) {
    $bannerUrl = $this->basePath($organizationAdditional->getBanner()->getUri());
}

$jsonLdSocialsString = '';
if ($organizationAdditional && $organizationAdditional->getSocials()) {
    if ($organizationAdditional->getSocials()->getFacebook()) {
        $jsonLdSocialsString .= '"' . $organizationAdditional->getSocials()->getFacebook() . '",';
    }
    if ($organizationAdditional->getSocials()->getLinkedin()) {
        $jsonLdSocialsString .= '"' . $organizationAdditional->getSocials()->getLinkedin() . '",';
    }
    if ($organizationAdditional->getSocials()->getTwitter()) {
        $jsonLdSocialsString .= '"' . $organizationAdditional->getSocials()->getTwitter() . '",';
    }
    if ($organizationAdditional->getSocials()->getInstagram()) {
        $jsonLdSocialsString .= '"' . $organizationAdditional->getSocials()->getInstagram() . '",';
    }
    if ($organizationAdditional->getSocials()->getYoutube()) {
        $jsonLdSocialsString .= '"' . $organizationAdditional->getSocials()->getYoutube() . '",';
    }

    $jsonLdSocialsString = rtrim($jsonLdSocialsString, ',');
}
?>

<?php $this->headStyle()->captureStart() ?>
    .company-bg-image:before {
        background-image: url(https://gastrojob24.gumlet.net<?= $bannerUrl?>?mode=crop&width=1200&height=410&quality=25);
    }
<?php $this->headStyle()->captureEnd() ?>

<script type="application/ld+json">
 {
 "@context": "https://schema.org",
 "@type": "Organization",
 "name": "<?= $organization->getName()?>",
 "url": "<?= $contact->getWebsite() ?>",
 "logo": "https://www.gastrojob24.ch<?= $logoUrl ?>",
 "description": "<?= $organization->getdescription()?>",
 "address": {
 "@type": "PostalAddress",
 "streetAddress": "<?= $contact->getStreet() ?> <?= $contact->getHouseNumber() ?>",
 "addressLocality": "<?= $contact->getCity() ?>",
 "postalCode": "<?= $contact->getPostalcode() ?>",
 "addressCountry": "<?= $contact->getCountry() ?>"
 },
 "contactPoint": {
 "@type": "ContactPoint",
 "contactType": "Human Resource",
 "telephone": "[<?= $contact->getPhone() ?>]"
 },
 "sameAs": [<?= $jsonLdSocialsString ?>]
 }
</script>


<style>


.company-description-wrapper {

    margin-top:15px;
}


a.morelink {
	text-decoration:none;
	outline: none;
    color:#1e69a3;
	text-decoration:underline;
}
.morecontent span {
	display: none;
}


  .full-width-bar-vw {
      
    width: 100vw;
    position: relative;
    left:50%;
    right: 50%;
    margin-left: -50vw;
    margin-right: -50vw;

  }
  .full-width-bar-vw ul {
      
      padding-left:15px!important;
  }


    .iframe-container {
    position: relative;
    padding-bottom: 56.25%;
    height: 0;
    overflow: hidden;
    width: 100%;
    height: auto;
}

.iframe-container img {
    width: 100%;
}

    .meta-adress {
        margin-top:15px;

    }

    .meta-adress a {
        display:block;
        color: #1e69a3; 

    }
    .social-media-company-profile {
        margin-bottom:25px;

    }
    .social-media-company-profile a {
        color:#dcdfe2;
        font-size: 22px;
        margin-right: 10px;

    }
    .social-media-company-profile a:hover {
        color:#000;
    }

    .yt-video {
        margin-top:20px;
    }

    address strong {

        display:block;
    }

    .company-link {
        color: rgb(71, 60, 60);
        text-decoration:underline;
    }

    @media (min-width: 992px) {
        .company-description-wrapper .row>.col-md-3 {
            position: -webkit-sticky;
            position: sticky;
            top: 5px;
            padding-left: 0
        }
    }


    .company-description-wrapper address {
        color: rgb(118, 115, 125);
        margin-bottom: 0px;
    }

    .company-description-wrapper .info-card h2 {
        display: block;
        text-overflow: ellipsis;
        white-space: nowrap;
        overflow: hidden;
    }

    .content {
        position: relative;
        overflow: hidden;
        margin-bottom: auto!important;
    }

    .content:after {
        content: "";
        position: absolute;
        left: 0;
        height: 400px;
        right: 0;
        top: 0px;
        bottom: -40px;
        filter: blur(20px);
        background-position: center center;
        position: absolute;
        overflow: hidden;
        botton: -20px;
        transform: scale(1.1);
    }

    .company-bg-image {
        width: 100vw;
        left: 50%;
        right: 50%;
        position: relative;
        margin-left: -50vw;
        margin-right: -50vw;
        height: 410px;
        overflow: hidden;
    }

    .company-bg-image:before {
        display: block;
        position: absolute;
        top: -45px;
        bottom: -45px;
        left: -35px;
        right: -35px;
        content: "";
        background-size: cover;
        background-position: center center;
        filter: blur(25px);
    }

    .company-profile-wrapper {
        left: 0;
        right: 0;
        top: 0;
        position: absolute;
        border-left: 1px solid #dcdfe2;
        border-right: 1px solid #dcdfe2;
    }

    main#content {
        padding-top: 0;
    }

    .jgArSS {
        background-size: cover;
        height: 410px;
        background-position: center center;
    }

    .company-profile-image {
        background-color: #fff;
        display: flex;
        padding: 20px 30px;
    }

    .info-card h1 {
        font-weight:bold;
    }

    .info-card {
        margin-bottom: 15px;
        margin-top: 30px;
        padding:15px;

    }

    .info-card:first-child {
        margin-top: 0px;
    }

    .job-logo-wrapper {
            display: block;
     width: 140px;
    padding: 5px;
        
    }

    .job-logo-wrapper img {
    width:100%;
    }

    .job-info-wrapper {
        position: relative;
        width: calc(100% - 175px);
        display: inline-block;
    }

    .job-info-wrapper .address-short {
        font-size: 16px;
        color: rgb(118, 115, 125);
    }

    .info-card h2 {
        font-size: 18px;
        margin-top: 0;
        margin-right: 25px;
        margin-bottom: 5px;
        overflow: hidden;
        text-overflow: ellipsis;
        line-height: 24px;
    }

    .iframe-container {
        position: relative;
        padding-bottom: 56.25%;
        /* ratio 16x9 */
        height: 0;
        overflow: hidden;
        width: 100%;
        height: auto;
    }

    .iframe-container iframe {
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
    }


    /* ratio 4x3 */

    .iframe-container.ratio4x3 {
        padding-bottom: 75%;
    }

    .breadcrumb {
        margin-top: 10px;
    }

    .job-count-badge {
        display: inline;
        padding: 7px 10px;
        font-size: 16px;
        font-weight: 300;
        line-height: 1;
        color: #fff;
        text-align: center;
        white-space: nowrap;
        background-color: #60a5d1;
        top: 0;
        right: 0;
        position: absolute;
        border-radius: 4px;
    }

    @media (max-width:991px) {
        .jgArSS {
            height: 250px;
        }
    
        .company-bg-image {
            height: 250px;
        }
    }

    @media (max-width:768px) {
    
        .jgArSS {
            height: 200px;
        }
        .company-bg-image {
           height: 200px;
        }
        .job-logo-wrapper {
            width: 100px
        }
        .job-info-wrapper {
            width: calc(100% - 135px);
        }
        .company-profile-image h1 {
            font-size: 24px;
            line-height: 28px;
            padding-right: 0px;
        }
        .company-profile-image {
            padding: 15px 20px;
        }
    }

    @media (max-width:510px) {
        .company-profile-image h1 {
            display: block;
            text-overflow: ellipsis;
            white-space: nowrap;
            overflow: hidden;
        }
        .jgArSS {
            height: 150px;
        }
        .company-bg-image {
            height: 150px;
        }
       
        .company-profile-image h1 {
            font-size: 20px;
            line-height: 28px;
        }
        .job-info-wrapper {
            width: calc(100% - 110px);
        }
    }

@media (max-width:468px) {
 

.company-profile-wrapper {
   
    margin-left: -12px;
    margin-right: -12px;
}
    }
</style>

<!-- Begin Organization Profile -->
<div id="navbar-home-site-links" class="full-width-bar-vw">
   <div class="container">
      <div class="row">
       <div class="col-md-12">
            <nav aria-label="breadcrumb" class="job-detail-breadcrumb-nav">
                <ol class="breadcrumb" itemscope="" itemtype="http://schema.org/BreadcrumbList">
                    <li class="breadcrumb-item" itemprop="itemListElement" itemscope="" itemtype="http://schema.org/ListItem">
                        <a itemprop="item" href="/"> <span itemprop="name">Home</span>
                        </a>
                        <meta itemprop="position" content="1">
                    </li>
                    <li class="breadcrumb-item" itemprop="itemListElement" itemscope="" itemtype="http://schema.org/ListItem">
                        <a itemprop="item" href="/de/jobs?clear=1"> <span itemprop="name">Jobs</span>
                        </a>
                        <meta itemprop="position" content="2">
                    </li>
                    <li class="breadcrumb-item" itemprop="itemListElement" itemscope="" itemtype="http://schema.org/ListItem">
                        <a itemprop="item" href="/de/organizations/profile"> <span itemprop="name">Firmen</span>
                        </a>
                        <meta itemprop="position" content="3">
                    </li>
                    <li class="breadcrumb-item" itemprop="itemListElement" itemscope="" itemtype="http://schema.org/ListItem"> <span itemprop="name">Firmenprofil von <?= $organization->getName()?></span>
                        <meta itemprop="position" content="4">
                    </li>
                </ol>
            </nav>
        </div>
      </div>
   </div>
</div>

<?php if ($organizationAdditional && $organizationAdditional->getBanner()): ?>
<div class="" style="position:relative;">
    <div class="company-bg-image"></div>
    <div class="company-profile-wrapper">
    <div class="jgArSS" 
        style="background-image: url(https://gastrojob24.gumlet.net<?= $bannerUrl?>?mode=crop&width=1200&height=410&quality=55);">
    </div>
       
</div>
</div>
<?php endif; ?>

<div class="company-description-wrapper">
    <div class="row">
        <div class="col-md-9">
              
            <div class="info-card stand-alone-card" id="portrait">
            <span class="job-logo-wrapper stand-alone-card">
				 <img class="job-logo" alt="Logo <?= $organization->getName()?>" src="<?= $logoUrl ?>">
			</span>
                <h1><?= $organization->getName()?></h1>

             <?php if($organizationAdditional && ($organizationAdditional->getVideoLink() || $organization->getdescription())) : ?>
                 <div class="more">
                    <?= nl2br($organization->getdescription()) ?>
                </div>

                <?php if($organizationAdditional && $organizationAdditional->getVideoLink()) : ?>
                    <div class="yt-video embed-responsive embed-responsive-16by9">
                        <iframe class="embed-responsive-item" src="<?= $organizationAdditional->getVideoLink() ?>" allowfullscreen></iframe>
                    </div>
                <?php endif; ?>

              

        <?php endif; ?>
        </div> 
            <!-- active jobs -->
            <div class="tab-pane active" id="jobs">
                <div id="jobs-list-container" class="pagination-container">
                    <div class="pagination-content">
                        <?php echo $this->render('organizations/profile/detail.ajax')?>
                    </div>
                </div>
            </div>
            <!-- end active jobs -->
        </div>
        <div class="col-md-3">
        <div class="stand-alone-card">
            <div class="info-card" style="margin-bottom:0px;">
            <div class="social-media-company-profile">
                    <?php if($organizationAdditional && $organizationAdditional->getSocials()) : ?>
                        <?php if($organizationAdditional->getSocials()->getFacebook()) :?>
                            <a href="<?= $organizationAdditional->getSocials()->getFacebook() ?>" target="_blank"> <i class="fa fa-facebook-square"></i></a>
                        <?php endif; ?>
                        <?php if($organizationAdditional->getSocials()->getLinkedin()) :?>
                            <a href="<?= $organizationAdditional->getSocials()->getLinkedin() ?>" target="_blank"><i class="fa fa-linkedin-square"></i></a>
                        <?php endif; ?>
                        <?php if($organizationAdditional->getSocials()->getTwitter()) :?>
                            <a href="<?= $organizationAdditional->getSocials()->getTwitter() ?>" target="_blank"> <i class="fa fa-twitter-square"></i></a>
                        <?php endif; ?>
                        <?php if($organizationAdditional->getSocials()->getInstagram()) :?>
                            <a href="<?= $organizationAdditional->getSocials()->getInstagram() ?>" target="_blank"><i class="fa fa-instagram"></i></a>
                        <?php endif; ?>
                        <?php if($organizationAdditional->getSocials()->getYoutube()) :?>
                            <a href="<?= $organizationAdditional->getSocials()->getYoutube() ?>" target="_blank">	<i class="fa fa-youtube-square"></i></a>
                        <?php endif; ?>
                    <?php endif; ?>
                </div>
                <address>
                    <strong><?= $organization->getName()?></strong>
                    <?= $contact->getStreet() ?> <?= $contact->getHouseNumber() ?> <br>
                    <?= $contact->getPostalcode() ?> <?= $contact->getCity() ?><br>
                    <?= $contact->getCountry() ?>
                </address>

                <div class="meta-adress">
                    <a href="tel:<?= $contact->getPhone() ?>" rel="nofollow"><?= $contact->getPhone() ?></a>
                    <a href="<?= $contact->getWebsite() ?>" rel="nofollow">zur Firmenwebsite</a>
                </div>
                
            </div>

           <div class="iframe-container" style="padding-bottom:50%;">
              <img style="position:absolute;" width="300"
         data-src="https://maps.googleapis.com/maps/api/staticmap?center=<?php echo $organization->getName()?>+<?php echo $contact->getStreet()?>+<?php echo $contact->getHouseNumber()?>+<?php echo $contact->getCity()?>>+<?php echo $contact->getCountry()?>&language=de&zoom=15&scale=2&size=300x150&maptype=roadmap&key=AIzaSyCoY42r_qqmRmnKdikLHnh3kPcAQePc-0w&format=jpg&visual_refresh=true&markers=size:mid%7Ccolor:0xd9534f%7Clabel:%7C=<?php echo $organization->getName()?>+<?php echo $contact->getStreet()?>+<?php echo $contact->getHouseNumber()?>+<?php echo $contact->getCity()?>>+<?php echo $contact->getCountry()?>"
         alt="Google Map">


          </div>
        </div>
    </div>
    </div>
</div>
<!-- End Organization Profile -->
