<div id="<?=$modalId?>" class="modal fade" role="dialog" aria-labelledby="job-by-mail-subscribe-label" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <strong id="job-by-mail-subscribe-label"><?=$this->translate('Get the right Job via e-mail')?></strong>
            </div>
            <?=$this->form()->openTag($form)?>
            <div class="modal-body">
                <?php foreach (['q', 'l', 'd'] as $optionalElementName):?>
                    <?php if ($form->has($optionalElementName)):?>
                        <?=$this->formRow($form->get($optionalElementName))?>
                    <?php endif;?>
                <?php endforeach;?>
                <?=$this->formRow($form->get('email'))?>
                <?php foreach ($form->getFieldsets() as $fieldset):?>
                    <?php foreach ($fieldset as $element):?>
                        <?=$this->formElement($element)?>
                    <?php endforeach;?>
                <?php endforeach;?>
                <?php if ($facets):?>
                    <?php $activeFacets = $facets->getActiveValues();?>
                    <?php foreach ($activeFacets as $facetName => $facetValues):?>
                        <div class="controls controls-row row">
                            <div class="col-md-3 yk-label">
                                <label><?=$this->translate($facets->getTitle($facetName))?></label>
                            </div>
                            <div class="col-md-9">
                                <?php foreach ($facetValues as $facetValue):?>
                                    <span class="label label-info"><?=$facetValue?></span>
                                <?php endforeach;?>
                            </div>
                        </div>
                    <?php endforeach;?>
                <?php endif;?>
            </div>
            <div class="modal-footer">
                <button class="btn btn-default" type="button" data-dismiss="modal" aria-hidden="true"><?=$this->translate('Close') ?></button>
                <button class="btn btn-primary" type="submit"><?=$this->translate('Subscribe') ?></button>
            </div>
            <?=$this->form()->closeTag()?>
        </div>
    </div>
</div>
