<?php
/**
 * YAWIK
 *
 * @filesource
 * @license MIT
 * @copyright  2013 - 2018 Cross Solution <http://cross-solution.de>
 */

$this->headTitle('Kostenlos Einzelinserat aufgeben');
$publishDate = $this->dateFormat(new DateTime(), 'medium', 'none');
$image = isset($this->details['image']['entity']) ? $this->details['image']['entity'] : null;

$imageServerUrl = $this->basePath('modules/Gastro24/images/bg_placeholder_gray.svg');
$hasBanner = false;
if (isset($this->details['image_url'])) {
    $serverUrl = new \Zend\View\Helper\ServerUrl();
    $imageServerUrl = $serverUrl($this->basePath($this->details['image_url']));
    $hasBanner = true;
}
$logoImageUrl = (isset($this->details['logo_url'])) ? $this->basePath($this->details['logo_url']) :
    $this->basePath('modules/Gastro24/images/no-company-logo.png');

$session = new \Zend\Session\Container('Gastro24_SingleJobData');
$sessionData = unserialize($session->data);
?>
<style>
 
iframe {
	background-color: #fff;
	height: 1800px;
	overflow: auto;
	width: 1px;
	min-width: 100%;
}

#single-job-address-form label,
#single-job-form label {
	font-weight: normal;
}

#single-job-address-form input[type="radio"] {
	height: 20px;
	box-shadow: none;
	-webkit-box-shadow: none;
	width: 35px;
	float: left;
}

.gender-field .radioBoxes {
	width: 30%;
	display: flex;
	justify-content: space-between;
}

.gender-field .radioBoxes label {
	display: flex;
	flex-direction: row;
	align-items: center;
}

.steps-form {
	display: table;
	width: 100%;
	position: relative;
	margin-bottom: 10px;
}

.steps-form .steps-row {
	display: table-row;
}

.steps-form .steps-row:before {
	top: 19px;
	bottom: 0;
	position: absolute;
	content: " ";
	width: 68%;
	left: 16%;
	height: 1px;
	background-color: #1e69a3;
}

.steps-form .steps-row .steps-step {
	display: table-cell;
	width: 33.333333%;
	text-align: center;
	position: relative;
}

.steps-form .steps-row .steps-step p {
	margin-top: 0.5rem;
}

.steps-form .steps-row .steps-step button[disabled] {
	opacity: 1 !important;
	filter: alpha(opacity=100) !important;
}

.steps-form .steps-row .steps-step .btn-circle {
	width: 40px;
	height: 40px;
	text-align: center;
	padding: 9px 0;
	font-size: 14px;
	line-height: 1.428571429;
	border-radius: 100%;
	margin-top: 0;
}

.btn-indigo {
	color: #fff;
	background: #1e69a3;
}

.steps-form .btn[disabled] {
	opacity: 1;
	color: #1e69a3;
	border: 1px solid #1e69a3;
}

.steps-step.active p {
	font-weight: bold;
}

@media (max-width: 768px) {
	.positionTextarea .tooltip-insert span {
		right: 0;
		left: 0;
	}
	.positionTextarea .tooltip-insert span::after {
		display: none;
	}
	.tooltip-insert span {
		top: 25px;
		right: 5px;
		left: auto;
		margin-left: 0;
	}
	.tooltip-insert span::after {
		top: 0;
		right: 0px;
		margin-top: -5px;
	}
}

@media (max-width: 468px) {
	.section-body {
		padding: 12px;
	}
}



</style>
<!-- breadcrumbs -->
<div class="row">
    <div class="col-md-12">
        <nav aria-label="breadcrumb">
            <ol class="hidden-xs breadcrumb" itemscope="" itemtype="http://schema.org/BreadcrumbList">
                <li class="breadcrumb-item" itemprop="itemListElement" itemscope="" itemtype="http://schema.org/ListItem">
                    <a itemprop="item" href="/">
                        <span itemprop="name">Home</span>
                    </a>
                    <meta itemprop="position" content="1">
                </li>
                
                <li class="breadcrumb-item" itemprop="itemListElement" itemscope="" itemtype="http://schema.org/ListItem">
                    <a itemprop="item" href="/de/jobs?clear=1">
                        <span itemprop="name">Jobs</span>
                    </a>
                    <meta itemprop="position" content="2">
                </li>
                
                <li class="breadcrumb-item" itemprop="itemListElement" itemscope="" itemtype="http://schema.org/ListItem">
                    <a itemprop="item" href="/lg/stellenanzeigen-schalten">
                        <span itemprop="name">Inserieren</span>
                    </a>
                    <meta itemprop="position" content="3">
                </li>
                
                <li class="breadcrumb-item" itemprop="itemListElement" itemscope="" itemtype="http://schema.org/ListItem">
                    <span itemprop="name">Einzelinserat</span>
                    <meta itemprop="position" content="4">
                </li>
            </ol>
        </nav>
    </div>
</div>
<!-- end breadcrumbs -->

<!-- Header & Pricing -->
<div class="row">
    <div class="col-md-12">
        <div style="max-width:100%;float:none;" class="page-title text-center">
            <h1><span class="hidden-xs">Einzelinserat erfassen – </span>30 Tage kostenlos inserieren</h1>
        </div>
    </div>
    <!--<div class="col-md-6">
        <div class="pull-right">
            <div class="page-title hidden-xs">
                <div>Preis</div>
                <div>Einzelinserat: CHF <em class="total">
                    <?php
                        if(isset($sessionData['totalPrice']) && !empty($sessionData['totalPrice'])){
                            echo $sessionData['totalPrice'];
                        }
                        else {
                            echo '0';
                        }
                    ?>
                </em>.- </div>
            </div>
        </div>
    </div>-->
     <div class="steps-form">
      <div class="steps-row setup-panel">
        <div class="steps-step active">
          <span type="button" class="btn btn-indigo btn-circle">1</span>
          <p>Schritt 1: Job-Details</p>
        </div>
        <div class="steps-step">
          <span type="button" class="btn btn-default btn-circle" disabled="disabled">2</span>
          <p>Schritt 2: Kontaktdaten</p>
        </div>
        <div class="steps-step">
          <span type="button" class="btn btn-default btn-circle" disabled="disabled">3</span>
          <p>Fertig</p>
        </div>
      </div>
    </div>
    
    
    
    
</div>
<!-- Ende --->

<!-- Form -->
<div class="form-container">
    <!-- begin form -->
    <?= $this->form()->openTag($form); ?>

    <!-- section main -->
    <div class="section-body">
        <h2>Stellendetails</h2>
        <div class="row form-group">
            <div class="col-md-11">
                <?= $this->formElementErrors()->setMessageOpenFormat('<div class="alert alert-danger register-form-error">')
                    ->setMessageCloseString('</div>')->render($this->form->get('jobTitle')); ?>
            </div>
            <div class="col-md-11">
                <?= $this->formLabel($this->form->get('jobTitle'), 'Stellentitel'); ?>
                <?= $this->formText($this->form->get('jobTitle')); ?>
            </div>
        </div>
        <div class="row controls controls-row form-group">
            <div class="col-md-12">
                <?= $this->formElementErrors()->setMessageOpenFormat('<div class="alert alert-danger register-form-error">')
                    ->setMessageCloseString('</div>')->render($this->form->get('locations')); ?>

                <?= $this->formElementErrors()->setMessageOpenFormat('<div class="alert alert-danger register-form-error">')
                    ->setMessageCloseString('</div>')->render($this->form->get('employmentTypes')); ?>
            </div>
            <div class="col-md-6 locationsSelect form-group">
                <?= $this->formLabel($this->form->get('locations'), 'Arbeitsort'); ?>
                <?= $this->formElement($this->form->get('locations')); ?>
            </div>

            <div class="col-md-5 employmentTypesSelect form-group">
                <?= $this->formLabel($this->form->get('employmentTypes'), 'Beschäftigungsart'); ?>
                <?= $this->formElement($this->form->get('employmentTypes')); ?>
            </div>
        </div>
        <div class="row form-group positionTextarea">
            <div class="col-md-12">
                <?= $this->formElementErrors()->setMessageOpenFormat('<div class="alert alert-danger register-form-error">')
                    ->setMessageCloseString('</div>')->render($this->form->get('position')); ?>
            </div>
            <div class="col-md-11">
                <?= $this->formLabel($this->form->get('position'), 'Stellenbeschreibung'); ?>
                <?= $this->formElement($this->form->get('position')); ?>
            </div>
            <div class="col-md-1">
                <label class="tooltip-insert"><i class="fa fa-info-circle"></i>
                    <input type="checkbox">
                    <span>Beschreiben Sie die Stellenanzeige mit so vielen Details wie möglich. Sie können Text ausschneiden und in dieses Feld einfügen. HTML und Nicht-Standard-Zeichen werden nicht unterstützt. Beispiele für Informationen, die enthalten sein sollten:<br /><br /><ul><li>Einleitung zu Ihrer Stellenanzeige.</li><li>Mehr über die erforderlichen Fähigkeiten. </li><li>Weitere Anforderungen wie Ausbildung und/oder jahrelange Erfahrung.</li><li>Weitere Angebote kostenlose Unterkunft, Zustupf an die Weiterbildung, etc.</li></ul></span>
                </label>
            </div>
        </div>
        <div class="row form-group pdf-link-text">
            <div class="col-md-12">
                <p>oder <a style="text-decoration:underline;" class="pdf-link" href="#">PDF-Inserat erfassen</a></p>
            </div>
        </div>
        <div class="row form-group pdf-upload" id="pdf-span">
            <div class="col-md-11">
                <?= $this->formLabel($this->form->get('pdf'), 'Stellenbeschreibung als PDF<span class="required-mark">*</span>'); ?>
                <div id="pdf-errors" class="errors"></div>
                <?= $this->formElement($this->form->get('pdf')); ?>
            </div>
        </div>
        <div class="row form-group textarea-link-text">
            <div class="col-md-12">
                <p>oder <a style="text-decoration:underline;" class="textarea-link" href="#">Text eingeben</a></p>
            </div>
        </div>

    </div>
    <!-- end section main -->

    <!-- section application -->
    <div class="section-body">
        <h2>Bewerbung</h2>
        <div class="row">
            <div class="col-xs-1 col-sm-1 col-md-1 col-lg-1 application-radio">
                <input type="radio" value="applicationMail" name="enableOnlineApplication"
                    <?php if ($sessionData['enableOnlineApplication'] == 'applicationMail') echo 'checked' ?> />
            </div>
            <div class="col-xs-10 col-sm-10 col-md-10 col-lg-10 application-input">
                <div class="form-group">
                    <?= $this->formLabel($this->form->get('applicationEmail'), 'E-Mail Adresse für Bewerbungen'); ?>
                    <?= $this->formEmail($this->form->get('applicationEmail')); ?>
                </div>
            </div>
            <div class="col-xs-1 col-sm-1 col-md-1 col-lg-1">
                <label class="tooltip-insert"><i class="fa fa-info-circle"></i>
                    <input type="checkbox">
                    <span>Bitte geben Sie die E-Mail Adresse(n) ein, an die Bewerbungen gesendet werden sollen.</span>
                </label>


            </div>
        </div>
        <div class="row form-group">
            <div class="col-xs-1 col-sm-1 col-md-1 col-lg-1 application-radio">
                <input type="radio" value="directLink" name="enableOnlineApplication"
                    <?php if ($sessionData['enableOnlineApplication'] == 'directLink') echo 'checked' ?> />
            </div>
            <div class="col-xs-10 col-sm-10 col-md-10 col-lg-10 application-input">
                <?= $this->formLabel($this->form->get('applicationUri'), 'Direktlink zum Bewerberformular'); ?>
                <?= $this->formUrl($this->form->get('applicationUri')); ?>
            </div>
            <div class="col-xs-1 col-sm-1 col-md-1 col-lg-1">
                <label class="tooltip-insert"><i class="fa fa-info-circle"></i>
                    <input type="checkbox">
                    <span>Sofern Sie auf Ihrer Website ein Bewerbungsformular haben, können Sie die Internet-Adresse hier eingeben. Bewerber werden dann direkt weitergeleitet.</span>
                </label>
            </div>
        </div>
        <div class="row" style="margin-top:15px;">
            <div class="col-xs-1 col-sm-1 col-md-1 col-lg-1 application-radio" style="padding-top:0px" >
                <input type="radio" value="noOnlineApplication" name="enableOnlineApplication"
                    <?php if(!isset($sessionData['enableOnlineApplication'])|| ($sessionData['enableOnlineApplication'] == 'noOnlineApplication')) echo 'checked' ?> />
            </div>
            <div class="col-xs-10 col-sm-10 col-md-10 col-lg-10 application-input">
                <div>
                    Keine Online-Bewerbung. Bitte geben Sie unbedingt eine alternative Kontaktmöglichkeit für Bewerber an.
                </div>
            </div>
        </div>
    </div>
    <!-- end section application -->

    <!-- section company details -->
    <div class="section-body">
        <h2>Firmendaten</h2>
        <div class="row form-group">
            <div class="col-md-11">
                <?= $this->formLabel($this->form->get('company'), 'Unternehmensname'); ?>
                <?= $this->formText($this->form->get('company')); ?>
            </div>
        </div>

        <div class="row form-group">
            <div class="col-xs-11 col-sm-11 col-md-11 col-lg-11 bannerImage-field" id="bannerImage-span">
                <?= $this->formLabel($this->form->get('bannerImage'), 'Bannerbild'); ?>
                <?= $this->formElement($this->form->get('bannerImage')); ?>
            </div>
            <div class="col-xs-1 col-sm-1 col-md-1 col-lg-1">
                <label class="tooltip-insert"><i class="fa fa-info-circle"></i>
                    <input type="checkbox">
                    <span>Ein Bild sagt mehr als 1000 Worte: Mit einem zusätzlichen Bannerbild noch mehr
                        Aufmerksamkeit generieren. Das Bannerbild erscheint zuoberst im Kopfbereich Ihrer Stellenanzeige.
                    </span>
                </label>
            </div>
        </div>
        <div class="row form-group">
            <div class="col-md-6 logo-field form-group" id="logo-span">
                <?= $this->formLabel($this->form->get('logo'), 'Unternehmenslogo'); ?>
                <?= $this->formElement($this->form->get('logo')); ?>
            </div>
            <div class="col-md-5">
                <?= $this->formLabel($this->form->get('companyWebsite'), 'Unternehmenswebsite'); ?>
                <?= $this->formUrl($this->form->get('companyWebsite')); ?>
            </div>
        </div>
        <div class="row form-group">
            <div class="col-xs-11 col-sm-11 col-md-11 col-lg-11">
                <?= $this->formLabel($this->form->get('companyDescription'), 'Unternehmensinformation'); ?>
                <?= $this->formTextarea($this->form->get('companyDescription')); ?>
            </div>
            <div class="col-xs-1 col-sm-1 col-md-1 col-lg-1">
                <label class="tooltip-insert"><i class="fa fa-info-circle"></i>
                    <input type="checkbox">
                    <span>Hier können Sie weitere Informationen zu Ihrem Unternehmen hinterlegen die Bewerber interessieren könnten.</span>
                </label>
            </div>
        </div>
    </div>
    <!-- end section company details -->

    <!-- section publication and addons -->
    <div class="section-body">
        <h2>Publikation</h2>
        <div class="row form-group">
            <div class="col-xs-11 col-sm-11 col-md-11 col-lg-11">
                    <?= $this->formLabel($this->form->get('publishDate'), 'Gewünschtes Aufschaltdatum'); ?>
                    <?php if($this->publishDateError): ?>
                        <div style="color: red; margin: 10px 0;">* Das gewünschte Aufschaltdatum sollte in der Zukunft liegen</div>
                    <?php endif; ?>
                    <?= $this->formDatePicker($this->form->get('publishDate')); ?>
            </div>
            <div class="col-xs-1 col-sm-1 col-md-1 col-lg-1">
                <label class="tooltip-insert"><i class="fa fa-info-circle"></i>
                    <input type="checkbox">
                    <span>Nach unserer persönlichen Kontrolle geht Ihre Anzeige innert 24h oder zu dem von Ihnen definierten Zeitpunkt online.</span>
                </label>
            </div>
        </div>

        <h3>Besetzen Sie Ihre Stellen schneller mit Zusatz-Optionen für mehr Reichweite</h3>

        <div class="row">
            <div class="add_box add_left col-md-4">
                <div>
                    <input type="checkbox" name="addons[]" data-value="15" value="addon_renewal"
                        <?php if (isset($sessionData['addons']) && (in_array('addon_renewal', $sessionData['addons']) !== false)) echo 'checked' ?> >
                    &nbsp;&nbsp;
                    <h3>Verlängerung 90 Tage</h3>
                    <p>Ihre Stellenanzeige bleibt ab Ihrem gewünschtem Aufschaltdatum anstatt 30 Tage, insgesamt 120 Tage online.</p>
                    <p class="add_price"><span class="price_add_1">15 </span> CHF</p>
                </div>
            </div>
            <div class="add_box add_left col-md-4">
                <div>
                    <input type="checkbox" name="addons[]" data-value="95" value="addon_startpage"
                        <?php if (isset($sessionData['addons']) && (in_array('addon_startpage', $sessionData['addons']) !== false)) echo 'checked' ?>>
                    &nbsp;&nbsp;
                    <h3>Auf Startseite anzeigen</h3>
                    <p>Ihre Stellenanzeige wird für die ganze Laufzeit auf der Startseite, direkt unterhalb des Suchformulars prominent angezeigt.</p>
                    <p class="add_price"><span class="price_add_1">95 </span> CHF</p>
                </div>
            </div>
            <div class="add_box add_left col-md-4">
                <div>
                    <input type="checkbox" name="addons[]" data-value="55" value="addon_top_result"
                        <?php if (isset($sessionData['addons']) && (in_array('addon_top_result', $sessionData['addons']) !== false)) echo 'checked' ?>>
                    &nbsp;&nbsp;
                    <h3>Top-Resultat</h3>
                    <p>Ihr Stellenanzeige erscheint bei relevanten Suchanfragen zuoberst vor allen anderen Suchresultaten.</p>
                    <p class="add_price"><span class="price_add_1">55 </span> CHF</p>
                </div>
            </div>
            <div class="add_box add_left col-md-4">
                <div>
                    <input type="checkbox" name="addons[]" data-value="25" value="addon_highlight"
                        <?php if (isset($sessionData['addons']) && (in_array('addon_highlight', $sessionData['addons']) !== false)) echo 'checked' ?>>
                    &nbsp;&nbsp;
                    <h3>Farbliche Hervorhebung</h3>
                    <p>Ihre Stellenanzeige wird farblich in den Suchresultaten hervorgehoben und dadurch besser wahrgenommen.</p>
                    <p class="add_price"><span class="price_add_1">25 </span> CHF</p>
                </div>
            </div>
            <div class="add_box add_left col-md-4">
                <div>
                    <input type="checkbox" name="addons[]" data-value="150" value="addon_facebook"
                        <?php if (isset($sessionData['addons']) && (in_array('addon_facebook', $sessionData['addons']) !== false)) echo 'checked' ?>>
                    &nbsp;&nbsp;
                    <h3>Zusätzliche Facebook Werbung</h3>
                    <p>Wir promoten Ihr Stelleninserat in der relevanten Zielgruppe und Region auf Facebook. Sie erhalten im Anschluss ein Reporting.</p>
                    <p class="add_price"><span class="price_add_1">150 </span> CHF</p>
                </div>
            </div>
        </div>
        <hr />
        <div class="post">
            <h3>Einzelinserat: <span class="currency">CHF</span> <span class="total">
                <?php
                    if(isset($sessionData['totalPrice']) && !empty($sessionData['totalPrice'])){
                        echo $sessionData['totalPrice'];
                    }
                    else {
                        echo '0';
                    }
                ?>
            </span>.-</h3>
        </div>
    </div>
    <!-- end section publication and addons -->

    <?= $this->formHidden($this->form->get('totalPrice')); ?>

    <!-- section buttons -->
    <div class="section-body">
        <div class="row">
            <div class="col-sm-12">
                <div class="btn-toolbar">
                    <button type="button" class="cam-btn-reset single-job-preview-modal-button" data-title="Vorschau anzeigen"
                            data-toggle="modal" data-target="#single-job-preview-modal"
                            title="Vorschau anzeigen">
                        Vorschau anzeigen
                    </button>

<!--                        <button type="reset" name="buttons[cancel]" id="buttons-cancel" -->
<!--                                class="cam-btn-reset" value="Cancel">Vorschau anzeigen</button>-->
                    <?= $this->formButton()->openTag($this->form->get('submit')); ?>
                    <div class="default">Schritt 2: Kontaktdaten &raquo; </div>
                    <?= $this->formButton()->closeTag(); ?>
                </div>
            </div>
        </div>
    </div>
    <!-- end section buttons -->

    <?= $this->form()->closeTag($form); ?>
    <!-- end form -->
</div>
<!-- End Form -->

<!-- Modal Box for Single Job Preview -->
<div class="modal fade" id="single-job-preview-modal" tabindex="-1" role="dialog" aria-labelledby="singleJobLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="singleJobModalLabel">Vorschau</h4>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="panel panel-default panel__job-detail">
                                <!-- Bannerbild -->
                                <div class="banner"></div>
                                <!-- End Bannerbild -->

                                <div class="panel-body">
                                    <!-- company logo and job title-->
                                    <div class="teaser__job-detail">
                                        <div itemprop="logo">
                                            <div class="wrapper__logo">
                                                <img src="<?= $logoImageUrl ?>" alt="<?= $this->organizationName?>">
                                            </div>
                                        </div>
                                        <h1><?= $sessionData['jobTitle'] ?></h1>
                                    </div>
                                    <h1 class="no-banner"><?= $sessionData['jobTitle'] ?></h1>
                                    <!-- end company logo and job title-->

                                    <div class="job-short-info <?php if(!$hasBanner) echo 'no-banner' ?>">
                                        <ul>
                                            <li class="location">
                                                <!-- location -->
                                                <?php
                                                $locationString = '';
                                                foreach ($sessionData['locations'] as $loc) {
                                                    $location = new \Jobs\Entity\Location($loc);
                                                    $locationString .= ' ' . $location->getCity() . ',';
                                                }
                                                $locationString = rtrim($locationString, ",");
                                                echo $locationString;
                                                ?>
                                                <!-- end location -->
                                            </li>
                                            <li class="company">
                                                <!-- company name -->
                                                <strong><?= $sessionData['company'] ?></strong>
                                                <!-- end company name -->
                                            </li>
                                            <li class="type">
                                                <!-- type of contract -->
                                                <?php
                                                $typesArray = [];
                                                foreach ($sessionData['employmentTypes'] as $employmentType) {
                                                    $typesArray[] = ucfirst($employmentType) ?: 'Vollzeit';
                                                }
                                                $typesString = implode(', ', $typesArray);
                                                echo $typesString;
                                                ?>
                                                <!-- end type of contract -->
                                            </li>
                                            <li class="date">
                                                <!-- published date -->
                                                <span><?= $publishDate ?></span>
                                                <!-- end published date -->
                                            </li>
                                        </ul>

                                        <div class="wrapper__right">
                                            <?php if (!$hasBanner): ?>
                                                <div class="wrapper__logo">
                                                    <img src="<?= $logoImageUrl ?>" alt="<?= $this->company?>">
                                                </div>
                                            <?php endif; ?>
                                        </div>
                                    </div>

                                    <hr class="job-details-devider"/>

                                    <div class="embed-container">
                                        <div class="frame-content">
                                            <div id="preload" class="loading hidden text-center">
                                                <div class="spinner">
                                                    <div class="bounce1"></div>
                                                    <div class="bounce2"></div>
                                                    <div class="bounce3"></div>
                                                </div>
                                                <p>Das Inserat wird geladen, bitte haben Sie einem Moment Geduld</p>
                                            </div>
                                            <iframe style="height:122rem" id="iframePdf" src=""></iframe>
                                            <iframe style="height:2500px" id="iframeDirectLink" src=""></iframe>
                                        </div>
                                    </div>

                                    <div class="row html-container">
                                        <div class="col-md-8 col-md-offset-2">

                                            <!-- position -->
                                            <div class="position">
                                                <?= $this->position ?>
                                            </div>

                                            <!-- companyDescription -->
                                            <div class="companyDescription">
                                                <?= $this->companyDescription ?>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>




