<?php
/**
 * YAWIK
 *
 * @filesource
 * @license MIT
 * @copyright  2013 - 2018 Cross Solution <http://cross-solution.de>
 */


$this->headTitle('Kostenlos Einzelinserat aufgeben');
$publishDate = $this->dateFormat(new DateTime(), 'medium', 'none');
$image = isset($this->details['image']['entity']) ? $this->details['image']['entity'] : null;

?>
<?php if (!$this->isProcessed):?>
   <h1>Einzelinserat</h1>
   <hr />
 <?php endif?>
<?php if ($this->isProcessed):?>

<?php if ('html' == $this->details['mode']):?>
    <div class="col-md-12">
        <div class="row">
            
            <div class="panel panel-default panel__job-detail">
                <!-- Bannerbild -->
                <?php if ($image):?>
                    <div class="banner">
                        <img src="<?=$this->basePath($image->getUri())?>">
                    </div>
                <?php endif ?>
                <!-- End Bannerbild -->

                <div class="panel-body">
                    <!-- company logo and job title-->
                    <div class="teaser__job-detail <?php if (!$image) echo 'no-banner'; ?>">
                        <div itemprop="logo">
                            <div class="wrapper__logo">
<!--                                <img src="--><?//= $image
//                                    ? $this->basePath($image->getUri())
//                                    : $this->uriLogo?><!--" alt="--><?//= $this->organizationName?><!--">-->
                            </div>
                        </div>
                        <h1><?=$this->title?></h1>
                    </div>
                    <!-- end company logo and job title-->

                    <div class="job-short-info">
                        <ul>
                            <li class="location">
                                <!-- location -->
                                <?php
                                    $locationString = '';
                                    foreach ($this->locations as $loc) {
                                        $location = new \Jobs\Entity\Location($loc);
                                        $locationString .= ' ' . $location->getCity() . ',';
                                    }
                                    $locationString = rtrim($locationString, ",");
                                    echo $locationString;
                                ?>
                                <!-- end location -->
                            </li>
                            <li class="company">
                                <!-- company name -->
                                <strong><?=$this->invoiceAddress['company']?></strong>
                                <!-- end company name -->
                            </li>

                            <li class="date">
                                <!-- published date -->
                                <span><?= $publishDate ?></span>
                                <!-- end published date -->
                            </li>
                        </ul>
                    </div>

                    <hr class="job-details-devider"/>

                    <!-- apply button -->
                    <div class="button-job-apply text-center">
                        <a style="background-color: #d9534f;border-color: #d43f3a" class="btn btn-primary"
                           href="?do=complete">Einzelinserat jetzt schalten</a>
                    </div>
                    <!-- end apply button -->

                    <!-- job content -->
                    <?php if ($this->html): ?>
                        <div class="position">
                            <?=$this->html?>
                        </div>
                    <?php else: ?>
                        <!-- introduction -->
                        <div class="introduction">
                            <?=$this->details['introduction']?>
                        </div>

                        <!-- position -->
                        <div class="position">
                            <?=$this->details['position']?>
                        </div>

                        <!-- requirements -->
                        <div class="position">
                            <?=$this->details['requirements']?>
                        </div>

                        <!-- qualifications -->
                        <div class="position">
                            <?=$this->details['qualifications']?>
                        </div>

                        <!-- benefits -->
                        <div class="position">
                            <?=$this->details['benefits']?>
                        </div>
                    <?php endif; ?>
                    <!-- end job content -->

                    <hr />

                    <!-- company description -->
                    <p>
                        <?=$this->details['description']?>
                    </p>
                    <!-- end company description -->

                    <!-- apply button -->
                    <div class="button-job-apply text-center">
                        <a style="background-color: #d9534f;border-color: #d43f3a" class="btn btn-primary"
                           href="?do=complete">Einzelinserat jetzt schalten</a>
                    </div>
                    <!-- end apply button -->

                    <hr class="job-details-devider"/>

                    <!-- share buttons -->
<!--                    <div>Diesen Job teilen: </div>-->
<!--                    <div id="share" class="pull-left round-shares"></div>-->
<!--                    <div class="clearfix"></div>-->
                    <!-- end share buttons -->

                    <h3>Rechnungsanschrift (kostenlos bis Mitte 2019)</h3>
                    <address>
                        <?=$this->invoiceAddress['company']?><br>
                        <?=$this->invoiceAddress['name']?> ( <?=$this->link($this->invoiceAddress['email']) ?> )<br>
                        <?=$this->invoiceAddress['street']?> <?=$this->invoiceAddress['houseNumber']?><br>
                        <?=$this->invoiceAddress['zipCode']?> <?=$this->invoiceAddress['city']?><br>
                        <?=$this->invoiceAddress['region'] ?><br /><?=$this->invoiceAddress['country']?>
                    </address>
                </div>
             </div>
        </div>
    </div>
<?php else: ?>
    <div class="col-md-12">
        <div class="row">
            <iframe style="background-color: #fff; width: 100%; height: 1800px;overflow: auto;" class="panel panel-default" frameborder="0" allowfullscreen="" src="<?= $this->details['uri'] ?>"></iframe>
        </div>
    </div>
<?php endif ?>
    <!--            <div class="col-md-3">-->
<!--               <div class="panel panel-default">-->
<!--                   <div class="panel-body">-->
<!--                      <div itemprop="logo" style="text-align:center; margin-bottom:15px">-->
<!--                         --><?php //$logo=isset($this->details['logo']['entity'])
//                                ? $this->details['logo']['entity'] : null;
//                            if ($logo):?>
<!--                                       <div  style=" -->
<!--                                          margin: 0 auto;-->
<!--                                          width: 115px;-->
<!--                                          height: 115px;   -->
<!--                                          transition: border .2s ease-in-out;-->
<!--                                          position: relative;-->
<!--                                          display: block;-->
<!--                                          padding: 4px;-->
<!--                                          line-height: 1.5;-->
<!--                                          background-color: #fff;-->
<!--                                          border: 1px solid #ddd;-->
<!--                                          border-radius: 3px;-->
<!--                                        overflow: hidden;">-->
<!--                                             <img style="-->
<!--                                             margin-bottom: auto;-->
<!--                                             text-align: center;-->
<!--                                             width: 65%;-->
<!--                                             position: absolute;-->
<!--                                             top: 5%;-->
<!--                                             bottom: 5%;-->
<!--                                             left: 5%;-->
<!--                                             right: 5%;-->
<!--                                             margin: auto;" src="--><?//=$this->basePath($logo->getUri())?><!--">-->
<!--                                       </div>-->
<!---->
<!--                            --><?php //endif?>
<!--                       </div>-->
<!--                -->
<!--                      <h2 class="text-center">--><?//= $this->invoiceAddress['company']?><!--</h2>-->
<!--         -->
<!--                    </div>-->
<!--               </div>-->
<!--            </div>-->
        
            
         
                    
      
      
      
      
      
      

           
            

            
     
     
     

       
       
       
       
  
       
<?php elseif ($this->isSuccess): ?>

       
 <div class="panel panel-default">     
    <div class="panel-body">  
    <?=$this->alert()->success('Inserat erfolgreich angelegt.');?>
    <p class="lead">Vielen Dank.</p>
    <p>Ihre Anzeige wurde angelegt. Nach der Prüfung wird sie freigeschaltet.</p>
<?php elseif ($this->isError): ?>
    <?=$this->alert()->danger('Inserat anlegen fehlgeschlagen');?>
    <p class="lead">Das Inserat konnte nicht angelegt werden.</p>
<p>Es ist ein Fehler aufgetreten. Versuchen Sie es <a href="">erneut</a> ...</p>

     </div>
   </div>
<?php else: ?>
<div class="container"><div class="row"><div class="col-md-12">
            <?=$this->form($this->form->setAttribute('data-handle-by', 'native'))?>
</div></div></div>
<?php endif ?>



