<!-- Event snippet for Einzelinserat gekauft conversion page -->
<script>
  gtag('event', 'conversion', {
      'send_to': 'AW-980688466/qj3KCISa0tkBENK80NMD',
      'transaction_id': ''
  });
</script>



<!-- breadcrumbs -->
<div class="sub-navigation-wrapper"></div>

<!-- end breadcrumbs -->


<div class="row">
<div class="col-md-4">
    <div class="stand-alone-card">
      

      <ol class="steps">
            <li>Stellendetails eingeben</li>
            <li>Ihre Kontaktdaten</li>
            <li class="step-active">Fertig</li>
        </ol>

   </div>
</div>
</div>

<div class="col-md-8 form-container extra-content">
 <div class="stand-alone-card">
    <div class="info-card">

           <?=$this->alert()->success('Inserat erfolgreich angelegt.');?>
            <h1>Gut gemacht! Ihr Einzelinserat wurde erfolgreich übermittelt</h1>
            <p>Nach der Prüfung wird das Inserat umgehend freigeschaltet und Sie erhalten eine E-Mail.</p>


  </div>
</div>


</div>
