<?php
    $session = new \Laminas\Session\Container('Gastro24_SingleJobData');
    $sessionData = unserialize($session->data);
?>


    <!-- breadcrumbs -->
   <div class="sub-navigation-wrapper"></div>
    <!-- end breadcrumbs -->

<div class="row">
<div class="col-md-4">
    <div class="stand-alone-card">
        <div class="info-card">
            <ol class="steps">
            <li>Stellendetails eingeben</li>
            <li class="step-active">Ihre Kontaktdaten</li>
            <li>Fertig</li>
            </ol>

        </div>
    </div>
    <div class="stand-alone-card" style="margin-top:15px;">
       <div class="extra-content info-card">
    
        <?php if ($this->payment) : ?>
     
            <h2>Ihre Bestellübersicht</h2>
            <?php foreach ($this->formattedAddons as $addon ) : ?>
                <div class="row form-group">
                    <div class="col-xs-1 col-sm-1 col-md-1 col-lg-1 summary-options">
                        <input type="checkbox" disabled="disabled" checked="checked">
                    </div>
                    <div class="col-xs-10 col-sm-10 col-md-10 col-lg-10 summary-options-values">
                        <span><?= $addon['name'] . ' - CHF' . $addon['price'] . '.-' ?></span>
                    </div>
                </div>
            <?php endforeach; ?>
            <div class="row form-group">
                    <div class="col-xs-1 col-sm-1 col-md-1 col-lg-1 summary-options">
                        <input type="checkbox" disabled="disabled" checked="checked">
                    </div>
                    <div class="col-xs-10 col-sm-10 col-md-10 col-lg-10 summary-options-values">
                        <span>Einzelinserat Standard 1 Monat - CHF 29.-</span>
                    </div>
                </div>

                <div class="row form-group">
                    <div class="col-xs-1 col-sm-1 col-md-1 col-lg-1 summary-options">
                        <input type="checkbox" disabled="disabled" checked="checked">
                    </div>
                    <div class="col-xs-10 col-sm-10 col-md-10 col-lg-10 summary-options-values">
                        <span>Datumsaktualisierung nach 15 Tagen - <em>inklusive</em> </span>
                    </div>
                </div>

                <div class="row form-group">
                    <div class="col-xs-1 col-sm-1 col-md-1 col-lg-1 summary-options">
                        <input type="checkbox" disabled="disabled" checked="checked">
                    </div>
                    <div class="col-xs-10 col-sm-10 col-md-10 col-lg-10 summary-options-values">
                        <span>Schaltung im Publikationsnetzwerk - <em>inklusive</em> </span>
                    </div>
                </div>

           <hr />
           <p> <a href="<?= $this->url('lang/jobs/single') ?>">&laquo; Job-Boostings ändern / hinzufügen</a></p>

        <div class="post">
        <h3>Total: <span class="total">CHF 
        <?php
        if(isset($sessionData['totalPrice']) && !empty($sessionData['totalPrice'])){
            echo $sessionData['totalPrice'];
        }
        else {
            echo '29';
        }
     ?>.-</span></h3></div>

       
    <?php endif; ?>


      </div>
    </div>   

</div>

<div class="col-md-8 form-container extra-content">
 <div class="stand-alone-card">
    <div class="info-card">

    <?php if ($this->isSuccess): ?>
    <div class="panel panel-default">
        <div class="panel-body">
            <?=$this->alert()->success('Inserat erfolgreich angelegt.');?>
                <p class="lead">Vielen Dank.</p>
                <p>Ihr Einzelinserat wurde angelegt. Nach der Prüfung durch uns wird das Inserat freigeschaltet.</p>
        </div>
    </div>
<?php elseif ($this->isError): ?>
    <div class="panel panel-default">
        <div class="panel-body">
                <?=$this->alert()->danger('Inserat anlegen fehlgeschlagen');?>
            <p class="lead">Das Inserat konnte nicht angelegt werden.</p>
            <p>Es ist ein Fehler aufgetreten. Versuchen Sie es bitte <a href="">erneut</a>.</p>
        </div>
    </div>
<?php else: ?>



        <?= $this->form()->openTag($this->invoiceAddressForm); ?>
        <?php
          $invoiceAddressFieldset = $this->invoiceAddressForm->get('invoiceAddress');
         ?>
        <?php if ($this->payment) : ?>
            <h1>Ihre Kontaktdaten
            <span class="pflicht">Pflichtfelder<span class="required-mark">*</span></span></h1>
            <p>Bitte überprüfen und vervollständigen Sie Ihre Rechnungsadresse.</p>
        <?php else: ?>
            <h1>Ihre Kontaktdaten 
            <span class="pflicht">Pflichtfelder<span class="required-mark">*</span></span></h1>
        <?php endif; ?>

         <div class="row form-group">
            <div class="col-md-12 gender-field">
               <!-- <?= $this->formLabel($this->invoiceAddressForm->get('gender'), 'Anrede'); ?> -->
                <div class="radioBoxes" style="display: flex;">
                    <?= $this->formRadio($this->invoiceAddressForm->get('gender')); ?>
                </div>
            </div>
        </div>
        <div class="row form-group">
            <div class="col-xs-6 col-md-6">
                <?= $this->formLabel($this->invoiceAddressForm->get('firstname'), 'Vorname'); ?>
                <?= $this->formText($this->invoiceAddressForm->get('firstname')); ?>
            </div>
            <div class="col-xs-6 col-md-6">
                <?= $this->formLabel($this->invoiceAddressForm->get('lastname'), 'Name'); ?>
                <?= $this->formText($this->invoiceAddressForm->get('lastname')); ?>
            </div>
        </div>
      
        <div class="row form-group">
            <div class="col-md-12">
                <?= $this->formLabel($invoiceAddressFieldset->get('company'), 'Unternehmen'); ?>
                <?= $this->formText($invoiceAddressFieldset->get('company')); ?>
            </div>
        </div>
        <div class="row form-group">
            <div class="col-md-12">
                <?= $this->formLabel($invoiceAddressFieldset->get('street'), 'Strasse / Nr.'); ?>
                <?= $this->formText($invoiceAddressFieldset->get('street')); ?>
            </div>
        </div>
        <div class="row form-group">
            <div class="col-xs-6 col-md-6">
                <?= $this->formLabel($invoiceAddressFieldset->get('zipCode'), 'PLZ'); ?>
                <?= $this->formText($invoiceAddressFieldset->get('zipCode')); ?>
            </div>
          <div class="col-xs-6 col-md-6">
                <?= $this->formLabel($invoiceAddressFieldset->get('city'), 'Ort'); ?>
                <?= $this->formText($invoiceAddressFieldset->get('city')); ?>
            </div>

        </div>
        <div class="row form-group">
            <div class="col-md-12">
                <?= $this->formLabel($invoiceAddressFieldset->get('region'), 'Land'); ?>
                <?= $this->formText($invoiceAddressFieldset->get('region')); ?>
            </div>
        </div>
        <div class="row form-group">
            <div class="col-md-12">
                <?= $this->formLabel($invoiceAddressFieldset->get('email'), 'E-Mail'); ?>
                <?= $this->formEmail($invoiceAddressFieldset->get('email')); ?>
            </div>
        </div>
        <div class="row form-group">
            <div class="col-md-12">
                <?= $this->formLabel($this->invoiceAddressForm->get('phonenumber'), 'Telefon'); ?>
                <?= $this->formText($this->invoiceAddressForm->get('phonenumber')); ?>
            </div>
        </div>

<hr />
   <?php if ($this->payment) : ?>
        <?php
            $otherAddressFieldset = $this->invoiceAddressForm->get('otherAddress');
        ?>
 
            <h1>Abweichende Rechnungsadresse?</h1>
            <div class="row form-group">
                <div class="col-md-12">
                    <?= $this->formElement($this->invoiceAddressForm->get('toggleOtherAddress')); ?>
                </div>
            </div>
            <div class="otherAddressForm">
              <div class="row form-group">
                    <div class="col-md-12 gender-field">
                        <?= $this->formLabel($this->invoiceAddressForm->get('gender-other-address'), 'Anrede'); ?>
                        <div class="radioBoxes" style="display: flex;">
                            <?= $this->formRadio($this->invoiceAddressForm->get('gender-other-address')); ?>
                        </div>
                    </div>
                </div>
                <div class="row form-group">
                    <div class="col-xs-6 col-md-6">
                        <?= $this->formLabel($this->invoiceAddressForm->get('firstname-other-address'), 'Vorname'); ?>
                        <?= $this->formText($this->invoiceAddressForm->get('firstname-other-address')); ?>
                    </div>
                    <div class="col-xs-6 col-md-6">
                        <?= $this->formLabel($this->invoiceAddressForm->get('lastname-other-address'), 'Name'); ?>
                        <?= $this->formText($this->invoiceAddressForm->get('lastname-other-address')); ?>
                    </div>
                </div>
              
                <div class="row form-group">
                    <div class="col-md-12">
                        <?= $this->formLabel($otherAddressFieldset->get('street'), 'Strasse / Nr.'); ?>
                        <?= $this->formText($otherAddressFieldset->get('street')); ?>
                    </div>
                </div>
                <div class="row form-group">
                    <div class="col-xs-6 col-md-6">
                        <?= $this->formLabel($otherAddressFieldset->get('zipCode'), 'PLZ'); ?>
                        <?= $this->formText($otherAddressFieldset->get('zipCode')); ?>
                    </div>
               
                    <div class="col-xs-6 col-md-6">
                        <?= $this->formLabel($otherAddressFieldset->get('city'), 'Ort'); ?>
                        <?= $this->formText($otherAddressFieldset->get('city')); ?>
                    </div>
                </div>
                <div class="row form-group">
                    <div class="col-md-12">
                        <?= $this->formLabel($otherAddressFieldset->get('region'), 'Land'); ?>
                        <?= $this->formText($otherAddressFieldset->get('region')); ?>
                    </div>
                </div>
            </div>
        
    <?php endif; ?>


    <hr />


    <h1>Allgemeine Geschäftsbedingungen</h1>
        <div class="row form-group">
            <div class="col-md-12">
                <?= $this->formElement($this->invoiceAddressForm->get('termsAccepted')); ?>
            </div>
        </div>

<hr />

    <div class="section-body">
        <div class="row">
            <div class="col-sm-12">
                <div class="btn-toolbar">
                    <a type="button" href="<?= $this->url('lang/jobs/single') ?>" class="cam-btn-reset"
                            title="Zurück">&laquo; Zurück und Inserat überarbeiten
                    </a>
                    <?= $this->formButton()->openTag($this->invoiceAddressForm->get('submit')); ?>
                    <div class="default">Fertig</div>
                    <?= $this->formButton()->closeTag(); ?>
                </div>
            </div>
        </div>
    </div>



<?= $this->form()->closeTag($this->invoiceAddressForm); ?>
    <!-- end form -->
<?php endif; ?>
   </div>
  </div>
 </div>
</div>






