<style>

    
    .steps-form {
	display: table;
	width: 100%;
	position: relative;
	margin-bottom: 10px;
}

.steps-form .steps-row {
	display: table-row;
}

.steps-form .steps-row:before {
	top: 19px;
	bottom: 0;
	position: absolute;
	content: " ";
	width: 68%;
	left: 16%;
	height: 1px;
	background-color: #1e69a3;
}

.steps-form .steps-row .steps-step {
	display: table-cell;
	width: 33.333333%;
	text-align: center;
	position: relative;
}

.steps-form .steps-row .steps-step p {
	margin-top: 0.5rem;
}

.steps-form .steps-row .steps-step button[disabled] {
	opacity: 1 !important;
	filter: alpha(opacity=100) !important;
}

.steps-form .steps-row .steps-step .btn-circle {
	width: 40px;
	height: 40px;
	text-align: center;
	padding: 9px 0;
	font-size: 14px;
	line-height: 1.428571429;
	border-radius: 100%;
	margin-top: 0;
}

.btn-indigo {
	color: #fff;
	background: #1e69a3;
}

.steps-form .btn[disabled] {
	opacity: 1;
	color: #1e69a3;
	border: 1px solid #1e69a3;
}

.steps-step.active p {
	font-weight: bold;
}

</style>
<div class="row">
    <div class="col-md-12">
        <div class="page-title text-center">
            <h1>Einzelinserat erfassen</h1>
        </div>
    </div>

 <div class="steps-form">
      <div class="steps-row setup-panel">
        <div class="steps-step active">
          <span type="button" class="btn btn-default btn-circle" disabled="disabled">1</span>
          <p>Schritt 1: Job-Details</p>
        </div>
        <div class="steps-step">
          <span type="button" class="btn btn-default btn-circle" disabled="disabled">2</span>
          <p>Schritt 2: Kontaktdaten</p>
        </div>
        <div class="steps-step">
          <span type="button" class="btn btn-indigo btn-circle">3</span>
          <p>Fertig</p>
        </div>
      </div>
    </div>

  </div>

<div class="panel panel-default">
    <div class="panel-body">
        <?=$this->alert()->success('Inserat erfolgreich angelegt.');?>
            <p class="lead">Vielen Dank.</p>
            <p>Ihr Einzelinserat wurde angelegt. Nach der Prüfung wird das Inserat freigeschaltet.</p>
    </div>
</div>