<?php //description: Renders the list of public jobs. ?>
<?php
$this->headLink()->prependStylesheet($this->basePath($this->asset('modules/Gastro24/Gastro24.css')));
$this->headLink()->prependStylesheet($this->basePath('/dist/css/jquery-ui-1-12.min.css'));

$this->headScript()->appendFile($this->basepath('/modules/Core/js/core.pagination-container.js'))
    ->appendFile($this->basePath('modules/Core/js/core.forms.js'))
    ->appendFile($this->basePath($this->asset('modules/Gastro24/js/jobs.js')))
    ->appendFile($this->basePath('/dist/js/bootstrap-dialog.min.js'));
?>

<?php
$queryGet = $this->params()->fromQuery();
unset($queryGet['clear']);
$query = $this->params()->fromRoute('wpId') ?: (count($queryGet) ? 0 : 304);
$wordpress = $this->proxy('wordpress');

$this->headMeta()->setName('description', $wordpress->chain(['page' => $query, 'value' => 'meta-fields.description'], ''));
//$this->headMeta()->setName('keywords', $wordpress->call('value', ['meta-fields.keywords'], ''));
$description = $wordpress->call('value', ['content.rendered'], '');

$title = $wordpress->call('value', ['meta-fields.title'], '');
$this->headTitle($title ?: $this->translate('Jobs'));

 
$robots = "noindex,follow";

 if (!count($this->jobs)) {
    $jobsLandingpage = "https://www.gastrojob24.ch/de/jobs?clear=1";
    $this->headLink()->headLink(array('rel' => 'canonical', 'href' => $jobsLandingpage));
 }

if (304 === $query || ($this->params()->fromRoute('isLandingPage') && !$this->params()->fromRoute('isFilteredLandingPage') && (!count($this->jobs) || $description))) {

//if (304 === $query || ($this->params()->fromRoute('isLandingPage') && !$this->params()->fromRoute('isFilteredLandingPage') && (count($this->jobs) || $description))) {
    $robots = substr($robots, 2);

    // set canonical link - but not on landing pages
    if (!$this->params()->fromRoute('isLandingPage')) {
        $jobUrl = $this->serverUrl() . $this->url('lang/jobboard', [], [], true);
        $this->headLink()->headLink(array('rel' => 'canonical', 'href' => $jobUrl), 'PREPEND');
    }
}


$this->headMeta()->setName('robots', $robots);


$this->headScript()->captureStart();

?>



(function($) {

    $(function() {
        var $tabbar = $('#search-tabs');

        $('#jobs-list-container').on('yk-paginator-container:loaded.gastro24 g24-jobs:init', function(ev) {
            $tabbar.show();
            var html = $('#jobs-list-container').find('.pagination-content').html();

            if ('' === html.trim()) { $tabbar.hide(); }

            $('#jobs-list-container ul.pagination a, link[rel="prev"], link[rel="next"]').each(function() {
                var $a = $(this), href = $a.attr('href');
                console.debug($a, href);
                if (href) {
                    href = href.replace(/__region_MultiString/, 'r')
                               .replace(/__city_MultiString/, 'l')
                               .replace(/__organizationTag/, 'c')
                               .replace(/__profession_MultiString/, 'p')
                               .replace(/__industry_MultiString/, 'i')
                               .replace(/__employmentType_MultiString/, 't');
                    $a.attr('href', href);
                }
            });


        }).trigger('g24-jobs:init');

        var $jobCount = $('#job-count');

        $('#jobs-list-container').on('yk-paginator-container:loaded.gastro24-job-count', function(ev) {
            var count = $('#update-job-count').text();
            $jobCount.text(count);
        });

        $('#jobs-list-filter').on('reset.gastro24', function(ev) { $(ev.target).find('input.facet-param').remove(); });

    });
    

    
})(jQuery);
<?php $this->headScript()->captureEnd();?>

<?php if ($jobs instanceof \Solr\FacetsProviderInterface): $this->headScript()->appendFile($this->basePath('modules/Gastro24/js/jobs.facets.js')); endif; ?>

<?php echo $this->flashMessenger()->render('default', array('alert', 'alert-success')) ?>

<!-- search form container -->
<?= $this->partial('partials/search-form-container.phtml', [
    'jobs' => $this->jobs,
    'filterForm' => $this->filterForm,
]); ?>
<!-- end search form container -->







    <div class="row">
        <div class="tab-content">
            
            
            <div id="jobs-list-container" class="pagination-container">
                 
                
                   <?php if (!count($this->jobs)):?>
                          
                          <style>
                              .form-container .form-content > button, .btn-info, .jobmail-listings {display:none!important;}
                              
                          </style>
                            <?=$this->proxy('jobsByMailSubscriptionForm')->render($jobs)?>
                     
                        <script type="text/javascript">
                            ;(function($) {
                                $(function() {
                                    $('#form-jobsbymail-subscribe-form').find('button.btn-info').hide().click()
                                        .end().find('#job-by-mail-subscribe-label').html('Informiert werden, sobald Jobs zu Ihrer Suchanfrage verfügbar sind.');
                                    $('#jobs-list-container').data('container').$message.show();
                                });
                            })(jQuery);
                        </script>
                        
                        
                              <div class="col-md-12">
                      
                                    <div class="alert alert-warning">
                                        <strong>Leider haben wir keine Stellenanzeigen, die Ihrer Suchanfrage entsprechen.</strong>
                                    </div>
                                  </div>
                 
                  
           
    
                 <?php endif ?>


          
                    
                <div class="container pagination-content">
                    <div class="row">
                       <?php echo $this->render('jobs/jobboard/index.ajax.phtml') ?>
                    </div>

                </div>
                  



         
              
            </div>

        </div>
    </div>



<div class="modal fade" id="job-apply-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
    <div class="modal-dialog" style="width: 90%; height: 90%" role="document">
        <div class="modal-content" style="height: 100%">
            <div class="modal-body" style="height: calc(100% - 65px)">

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Schliessen</button>
            </div>
        </div>
    </div>
