<?php
/**
 * YAWIK
 *
 * @filesource
 * @copyright (c) 2013 - 2016 Cross Solution (http://cross-solution.de)
 * @license   MIT
 */

// We only want to render something, if there are items.
if (count($jobs)): ?>
    <div class="hidden" id="update-job-count">
        <?=$this->jobs->getTotalItemCount()?>
    </div>

    <?php
        /** @var \Gastro24\Options\TopJobsOptions $topJobOptions */
        $topJobOptions = $this->services(\Gastro24\Options\TopJobsOptions::class);
        $topJobsOrganizations = $topJobOptions->getOrganizationNames();
        $topJobsIds = $topJobOptions->getJobIds();

        $hasFacets = $jobs instanceof \Solr\FacetsProviderInterface;
        $queryGet = $this->params()->fromQuery();
        unset($queryGet['clear']);
        $query = $this->params()->fromRoute('wpId') ?: (count($queryGet) ? 0 : 304);
        $wordpress = $this->proxy('wordpress');
        $searchTerm = (isset($queryGet['q']) && is_string($queryGet['q'])) ? trim($queryGet['q'],'"') : null;
        $hasRegion= isset($queryGet['region_MultiString']);
        $hasCity= isset($queryGet['city_MultiString']);
        //$breadcrumbText = $options->$text;
        $dateFilterValue = isset($queryGet['dateFilter']) ? $queryGet['dateFilter'] : '';

        $this->headMeta()->setName('description', $wordpress->chain(['page' => $query, 'value' => 'meta-fields.description'], ''));
        $description = $wordpress->call('value', ['content.rendered'], '');
        $wordpressTitle = '';

        if ($this->params()->fromRoute('isLandingPage')) {
            //$wordpressTitle = $wordpress->call('value', ['title.rendered'], '');
            //$descriptionText = 'Aktuell ' . $this->jobs->getTotalItemCount() . ' verfügbare ' .
                $descriptionText = $wordpress->call('value', ['meta-fields.title'], '').
                $wordpressTitle . ' finden auf Gastrojob24.ch, der #1 Gastronomie & Hotellerie Jobbörse der Schweiz.';
            if ($this->jobs->getTotalItemCount() == 1) {
               // $descriptionText = 'Aktuell ' . $this->jobs->getTotalItemCount() . ' verfügbaren ' .
                    $descriptionText = $wordpress->call('value', ['meta-fields.title'], '').
                    $wordpressTitle . ' finden auf Gastrojob24.ch, der #1 Gastronomie & Hotellerie Jobbörse der Schweiz.';
            }

            $titleOgText = $this->jobs->getTotalItemCount() . ' ' . $wordpress->call('value', ['title.rendered'], '') . ' verfügbar - Gastrojob24.ch.';
            $descriptionOgText = 'Jetzt Traumjob finden aus '. $this->jobs->getTotalItemCount() . ' ' . $wordpress->call('value', ['title.rendered'], '') . ' bei Gastrojob24.ch - der Gastronomie & Hotellerie Jobbörse der Schweiz.';
            $this->headMeta()->setName('description', $descriptionText)
                ->setProperty('og:title', $titleOgText)
                ->setProperty('og:description', $descriptionOgText)
                ->setProperty('og:url', 'https://www.gastrojob24.ch' . $this->url('lang/landingPage', ['q' => $this->params()->fromRoute('term'), 'format' => 'html'], true))
                ->setProperty('og:image', 'https://www.gastrojob24.ch/modules/Gastro24/gastro-logo-fb.png')
                ->setProperty('og:locale', 'de_DE')
                ->setProperty('og:type', 'website')
                ->setAutoEscape(false);
        }

        $container = new \Laminas\Session\Container('gastro24_jobboardcontainer');
        $container->fromCompanyProfile = false;
        $container->searchTerm = $searchTerm;

        $savedJobsContainer = new \Laminas\Session\Container('gastro24_savedjobs');
        $defaultLogoUrl = $this->basePath('modules/Gastro24/images/no-company-logo.png');
    ?>
    <?php if ($hasFacets):
        /*if ($this->params()->fromRoute('isLandingPage')):?>
            <span class="facets-url" data-url="<?=$this->url('lang/landingPage', ['q' => $this->params()->fromRoute('term'), 'format' => 'html'], true)?>"></span>
        <?php endif;*/
        /** @var \Gastro24\Paginator\JobsBoardFacets $facets */
        $facets = $jobs->getFacets();
        $activeFacets = $facets->getActiveValues();
    ?>
<?php endif;?>
<div class="row">
    <div class="col-md-12">
           <?php
                /** @var \Gastro24\Options\Landingpages $landingpagesOptions */
                 $landingpagesOptions = $this->services(\Gastro24\Options\Landingpages::class);
          ?>

    <?php if ($searchTerm) { ?>
      <nav aria-label="breadcrumb" class="job-detail-breadcrumb-nav">
        <ol class="breadcrumb" itemscope itemtype="http://schema.org/BreadcrumbList">
            <li class="breadcrumb-item" itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">
                <a itemprop="item" href="/">
                    <span itemprop="name">Home</span>
                </a>
                <meta itemprop="position" content="1"/>
            </li>


           


            <?php if ($this->params()->fromRoute('isLandingPage')) : ?>

               <li class="breadcrumb-item" itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">
                <a title="Jobs" itemprop="item" href="/de/jobs?clear=1">
                    <span itemprop="name">Jobs</span>
                </a>
                <meta itemprop="position" content="2"/>
               </li>

                <!-- build parent breadcrumbs -->
                <?php
                    $mainTerm = $searchTerm;
                    $content = 3;
                    $parentsBreadcrumbHtml = '';
                    while ($parentTermData = $landingpagesOptions->getParentByTerm($mainTerm)) {
                        $breadcrumbHtml = '<li class="breadcrumb-item" itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">' .
                            '<a title="' . $parentTermData['parent']['query']['q'] . ' Jobs" itemprop="item" href="' . $this->url('lang/landingPage', ['q' => $parentTermData['searchTerm'], 'format' => 'html' ], true) . '">' .
                                '<span itemprop="name"> ' . $parentTermData['parent']['query']['q'] . '</span></a>' .
                            '<meta itemprop="position" content="' . $content . '"/></li>';
                        $content++;
                        $mainTerm = $parentTermData['parent']['query']['q'];
                        $parentsBreadcrumbHtml = $breadcrumbHtml . $parentsBreadcrumbHtml;
                    }
                    echo $parentsBreadcrumbHtml;
                ?>
                <li class="breadcrumb-item active" itemprop="itemListElement" itemscope
                    itemtype="http://schema.org/ListItem" aria-current="page">

                    <span itemprop="name"> <h1><?=$this->jobs->getTotalItemCount() ?> <?=$wordpress->call('value', ['title.rendered'], '') ?: (count($this->jobs) ? 'Treffer' : 'Leider keine passenden Jobs gefunden'); ?></h1></span>
                    <meta itemprop="position" content="<?= $content ?>"/>
                </li>

            <?php else: ?>

              <li class="breadcrumb-item" itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">
                <a title="Jobs" itemprop="item" href="/de/jobs?clear=1">
                    <span itemprop="name">Jobs</span>
                </a>
                <meta itemprop="position" content="2"/>
            </li>


                <li class="breadcrumb-item active" itemprop="itemListElement" itemscope
                itemtype="http://schema.org/ListItem" aria-current="page">
             
                 <span itemprop="name"> <h1><?=$this->jobs->getTotalItemCount()?> Treffer</h1></span>
                
                <meta itemprop="position" content="3"/>
            </li>


            <?php endif; ?>
        </ol>
    </nav>

<?php } else { ?>
   <nav aria-label="breadcrumb" class="job-detail-breadcrumb-nav">
        <ol class="breadcrumb" itemscope itemtype="http://schema.org/BreadcrumbList">
            <li class="breadcrumb-item" itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">
                <a itemprop="item" href="/">
                    <span itemprop="name">Home</span>
                </a>
                <meta itemprop="position" content="1"/>
            </li>
            
           <li class="breadcrumb-item" itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">
                <a title="Jobs" itemprop="item" href="/de/jobs?clear=1">
                    <span itemprop="name">Jobs</span>
                </a>
                <meta itemprop="position" content="2"/>
            </li>

             <li class="breadcrumb-item active" itemprop="itemListElement" itemscope
                itemtype="http://schema.org/ListItem" aria-current="page">
             
                 <span itemprop="name"> <h1><?=$this->jobs->getTotalItemCount() ?> <?=$wordpress->call('value', ['title.rendered'], '') ?: (count($this->jobs) ? 'Treffer' : 'Leider keine passenden Jobs gefunden'); ?></h1></span>
                
                <meta itemprop="position" content="3"/>
            </li>
        </ol>
    </nav>

<?php }; ?>





<div class="row job-results-container">
    <div class="col-md-12 container__date-filter">
        <!-- filter icon on mobile -->
        <div class="container--filter">
            <span class="filter-icon <?= ($activeFacets) ? 'active' : '' ?>">
                <a data-toggle="collapse" href="#facets-container" aria-expanded="false" aria-controls="facets-container">
                    <i class="fa fa-sliders" aria-hidden="true"></i>
                </a>
            </span>
        </div>
        <!-- end filter icon on mobile -->
    </div>
     <div class="col-md-3 container--facets dont-collapse-sm collapse <?= ($activeFacets) ? 'in' : '' ?>"
          aria-expanded="<?= ($activeFacets) ? 'true' : 'false' ?>" id="facets-container">
        <!-- list active filters -->
        <?php if ($activeFacets):?>
            <div class="well well-sm">
                <?php foreach ($activeFacets as $facetName => $facetValues):?>
                    <?php foreach ($facetValues as $facetValue):?>
                        <?php if($facetValue == '1440'): ?>
                            <button type="button" class="btn btn-primary btn-sm facet-active"
                                    data-name="<?=$this->escapeHtmlAttr($facetName)?>[<?=$this->escapeHtmlAttr($facetValue)?>]"
                                    title="<?=$this->translate('Remove filter')?>">neuer als 24 h <span>&times;</span>
                            </button>
                        <?php elseif($facetValue == '4320'): ?>
                            <button type="button" class="btn btn-primary btn-sm facet-active"
                                    data-name="<?=$this->escapeHtmlAttr($facetName)?>[<?=$this->escapeHtmlAttr($facetValue)?>]"
                                    title="<?=$this->translate('Remove filter')?>">neuer als 3 Tage <span>&times;</span>
                            </button>
                        <?php elseif($facetValue == '10080'): ?>
                            <button type="button" class="btn btn-primary btn-sm facet-active"
                                    data-name="<?=$this->escapeHtmlAttr($facetName)?>[<?=$this->escapeHtmlAttr($facetValue)?>]"
                                    title="<?=$this->translate('Remove filter')?>">neuer als 7 Tage <span>&times;</span>
                            </button>
                        <?php elseif($facetValue == '43200'): ?>
                            <button type="button" class="btn btn-primary btn-sm facet-active"
                                    data-name="<?=$this->escapeHtmlAttr($facetName)?>[<?=$this->escapeHtmlAttr($facetValue)?>]"
                                    title="<?=$this->translate('Remove filter')?>">neuer als 30 Tage <span>&times;</span>
                            </button>
                        <?php else: ?>
                        <button type="button" class="btn btn-primary btn-sm facet-active"
                                data-name="<?=$this->escapeHtmlAttr($facetName)?>[<?=$this->escapeHtmlAttr($facetValue)?>]"
                                title="<?=$this->translate('Remove filter')?>"><?=$facetValue?> <span>&times;</span></button>
                        <?php endif;?>
                    <?php endforeach;?>
                <?php endforeach;?>

                <p>Sie können Ihre Jobsuche weiter einschränken, indem Sie unten ein oder mehrere Filterkriterien auswählen.</p>
                <button type="button" class="btn btn-link facet-reset"><?=$this->translate('Remove all filters')?></button>
            </div>
        <?php endif;?>
        <!-- end list active filters -->
        
         <!-- filter -->
        <div class="panel-group">
            <?php
                    $facetsHtml = '';
                    $isFirstFacet = true;
                    $atLeastOneTotalActive = false;
                    foreach ($facets as $facetName => $facetValues):?>
                <?php $facetOptionsCounter = 0; ?>
                <?php if(count($facetValues)>0): $atLeastOneActive = false; $facetsList = []; ob_start();?>
                <div id="facets-box-<?=$facetName?>" class="panel panel-default">
                    <div class="panel-heading">
                        <a class="facets-heading-<?=$facetName?> <?=$isFirstFacet ?  '%firstCollapsed% ' : '%collapsed%'?>" data-toggle="collapse" data-parent="#facets-box-<?=$facetName?>" href="#facets-box-<?=$facetName?>-content">
                        <?=$this->translate($facets->getTitle($facetName))?>
                             <span class="fa fa-chevron-down"></span>
                        </a>

                    </div>
                    <div id="facets-box-<?=$facetName?>-content" class="panel-collapse collapse <?=$isFirstFacet ? '%firstIn%' : '%in%' ?>">
                    <div class="panel-body">
                        <?php foreach ($facetValues as $facetValue => $facetValueCount):
                            $facetOptionsCounter++;
                            if($facetOptionsCounter > 10) continue;
                            $activeFacet = $facets->isValueActive($facetName, $facetValue);
                            $atLeastOneActive = $atLeastOneActive || $activeFacet;?>
                            <?php if ($facetValueCount) : ?>
                                <div class="filter-links">
                                    <label<?=$activeFacet ? ' class="text-primary"' : ''?>>  <?=$activeFacet ? ' <i class="fa fa-check"></i>' : ''?>
                                        <input type="checkbox" name="<?=$this->escapeHtmlAttr($facetName)?>[<?=$this->escapeHtmlAttr($facetValue)?>]"
                                               class="facet-checkbox"<?=$activeFacet?" checked":""?>>
                                        <?=($facetName == 'publishDateFilter') ? \Gastro24\Paginator\JobsBoardFacets::$formattedPublishDateValue[$facetValue] : $facetValue?> <span class="filter-count"><?=$facetValueCount?></span>
                                    </label>
                                </div>
                            <?php endif; ?>
                        <?php if ($activeFacet): $facetsList[] = $facetValue; endif; endforeach;?>
                    </div>
                    </div> <!-- facets-collaps-* -->
                </div>
                <?php $facetsHtml .= str_replace(
                        ['%in%', '%firstIn%', '%firstCollapsed%', '%collapsed%', '%facetsList%' ],
                        [
                                $atLeastOneActive ? 'in' : '',
                                $atLeastOneActive ? 'in' : '%firstIn%',
                                $atLeastOneActive ? '' : '%firstCollapsed%',
                                $atLeastOneActive ? '' : 'collapsed',
                                join(', ', $facetsList),
                        ],
                        ob_get_clean()
                    ); $atLeastOneTotalActive = $atLeastOneTotalActive || $atLeastOneActive; endif; $isFirstFacet = false;?>
            <?php endforeach;
                echo str_replace(
                        ['%firstCollapsed%', '%firstIn%'],
                        [$atLeastOneTotalActive ? 'collapsed' : '', $atLeastOneTotalActive ? '' : 'in'],
                        $facetsHtml
                );
            ?>
        </div>
       </div>
         

        
         

            <div class="col-md-9">


              <div class="row">
         
                   <div class="col-md-3">
                       <?=$this->proxy('jobsByMailSubscriptionForm')->render($jobs)?>
                   </div>
                </div>




                 <div class="item-group">
                        <?php
                            // get date difference
                            $today = new DateTime();
                        ?>

                        <?php foreach ($jobs as $index => $job): ?>
                            <?php
                                /** @var Solr\Entity\JobProxy $job */
                                $org = $job->getOrganization();
                                $hasJobTemplate = $this->gastroJobTemplate($org);
                                $isIntern = (!$job->getLink() || $hasJobTemplate);
                                $isEmbeddable = $this->gastroIsEmbeddable($job->getLink());
                                $jobHasExternLink = (!$isIntern && !$isEmbeddable);
                                $industries = $job->getClassifications()->getIndustries();
                                $template = $job->getAttachedEntity('gastro24-template');
                                $orgName = $this->jobOrganizationName($job);
                                /* mark as topjob */
                                $additionalCardCss = ((in_array($orgName, $topJobsIds) !== false) ||
                                    (in_array($job->getId(), $topJobsIds) !== false)) ? 'topjob' : '';

                                $isExpired = ($job->getStatus()) ? $job->getStatus()->getName() == \Jobs\Entity\StatusInterface::EXPIRED : false;
                                $orgIsDisabled = false;
                                if ($org && (Organizations\Entity\Organization::PROFILE_DISABLED == $org->getProfileSetting() || is_null($org->getProfileSetting())) ) {
                                    $orgIsDisabled = true;
                                }
                                $href = ($jobHasExternLink) ? $job->getLink() : $this->jobUrl($job, ['linkOnly' => true, 'absolute' => true ]);
                             ?>


 <!-- begin card-->
 <div class="<?= $additionalCardCss ?> card box__job-favorite">
  <?php
    $logoUrl = null;
    if (is_object($org) && is_object($org->getImage()) && $org->getImage()->getUri()) {
     $logoUrl = $this->basePath($this->organizationImageCache->getUri($org->getImage(true)));
        }
     if ($template && ($logo = $template->getLogo())) {
     $logoUrl = $this->basePath($logo->getUri());
     }
    ?>
  <?php if($jobHasExternLink) { ?>
  <a class="stand-alone-card job-logo-link" rel="sponsored noopener" title="<?=strip_tags($job->getTitle())?>" href="<?=$href?>"><img class="job-logo" alt="<?= $orgName ?>" src="<?= $logoUrl ? $logoUrl : $defaultLogoUrl ?>" /></a>
  <?php }
    else { ?>
  <a class="stand-alone-card job-logo-link" title="<?=strip_tags($job->getTitle())?>" href="<?=$href?>"><img class="job-logo" alt="<?= $orgName ?>" src="https://gastrojob24.gumlet.net<?= $logoUrl ? $logoUrl : $defaultLogoUrl ?>?mode=fit&width=90&height=90&quality=75" /></a>
  <?php } ?>
  <div class="card__job-content box__action-buttons">

          <?php if(!$jobHasExternLink) : ?>
                                                    <!-- favorite button -->
                                                    <?php if (isset($savedJobsContainer->jobs[$job->getId()])) : ?>
                                                        <button type="button" class="btn btn-default saved"
                                                                data-text-saved="<?=$this->translate('Marked')?>" data-text-save="<?=$this->translate('Mark')?>" data-job="<?= $job->getId() ?>">
                                                            <span><?=$this->translate('Marked')?></span>
                                                        </button>
                                                    <?php else : ?>
                                                        <button type="button" class="pull-right btn btn-default"
                                                                data-text-saved="<?=$this->translate('Marked')?>" data-text-save="<?=$this->translate('Mark')?>" data-job="<?= $job->getId() ?>">
                                                            <span><?=$this->translate('Mark')?></span>
                                                        </button>
                                                    <?php endif ?>
                                                    <!-- end favorite button -->
                                                <?php endif; ?>

    <?php if($jobHasExternLink) { ?>
    <h2><a rel="sponsored noopener" title="<?=strip_tags($job->getTitle())?>" href="<?=$href?>"><?=strip_tags($job->getTitle())?> <i class="fa fa-external-link"></i></a></h2>
    <span class="top-listing fa fa-star"><span>Top Job</span></span> 
    <?php }
      else { ?>
    <h2><a title="<?=strip_tags($job->getTitle())?>" href="<?=$href?>"><?=ucfirst(strip_tags($job->getTitle()))?></a></h2>
    <span class="top-listing fa fa-star"><span>Top Job</span></span> 
    <?php } ?>
    <div class="card__job-info">
      <div class="card__job-empname-label">
        <?php if ($org): ?>
        <?= $orgName ?>
        <?php else: ?>
        <?= (!empty($this->organizationName)) ? $this->organizationName : $orgName ?>
        <?php endif ?>
      </div>
      <div class="card__job-location">
        <?php
          $location = $job->getLocations()->last();
            if ($location == '') {
                 $locationString = $this->translate('Swiss');
             }
           elseif ($location) {
              $locationString = $location->getCity() ? $location->getCity() :
             preg_replace('~\(.*?\)$~', '', (string) $job->getLocation());
                }
            else {
             $locationString = preg_replace('~\(.*?\)$~', '', (string) $job->getLocation());
                }
              ?>
        <?=$locationString ?>
      </div>
    </div>
    <div class="card__job-snippet-logo">
      <p class="card__job-snippet" dir="auto">
        <?php
          $preview = null;
          if($job->getTemplateValues()->get('position')) {
              $preview = $job->getTemplateValues()->get('position');
              $preview = str_replace(['<li>', '<strong>', '</strong>', '</u>', '</p>', '</h2>', '<b>', '<u>', '</b>', '<br>', '</h4>','</h3>','</span>','<span>','<div>'], ' ', $preview);
              $preview = substr(strip_tags($preview), 0 , 215);
          }
          elseif ($job->getTemplateValues()->getHtml()) {
              $preview = $job->getTemplateValues()->getHtml();
              $preview = str_replace(['<li>', '<strong>', '</strong>', '</u>', '</p>', '</h2>', '<b>', '<u>', '</b>', '<br>', '</h4>','</h3>','</span>','<span>','<div>'], ' ', $preview);
              $preview = substr(strip_tags($preview), 0 , 215);
          }
          if ($preview) {
              $preview = str_replace('<p>', '', $preview);
              $preview = str_replace('</p>', '', $preview);
              $preview   = implode(' ', explode(' ', $preview, -1));
              $preview .= ' ... ';
          }
          ?>
        <?= $preview ?>
      </p>
    </div>
    <div class="card_job-short-info ">
      <ul>

        <?php
          // check for newer than 24 hours
          $jobDate = $job->getDatePublishStart() ?? $job->getDateCreated();
          $dayDiff = $today->diff($jobDate);
          if ($dayDiff->days < 1) {
              echo '<li class="new">Neu</li>';
          }
          ?>
        <li class="type"><?= $this->publishDateFormatter($job) ?></li>
        <li class="contract"><?php $typeOfContract = $job->getClassifications()->getEmploymentTypes()->__toString() ?:'Vollzeit' ?>
          <?=$typeOfContract; ?>
        </li>
        <!-- HINT: some jobs has invalid industries, therefore check for empty string -->
        <?php if ($industries->getItems()->count() && !$this->isCrawlerJob($org) && $industries->__toString() != ""): ?>
        <li class="industries">
          <?= $industries->__toString(); ?>
        </li>
        <?php endif; ?>
      </ul>
    </div>
  </div>
</div>
 <!-- end card -->

<?php if ($index == 0) : ?>
<!-- box after second job -->

<div class="card">

<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<ins class="adsbygoogle"
     style="display:block"
     data-ad-format="fluid"
     data-ad-layout-key="-gh-1p-b-ax+yh"
     data-ad-client="ca-pub-7494685726823151"
     data-ad-slot="6624146075"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>

</div>
<?php endif ?>
<?php if ($index == 4) : ?>
<!-- box after third job -->
<div class="card">

<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<ins class="adsbygoogle"
     style="display:block"
     data-ad-format="fluid"
     data-ad-layout-key="-gh-1p-b-ax+yh"
     data-ad-client="ca-pub-7494685726823151"
     data-ad-slot="6624146075"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>

</div>

<?php endif ?>
<?php if ($index == 17) : ?>
<!-- box after third job -->
<div class="card">

<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<ins class="adsbygoogle"
     style="display:block"
     data-ad-format="fluid"
     data-ad-layout-key="-gh-1p-b-ax+yh"
     data-ad-client="ca-pub-7494685726823151"
     data-ad-slot="6624146075"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>

</div>

<?php endif ?>
<?php endforeach?>

</div>
             
                <!-- pagination -->
                   <?= $this->paginationControl($jobs, 'Sliding', 'pagination-control', ['lang' => $this->params('lang'), 'route' => 'lang/jobboard']); ?>
                <!-- end pagination -->
 

                <?php $parts=preg_split('~<!--more-->~' , $description);?>
                <?php if (isset($parts[1]) && "" != trim($parts[1])): ?>
							<div class="row">
                              <div class="col-md-12" id="infobox-<?=$this->params()->fromRoute('term') ?>">
                                <div class="card similarjob extra-content">
                                <?php echo $this->landingpages(); ?>
                                   <?= $parts[1] ?>
                                    <?php if (51 == $query): echo $this->landingpages(); endif; ?>
                                    
                                    </div>
                                 </div>
								</div>
                 <?php endif ?>
                


            </div>
            <?=$hasFacets ? '</div>' : '' ?>
<?php endif ?>



        </div>
    </div>
</div>

<?php
    $queryGet = $this->params()->fromQuery();
    $hasPartTwo = (isset($parts[2]) && "" != trim($parts[2]));
    $searchTerm = (isset($queryGet['q']) && is_string($queryGet['q'])) ? trim($queryGet['q'],'"') : null;
    $hasRegion= isset($queryGet['region_MultiString']);
    $hasCity= isset($queryGet['city_MultiString']);
?>
