<?php //description: Renders the list of public jobs. ?>
<?php
$this->headLink()->prependStylesheet($this->basePath($this->asset('modules/Gastro24/Gastro24.css')));
$this->headLink()->prependStylesheet($this->basePath('/dist/css/jquery-ui-1-12.min.css'));

$this->headScript()->appendFile($this->basepath('/modules/Core/js/core.pagination-container.js'))
    ->appendFile($this->basePath('modules/Core/js/core.forms.js'))
    ->appendFile($this->basePath($this->asset('modules/Gastro24/js/jobs.js')))
    ->appendFile($this->basePath('/dist/js/bootstrap-dialog.min.js'));
?>

<?php
$queryGet = $this->params()->fromQuery();
unset($queryGet['clear']);
$searchTerm = (isset($queryGet['q']) && is_string($queryGet['q'])) ? trim($queryGet['q'],'"') : null;
$query = $this->params()->fromRoute('wpId') ?: (count($queryGet) ? 0 : 304);
$wordpress = $this->proxy('wordpress');

$this->headMeta()->setName('description', $wordpress->chain(['page' => $query, 'value' => 'meta-fields.description'], ''));
//$this->headMeta()->setName('keywords', $wordpress->call('value', ['meta-fields.keywords'], ''));
$description = $wordpress->call('value', ['content.rendered'], '');

$title = $wordpress->call('value', ['meta-fields.title'], '');
$this->headTitle($title ?: $this->translate('Jobs'));
$headline = $wordpress->call('value', ['title.rendered'], '');
$headline = $headline ?: $searchTerm;

$wordpressTitle = '';
// set temporarly index,follow without canonical only on landing pages without jobs, because there is an issue with google indexing
 if (!count($this->jobs) && $this->params()->fromRoute('isLandingPage')) {
     $wordpressTitle = $wordpress->call('value', ['title.rendered'], '');
   //$jobsLandingpage = "/de/jobs?clear=1";
   // $this->headLink()->headLink(array('rel' => 'canonical', 'href' => $jobsLandingpage));
    $robots = "index,follow";
 } else {
     $robots = "noindex,follow";
 }

if (304 === $query || ($this->params()->fromRoute('isLandingPage') && !$this->params()->fromRoute('isFilteredLandingPage') && (count($this->jobs) || $description))) {
    $robots = substr($robots, 2);

    // set canonical link - but not on landing pages
    if (!$this->params()->fromRoute('isLandingPage')) {
       // $jobUrl = $this->serverUrl() . $this->url('lang/jobboard', [], [], true);
      //  $this->headLink()->headLink(array('rel' => 'canonical', 'href' => $jobUrl), 'PREPEND');
      
      $jobsLandingpage = $this->serverUrl() . "/de/jobs?clear=1";
      $this->headLink()->headLink(array('rel' => 'canonical', 'href' => $jobsLandingpage));
    }
}

$this->headMeta()->setName('robots', $robots);
$noJobsMessage = $this->translate('No jobs found.');
?>
<?php $this->headScript()->captureStart();?>
(function($) {
    $(function() {
        var $tabbar = $('#search-tabs');

        $('#jobs-list-container').on('yk-paginator-container:loaded.gastro24 g24-jobs:init', function(ev) {
            $tabbar.show();
            var html = $('#jobs-list-container').find('.pagination-content').html();

            if ('' === html.trim()) { $tabbar.hide(); }
           
             $('#jobDateFilter').each($.fn.form.initSelect);

            $('#jobs-list-container ul.pagination a, link[rel="prev"], link[rel="next"]').each(function() {
                var $a = $(this),
                    href = $a.attr('href');
                console.debug($a, href);
                if (href) {
                    href = href.replace(/__region_MultiString/, 'r')
                               .replace(/__city_MultiString/, 'l')
                               .replace(/__organizationTag/, 'c')
                               .replace(/__profession_MultiString/, 'p')
                               .replace(/__industry_MultiString/, 'i')
                               .replace(/__employmentType_MultiString/, 't');
                    $a.attr('href', href);
                }
            });

            $('.container--filter .filter-icon').on('click', function() {
                var regionFacet = $('.facets-heading-region_MultiString'),
                    hasActiveRegionFacet = $('.container--facets .well').find('button[data-name*="region_MultiString"]');

                $(this).toggleClass('active');

                if (!regionFacet.hasClass('collapsed') && !hasActiveRegionFacet.length) {
                    $('.facets-heading-region_MultiString').click();
                }
            });

            // scroll to top after pagination clicked
            $('.pagination li[class!="disabled"] a, .pagination li[class!="disabled"] a').on('click', function() {
                $('html, body').animate({ scrollTop: 0 }, 'fast');
            });

        }).trigger('g24-jobs:init');

        var $jobCount = $('#job-count');

        $('#jobs-list-container').on('yk-paginator-container:loaded.gastro24-job-count', function(ev) {
            var count = $('#update-job-count').text();
            $jobCount.text(count);
        });

        $('#jobs-list-filter').on('reset.gastro24', function(ev) { $(ev.target).find('input.facet-param').remove(); });

        // used for first facet collapse
        if ($(window).width() < 992) {
            $('.facets-heading-region_MultiString').click();
        }
    });
})(jQuery);
<?php $this->headScript()->captureEnd();?>

<?php if ($jobs instanceof \Solr\FacetsProviderInterface): $this->headScript()->appendFile($this->basePath($this->asset('modules/Gastro24/js/jobs.facets.js'))); endif; ?>

<?php echo $this->flashMessenger()->render('default', array('alert', 'alert-success')) ?>
<div class="row">

    <div class="col-md-12">
        <?php if (!count($this->jobs)):?>
            <!-- breadcrumbs -->
            <?= $this->partial('jobs/partials/breadcrumbs.phtml', [
                'searchTerm' => $searchTerm,
                'hasRegion' => $hasRegion,
                'wordpressTitle' => $wordpressTitle
            ]); ?>
            <!-- breadcrumbs -->
            <div class="page-title pull-left">
                
                <h1><?= $headline ?></h1>
            </div>
        <?php endif ?>

        <div id="jobs-list-container" class="pagination-container"
             <?php if (!count($this->jobs)):?>data-message="<strong><?= $noJobsMessage ?></strong>"<?php endif ?>
             data-uri="<?php echo $this->url('lang/jobboard', [], ['query' => $this->params()->fromQuery()], true)?>">

            <?php if (!count($this->jobs)):?>
              <?=$this->proxy('jobsByMailSubscriptionForm')->render($jobs)?>
                <?php $this->headScript()->captureStart();?>
                    (function($) {
                        $(function() {
                            $('#form-jobsbymail-subscribe-form').find('button.btn-info').hide().click()
                                .end().find('#job-by-mail-subscribe-label').html('Informiert werden, sobald Jobs zu Ihrer Suchanfrage verfügbar sind.');
                            $('#jobs-list-container').data('container').$message.show();
                        });
                    })(jQuery);
                <?php $this->headScript()->captureEnd();?>

                <!-- similar jobs by raw string -->
                <?php echo $this->partial('jobs/partials/similar-jobs-by-title.phtml', ['headline' => $headline]); ?>
                <!-- end similar jobs by raw string -->

                <?php $parts=preg_split('~<!--more-->~' , $description);?>
                <?php if (isset($parts[1]) && "" != trim($parts[1])): ?>
                    <div class="row">
                        <div class="col-md-12" id="infobox-<?=$this->params()->fromRoute('term') ?>">
                            <div class="featured-image-box similarjob">
                                <?php echo $this->landingpages(); ?>
                                <?= $parts[1] ?>
                                <?php if (51 == $query): echo $this->landingpages(); endif; ?>

                            </div>
                        </div>
                    </div>
                <?php endif ?>
            <?php endif ?>

           <div class="pagination-content">
               <?php echo $this->render('jobs/jobboard/index.ajax.phtml') ?>
            </div>
        </div>

    </div>
</div>

<div class="modal fade" id="job-apply-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
    <div class="modal-dialog" style="width: 90%; height: 90%" role="document">
        <div class="modal-content" style="height: 100%">
            <div class="modal-body" style="height: calc(100% - 65px)">

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Schliessen</button>
            </div>
        </div>
    </div>
</div>
