<?php
/**
 * YAWIK
 *
 * @filesource
 * @copyright (c) 2013 - 2016 Cross Solution (http://cross-solution.de)
 * @license   MIT
 */

// We only want to render something, if there are items.
if (count($jobs)): ?>
    <div class="hidden" id="update-job-count">
        <?=$this->jobs->getTotalItemCount()?>
    </div>

    <?php
        /** @var \Gastro24\Options\TopJobsOptions $topJobOptions */
        $topJobOptions = $this->services(\Gastro24\Options\TopJobsOptions::class);
        $topJobsOrganizations = $topJobOptions->getOrganizationNames();
        $topJobsIds = $topJobOptions->getJobIds();

        $hasFacets = $jobs instanceof \Solr\FacetsProviderInterface;
        $queryGet = $this->params()->fromQuery();
        unset($queryGet['clear']);
        $query = $this->params()->fromRoute('wpId') ?: (count($queryGet) ? 0 : 304);
        $wordpress = $this->proxy('wordpress');
        $searchTerm = (isset($queryGet['q']) && is_string($queryGet['q'])) ? trim($queryGet['q'],'"') : null;
        $hasRegion= isset($queryGet['region_MultiString']);
        $hasCity= isset($queryGet['city_MultiString']);
        //$breadcrumbText = $options->$text;
        $dateFilterValue = isset($queryGet['dateFilter']) ? $queryGet['dateFilter'] : '';

        $this->headMeta()->setName('description', $wordpress->chain(['page' => $query, 'value' => 'meta-fields.description'], ''));
        $this->headScript()->appendFile($this->basePath($this->asset('modules/Gastro24/jssocials-1.4.0/dist/jssocials.js')));
        $description = $wordpress->call('value', ['content.rendered'], '');
        $wordpressTitle = '';

        if ($this->params()->fromRoute('isLandingPage')) {
            $wordpressTitle = $wordpress->call('value', ['title.rendered'], '');
            $descriptionText = 'Aktuell ' . $this->jobs->getTotalItemCount() . ' verfügbare ' .
                $wordpressTitle . ' finden auf Gastrojob24.ch, der #1 Gastronomie & Hotellerie Jobbörse der Schweiz.';
            if ($this->jobs->getTotalItemCount() == 1) {
                $descriptionText = 'Aktuell ' . $this->jobs->getTotalItemCount() . ' verfügbaren ' .
                    $wordpressTitle . ' finden auf Gastrojob24.ch, der #1 Gastronomie & Hotellerie Jobbörse der Schweiz.';
            }

            $titleOgText = $this->jobs->getTotalItemCount() . ' ' . $wordpressTitle . ' verfügbar - Gastrojob24.ch.';
            $descriptionOgText = 'Jetzt Traumjob finden aus ' . $this->jobs->getTotalItemCount() . ' ' . $wordpressTitle . ' bei Gastrojob24.ch - der Gastronomie & Hotellerie Jobbörse der Schweiz.';
            $this->headMeta()->setName('description', $descriptionText)
                ->setProperty('og:title', $titleOgText)
                ->setProperty('og:description', $descriptionOgText)
                ->setProperty('og:url', 'https://www.gastrojob24.ch' . $this->url('lang/landingPage', ['q' => $this->params()->fromRoute('term'), 'format' => 'html'], true))
                ->setProperty('og:image', 'https://www.gastrojob24.ch/modules/Gastro24/gastro-logo-fb.png')
                ->setProperty('og:locale', 'de_DE')
                ->setProperty('og:type', 'website')
                ->setAutoEscape(false);
        }

        $container = new \Laminas\Session\Container('gastro24_jobboardcontainer');
        $container->fromCompanyProfile = false;
        $container->searchTerm = $searchTerm;

        $savedJobsContainer = new \Laminas\Session\Container('gastro24_savedjobs');
        $defaultLogoUrl = $this->basePath('modules/Gastro24/images/no-company-logo.png');
    ?>
    <?php if ($hasFacets):
        if ($this->params()->fromRoute('isLandingPage')):?>
            <span class="facets-url" data-url="<?=$this->url('lang/landingPage', ['q' => $this->params()->fromRoute('term'), 'format' => 'html'], true)?>"></span>
        <?php endif;
        /** @var \Gastro24\Paginator\JobsBoardFacets $facets */
        $facets = $jobs->getFacets();
        $activeFacets = $facets->getActiveValues();
    ?>
<?php endif;?>

<style>
    
.card:not(.topjob) .fa-star  {
display:none;
}
    
.topjob {
background-color:#fcf8e3;
box-shadow: 1px 2px 6px 0px #ccc;
-webkit-box-shadow: 1px 2px 6px 0px #ccc;
-moz-box-shadow: 1px 2px 6px 0px #ccc;
}

.topjob .fa-star {
background-color: #f4da1e;
color: #fff;
padding: 3px 10px;
-webkit-border-radius: 4px;
-moz-border-radius: 4px;
border-radius: 4px;
}
.topjob .fa-star:before {
padding-right: 10px;
}

.topjob .fa-star span {
font-family:sans-serif;
}
.topjob h2>a {
color: #000;
}
    
    
</style>


<div class="row">
    <div class="col-md-12">

        <!-- breadcrumbs -->
        <?= $this->partial('jobs/partials/breadcrumbs.phtml', [
            'searchTerm' => $searchTerm,
            'hasRegion' => $hasRegion,
            'hasCity' => $hasCity,
            //'breadcrumbText' => $breadcrumbText,
            'wordpressTitle' => $wordpressTitle
        ]); ?>
        <!-- breadcrumbs -->


        <div class="row job-results-container">
    <div class="col-md-12 container__date-filter">
        <!-- filter icon on mobile -->
        <div class="container--filter">
            <span class="filter-icon <?= ($activeFacets) ? 'active' : '' ?>">
                <a data-toggle="collapse" href="#facets-container" aria-expanded="false" aria-controls="facets-container">
                    <i class="fa fa-sliders" aria-hidden="true"></i>
                </a>
            </span>
        </div>
        <!-- end filter icon on mobile -->
    </div>
     <div class="col-md-3 container--facets dont-collapse-sm collapse <?= ($activeFacets) ? 'in' : '' ?>"
          aria-expanded="<?= ($activeFacets) ? 'true' : 'false' ?>" id="facets-container">
        <!-- list active filters -->
        <?php if ($activeFacets):?>
            <div class="well well-sm">
                <?php foreach ($activeFacets as $facetName => $facetValues):?>
                    <?php foreach ($facetValues as $facetValue):?>
                        <?php if($facetValue == '1440'): ?>
                            <button type="button" class="btn btn-primary btn-sm facet-active"
                                    data-name="<?=$this->escapeHtmlAttr($facetName)?>[<?=$this->escapeHtmlAttr($facetValue)?>]"
                                    title="<?=$this->translate('Remove filter')?>">neuer als 24 h <span>&times;</span>
                            </button>
                        <?php elseif($facetValue == '4320'): ?>
                            <button type="button" class="btn btn-primary btn-sm facet-active"
                                    data-name="<?=$this->escapeHtmlAttr($facetName)?>[<?=$this->escapeHtmlAttr($facetValue)?>]"
                                    title="<?=$this->translate('Remove filter')?>">neuer als 3 Tage <span>&times;</span>
                            </button>
                        <?php elseif($facetValue == '10080'): ?>
                            <button type="button" class="btn btn-primary btn-sm facet-active"
                                    data-name="<?=$this->escapeHtmlAttr($facetName)?>[<?=$this->escapeHtmlAttr($facetValue)?>]"
                                    title="<?=$this->translate('Remove filter')?>">neuer als 7 Tage <span>&times;</span>
                            </button>
                        <?php elseif($facetValue == '43200'): ?>
                            <button type="button" class="btn btn-primary btn-sm facet-active"
                                    data-name="<?=$this->escapeHtmlAttr($facetName)?>[<?=$this->escapeHtmlAttr($facetValue)?>]"
                                    title="<?=$this->translate('Remove filter')?>">neuer als 30 Tage <span>&times;</span>
                            </button>
                        <?php else: ?>
                        <button type="button" class="btn btn-primary btn-sm facet-active"
                                data-name="<?=$this->escapeHtmlAttr($facetName)?>[<?=$this->escapeHtmlAttr($facetValue)?>]"
                                title="<?=$this->translate('Remove filter')?>"><?=$facetValue?> <span>&times;</span></button>
                        <?php endif;?>
                    <?php endforeach;?>
                <?php endforeach;?>

                <p>Sie können Ihre Jobsuche weiter einschränken, indem Sie unten ein oder mehrere Filterkriterien auswählen.</p>
                <button type="button" class="btn btn-link facet-reset"><?=$this->translate('Remove all filters')?></button>
            </div>
        <?php endif;?>
        <!-- end list active filters -->
        
         <!-- filter -->
        <div class="panel-group">
            <?php
                    $facetsHtml = '';
                    $isFirstFacet = true;
                    $atLeastOneTotalActive = false;
                    foreach ($facets as $facetName => $facetValues):?>
                <?php $facetOptionsCounter = 0; ?>
                <?php if(count($facetValues)>0): $atLeastOneActive = false; $facetsList = []; ob_start();?>
                <div id="facets-box-<?=$facetName?>" class="panel panel-default">
                    <div class="panel-heading">
                        <a class="facets-heading-<?=$facetName?> <?=$isFirstFacet ?  '%firstCollapsed% ' : '%collapsed%'?>" data-toggle="collapse" data-parent="#facets-box-<?=$facetName?>" href="#facets-box-<?=$facetName?>-content">
                        <?=$this->translate($facets->getTitle($facetName))?>
                             <span class="fa fa-chevron-down"></span>
                        </a>

                    </div>
                    <div id="facets-box-<?=$facetName?>-content" class="panel-collapse collapse <?=$isFirstFacet ? '%firstIn%' : '%in%' ?>">
                    <div class="panel-body">
                        <?php foreach ($facetValues as $facetValue => $facetValueCount):
                            $facetOptionsCounter++;
                            if($facetOptionsCounter > 10) continue;
                            $activeFacet = $facets->isValueActive($facetName, $facetValue);
                            $atLeastOneActive = $atLeastOneActive || $activeFacet;?>
                            <div class="filter-links">
                                <label<?=$activeFacet ? ' class="text-primary"' : ''?>>  <?=$activeFacet ? ' <i class="fa fa-check"></i>' : ''?>
                                    <input type="checkbox" name="<?=$this->escapeHtmlAttr($facetName)?>[<?=$this->escapeHtmlAttr($facetValue)?>]"
                                           class="facet-checkbox"<?=$activeFacet?" checked":""?>>
                                    <?=($facetName == 'publishDateFilter') ? \Gastro24\Paginator\JobsBoardFacets::$formattedPublishDateValue[$facetValue] : $facetValue?> <span class="filter-count"><?=$facetValueCount?></span>
                                </label>
                            </div>
                        <?php if ($activeFacet): $facetsList[] = $facetValue; endif; endforeach;?>
                    </div>
                    </div> <!-- facets-collaps-* -->
                </div>
                <?php $facetsHtml .= str_replace(
                        ['%in%', '%firstIn%', '%firstCollapsed%', '%collapsed%', '%facetsList%' ],
                        [
                                $atLeastOneActive ? 'in' : '',
                                $atLeastOneActive ? 'in' : '%firstIn%',
                                $atLeastOneActive ? '' : '%firstCollapsed%',
                                $atLeastOneActive ? '' : 'collapsed',
                                join(', ', $facetsList),
                        ],
                        ob_get_clean()
                    ); $atLeastOneTotalActive = $atLeastOneTotalActive || $atLeastOneActive; endif; $isFirstFacet = false;?>
            <?php endforeach;
                echo str_replace(
                        ['%firstCollapsed%', '%firstIn%'],
                        [$atLeastOneTotalActive ? 'collapsed' : '', $atLeastOneTotalActive ? '' : 'in'],
                        $facetsHtml
                );
            ?>
        </div>
       </div>
            <div class="col-md-9">
                <div class="row">
                   <div class="col-md-9">
                      <div class="pull-left page-title">
                         <span><?=$this->jobs->getTotalItemCount() ?> </span>
                          <h1><?=$wordpress->call('value', ['title.rendered'], '') ?: (count($this->jobs) ? 'Treffer für '.$searchTerm.' Jobs' : 'Leider keine passenden Jobs gefunden'); ?></h1>
                      </div>
                   </div>
                   <div class="col-md-3">
                       <?=$this->proxy('jobsByMailSubscriptionForm')->render($jobs)?>
                   </div>
                </div>

                        <?php
                            // get date difference
                            $today = new DateTime();
                        ?>

                        <?php foreach ($jobs as $index => $job): ?>
                            <?php
                                /** @var Solr\Entity\JobProxy $job */
                                $org = $job->getOrganization();
                                $hasJobTemplate = $this->gastroJobTemplate($org);
                                $isIntern = (!$job->getLink() || $hasJobTemplate);
                                $isEmbeddable = $this->gastroIsEmbeddable($job->getLink());
                                $jobHasExternLink = (!$isIntern && !$isEmbeddable);
                                $industries = $job->getClassifications()->getIndustries();
                                $template = $job->getAttachedEntity('gastro24-template');
                                $orgName = $this->jobOrganizationName($job);
                                /* mark as topjob */
                                $additionalCardCss = ((in_array($orgName, $topJobsOrganizations) !== false) ||
                                    (in_array($job->getId(), $topJobsIds) !== false)) ? 'topjob' : '';

                                $isExpired = ($job->getStatus()) ? $job->getStatus()->getName() == \Jobs\Entity\StatusInterface::EXPIRED : false;
                                $orgIsDisabled = false;
                                if ($org && (Organizations\Entity\Organization::PROFILE_DISABLED == $org->getProfileSetting() || is_null($org->getProfileSetting())) ) {
                                    $orgIsDisabled = true;
                                }
                                $href = ($jobHasExternLink) ? $job->getLink() : $this->jobUrl($job, ['linkOnly' => true, 'absolute' => true ]);
                            ?>
 <!-- begin card-->
<div class="<?= $additionalCardCss ?> card box__job-favorite">
  <?php
    $logoUrl = null;
    if (is_object($org) && is_object($org->getImage()) && $org->getImage()->getUri()) {
     $logoUrl = $this->basePath($this->organizationImageCache->getUri($org->getImage(true)));
        }
     if ($template && ($logo = $template->getLogo())) {
     $logoUrl = $this->basePath($logo->getUri());
     }
    ?>
  <?php if($jobHasExternLink) { ?>
  <a class="job-logo-link" rel="sponsored noopener" title="<?=strip_tags($job->getTitle())?>" href="<?=$href?>"><img class="job-logo" alt="<?= $orgName ?>" src="<?= $logoUrl ? $logoUrl : $defaultLogoUrl ?>" /></a>
  <?php }
    else { ?>
  <a class="job-logo-link" title="<?=strip_tags($job->getTitle())?>" href="<?=$href?>"><img class="job-logo" alt="<?= $orgName ?>" src="<?= $logoUrl ? $logoUrl : $defaultLogoUrl ?>" /></a>
  <?php } ?>
  <div class="card__job-content box__action-buttons">

          <?php if(!$jobHasExternLink) : ?>
                                                    <!-- favorite button -->
                                                    <?php if (isset($savedJobsContainer->jobs[$job->getId()])) : ?>
                                                        <button type="button" class="btn btn-default saved"
                                                                data-text-saved="<?=$this->translate('Marked')?>" data-text-save="<?=$this->translate('Mark')?>" data-job="<?= $job->getId() ?>">
                                                            <span><?=$this->translate('Marked')?></span>
                                                        </button>
                                                    <?php else : ?>
                                                        <button type="button" class="pull-right btn btn-default"
                                                                data-text-saved="<?=$this->translate('Marked')?>" data-text-save="<?=$this->translate('Mark')?>" data-job="<?= $job->getId() ?>">
                                                            <span><?=$this->translate('Mark')?></span>
                                                        </button>
                                                    <?php endif ?>
                                                    <!-- end favorite button -->
                                                <?php endif; ?>

    <?php if($jobHasExternLink) { ?>
    <h2><a rel="sponsored noopener" title="<?=strip_tags($job->getTitle())?>" href="<?=$href?>"><?=strip_tags($job->getTitle())?> <i class="fa fa-external-link"></i></a></h2>
    <?php }
      else { ?>
    <h2><a title="<?=strip_tags($job->getTitle())?>" href="<?=$href?>"><?=ucfirst(strip_tags($job->getTitle()))?></a></h2>
    <?php } ?>
    <div class="card__job-info">
      <div class="card__job-empname-label">
        <?php if ($org): ?>
        <?= $orgName ?>
        <?php else: ?>
        <?= (!empty($this->organizationName)) ? $this->organizationName : $orgName ?>
        <?php endif ?>
      </div>
      <div class="card__job-location">
        <?php
          $location = $job->getLocations()->last();
            if ($location == '') {
                 $locationString = $this->translate('Swiss');
             }
           elseif ($location) {
              $locationString = $location->getCity() ? $location->getCity() :
             preg_replace('~\(.*?\)$~', '', (string) $job->getLocation());
                }
            else {
             $locationString = preg_replace('~\(.*?\)$~', '', (string) $job->getLocation());
                }
              ?>
        <?=$locationString ?>
      </div>
    </div>
    <div class="card__job-snippet-logo">
      <p class="card__job-snippet" dir="auto">
        <?php
          $preview = null;
          if($job->getTemplateValues()->get('position')) {
              $preview = $job->getTemplateValues()->get('position');
              $preview = str_replace(['<li>', '<strong>', '</strong>', '</u>', '</p>', '</h2>', '<b>', '<u>', '</b>', '<br>', '</h4>','</h3>','</span>','<span>','<div>'], ' ', $preview);
              $preview = substr(strip_tags($preview), 0 , 215);
          }
          elseif ($job->getTemplateValues()->getHtml()) {
              $preview = $job->getTemplateValues()->getHtml();
              $preview = str_replace(['<li>', '<strong>', '</strong>', '</u>', '</p>', '</h2>', '<b>', '<u>', '</b>', '<br>', '</h4>','</h3>','</span>','<span>','<div>'], ' ', $preview);
              $preview = substr(strip_tags($preview), 0 , 215);
          }
          if ($preview) {
              $preview = str_replace('<p>', '', $preview);
              $preview = str_replace('</p>', '', $preview);
              $preview   = implode(' ', explode(' ', $preview, -1));
              $preview .= ' ... ';
          }
          ?>
        <?= $preview ?>
      </p>
    </div>
    <div class="card_job-short-info ">
      <ul>
         <li class="fa fa-star"><span>Top-Listing</span></li>
        <?php
          // check for newer than 24 hours
          $jobDate = $job->getDatePublishStart() ?? $job->getDateCreated();
          $dayDiff = $today->diff($jobDate);
          if ($dayDiff->days < 1) {
              echo '<li class="new">Neu</li>';
          }
          ?>
        <li class="type"><?= $this->publishDateFormatter($job) ?></li>
        <li class="contract"><?php $typeOfContract = $job->getClassifications()->getEmploymentTypes()->__toString() ?:'Vollzeit' ?>
          <?=$typeOfContract; ?>
        </li>
        <!-- HINT: some jobs has invalid industries, therefore check for empty string -->
        <?php if ($industries->getItems()->count() && !$this->isCrawlerJob($org) && $industries->__toString() != ""): ?>
        <li class="industries">
          <?= $industries->__toString(); ?>
        </li>
        <?php endif; ?>
      </ul>
    </div>
  </div>
</div>
<!-- end card -->
<?php if ($index == 1) : ?>
<!-- box after second job -->
<?php endif ?>
<?php if ($index == 2) : ?>
<!-- box after third job -->
<?php endif ?>
<?php endforeach?>

             
                <!-- pagination -->
                   <?= $this->paginationControl($jobs, 'Sliding', 'pagination-control', ['lang' => $this->params('lang'), 'route' => 'lang/jobboard']); ?>
                <!-- end pagination -->
                

                <?php $parts=preg_split('~<!--more-->~' , $description);?>
                <?php if (isset($parts[1]) && "" != trim($parts[1])): ?>
							<div class="row">
                              <div class="col-md-12" id="infobox-<?=$this->params()->fromRoute('term') ?>">
                                <div class="card similarjob">
                                   <?= $parts[1] ?>
                                    <?php if (51 == $query): echo $this->landingpages(); endif; ?>
                                    
                                    </div>
                                 </div>
								</div>
                 <?php endif ?>
                

              <?php if (count($this->jobs)):?>
                <div class="to-top-link">
                    <a id="scroll-to-top" href="#top"><span class="fa fa-chevron-up"></span> nach oben</a>
                </div>
                 <?php endif ?>

            </div>
            <?=$hasFacets ? '</div>' : '' ?>
<?php endif ?>



        </div>
    </div>
</div>

<?php
    $queryGet = $this->params()->fromQuery();
    $hasPartTwo = (isset($parts[2]) && "" != trim($parts[2]));
    $searchTerm = (isset($queryGet['q']) && is_string($queryGet['q'])) ? trim($queryGet['q'],'"') : null;
    $hasRegion= isset($queryGet['region_MultiString']);
    $hasCity= isset($queryGet['city_MultiString']);
?>