<?php
/**
 * YAWIK  - Anzeige im Tab Prozess Nr. 2
 *
 * @filesource
 * @license MIT
 * @copyright  2013 - 2018 Cross Solution <http://cross-solution.de>
 */

use Laminas\Form\Element\Hidden;

$fieldset = $this->element;
$mode = $fieldset->get('mode');
$isUri = 'uri' == $mode->getValue();
$isPdf = 'pdf' == $mode->getValue();
$isHtml = 'html' == $mode->getValue();

$modeLabels = $mode->getOption('labels');

?>
<?php if (isset($this->renderSummary) && $this->renderSummary): ?>

    <style type="text/css">
        .mce-content-body { min-height: 100px; }
    </style>
    <div class="row">
        <?php if ($isUri): ?>
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">Online-Inserat</h3>
                    </div>
                    <div class="panel-body">
                        <?=$fieldset->get('uri')->getValue()?>
                    </div>
                </div>
            </div>
        <?php elseif ($isPdf): ?>
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">PDF-Datei</h3>
                    </div>
                    <div class="panel-body">
                        <a href="<?=$fieldset->getObject()->getLink() ?>">PDF-Datei</a> ausgewählt.
                    </div>
                </div>
            </div>
        <?php endif; ?>

        <!-- banner preview -->
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Banner</h3>
                </div>
                <div class="panel-body">
                    <?php
                    $template = $fieldset->getObject()->getAttachedEntity('gastro24-template');
                    if ($template && ($image = $template->getImage())):?>
                        <img style="width:100%" src="<?=$this->basePath($image->getUri());?>">
                    <?php endif ?>
                </div>
            </div>
        </div>
        <!-- end banner preview -->

        <?php if ($isHtml): ?>
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">Stellenbeschreibung</h3>
                    </div>
                    <div class="panel-body">
                        <?=$fieldset->get('position')->getValue()?>
                    </div>
                </div>
            </div>
            <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Beschreibung des Unternehmens</h3>
                </div>
                <div class="panel-body">
                    <?=$fieldset->get('description')->getValue()?>
                </div>
            </div>
        </div>
        <?php endif ?>
    </div>

<?php else: ?>
    <fieldset id="details-fs">
        <div class="fieldset-content">

            <!-- job creation - all modes:  html, pdf, link -->
            <?php if (!$mode instanceof Laminas\Form\Element\Hidden): ?>
                <div class="controls controls-row form-group">
                    <div class="col-md-3 yk-label">&nbsp;</div>
                    <div class="col-md-9">
                        <?php if(isset($modeLabels['uri'])) : ?>
                            <div class="pull-left" style="margin-right: 15px;" id="csj-mode-uri-span">
                                <input type="radio" id="csj-mode-uri" name="<?=$mode->getName()?>" value="uri" <?=$isUri ? 'checked' : ''?>> <label for="csj-mode-uri"> <?=$modeLabels['uri']?></label>
                            </div>
                        <?php endif; ?>
                        <?php if(isset($modeLabels['pdf'])) : ?>
                            <div class="pull-left" style="margin-right: 15px;" id="csj-mode-pdf-span">
                                <input type="radio" id="csj-mode-pdf" name="<?=$mode->getName()?>" value="pdf" <?=$isPdf ? 'checked' : '' ?>> <label for="csj-mode-pdf"> <?=$modeLabels['pdf']?></label>
                            </div>
                        <?php endif; ?>
                        <?php if(isset($modeLabels['html'])) : ?>
                            <div class="pull-left" id="csj-mode-html-span">
                                <input type="radio" id="csj-mode-html" name="<?=$mode->getName()?>" value="html" <?=$isUri || $isPdf ? '' : 'checked' ?>> <label for="csj-mode-html"> <?=$modeLabels['html']?></label>
                            </div>
                        <?php endif; ?>
                    </div>
                </div>
            <!-- end job creation - all modes:  html, pdf, link -->
            <!-- single job creation - only html mode -->
            <?php else: ?>
                <input type="hidden" id="csj-mode-html" name="<?=$mode->getName()?>" value="html">
            <?php endif; ?>
            <!-- end single job creation - only html mode -->

            <?=$this->formRow($fieldset->get('uri'))?>

            <!-- HINT: single job does not have pdf input -->
            <?php if($fieldset->has('pdf')) {
                $input = $this->formRow($fieldset->get('pdf'));
                if ($value = $fieldset->get('pdf')->getValue()) {
                    $input = str_replace(
                        '<div class="col-md-9" id="details-pdf-span">',
                        '<div class="col-md-9" id="details-pdf-span"><div class="file-info"><a href="' . $value . '" target="_blank">' . basename($value) . '</a>
                            <a href="?ajax=jobdetailsdelete&file=' .basename($value). '" class="file-delete btn btn-default btn-xs">
                    <span class="yk-icon yk-icon-minus"></span>
                </a>
                <input type="hidden" value="' . $value . '" name="pdf_uri"></div>',
                        $input
                    );
                    $input = str_replace('<input type="file"', '<input type="file" style="display:none;"', $input);

                }
                echo $input;
            }
            ?>

            <!-- Logo and banner fields -->
            <?php
                $inputLogo = $this->formRow($fieldset->get('logo'));
                $logoValue = $fieldset->get('logo')->getValue();

                /* HINT: form throws error - returns empty array*/
                if (is_array($logoValue) && $logoValue['name'] == '') {
                    $logoValue = null;
                }

                if ($logoValue) {
                    $inputLogo = str_replace(
                        '<div class="col-md-9" id="details-logo-span">',
                        '<div class="col-md-9" id="details-logo-span"><div class="file-info"><a href="' . $logoValue . '" target="_blank">' . basename($logoValue) . '</a>
                                <a href="/' . $logoValue . '?do=delete" class="file-delete btn btn-default btn-xs">
                                    <span class="yk-icon yk-icon-minus"></span>
                                </a>
                                <input type="hidden" value="' . basename(dirname($logoValue)) . '" name="details[logo_id]">
                                <input type="hidden" value="' . $logoValue . '" name="details[logo_url]"></div>',
                        $inputLogo
                    );
                    $inputLogo = str_replace('<input type="file"', '<input type="file" style="display:none;"', $inputLogo);
                }

                echo $inputLogo;
            ?>

            <?php
                $input = $this->formRow($fieldset->get('image'));
                $imageValue = $fieldset->get('image')->getValue();

                /* HINT: form throws error - returns empty array*/
                if (is_array($imageValue) && $imageValue['name'] == '') {
                    $imageValue = null;
                }

                if ($imageValue) {
                    $input = str_replace(
                        '<div class="col-md-9" id="details-image-span">',
                        '<div class="col-md-9" id="details-image-span"><div class="file-info"><a href="' . $imageValue . '" target="_blank">' . basename($imageValue) . '</a>
                            <a href="/' . $imageValue . '?do=delete" class="file-delete btn btn-default btn-xs">
                                <span class="yk-icon yk-icon-minus"></span>
                            </a>
                            <input type="hidden" value="' . basename(dirname($imageValue)) . '" name="details[image_id]">
                            <input type="hidden" value="' . $imageValue . '" name="details[image_url]"></div>',
                        $input
                    );
                    $input = str_replace('<input type="file"', '<input type="file" style="display:none;"', $input);

                }
                echo $input;
            ?>


            <?=$this->formRow($fieldset->get('position')); ?>
            <?=$this->formRow($fieldset->get('description'))?>

        </div>
    </fieldset>


<?php endif ?>
