<?php
/**
 * YAWIK - Anzeige für Vorschau & Ausgabe
 *
 * @filesource
 * @license MIT
 * @copyright  2013 - 2018 Cross Solution <http://cross-solution.de>
 */

$this->headScript()->appendFile($this->basePath($this->asset('modules/Gastro24/jssocials-1.4.0/dist/jssocials.js')));

// check for preview
$routeParams = $this->params()->fromRoute();
$preview = false;
if (isset($routeParams['isPreview']) && $routeParams['isPreview']) {
    $preview = true;
}
$isExpired = ($this->job->getStatus()) ? $this->job->getStatus()->getName() == \Jobs\Entity\StatusInterface::EXPIRED : false;
$template = $this->job->getAttachedEntity('gastro24-template');
$basePathHelper = $this->plugin('basePath');
$replaceImage = function($str) use ($template, $basePathHelper)
{
    $image = $template ? $template->getImage() : null;
    if ($image) {
        $imageUri = $basePathHelper($image->getUri());
        $imageHtml = '<img src="' . $imageUri . '">';
    } else {
        $imageHtml = '';
    }

    return str_replace('#image#', $imageHtml, $str);
};

$logoUrl = $this->uriLogo;
if ($template && ($logo = $template->getLogo())) {
    $logoUrl = $this->basePath($logo->getUri());
}

// check for banner
$hasBanner = $template && ($image = $template->getImage());
$imageServerUrl = $this->basePath('modules/Gastro24/images/bg_placeholder_gray.svg');
if ($hasBanner) {
    $serverUrl = new \Zend\View\Helper\ServerUrl();
    $imageServerUrl = $serverUrl($this->basePath($image->getUri()));
}

// check for newer than 24 hours
$newerThanDay = false;
// get date difference
$today = new DateTime();
$jobDate = $job->getDatePublishStart() ?? $job->getDateCreated();
// workaround - mongodb entity has difference in time
$time = strtotime($jobDate->format('y-m-d\TH:i:s.u'). '+02:00');
$jobDate->setTimestamp($time);
$dayDiff = $today->diff($jobDate);
if ($dayDiff->days < 1) {
    $newerThanDay = true;
}

// organisation values
$org = $this->job->getOrganization();
$orgIsDisabled = false;
$orgName = $this->jobOrganizationName($this->job);
if ($org && (Organizations\Entity\Organization::PROFILE_DISABLED == $org->getProfileSetting() || is_null($org->getProfileSetting()) )) {
    $orgIsDisabled = true;
}
$industries = $job->getClassifications()->getIndustries();

?>
<?=$this->jsonLd($this->job)?>
  <style>
  .link-tag:hover, .link-tag.active {
    background-color: #4e4e4e;
  }
  .link-tag, .link-tag:visited {
    display: inline-block;
    padding: 2px 10px;
    line-height: 23px;
    border: 0;
    border-radius: 13px;
    color: #fff;
    background-color: #6f6f6f;
    text-decoration: none;
    cursor: pointer;
  }
  .list-no-style, .ui-autocomplete {
    margin: 0;
    padding: 0;
    list-style: none;
  }
  .list-no-style li {
    display: inline;
  }
  </style>
<div class="panel panel-default panel__job-detail">
    <!-- New Badge -->
    <?php if (!$hasBanner && $newerThanDay): ?>
        <div class="corner"><span>NEU</span></div>
    <?php endif; ?>
    <!-- End New Badge -->

    <!-- Bannerbild -->
    <?php if ($hasBanner): ?>
        <div class="banner" style="background-image: url(<?= $imageServerUrl ?>)"></div>
    <?php endif; ?>
    <!-- End Bannerbild -->

    <div class="panel-body">
        <!-- company logo and job title-->
        <?php if ($hasBanner): ?>
            <div class="teaser__job-detail">
                <!-- New Badge -->
                <?php if ($newerThanDay): ?>
                    <div class="corner"><span>NEU</span></div>
                <?php endif; ?>
                <!-- End New Badge -->

                <div itemprop="logo">
                    <div class="wrapper__logo">
                        <img src="<?= $logoUrl ?>" alt="<?= $this->organizationName?>">
                    </div>
                </div>
                <h1><?=$this->job->getTitle()?></h1>
            </div>
        <?php endif; ?>
        <?php if (!$hasBanner): ?>
            <h1 class="no-banner"><?=$this->job->getTitle()?></h1>
        <?php endif; ?>
        <!-- end company logo and job title-->

        <!-- expired info box -->
        <?= $this->partial('jobs/partials/expired-info.phtml', ['isExpired' => $isExpired]); ?>
        <!-- end expired info box -->

        <div class="job-short-info <?php if(!$hasBanner) echo 'no-banner' ?>">
            <ul>
                <li class="location">
                    <!-- location -->
                    <?php
                    $location = $job->getLocations()->current();
                    if ($location == '') {
                        echo $this->translate('Swiss');
                    }
                    elseif ($location) {
                        echo $location->getCity() ? $location->getCity() : preg_replace('~\(.*?\)$~', '', (string) $job->getLocation());
                    }
                    else {
                        echo preg_replace('~\(.*?\)$~', '', (string) $job->getLocation());
                    }
                    ?>
                    <!-- end location -->
                </li>
                <li class="company">
                    <!-- company name -->
                    <?php if ($org && !$orgIsDisabled): ?>
                        <a title="Jobs <?= $this->organizationName ?>" href="<?= $this->orgProfileUrl($org)?>?clear=1"><?= $orgName ?></a>
                    <?php else: ?>
                        <strong><?= $this->organizationName ?></strong>
                    <?php endif ?>
                    <!-- end company name -->
                </li>
                <li class="type">
                    <!-- type of contract -->
                    <?php
                    $typeOfContract = $job->getClassifications()->getEmploymentTypes()->__toString() ?:'Vollzeit' ?>
                    <span class="yk-contract yk-<?=$typeOfContract?>"><?=$typeOfContract; ?></span>
                    <!-- end type of contract -->
                </li>
                <li class="date">
                    <!-- published date -->
                    <span><?= $this->publishDateFormatter($job) ?></span>
                    <!-- end published date -->
                </li>
                <?php if ($industries->getItems()->count() && !$this->isCrawlerJob($org)): ?>
                    <li class="industries">
                        <?= $industries->__toString(); ?>
                    </li>
                <?php endif; ?>
            </ul>

            <div class="wrapper__right">
                <?php if (!$hasBanner): ?>
                    <div class="wrapper__logo">
                        <img src="<?= $logoUrl ?>" alt="<?= $this->organizationName?>">
                    </div>
                <?php endif; ?>
            </div>
        </div>

        <hr class="job-details-devider"/>

        <div class="first apply-button-group">
            <!-- share button -->
            <div id="shareMailTop" class="text-center hidden-xs"></div>
            <div id="shareWhatsappTop" class="text-center visible-xs"></div>
            <!-- end share button -->

            <!-- apply button -->
            <?= $this->partial('jobs/partials/apply-button.phtml', [
                'preview' => $preview,
                'isExpired' => $isExpired,
                'job' => $this->job,
            ]); ?>
            <!-- end apply button -->

            <!-- favorite button -->
            <?= $this->partial('jobs/partials/favorite-button.phtml', [
                'jobId' => $job->getId(),
                'isExpired' => $isExpired,
                'buttonCss' => 'favorite-button',
            ]); ?>
            <!-- end favorite button -->
        </div>

        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <!-- job content -->
                <div id="job_content">
                <?php if ($this->html): ?>
                    <div class="position">
                        <?=$this->html?>
                    </div>
                <?php else: ?>
                    <!-- introduction -->
                    <div class="introduction">
                        <?= $this->job->getTemplateValues()->getIntroduction();?>
                    </div>

                    <!-- position -->
                    <div class="position">
                        <?= $replaceImage($this->job->getTemplateValues()->get('position'));?>
                    </div>

                    <!-- requirements -->
                    <div class="position">
                        <?php if($this->benefits): ?>
                         <!--   <div><b><?=$this->labelRequirements?></b></div> -->
                        <?php endif;?>
                        <?=$this->requirements;?>
                    </div>

                    <!-- qualifications -->
                    <?php if ($this->qualifications): ?>
                        <div class="position">
                            <!--  <div><b>Qualifikation</b></div> -->
                            <?=$this->qualifications;?>
                        </div>
                    <?php endif;?>

                    <!-- benefits -->
                    <?php if ($this->benefits): ?>
                        <div class="position">
                           <!--   <div><b><?=$this->labelBenefits?></b></div>-->
                            <?=$this->benefits;?>
                        </div>
                    <?php endif;?>
                <?php endif; ?>
                <!-- end job content -->

                <!-- company description -->
                <p ><?=($org = $this->job->getOrganization()) && ($desc = $org->getDescription()) ? $desc : '' ?></p>
                <!-- end company description -->
                <!-- company address -->
                <div itemscope itemtype="http://schema.org/Organization">
                    <strong itemprop="name">
                        <?= $this->organizationName?>
                    </strong><br/>
                    <?php if ($this->street || $this->postalCode || $this->city || $this->phone):?>
                        <address itemprop="address" itemscope itemtype="http://schema.org/PostalAddress">
                            <?php if ($this->street): ?><span itemprop="streetAddress"><?=$this->street?></span><br><?php endif ?>
                            <?php if ($this->postalCode): ?><span itemprop="postalCode"><?=$this->postalCode?></span><?php endif ?>
                            <?php if ($this->city): ?><span itemprop="addressLocality"><?=$this->city?></span><br /><?php endif ?>
                            <?php if ($this->phone): ?>Telefon: <span itemprop="telephone"><?=$this->phone?></span><br /><?php endif ?>
                            <?php if ($this->fax): ?>Fax: <?=$this->fax?></span><br /><?php endif ?>
                        </address>
                    <?php endif?>
                </div>
                </div>
                <!-- end company address -->
            </div>
        </div>

        <div class="apply-button-group">
            <!-- share button -->
            <div id="shareMailBottom" class="text-center hidden-xs"></div>
            <div id="shareWhatsappBottom" class="text-center visible-xs"></div>
            <!-- end share button -->

            <!-- apply button -->
            <?= $this->partial('jobs/partials/apply-button.phtml', [
                'preview' => $preview,
                'isExpired' => $isExpired,
                'job' => $this->job,
            ]); ?>
            <!-- end apply button -->

            <!-- favorite button -->
            <?= $this->partial('jobs/partials/favorite-button.phtml', [
                'jobId' => $job->getId(),
                'isExpired' => $isExpired,
                'buttonCss' => 'favorite-button',
            ]); ?>
            <!-- end favorite button -->
        </div>
        
<div style="
    background: #f6f6f6;
    border-radius: 3px 3px 0 0;
    font-size: 16px;
    padding: 13px 10px 10px;
    margin-bottom: 0;
    text-align: center;
    position: relative;
    border-bottom: 1px solid #ececec;
    border-top: 1px solid #ececec;
    margin-bottom: 25px;
    ">
  <p class="text-center" style="
    margin-bottom: 0;
    color: #454342;
    ">Bitte beziehen Sie sich bei Ihrer Bewerbung auf <strong>gastrojob24.ch</strong>.</p>
    
</div>

        <!-- share buttons -->
        <div class="text-center">Diesen Job teilen: </div>
        <div id="share" class="text-center round-shares"></div>
        <div class="clearfix"></div>
        <!-- end share buttons -->

        <!-- similar jobs -->
        <?php if (!$preview): ?>
            <?php echo $this->partial('jobs/partials/similar-jobs.phtml', ['job' => $this->job]); ?>
        <?php endif; ?>
        <!-- end similar jobs -->

        <!-- similar company jobs -->
        <?php if (!$preview): ?>
            <?php echo $this->partial('jobs/partials/similar-company-jobs.phtml', ['job' => $this->job]); ?>
        <?php endif; ?>
        <!-- end similar company jobs -->

        <?php if (!$preview): ?>
            <!-- recommended jobs
            <div class="grey-description-container">
                <div class="content">
                    <div class="headline">Empfohlene Jobs</div>
                    <div class="content__inner">
                      
                    </div>
                </div>
            </div>
             end recommended jobs -->

            <!-- recommended jobs by cities
            <div class="grey-description-container">
                <div class="content">
                    <div class="headline">Jobs nach Städten</div>
                    <div class="content__inner">
                        
                    </div>
                </div>
            </div>
           end recommended jobs by cities -->
        <?php endif; ?>

    </div>
</div>

<!-- socials -->
<?php $this->configHeadScript()->appendScript('
    $("#share").jsSocials({
        showLabel: false,
        showCount: true,
        shares: ["email", "twitter", "facebook", "whatsapp"]
    });
    $("#shareMailTop").jsSocials({
        showCount: true,
        shares: ["email"]
    });
    $("#shareMailBottom").jsSocials({
        showCount: true,
        shares: ["email"]
    });
    $("#shareWhatsappTop").jsSocials({
        showLabel: false,
        showCount: true,
        shares: ["whatsapp"]
    });
    $("#shareWhatsappBottom").jsSocials({
        showLabel: false,
        showCount: true,
        shares: ["whatsapp"]
    });
'); ?>
<!-- end socials -->