<?php
/**
 * YAWIK
 *
 * @filesource
 * @license MIT
 * @copyright  2013 - 2018 Cross Solution <http://cross-solution.de>
 *
 * Variables:
 *             $job         JobInterface    Job Entity
 *             $isVisited   bool            Has the user already visited this job in the current session
 */

// meta data
$this->headTitle($this->metaTitle);
$this->headMeta()->setName('description', $this->translate($this->metaDescription))
    ->setProperty('og:title', $this->metaOgTitle)
    ->setProperty('og:description', 'Jetzt bewerben auf die Stelle &quot;' . $job->getTitle() . '&quot; bei Gastrojob24.ch - der Gastronomie & Hotellerie Jobbörse der Schweiz.')
    ->setProperty('og:url', $this->jobUrl($job, ['linkOnly' => true, 'absolute' => true]))
    ->setProperty('og:image', 'https://www.gastrojob24.ch/modules/Gastro24/gastro-logo-fb.png')
    ->setProperty('og:locale', 'de_DE')
    ->setProperty('og:type', 'website')
    ->setAutoEscape(false);


// check for preview
$routeParams = $this->params()->fromRoute();
$preview = false;
if (isset($routeParams['isPreview']) && $routeParams['isPreview']) {
    $preview = true;
}

// WORKAROUND for coop crawler -> wrong link
$isCoopJobWithWrongLink = false;
if ($job->getOrganization() && $job->getOrganization()->getOrganizationName()->getName() == 'Coop' && strpos($job->getLink(), 'https://www.jobs.ch') !== false) {
    $isCoopJobWithWrongLink = true;
}


if ($this->isIntern):
     $this->headMeta()->setName('robots', 'index,follow');
     // intern HTML
elseif(!$this->isIntern && !$this->isEmbeddable):
      $this->headMeta()->setName('robots', 'noindex,follow');
     // External Redirects
elseif($isCoopJobWithWrongLink):
    $this->headMeta()->setName('robots', 'noindex,follow');
endif;

// organisation values
$org = $job->getOrganization();
$orgIsDisabled = false;
$orgName = $this->jobOrganizationName($this->job);
if ($org && (Organizations\Entity\Organization::PROFILE_DISABLED == $org->getProfileSetting() || is_null($org->getProfileSetting()) )) {
    $orgIsDisabled = true;
}

$isExpired = ($this->job->getStatus()) ? $this->job->getStatus()->getName() == \Jobs\Entity\StatusInterface::EXPIRED : false;

// pagination values
$container = new \Laminas\Session\Container('gastro24_jobboardcontainer');
$lastSearchQuery = $container->landingPageSearchQuery;
$searchTerm = $container->searchTerm;
$hasSession = count($container->getArrayCopy());

if($container->fromCompanyProfile && $container->companyName) {
    $backTitle = $container->companyName . ' Jobs';
    $lastSearchQueryUrl = $this->orgProfileUrl($org) . '?clear=1';
}
elseif (!$lastSearchQuery) {
    $lastSearchQueryUrl = ($container->fromCompanyProfile) ? '/de/jobs?clear=1' : $this->url('lang/jobboard', [], ['query'=> ['q' => $searchTerm]], true);
    $backTitle = $this->translate('Back to search');
}
else {
    $lastSearchQueryUrl = $this->url('lang/landingPage', ['q' => $container->landingPageTerm, 'format' => 'html' ], true);
    $backTitle = $this->translate($lastSearchQuery . ' Jobs');
}

// banner image
$hasBanner = false;
if (!$this->isIntern && $this->isEmbeddable) {
    // check for banner
    // default banner
    $imageServerUrl = $this->basePath('modules/Gastro24/images/bg_placeholder_blue.svg');
    // banner from org
    if ($org) {
        $organizationAdditionalRepo = $this->services('repositories')->get(\Gastro24\Entity\OrganizationAdditional::class);
        /** @var \Gastro24\Entity\OrganizationAdditional $organizationAdditional */
        $organizationAdditional = $organizationAdditionalRepo->findOneByOrganizationId($org->getId());
        if ($organizationAdditional && $organizationAdditional->getBanner()) {
            $imageServerUrl = $this->basePath($organizationAdditional->getBanner()->getUri());
            $hasBanner = true;
        }
    }
    // banner from job
    /** @var \Gastro24\Entity\Template $template */
    $template = $this->job->getAttachedEntity('gastro24-template');
    $jobBanner = $template && ($image = $template->getImage());
    if ($jobBanner) {
        $serverUrl = new \Laminas\View\Helper\ServerUrl();
        $imageServerUrl = $serverUrl($this->basePath($image->getUri()));
        $hasBanner = true;
    }
    if ($template && $template->getHideBanner()) {
        $hasBanner = false;
    }
}

// get logo url
$organizationImageCache = $this->services('Organizations\ImageFileCache\Manager');
$logoUrl = $this->basePath('modules/Gastro24/images/no-company-logo.png');
// get org logo as default
$org = $this->job->getOrganization();
if($org && $org->getImages()->notEmpty('images')) {
    $logoUrl = $this->basePath($organizationImageCache->getUri($org->getImages()->get('thumbnail')));
}
$jobLogoUrl = $this->gastroLogoUri($this->job);
if ($jobLogoUrl) {
    $logoUrl = $jobLogoUrl;
}

// check for newer than 24 hours
$newerThanDay = false;
// get date difference
$today = new DateTime();
$jobDate = $job->getDatePublishStart() ?? $job->getDateCreated();
// workaround - mongodb entity has difference in time
$time = strtotime($jobDate->format('y-m-d\TH:i:s.u'). '+02:00');
$jobDate->setTimestamp($time);
$dayDiff = $today->diff($jobDate);
if ($dayDiff->days < 1) {
    $newerThanDay = true;
}

$link = $this->job->getLink();
$industries = $job->getClassifications()->getIndustries();
$qualifications = $this->job->getClassifications()->getProfessions();

//if (!$link) {
//    $link = $this->jobUrl($job, ['preview' => true, 'linkOnly' => true]);
//    $this->isEmbeddable = true;
//}

if (!$this->isIntern && !$this->isVisited && !$this->isEmbeddable):
$this->headScript()->captureStart();?>
;(function($, w) {
    $(function() {
        w.setTimeout(
            function() { w.location.href='<?=$this->job->getLink()?>'; },
            3000
        );
    });
})(jQuery, window);
<?php $this->headScript()->captureEnd();
endif;

$this->headScript()->appendFile($this->basePath($this->asset('modules/Gastro24/js/jobs.js')))
    ->appendFile($this->basePath('/dist/js/bootstrap-dialog.min.js'))
?>

<?php if ($preview): ?>
    <?php $this->headStyle()->captureStart() ?>
    .container {
    min-width: 100%;
    padding: 0;
    }
    <?php $this->headStyle()->captureEnd() ?>
<?php endif; ?>


<?php if (!$preview) : ?>

    <?php echo $this->partial('jobs/partials/navigation.phtml', [
        
        'hasBanner' => $this->hasBanner,
        'hasSession' => $hasSession,
        'backTitle' => $backTitle,
        'lastSearchQueryUrl' => $lastSearchQueryUrl,
        'prevJob' => $this->prevJob,
        'nextJob' => $this->nextJob,
    ]);
    ?>
<?php endif; ?>
<style>

.intro p {

    margin-bottom:20px;
 
}
 
.apply-detail {

    margin-right: 10px;
    margin-top: 0px;
}


.apply-wrapper {
    display: flex;
    flex-direction: row;
    padding: 10px 0;
    float: left;
}

.apply-wrapper .favorite-button {
    border-radius: 0;
    margin-left: 10px;
    margin-bottom: 0;
}

.apply-info-new {
    color: #ccc;
    font-size: 12px;
    display: block;
    float: left;
    width: 100%;

}

.apply-info-new i {
    color: green;
    font-size: 16px;

}


.full-width-bar-vw {

    background: #fff;
    width: 100vw;
    position: relative;
    left: 50%;
    right: 50%;
    margin-left: -50vw;
    margin-right: -50vw;
}


.meta-adress {
    margin-top: 16px;
    margin-bottom: 0px;

}

.meta-adress a {
    display: block;
    color: #1e69a3; 
}

.social-media-company-profile {
    margin-top: 16px;

}

.social-media-company-profile a {
    color: #b1b1b1;
    font-size: 16px;
    margin-right: 5px;

}

.social-media-company-profile a:hover {
    color: #000;
}

.company-link {
    color: rgb(71, 60, 60);
    text-decoration: underline;
}

@media (min-width: 992px) {
    .company-description-wrapper .row>.col-md-3 {
        position: -webkit-sticky;
        position: sticky;
        top: 5px;
        padding-left: 0;
    }
}


.company-description-wrapper address {
    color: rgb(118, 115, 125);
    margin-bottom: 0px;
}

.company-description-wrapper .info-card h2 {
    display: block;
    text-overflow: ellipsis;
    white-space: nowrap;
    overflow: hidden;
}

.content {
    position: relative;
    overflow: hidden;
    margin-bottom: auto !important;
}

.content:after {
    content: "";
    position: absolute;
    left: 0;
    height: 400px;
    right: 0;
    top: 0px;
    bottom: -40px;
    filter: blur(20px);
    background-position: center center;
    position: absolute;
    overflow: hidden;
    botton: -20px;
    transform: scale(1.1);
}

.company-bg-image {
    width: 100vw;
    left: 50%;
    right: 50%;
    position: relative;
    margin-left: -50vw;
    margin-right: -50vw;
    overflow: hidden;
}

.company-bg-image:before {
    display: block;
    position: absolute;
    top: -45px;
    bottom: -45px;
    left: -35px;
    right: -35px;
    content: "";
    background-size: cover;
    background-position: center center;
    filter: blur(25px);
}

.company-profile-wrapper {
    left: 0;
    right: 0;
    top: 0;
    position: absolute;
}

main#content {
    padding-top: 0;
}

.jgArSS {
    background-size: cover;
    height: 410px;
    background-position: center center;
}

.company-profile-image {
    background-color: #fff;
    display: flex;
    padding: 20px 30px;
}

.no-banner .company-profile-image {
    padding: 0 15px;
}

.company-profile-image h1 {
    margin-top: 0px;
    padding-right: 95px;
    font-weight: bold;
}

.info-card {
    background: white;
    padding: 20px 30px;
    margin-bottom: 16px;
    margin-top: 32px;

}

.info-card:first-child {
    margin-top: 0px;
}

.job-logo-wrapper {
    height: 150px;
    display: inline-block;
    text-align: center;
    width: 150px;
    padding: 5px;
    background-color: #fff;
    margin-right: 20px;
    box-shadow: 0 0 6px #ccc;
    -webkit-border-radius: 2px;
    -moz-border-radius: 2px;
    border-radius: 2px;
    margin-top: -70px;
    line-height: 140px;
    border-radius: 4px;
}

.no-banner .job-logo-wrapper {

    margin-top: -20px;

}

.job-logo-wrapper img {
    max-width: 100%;
    display: inline-flex;
    max-height: 100%;
    vertical-align: middle;
    text-align: center;
    margin: 0 auto;
}

.job-info-wrapper {
    position: relative;
    width: calc(100% - 175px);
    display: inline-block;
}


.job-info-wrapper p {

    font-size: 16px;
    color: rgb(118, 115, 125);
}

.job-info-wrapper p a {

    color: #1e69a3;
}

.job-info-wrapper .address-short {
    font-size: 16px;
    color: rgb(118, 115, 125);
}

.info-card h2 {
    font-size: 18px;
    margin-top: 0;
    margin-right: 25px;
    margin-bottom: 5px;
    overflow: hidden;
    text-overflow: ellipsis;
    line-height: 24px;
}

.iframe-container {
    position: relative;
    padding-bottom: 56.25%;
    /* ratio 16x9 */
    height: 0;
    overflow: hidden;
    width: 100%;
    height: auto;
}

.iframe-container iframe {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
}
.iframe-container img {
  
    width: 100%;
   
}


/* ratio 4x3 */

.iframe-container.ratio4x3 {
    padding-bottom: 75%;
}

.breadcrumb {
    margin-top: 10px;
}

.job-count-badge {
    display: inline;
    padding: 7px 10px;
    font-size: 16px;
    font-weight: 300;
    line-height: 1;
    color: #fff;
    text-align: center;
    white-space: nowrap;
    background-color: #60a5d1;
    top: 0;
    right: 0;
    position: absolute;
    border-radius: 4px;
}

@media (min-width:768px) {

   .gastro24-controller-redirectexternaljobs-index #jobs-list-filter-wrapper {

     display:none!important;
    }

}
@media (max-width:991px) {
    .jgArSS {
        height: 250px;
    }

    .company-bg-image {
        height: 435px;
    }
}

@media (max-width:768px) {
    .company-description-wrapper .info-card:first-child {
        margin-top: 20px;
    }

    .jgArSS {
        height: 200px;
    }

    .company-bg-image {
        height: 385px;
    }

    .job-logo-wrapper {
        height: 115px;
        margin-top: -50px;
        width: 115px;
        line-height: 105px;
    }

    .job-info-wrapper {
        width: calc(100% - 135px);
    }

    .company-profile-image h1 {
        font-size: 24px;
        line-height: 28px;
        padding-right: 85px;
    }

    .company-profile-image {
        padding: 15px 20px;
    }


    .company-profile-wrapper {
        left: -15px;
        right: -15px;
    }

}

@media (max-width:510px) {
    .company-profile-image h1 {
        display: block;
        text-overflow: ellipsis;
        overflow: hidden;
    }

    .jgArSS {
        height: 150px;
    }

    .company-bg-image {
        height: 300px;
    }

    .job-logo-wrapper {
        height: 90px;
        margin-top: -40px;
        width: 90px;
        line-height: 80px;
    }

    .company-profile-image h1 {
        font-size: 20px;
        line-height: 28px;
    }

    .job-info-wrapper {
        width: calc(100% - 110px);
    }

  .no-banner .job-info-wrapper {
    top: -20px;

   }
   
}
@media (max-width:468px) {
    .info-card {
        padding: 15px;
    }
    
   .company-profile-image h1 {
    padding-right: 0;
  }

    .no-banner.company-profile-image {
        padding: 0 12px;
    }

    .company-profile-wrapper {
        left: -12px;
        right: -12px;
    }
}


.no-banner .company-bg-image:before {
    display: block;
    position: absolute;
    top: 0;
    bottom: 0;
    left: 0;
    right: 0;
    content: "";
    background-size: cover;
    background-position: center center;
    filter: none;
    background-color: #fff;
    background-image: none;
    height: 305px;


}

.no-banner .company-profile-wrapper {
    top: 50px;
}

.no-banner .company-bg-image {
    height: 305px !important;
}

.no-banner .jgArSS {

    height: 45px;
    background-color: #fff;
    background-image: none !important;
}

.no-banner.full-width-bar-vw {
    -moz-box-shadow: 0 2px 3px 0 rgba(91, 91, 91, 0.25);
    -webkit-box-shadow: 0 2px 3px 0 rgba(91, 91, 91, 0.25);
    box-shadow: 0 2px 3px 0 rgba(91, 91, 91, 0.25);
    z-index: 8;

}

.details-list-horizontal {
    list-style: none;
    padding: 0;
    margin: 0;
    display: flex;
    flex-wrap: wrap;
    margin-bottom: 20px;
}

.details-list-horizontal>li:not(:nth-last-child(-n+1)) {
    border-bottom: 1px solid #e7eaee;
}




.details-list-horizontal>li .details-list-content {
    padding-left: 36px;
    line-height: 1.2;
}

.details-list-horizontal>li .details-list-content>.title {
    filter: alpha(Opacity=30);
    opacity: .3;
    display: block;
    font-size: 14px;
}

.details-list-horizontal>li i.fa-angle-right {
    font-size: 130%;
}

.details-list-horizontal>li i {
    float: left;
    color: #3886f3;
    margin-top: .5rem;
}

.details-list-horizontal>li {
    flex: 0 0 50%;
}

.details-list-horizontal>li {
    padding: 1.5rem 1.5rem 1.5rem 0;
    border-bottom: 1px solid rgba(255, 255, 255, .15);
    font-weight: 600;
}

.position ul {
    margin-left: 15px;

}

.job-pagination li a {
    font-size: 14px;
}

.job-pagination li a {
    opacity: .3;
}

.job-pagination li:hover a {
    opacity: 1;
}

.position a[href^="mailto:"], .pdf-link-original, .position p a {

    color: #1e69a3;
    text-decoration: underline;
}
 

</style>

<div class="row">
    <div class="col-md-12">
       
       <!-- view-intern --> 
        <?php if ($this->isIntern):?>
            <?= $this->internalJob ?>
        <?php endif ?>

      <!-- end view-intern --> 
       
<!-- view PDF / External --> 
<?php if (!$this->isIntern && $this->isEmbeddable):?>
        
<?php if ($hasBanner): ?>
<style>
    .company-bg-image:before {
        background-image: url(<?= $imageServerUrl ?>);
    }
</style>
<?php endif; ?>

<div class="<?php if(!$hasBanner) echo 'no-banner' ?>" style="position:relative;">
    <div style="height:482.5px" class="company-bg-image"></div>
    <div class="<?php if(!$hasBanner) echo 'no-banner' ?> company-profile-wrapper">
        <div class="jgArSS" style="background-image: url(<?= $imageServerUrl ?>);"></div>
        <div class="company-profile-image">


            <?php if ($jobLogoUrl): ?>
            <span class="job-logo-wrapper">
                <img class="job-logo" alt="<?= $orgName?>" src="<?= $logoUrl ?>" />
            </span>
            <?php endif; ?>



            <div class="job-info-wrapper">
                <h1><?=ucfirst($this->job->getTitle())?></h1>

                <?php $typeOfContract = $job->getClassifications()->getEmploymentTypes()->__toString() ?:'Vollzeit' ?>

                <p><?=$typeOfContract; ?> bei <?php if ($org && !$orgIsDisabled && !$preview): ?>
                    <a title="<?= $this->organizationName ?> " href="<?= $this->orgProfileUrl($org)?>?clear=1"><?= $orgName ?></a>
                    <?php elseif (!$preview && $job->getTemplateValues()->get('companyWebsite')) : ?>
                    <a rel="nofollow" title="<?= $this->organizationName ?>" href="<?= $job->getTemplateValues()->get('companyWebsite') ?>"><?= $orgName ?></a>
                    <?php else: ?>
                    <?= (!empty($this->organizationName)) ? $this->organizationName : $orgName ?>
                    <?php endif ?> in <?php
                    $location = $job->getLocations()->current();
                    if ($location == '') {
                        echo $this->translate('Swiss');
                    }
                    elseif ($location) {
                        echo $location->getCity() ? $location->getCity() : preg_replace('~\(.*?\)$~', '', (string) $job->getLocation());
                    }
                    else {
                        echo preg_replace('~\(.*?\)$~', '', (string) $job->getLocation());
                    }
                    ?>
                </p>

                <div class="apply-wrapper">
                    <?= $this->partial('jobs/partials/apply-button.phtml', [
                        'preview' => $preview,
                        'isExpired' => $isExpired,
                        'job' => $this->job,
                          ]); 
                        ?>
                <?php if (!$preview): ?>
                     <?= $this->partial('jobs/partials/favorite-button.phtml', [
                        'jobId' => $job->getId(),
                        'isExpired' => $isExpired,
                        'buttonCss' => 'favorite-button',
                      ]); 
                    ?>
                <?php endif; ?>
                  
                </div>

                <?php if ($newerThanDay): ?>
                <span class="apply-info-new"><i class="fa fa-clock-o"></i> Gehören Sie zu den ersten 3 Bewerbern.</span>
                <?php endif; ?>

                <?= $this->partial('jobs/partials/expired-info.phtml', ['isExpired' => $isExpired]); ?>


            </div>
        </div>
    </div>
</div>

<div class="company-description-wrapper">
    <div class="row">
        <div class="col-md-12">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb" itemscope="" itemtype="http://schema.org/BreadcrumbList">
                    <li class="breadcrumb-item" itemprop="itemListElement" itemscope="" itemtype="http://schema.org/ListItem">
                        <a itemprop="item" href="/"> <span itemprop="name">Home</span></a>
                        <meta itemprop="position" content="1">
                    </li>
                    <li class="breadcrumb-item" itemprop="itemListElement" itemscope="" itemtype="http://schema.org/ListItem">
                        <a itemprop="item" href="/de/jobs?clear=1"> <span itemprop="name">Jobs</span></a>
                        <meta itemprop="position" content="2">
                    </li>
                    <li class="breadcrumb-item" itemprop="itemListElement" itemscope="" itemtype="http://schema.org/ListItem">
                        <span itemprop="name"><?=ucfirst($this->job->getTitle())?></span>
                        <meta itemprop="position" content="3">
                    </li>
                </ol>
            </nav>
        </div>


        <div class="col-md-9">
            <div class="info-card" style="margin-bottom:0px;">
                <h2>Kurz & knapp</h2>
                <ul class="details-list-horizontal">


                    <li><i class="fa fa-angle-right"></i>
                        <div class="details-list-content"><span class="title">Datum der Veröffentlichung</span><span class="value"><?= $this->publishDateFormatter($job) ?></span></div>
                    </li>
<?php if ($industries->getItems()->count() && !$this->isCrawlerJob($org) && $industries->__toString() != ""): ?>
 <li ><i class="fa fa-angle-right"></i>
   <div class="details-list-content"><span class="title">Branche</span><span class="value"><?= $industries->__toString(); ?></span></div>
</li>

<?php else: ?>

 <li ><i class="fa fa-angle-right"></i>
   <div class="details-list-content"><span class="title">Branche</span><span class="value">Gastronomie / Tourismus</span></div>
</li>
<?php endif; ?>

<?php if ($qualifications->getItems()->count() && !$this->isCrawlerJob($org) && $qualifications->__toString() != ""): ?>
 <li ><i class="fa fa-angle-right"></i>
   <div class="details-list-content"><span class="title">Erforderliche Qualifikation</span><span class="value"><?= $qualifications->__toString(); ?></span></div>
</li>
<?php endif; ?>


                    <li><i class="fa fa-angle-right"></i>
                        <div class="details-list-content"><span class="title">Beschäftigungsart</span><span class="value"><?=$typeOfContract; ?></span></div>
                    </li>

                    </li>
                    <li><i class="fa fa-angle-right"></i>
                        <div class="details-list-content"><span class="title">Arbeitsort</span><span class="value"><?php
                    $location = $job->getLocations()->current();
                    if ($location == '') {
                        echo $this->translate('Swiss');
                    }
                    elseif ($location) {
                        echo $location->getCity() ? $location->getCity() : preg_replace('~\(.*?\)$~', '', (string) $job->getLocation());
                    }
                    else {
                        echo preg_replace('~\(.*?\)$~', '', (string) $job->getLocation());
                    }
                    ?></span></div>
                    </li>

                </ul>
                
               <?php if ($this->job->getTemplateValues()->get('companyDescription')): ?>
               <h2><?= (!empty($this->organizationName)) ? $this->organizationName : $orgName ?> als Arbeitgeber</h2>
                <div class="position intro">
                    <p><?= nl2br($this->job->getTemplateValues()->get('companyDescription')); ?></p>
                </div>
                <?php endif;?>

                 <h2>Stellenbeschreibung</h2>

                <!-- end info-card -->
                
                 <?php if(strpos($link, '.pdf') !== false): ?>
                
                    <i class="fa fa-file-pdf-o"></i> <a href="<?=$link?>" class="pdf-link-original" target="_blank" rel="noopener" title="Originalinserat öffnen">Originalinserat öffnen</a>
                     
                <?php endif; ?>
                
            </div>
             <?php if(strpos($link, '.pdf') !== false): ?>
                <style>
                    
                    .no-apply-link { display:none;}
     
                </style>
                   <canvas style="width:100%" id="my_canvas"></canvas>
                   	<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/pdfjs-dist@2.0.943/build/pdf.min.js"></script>
                    <script>
                    
                        pdfjsLib.getDocument("<?=$link?>").then(doc => {
                            //console.log("This file has " + doc._pdfInfo.numPages + " pages");
                    
                            doc.getPage(1).then(page => {
                                
                        
                                var myCanvas = document.getElementById("my_canvas");
                                var context = myCanvas.getContext("2d");
                                var viewport = page.getViewport(1.2);
                                 myCanvas.width = viewport.width;
                                 myCanvas.height = viewport.height;
                    
                                page.render({
                                    canvasContext: context,
                                    viewport: viewport

                                });
                    
                                var renderTask = page.render(renderContext);
                                renderTask.promise.then(function() {
                                    //console.log('Page rendered');
                                });
                    
                    
                            });
                    
                    
                        });
                    
                    </script>
             

          
                  <?php else: ?>
                      <iframe defer style="height:1500px;width:100%;" src="<?=$link?>"></iframe>
            <?php endif; ?>

            <?php if (!$preview): ?>
            <?php echo $this->partial('jobs/partials/similar-company-jobs.phtml', ['job' => $this->job]); ?>
            <?php endif; ?>

            <?php if (!$preview && !$isExpired): ?>
            <?php echo $this->partial('jobs/partials/similar-jobs.phtml', ['job' => $this->job]); ?>
            <?php endif; ?>

            <!-- end col-md-9 -->
        </div>


        <div class="col-md-3">
            <div class="info-card" style="margin-bottom:0px;">
                <h2>Kontakt</h2>
                <address>
                    <?= (!empty($this->organizationName)) ? $this->organizationName : $orgName ?> <br>
                    <?php
                        $location = $job->getLocations()->current();
                        if ($location == '') {
                            echo $this->translate('Swiss');
                        }
                        elseif ($location->getCity() && $location->getStreetname() && $location->getPostalcode()) {
                            echo $location->getStreetname() . '<br>';
                            echo $location->getPostalcode() . ' ' . $location->getCity();
                        }
                        else {
                            echo preg_replace('~\(.*?\)$~', '', (string) $job->getLocation());
                        }
                    ?>
                </address>

                <?php if (!$preview && $job->getTemplateValues()->get('companyWebsite')) : ?>
                <div class="meta-adress">
                    <a rel="nofollow" title="<?= $this->organizationName ?>" href="<?= $job->getTemplateValues()->get('companyWebsite') ?>">zur Website</a>
                  </div>
                <?php endif ?>
            </div>
            <div class="iframe-container">
                <?php
                $googleMapsString = '';
                $googleMapsString .= !empty($this->organizationName) ? $this->organizationName : $orgName ;
                $googleMapsString .= '+';

                $location = $job->getLocations()->current();
                if ($location == '') {
                    $googleMapsString .= 'Schweiz';
                }
                elseif ($location->getCity() && $location->getStreetname() && $location->getPostalcode()) {
                    $googleMapsString .= $location->getStreetname() . '+' . $location->getCity() . '+' . $location->getPostalcode() . '+Schweiz';
                }
                else {
                    $googleMapsString .= preg_replace('~\(.*?\)$~', '', (string) $job->getLocation());
                }
                ?>

                <iframe src="https://maps.google.com/maps?width=100%&amp;height=450&amp;hl=de&amp;q=1%20<?= $googleMapsString ?>&amp;ie=UTF8&amp;t=&amp;z=16&amp;iwloc=B&amp;output=embed"
                        frameborder="0" scrolling="no" marginheight="0" marginwidth="0"></iframe>
            </div>
            


            <!-- end col-md-3 -->

 <div class="info-card" style="margin-top:0px;">
    <div class="meta-adress" style="margin-top:0px; margin-bottom:0px;">
        <i class="fa fa-car"></i> <a style="display:inline;" target="_blank" rel="noopener nofollow" href="https://www.google.com/maps/dir//<?= $googleMapsString ?>/">Anfahrt zum Arbeitgeber</a>
    </div>
</div>
        </div>
        

    </div>

    <!-- end company-description-wrapper -->
</div>

<?php if (!$this->auth()->isLoggedIn() || !$preview):?>
   <div class="to-top-link">
                    <a id="scroll-to-top" href="#top"><span class="fa fa-chevron-up"></span> nach oben</a>
   </div>
<?php endif ?>
 
<?php endif ?>
<!-- end view PDF / External -->
        
                  
      <?php $this->configHeadScript()->appendScript('
      
       $(window).resize(function() {
            $(".company-bg-image").height($(".company-profile-wrapper:not(.no-banner)").height());

        });

        $(window).trigger("resize");
      
           
          ');  
        ?>



    </div>
</div>


<!-- apply modal -->
<div class="modal fade" id="job-apply-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
    <div class="modal-dialog" style="width: 90%; max-width:1200px; height: 90%" role="document">
        <div class="modal-content" style="height: 100%">
            <div class="modal-body" style="height: calc(100% - 65px)"></div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Schliessen</button>
            </div>
        </div>
    </div>
</div>
<!-- end apply modal -->
