<?php
/**
 * YAWIK
 *
 * @filesource
 * @license MIT
 * @copyright  2013 - 2018 Cross Solution <http://cross-solution.de>
 *
 * Variables:
 *             $job         JobInterface    Job Entity
 *             $isVisited   bool            Has the user already visited this job in the current session
 */

// meta data
$this->headTitle($this->metaTitle);
$this->headMeta()->setName('description', $this->translate($this->metaDescription))
    ->setProperty('og:title', $this->metaOgTitle)
    ->setProperty('og:description', 'Jetzt bewerben auf die Stelle &quot;' . $job->getTitle() . '&quot; bei Gastrojob24.ch - der Gastronomie & Hotellerie Jobbörse der Schweiz.')
    ->setProperty('og:url', $this->jobUrl($job, ['linkOnly' => true, 'absolute' => true]))
    ->setProperty('og:image', 'https://www.gastrojob24.ch/modules/Gastro24/gastro-logo-fb.png')
    ->setProperty('og:locale', 'de_DE')
    ->setProperty('og:type', 'website')
    ->setAutoEscape(false);

// check for preview
$routeParams = $this->params()->fromRoute();
$preview = false;
if (isset($routeParams['isPreview']) && $routeParams['isPreview']) {
    $preview = true;
}

// WORKAROUND for coop crawler -> wrong link
$isCoopJobWithWrongLink = false;
if ($job->getOrganization() && $job->getOrganization()->getOrganizationName()->getName() == 'Coop' && strpos($job->getLink(), 'https://www.jobs.ch') !== false) {
    $isCoopJobWithWrongLink = true;
}
if ($this->isIntern):
     $this->headMeta()->setName('robots', 'index,follow');
elseif(!$this->isIntern && !$this->isEmbeddable):
      $this->headMeta()->setName('robots', 'noindex,follow');
elseif($isCoopJobWithWrongLink):
    $this->headMeta()->setName('robots', 'noindex,follow');
endif;

// organisation values
$org = $job->getOrganization();
$orgIsDisabled = false;
$orgName = $this->jobOrganizationName($this->job);
if ($org && (Organizations\Entity\Organization::PROFILE_DISABLED == $org->getProfileSetting() || is_null($org->getProfileSetting()) )) {
    $orgIsDisabled = true;
}

$isExpired = ($this->job->getStatus()) ? $this->job->getStatus()->getName() == \Jobs\Entity\StatusInterface::EXPIRED : false;

// pagination values
$container = new \Laminas\Session\Container('gastro24_jobboardcontainer');
$lastSearchQuery = $container->landingPageSearchQuery;
$searchTerm = $container->searchTerm;
$hasSession = count($container->getArrayCopy());

if($container->fromCompanyProfile && $container->companyName) {
    $backTitle = $container->companyName . ' Jobs';
    $lastSearchQueryUrl = $this->orgProfileUrl($org) . '?clear=1';
}
elseif (!$lastSearchQuery) {
    $lastSearchQueryUrl = ($container->fromCompanyProfile) ? '/de/jobs?clear=1' : $this->url('lang/jobboard', [], ['query'=> ['q' => $searchTerm]], true);
    $backTitle = $this->translate('Back to search');
}
else {
    $lastSearchQueryUrl = $this->url('lang/landingPage', ['q' => $container->landingPageTerm, 'format' => 'html' ], true);
    $backTitle = $this->translate($lastSearchQuery . ' Jobs');
}

// banner image
$hasBanner = false;
if (!$this->isIntern && $this->isEmbeddable) {
    // check for banner
    // default banner
    $imageServerUrl = $this->basePath('modules/Gastro24/images/bg_placeholder_blue.svg');
    // banner from org
    if ($org) {
        $organizationAdditionalRepo = $this->services('repositories')->get(\Gastro24\Entity\OrganizationAdditional::class);
        /** @var \Gastro24\Entity\OrganizationAdditional $organizationAdditional */
        $organizationAdditional = $organizationAdditionalRepo->findOneByOrganizationId($org->getId());
        if ($organizationAdditional && $organizationAdditional->getBanner()) {
            $imageServerUrl = $this->basePath($organizationAdditional->getBanner()->getUri());
            $hasBanner = true;
        }
    }
    // banner from job
    /** @var \Gastro24\Entity\Template $template */
    $template = $this->job->getAttachedEntity('gastro24-template');
    $jobBanner = $template && ($image = $template->getImage());
    if ($jobBanner) {
        $serverUrl = new \Laminas\View\Helper\ServerUrl();
        $imageServerUrl = $serverUrl($this->basePath($image->getUri()));
        $hasBanner = true;
    }
    if ($template && $template->getHideBanner()) {
        $hasBanner = false;
    }
}

// get logo url
$organizationImageCache = $this->services('Organizations\ImageFileCache\Manager');
$logoUrl = $this->basePath('modules/Gastro24/images/no-company-logo.png');
// get org logo as default
$org = $this->job->getOrganization();
if($org && $org->getImages()->notEmpty('images')) {
    $logoUrl = $this->basePath($organizationImageCache->getUri($org->getImages()->get('thumbnail')));
}
$jobLogoUrl = $this->gastroLogoUri($this->job);
if ($jobLogoUrl) {
    $logoUrl = $jobLogoUrl;
}

// check for newer than 24 hours
$newerThanDay = false;
// get date difference
$today = new DateTime();
$jobDate = $job->getDatePublishStart() ?? $job->getDateCreated();
// workaround - mongodb entity has difference in time
$time = strtotime($jobDate->format('y-m-d\TH:i:s.u'). '+02:00');
$jobDate->setTimestamp($time);
$dayDiff = $today->diff($jobDate);
if ($dayDiff->days < 1) {
    $newerThanDay = true;
}

$link = $this->job->getLink();
$industries = $job->getClassifications()->getIndustries();

//if (!$link) {
//    $link = $this->jobUrl($job, ['preview' => true, 'linkOnly' => true]);
//    $this->isEmbeddable = true;
//}

if (!$this->isIntern && !$this->isVisited && !$this->isEmbeddable):
$this->headScript()->captureStart();?>
;(function($, w) {
    $(function() {
        w.setTimeout(
            function() { w.location.href='<?=$this->job->getLink()?>'; },
            3000
        );
    });
})(jQuery, window);
<?php $this->headScript()->captureEnd();
endif;

$this->headScript()->appendFile($this->basePath($this->asset('modules/Gastro24/js/jobs.js')))
    ->appendFile($this->basePath('/dist/js/bootstrap-dialog.min.js'))
    ->appendFile($this->basePath('/dist/js/iframeResizer.js'))
    ->appendFile($this->basePath('/dist/js/iframeResizer.contentWindow.min.js'))
    ->appendFile($this->basePath($this->asset('modules/Gastro24/jssocials-1.4.0/dist/jssocials.js')));
?>
<?php if ($preview): ?>
    <?php $this->headStyle()->captureStart() ?>
    .container {
    min-width: 100%;
    padding: 0;
    }
    <?php $this->headStyle()->captureEnd() ?>
<?php endif; ?>

<?php if (!$preview) : ?>
  

    <?php echo $this->partial('jobs/partials/navigation.phtml', [
        'hasSession' => $hasSession,
        'backTitle' => $backTitle,
        'lastSearchQueryUrl' => $lastSearchQueryUrl,
        'prevJob' => $this->prevJob,
        'nextJob' => $this->nextJob,
    ]);
    ?>
<?php endif; ?>
<style>
      
.apply-detail {

    margin-right: 10px;
    margin-top: 0px;
}


.apply-wrapper {

    padding: 10px 0;
    float: left;
}

.apply-info-new {
    color: #ccc;
    font-size: 12px;
    display: block;
    float: left;
    width: 100%;

}

.apply-info-new i {
    color: green;
    font-size: 16px;

}


.full-width-bar-vw {

    background: #fff;
    width: 100vw;
    position: relative;
    left: 50%;
    right: 50%;
    margin-left: -50vw;
    margin-right: -50vw;
}


.meta-adress {
    margin-top: 16px;
    margin-bottom: 16px;

}

.meta-adress a {
    display: block;
    text-decoration: underline;
}

.social-media-company-profile {
    margin-top: 16px;

}

.social-media-company-profile a {
    color: #b1b1b1;
    font-size: 16px;
    margin-right: 5px;

}

.social-media-company-profile a:hover {
    color: #000;
}

.company-link {
    color: rgb(71, 60, 60);
    text-decoration: underline;
}

@media (min-width: 992px) {
    .company-description-wrapper .row>.col-md-3 {
        position: -webkit-sticky;
        position: sticky;
        top: 5px;
        padding-left: 0
    }
}


.company-description-wrapper address {
    color: rgb(118, 115, 125);
    margin-bottom: 0px;
}

.company-description-wrapper .info-card h2 {
    display: block;
    text-overflow: ellipsis;
    white-space: nowrap;
    overflow: hidden;
}

.content {
    position: relative;
    overflow: hidden;
    margin-bottom: auto !important;
}

.content:after {
    content: "";
    position: absolute;
    left: 0;
    height: 400px;
    right: 0;
    top: 0px;
    bottom: -40px;
    filter: blur(20px);
    background-position: center center;
    position: absolute;
    overflow: hidden;
    botton: -20px;
    transform: scale(1.1);
}

.company-bg-image {
    width: 100vw;
    left: 50%;
    right: 50%;
    position: relative;
    margin-left: -50vw;
    margin-right: -50vw;
    overflow: hidden;
}

.company-bg-image:before {
    display: block;
    position: absolute;
    top: -45px;
    bottom: -45px;
    left: -35px;
    right: -35px;
    content: "";
    background-size: cover;
    background-position: center center;
    filter: blur(25px);
}

.company-profile-wrapper {
    left: 0;
    right: 0;
    top: 0;
    position: absolute;
}

main#content {
    padding-top: 0;
}

.jgArSS {
    background-size: cover;
    height: 300px;
    background-position: center center;
}

.company-profile-image {
    background-color: #fff;
    display: flex;
    padding: 20px 30px;
}

.no-banner .company-profile-image {
    padding: 0 15px;
}

.company-profile-image h1 {
    margin-top: 0px;
    padding-right: 95px;
    font-weight: bold;
}

.info-card {
    background: white;
    padding: 20px 30px;
    margin-bottom: 16px;
    margin-top: 32px;

}

.info-card:first-child {
    margin-top: 0px;
}

.job-logo-wrapper {
    height: 150px;
    display: inline-block;
    width: 150px;
    padding: 5px;
    background-color: #fff;
    margin-right: 20px;
    box-shadow: 0 0 6px #ccc;
    -webkit-border-radius: 2px;
    -moz-border-radius: 2px;
    border-radius: 2px;
    margin-top: -70px;
    line-height: 140px;
    border-radius: 4px;
}

.no-banner .job-logo-wrapper {

    margin-top: -20px;

}

.job-logo-wrapper img {
    width: 100%;
    display: inline-table;
    vertical-align: middle;
}

.job-info-wrapper {
    position: relative;
    width: calc(100% - 175px);
    display: inline-block;
}


.job-info-wrapper p {

    font-size: 16px;
    color: rgb(118, 115, 125);
}

.job-info-wrapper p a {

    color: #1e69a3;
}

.job-info-wrapper .address-short {
    font-size: 16px;
    color: rgb(118, 115, 125);
}

.info-card h2 {
    font-size: 18px;
    margin-top: 0;
    margin-right: 25px;
    margin-bottom: 5px;
    overflow: hidden;
    text-overflow: ellipsis;
    line-height: 24px;
}

.iframe-container {
    position: relative;
    padding-bottom: 56.25%;
    /* ratio 16x9 */
    height: 0;
    overflow: hidden;
    width: 100%;
    height: auto;
}

.iframe-container iframe {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
}


/* ratio 4x3 */

.iframe-container.ratio4x3 {
    padding-bottom: 75%;
}

.breadcrumb {
    margin-top: 10px;
}

.job-count-badge {
    display: inline;
    padding: 7px 10px;
    font-size: 16px;
    font-weight: 300;
    line-height: 1;
    color: #fff;
    text-align: center;
    white-space: nowrap;
    background-color: #60a5d1;
    top: 0;
    right: 0;
    position: absolute;
    border-radius: 4px;
}

@media (min-width:768px) {

   .gastro24-controller-redirectexternaljobs-index #jobs-list-filter-wrapper {

     display:none!important;
    }

}
@media (max-width:991px) {
    .jgArSS {
        height: 250px;
    }

    .company-bg-image {
        height: 435px;
    }
}

@media (max-width:768px) {
    .company-description-wrapper .info-card:first-child {
        margin-top: 20px;
    }

    .jgArSS {
        height: 200px;
    }

    .company-bg-image {
        height: 385px;
    }

    .job-logo-wrapper {
        height: 115px;
        margin-top: -50px;
        width: 115px;
        line-height: 105px;
    }

    .job-info-wrapper {
        width: calc(100% - 135px);
    }

    .company-profile-image h1 {
        font-size: 24px;
        line-height: 28px;
        padding-right: 85px;
    }

    .company-profile-image {
        padding: 15px 20px;
    }


    .company-profile-wrapper {
        left: -15px;
        right: -15px;
    }

}

@media (max-width:510px) {
    .company-profile-image h1 {
        display: block;
        text-overflow: ellipsis;
        overflow: hidden;
    }

    .jgArSS {
        height: 150px;
    }

    .company-bg-image {
        height: 300px;
    }

    .job-logo-wrapper {
        height: 90px;
        margin-top: -40px;
        width: 90px;
        line-height: 80px;
    }

    .company-profile-image h1 {
        font-size: 20px;
        line-height: 28px;
    }

    .job-info-wrapper {
        width: calc(100% - 110px);
    }
}

@media (max-width:468px) {
    .info-card {
        padding: 15px;
    }
    
   .company-profile-image h1 {
    padding-right: 0;
  }

    .no-banner.company-profile-image {
        padding: 0 12px;
    }

    .company-profile-wrapper {
        left: -12px;
        right: -12px;
    }
}


.no-banner .company-bg-image:before {
    display: block;
    position: absolute;
    top: 0;
    bottom: 0p;
    left: 0;
    right: 0;
    content: "";
    background-size: cover;
    background-position: center center;
    filter: none;
    background-color: #fff;
    background-image: none;
    height: 305px;


}

.no-banner .company-profile-wrapper {
    top: 50px;
}

.no-banner .company-bg-image {
    height: 305px !important;
}

.no-banner .jgArSS {

    height: 45px;
    background-color: #fff;
    background-image: none !important;
}

.no-banner.full-width-bar-vw {
    -moz-box-shadow: 0 2px 3px 0 rgba(91, 91, 91, 0.25);
    -webkit-box-shadow: 0 2px 3px 0 rgba(91, 91, 91, 0.25);
    box-shadow: 0 2px 3px 0 rgba(91, 91, 91, 0.25);
    z-index: 8;

}

.details-list-horizontal {
    list-style: none;
    padding: 0;
    margin: 0;
    display: flex;
    flex-wrap: wrap;
    margin-bottom: 20px;
}

.details-list-horizontal>li:not(:nth-last-child(-n+2)) {
    border-bottom: 1px solid #e7eaee;
}

.details-list-horizontal>li .details-list-content {
    padding-left: 36px;
    line-height: 1.2;
}

.details-list-horizontal>li .details-list-content>.title {
    filter: alpha(Opacity=50);
    opacity: .5;
    display: block;
    font-size: .7rem;
    text-transform: uppercase;
}

.details-list-horizontal>li i.fa-angle-right {
    font-size: 130%;
}

.details-list-horizontal>li i {
    float: left;
    color: #3886f3;
    margin-top: .5rem;
}

.details-list-horizontal>li {
    flex: 0 0 50%;
}

.details-list-horizontal>li {
    padding: 1.5rem 1.5rem 1.5rem 0;
    border-bottom: 1px solid rgba(255, 255, 255, .15);
    font-weight: 600;
}

.position ul {
    margin-left: 15px;

}

.job-pagination li a {
    font-size: 14px;
}

.job-pagination li a {
    opacity: .3;
}

.job-pagination li:hover a {
    opacity: 1;
}

.position a[href^="mailto:"] {

    color: #1e69a3;
    text-decoration: underline;


}
 

</style>



<div class="row">
    <div class="col-md-12">
       
       <!-- view-intern --> 
        <?php if ($this->isIntern):?>
            <?= $this->internalJob ?>
        <?php endif ?>

      <!-- end view-intern --> 
        
        
        
        
        
        
        
        
        
        
        <?php if (!$this->isIntern && $this->isVisited && !$this->isEmbeddable): ?>

        <?php elseif (!$this->isIntern && !$this->isEmbeddable): ?>

            <style>

         .spinner {
          margin: 0 auto;
          width: 70px;
          text-align: center;
        }

        .spinner > div {
          width: 18px;
          height: 18px;
          background-color: #333;

          border-radius: 100%;
          display: inline-block;
          -webkit-animation: sk-bouncedelay 1.4s infinite ease-in-out both;
          animation: sk-bouncedelay 1.4s infinite ease-in-out both;
        }

        .spinner .bounce1 {
          -webkit-animation-delay: -0.32s;
          animation-delay: -0.32s;
        }

        .spinner .bounce2 {
          -webkit-animation-delay: -0.16s;
          animation-delay: -0.16s;
        }

        @-webkit-keyframes sk-bouncedelay {
          0%, 80%, 100% { -webkit-transform: scale(0) }
          40% { -webkit-transform: scale(1.0) }
        }

        @keyframes sk-bouncedelay {
          0%, 80%, 100% {
            -webkit-transform: scale(0);
            transform: scale(0);
          } 40% {
            -webkit-transform: scale(1.0);
            transform: scale(1.0);
          }
        }

        </style>
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="spinner">
                        <div class="bounce1"></div>
                        <div class="bounce2"></div>
                        <div class="bounce3"></div>
                     </div>
                     <br /><br />
                     <p style="text-align:center;">Sie werden in Kürze automatisch auf das Job-Inserat von <?=$orgName?> weitergeleitet...</p>
                </div>
            </div>
        <?php endif ?>

        <!-- not intern and embedded -->
        <?php if (!$this->isIntern && $this->isEmbeddable):?>

            <style>
            #preload {
            background-color:#fff;
            padding:100px 15px;
            }
            .embed-container {
                margin-bottom: 50px;
            }
            .frame-content {
            width: 100%;
            }
            .frame-content iframe {

            background-color:#fff;
            /*width:100%;*/
            /*height:1800px;*/
            /*overflow:auto;*/
            }
            iframe {
            width: 1px;
            min-width: 100%;
            }
            .spinner {
            margin: 0 auto;
            width: 70px;
            text-align: center;
            }

            .spinner > div {
            width: 18px;
            height: 18px;
            background-color: #333;

            border-radius: 100%;
            display: inline-block;
            -webkit-animation: sk-bouncedelay 1.4s infinite ease-in-out both;
            animation: sk-bouncedelay 1.4s infinite ease-in-out both;
            }

            .spinner .bounce1 {
            -webkit-animation-delay: -0.32s;
            animation-delay: -0.32s;
            }

            .spinner .bounce2 {
            -webkit-animation-delay: -0.16s;
            animation-delay: -0.16s;
            }

            @-webkit-keyframes sk-bouncedelay {
            0%, 80%, 100% { -webkit-transform: scale(0) }
            40% { -webkit-transform: scale(1.0) }
            }

            @keyframes sk-bouncedelay {
            0%, 80%, 100% {
            -webkit-transform: scale(0);
            transform: scale(0);
            } 40% {
            -webkit-transform: scale(1.0);
            transform: scale(1.0);
            }
            }

            </style>


            <?php $this->configHeadScript()->appendScript('
            $(function(){
                var d=15,
                    a=$("#preload").removeClass("hidden"),
                    e=$(".frame-content iframe").addClass("hidden"),
                    c=$(window),
                    g=$("header"),
                    f=$("footer"),
                    b=$(".box.intro"),
                    g=$(".apply-button-group").not(".first").addClass("hidden");
    
                setTimeout(function(){
                    a.addClass("hidden");
                    e.removeClass("hidden");
                    g.removeClass("hidden");
                },3000);
    
                c.resize(function(){
                    e.height(c.height()-g.outerHeight(true)-f.outerHeight(true)-b.outerHeight(true)-d)
                }).resize()
            });
            '); ?>

            <div class="panel panel-default panel__job-detail">
                <!-- New Badge -->
                <?php if (!$hasBanner && $newerThanDay): ?>
                    <div class="corner"><span>NEU</span></div>
                <?php endif; ?>
                <!-- End New Badge -->

                 <!-- Bannerbild -->
                <?php if ($hasBanner): ?>
                    <div class="banner" style="background-image: url(<?= $imageServerUrl ?>)"></div>
                <?php endif; ?>
                 <!-- End Bannerbild -->

                <div class="panel-body">
                    <!-- company logo and job title-->
                    <?php if ($hasBanner): ?>
                        <div class="teaser__job-detail">
                            <!-- New Badge -->
                            <?php if ($newerThanDay): ?>
                                <div class="corner"><span>NEU</span></div>
                            <?php endif; ?>
                            <!-- End New Badge -->
                            <div itemprop="logo">
                                <div class="wrapper__logo">
                                    <img src="<?= $logoUrl ?>" alt="<?= $orgName?>">
                                </div>
                            </div>
                            <h1><?=$job->getTitle()?></h1>
                        </div>
                    <?php endif; ?>
                    <?php if (!$hasBanner): ?>
                        <h1 class="no-banner"><?=$job->getTitle()?></h1>
                    <?php endif; ?>
                    <!-- end company logo and job title-->

                    <!-- expired info box -->
                    <?= $this->partial('jobs/partials/expired-info.phtml', ['isExpired' => $isExpired]); ?>
                    <!-- end expired info box -->

                    <div class="job-short-info <?php if(!$hasBanner) echo 'no-banner' ?>">
                        <ul>
                            <li class="location">
                                <!-- location -->
                                <?php
                                $location = $job->getLocations()->current();
                                if ($location == '') {
                                    echo $this->translate('Swiss');
                                }
                                elseif ($location) {
                                    echo $location->getCity() ? $location->getCity() : preg_replace('~\(.*?\)$~', '', (string) $job->getLocation());
                                }
                                else {
                                    echo preg_replace('~\(.*?\)$~', '', (string) $job->getLocation());
                                }
                                ?>
                                <!-- end location -->
                            </li>
                            <li class="company">
                                <!-- company name -->
                                <?php if ($org && !$orgIsDisabled && !$preview): ?>
                                    <a title="Jobs <?= ($org->getOrganizationName()) ? $org->getOrganizationName()->getName() : $orgName ?>" href="<?= $this->orgProfileUrl($org)?>?clear=1"><?= $orgName ?></a>
                                <?php elseif (!$preview && $job->getTemplateValues()->get('companyWebsite')) : ?>
                                    <a title="Website <?= ($org && $org->getOrganizationName()) ? $org->getOrganizationName()->getName() : $orgName ?>" href="<?= $job->getTemplateValues()->get('companyWebsite') ?>"><?= $orgName ?></a>
                                <?php else: ?>
                                    <strong><?= ($org && $org->getOrganizationName()) ? $org->getOrganizationName()->getName() : $orgName ?></strong>
                                <?php endif ?>
                                <!-- end company name -->
                            </li>
                            <li class="type">
                                <!-- type of contract -->
                                <?php
                                $typeOfContract = $job->getClassifications()->getEmploymentTypes()->__toString() ?:'Vollzeit' ?>
                                <span class="yk-contract yk-<?=$typeOfContract?>"><?=$typeOfContract; ?></span>
                                <!-- end type of contract -->
                            </li>
                            <li class="date">
                                <!-- published date -->
                                <span><?= $this->publishDateFormatter($job) ?></span>
                                <!-- end published date -->
                            </li>
                            <?php if ($industries->getItems()->count() && !$this->isCrawlerJob($org)): ?>
                                <li class="industries">
                                    <?= $industries->__toString(); ?>
                                </li>
                            <?php endif; ?>
                        </ul>

                        <div class="wrapper__right">
                            <?php if (!$hasBanner): ?>
                                <div class="wrapper__logo">
                                    <img src="<?= $logoUrl ?>" alt="<?= $orgName?>">
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>

                    <hr class="job-details-devider"/>

                    <div class="first apply-button-group">
                        <!-- share button -->
                        <div id="shareMailTop" class="text-center hidden-xs"></div>
                        <div id="shareWhatsappTop" class="text-center visible-xs"></div>
                        <!-- end share button -->

                        <!-- apply button -->
                        <?= $this->partial('jobs/partials/apply-button.phtml', [
                            'preview' => $preview,
                            'isExpired' => $isExpired,
                            'job' => $this->job,
                        ]); ?>
                        <!-- end apply button -->

                        <!-- favorite button -->
                        <?= $this->partial('jobs/partials/favorite-button.phtml', [
                            'jobId' => $job->getId(),
                            'isExpired' => $isExpired,
                            'buttonCss' => 'favorite-button',
                        ]); ?>
                        <!-- end favorite button -->
                    </div>

                    <div class="embed-container">
                        <div class="frame-content">
                            <div id="preload" class="loading hidden text-center">
                                <div class="spinner">
                                    <div class="bounce1"></div>
                                    <div class="bounce2"></div>
                                    <div class="bounce3"></div>
                                </div>
                                <p>Das Inserat wird geladen, bitte haben Sie einem Moment Geduld</p>
                            </div>
                            <?php if(strpos($link, '.pdf') !== false): ?>
                                <iframe style="height:122rem" id="iframePdf" src="<?=$link?>"></iframe>
                            <?php else: ?>
                                <iframe style="height:2500px" id="iframe4" src="<?=$link?>"></iframe>
                            <?php endif; ?>
                        </div>
                    </div>

                    <!-- company description of single job -->
                    <?php if ($this->job->getTemplateValues()->get('companyDescription')): ?>
                        <div class="position">
                            <?= $this->job->getTemplateValues()->get('companyDescription'); ?>
                        </div>
                    <?php endif;?>
                    <!-- end company description of single job -->

                    <div class="apply-button-group">
                        <!-- share button -->
                        <div id="shareMailBottom" class="text-center hidden-xs"></div>
                        <div id="shareWhatsappBottom" class="text-center visible-xs"></div>
                        <!-- end share button -->

                        <!-- apply button -->
                        <?= $this->partial('jobs/partials/apply-button.phtml', [
                            'preview' => $preview,
                            'isExpired' => $isExpired,
                            'job' => $this->job,
                        ]); ?>
                        <!-- end apply button -->

                        <!-- favorite button -->
                        <?= $this->partial('jobs/partials/favorite-button.phtml', [
                            'jobId' => $job->getId(),
                            'isExpired' => $isExpired,
                            'buttonCss' => 'favorite-button',
                        ]); ?>
                        <!-- end favorite button -->
                    </div>

                  

                    <!-- share buttons -->
                    <div class="text-center">Diesen Job teilen: </div>
                    <div id="share" class="text-center round-shares"></div>
                    <div class="clearfix"></div>
                    <!-- end share buttons -->




                   <?php if (!$preview): ?>
                        <?php echo $this->partial('jobs/partials/similar-company-jobs.phtml', ['job' => $this->job]); ?>
                    <?php endif; ?>


                  
                    <?php if (!$preview): ?>
                        <?php echo $this->partial('jobs/partials/similar-jobs.phtml', ['job' => $this->job]); ?>
                    <?php endif; ?>
                 


                  
                   
                    
                    
                    

                
                
                
                
                </div>
            </div>

            <!-- socials -->
            <?php $this->configHeadScript()->appendScript('
                $("#share").jsSocials({
                    showLabel: false,
                    showCount: true,
                    shares: ["email", "twitter", "facebook", "whatsapp"]
                });
                $("#shareMailTop").jsSocials({
                    showCount: true,
                    shares: ["email"]
                });
                $("#shareMailBottom").jsSocials({
                    showCount: true,
                    shares: ["email"]
                });
                $("#shareWhatsappTop").jsSocials({
                    showLabel: false,
                    showCount: true,
                    shares: ["whatsapp"]
                });
                $("#shareWhatsappBottom").jsSocials({
                    showLabel: false,
                    showCount: true,
                    shares: ["whatsapp"]
                });
            '); ?>
            <!-- end socials -->

            <!-- iframe resizer -->
            <?php $this->configHeadScript()->appendScript('iFrameResize({ log: false }, "#iframe4")'); ?>
            <!-- end iframe resizer -->

        <?php endif; ?>

      
      
      
      
      
      

    </div>
</div>

<!-- apply modal -->
<div class="modal fade" id="job-apply-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
    <div class="modal-dialog" style="width: 90%; max-width:1200px; height: 90%" role="document">
        <div class="modal-content" style="height: 100%">
            <div class="modal-body" style="height: calc(100% - 65px)"></div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Schliessen</button>
            </div>
        </div>
    </div>
</div>
<!-- end apply modal -->
