<?php
/**
 * YAWIK - Anzeige für Vorschau & Ausgabe
 *
 * @filesource
 * @license MIT
 * @copyright  2013 - 2018 Cross Solution <http://cross-solution.de>
 */

$this->headScript()->appendFile($this->basePath('/dist/js/iframeResizer.contentWindow.min.js'))
    ->appendFile($this->basePath($this->asset('modules/Gastro24/jssocials-1.4.0/dist/jssocials.js')));

// check for preview
$routeParams = $this->params()->fromRoute();
$preview = false;
if (isset($routeParams['isPreview']) && $routeParams['isPreview']) {
    $preview = true;
}

/** @var \Gastro24\Entity\Template $template */
$template = $this->job->getAttachedEntity('gastro24-template');
$basePathHelper = $this->plugin('basePath');
$replaceImage = function($str) use ($template, $basePathHelper)
{
    $image = $template ? $template->getImage() : null;
    if ($image) {
        $imageUri = $basePathHelper($image->getUri());
        $imageHtml = '<img src="' . $imageUri . '">';
    } else {
        $imageHtml = '';
    }

    return str_replace('#image#', $imageHtml, $str);
};

$isExpired = ($this->job->getStatus()) ? $this->job->getStatus()->getName() == \Jobs\Entity\StatusInterface::EXPIRED : false;
$defaultLogoUrl = $this->basePath('modules/Gastro24/images/no-company-logo.png');

// organisation values
$organizationImageCache = $this->services('Organizations\ImageFileCache\Manager');
$org = $this->job->getOrganization();
$orgIsDisabled = false;
$orgName = $this->jobOrganizationName($this->job);
if ($org && (Organizations\Entity\Organization::PROFILE_DISABLED == $org->getProfileSetting() || is_null($org->getProfileSetting())) ) {
    $orgIsDisabled = true;
}
// get org logo as default
if($org && $org->getImages()->notEmpty('images')) {
    $defaultLogoUrl = $this->basePath($organizationImageCache->getUri($org->getImages()->get('thumbnail')));
}

// check for banner
$hasBanner = false;
// default banner
$imageServerUrl = $this->basePath('modules/Gastro24/images/bg_placeholder_gray.svg');
// banner from org
if ($org) {
    $organizationAdditionalRepo = $this->services('repositories')->get(\Gastro24\Entity\OrganizationAdditional::class);
    /** @var \Gastro24\Entity\OrganizationAdditional $organizationAdditional */
    $organizationAdditional = $organizationAdditionalRepo->findOneByOrganizationId($org->getId());
    if ($organizationAdditional && $organizationAdditional->getBanner()) {
        $imageServerUrl = $this->basePath($organizationAdditional->getBanner()->getUri());
        $hasBanner = true;
    }
}
// banner from job
$jobBanner = $template && ($image = $template->getImage());
if ($jobBanner) {
    $serverUrl = new \Laminas\View\Helper\ServerUrl();
    $imageServerUrl = $serverUrl($this->basePath($image->getUri()));
    $hasBanner = true;
}
if ($template && $template->getHideBanner()) {
    $hasBanner = false;
}

// check for newer than 24 hours
$newerThanDay = false;
// get date difference
$today = new DateTime();
$jobDate = $job->getDatePublishStart() ?? $job->getDateCreated();
// workaround - mongodb entity has difference in time
$time = strtotime($jobDate->format('y-m-d\TH:i:s.u'). '+02:00');
$jobDate->setTimestamp($time);
$dayDiff = $today->diff($jobDate);
if ($dayDiff->days < 1) {
    $newerThanDay = true;
}

$industries = $job->getClassifications()->getIndustries();
?>
<?php if ($preview): ?>
    <?php $this->headStyle()->captureStart() ?>
        .container {
            min-width: 100%;
            padding: 0;
        }
    <?php $this->headStyle()->captureEnd() ?>
<?php endif; ?>

<div class="panel panel-default panel__job-detail">

      <!-- New Badge -->
      <?php if (!$hasBanner && $newerThanDay): ?>
          <div class="corner"><span>NEU</span></div>
      <?php endif; ?>
      <!-- End New Badge -->

    <!-- Bannerbild -->
    <?php if ($hasBanner): ?>
        <div class="banner" style="background-image: url(<?= $imageServerUrl ?>)"></div>
    <?php endif; ?>
    <!-- End Bannerbild -->

    <div class="panel-body">
        <!-- company logo and job title-->
        <?php if ($hasBanner): ?>
            <div class="teaser__job-detail">
                <!-- New Badge -->
                <?php if ($newerThanDay): ?>
                    <div class="corner"><span>NEU</span></div>
                <?php endif; ?>
                <!-- End New Badge -->
                <div itemprop="logo">
                    <div class="wrapper__logo">
                        <?php
                            $wrapperLogoUrl = $defaultLogoUrl;
                            if ($template && ($logo = $template->getLogo())) {
                                $wrapperLogoUrl = $this->basePath($logo->getUri());
                            }
                            else {
                                $wrapperLogoUrl = $defaultLogoUrl;
                            }
                        ?>
                        <img src="<?= $wrapperLogoUrl ?>" alt="<?= $this->organizationName ?>">
                    </div>
                </div>
                <h1><?=$this->job->getTitle()?></h1>
            </div>
        <?php endif; ?>
        <?php if (!$hasBanner): ?>
            <h1 class="no-banner"><?=$this->job->getTitle()?></h1>
        <?php endif; ?>
        <!-- end company logo and job title-->

        <!-- expired info box -->
        <?= $this->partial('jobs/partials/expired-info.phtml', ['isExpired' => $isExpired]); ?>
        <!-- end expired info box -->
        
        
         <!-- similar jobs -->
        <?php if (!$preview && $isExpired): ?>  
            <?php echo $this->partial('jobs/partials/similar-jobs.phtml', ['job' => $this->job]); ?>
         <?php endif; ?>
        <!-- end similar jobs -->
        
        

        <div class="job-short-info <?php if(!$hasBanner) echo 'no-banner' ?>">
            <ul>
                <li class="location">
                    <!-- location -->
                    <?php
                    $location = $job->getLocations()->current();
                    if ($location == '') {
                        echo $this->translate('Swiss');
                    }
                    elseif ($location) {
                        echo $location->getCity() ? $location->getCity() : preg_replace('~\(.*?\)$~', '', (string) $job->getLocation());
                    }
                    else {
                        echo preg_replace('~\(.*?\)$~', '', (string) $job->getLocation());
                    }
                    ?>
                    <!-- end location -->
                </li>
                <li class="company">
                    <!-- company name -->
                    <?php if ($org && !$orgIsDisabled && !$preview): ?>
                        <a title="Jobs <?= $this->organizationName ?> " href="<?= $this->orgProfileUrl($org)?>?clear=1"><?= $orgName ?></a>
                    <?php elseif (!$preview && $job->getTemplateValues()->get('companyWebsite')) : ?>
                        <a title="Website <?= $this->organizationName ?>" href="<?= $job->getTemplateValues()->get('companyWebsite') ?>"><?= $orgName ?></a>
                    <?php else: ?>
                        <strong><?= (!empty($this->organizationName)) ? $this->organizationName : $orgName ?></strong>
                    <?php endif ?>
                    <!-- end company name -->
                </li>
                <li class="type">
                    <!-- type of contract -->
                    <?php
                    $typeOfContract = $job->getClassifications()->getEmploymentTypes()->__toString() ?:'Vollzeit' ?>
                    <span class="yk-contract yk-<?=$typeOfContract?>"><?=$typeOfContract; ?></span>
                    <!-- end type of contract -->
                </li>
                <li class="date">
                    <!-- published date -->
                    <span><?= $this->publishDateFormatter($job) ?></span>
                    <!-- end published date -->
                </li>
                <!-- HINT: some jobs has invalid industries, therefore check for empty string -->
                <?php if ($industries->getItems()->count() && !$this->isCrawlerJob($org) && $industries->__toString() != ""): ?>
                    <li class="industries">
                        <?= $industries->__toString(); ?>
                    </li>
                <?php endif; ?>
            </ul>
            <div class="wrapper__right">
                <?php if (!$hasBanner): ?>
                    <div class="wrapper__logo">
                        <img src="<?= $template && ($logo = $template->getLogo())
                            ? $this->basePath($logo->getUri())
                            : $defaultLogoUrl ?>" alt="<?= $this->organizationName?>">
                    </div>
                <?php endif; ?>
            </div>
        </div>

        <hr class="job-details-devider"/>

        <div class="first apply-button-group">
            <!-- share button -->
            <div id="shareMailTop" class="text-center hidden-xs"></div>
            <div id="shareWhatsappTop" class="text-center visible-xs"></div>
            <!-- end share button -->

            <!-- apply button -->
            <?= $this->partial('jobs/partials/apply-button.phtml', [
                'preview' => $preview,
                'isExpired' => $isExpired,
                'job' => $this->job,
            ]); ?>
            <!-- end apply button -->

            <!-- favorite button -->
            <?= $this->partial('jobs/partials/favorite-button.phtml', [
                'jobId' => $job->getId(),
                'isExpired' => $isExpired,
                'buttonCss' => 'favorite-button',
            ]); ?>
            <!-- end favorite button -->
        </div>

        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <!-- job content -->
                <p id="job_content">
                <?php if ($this->html): ?>
                    <div class="position">
                        <?=$this->html?>
                    </div>
                <?php else: ?>
                    <!-- position / job description -->
                    <div class="position">
                        <?= $replaceImage($this->job->getTemplateValues()->get('position'));?>
                    </div>
                <?php endif; ?>
                <!-- end job content -->

                <!-- company description of single job -->
                <?php if ($this->job->getTemplateValues()->get('companyDescription')): ?>
                    <div class="position">
                       <p><?= $this->job->getTemplateValues()->get('companyDescription'); ?></p> 
                    </div>
                <?php endif;?>
                <!-- end company description of single job -->
            </div>
        </div>

        <div class="apply-button-group">
            <!-- share button -->
            <div id="shareMailBottom" class="text-center hidden-xs"></div>
            <div id="shareWhatsappBottom" class="text-center visible-xs"></div>
            <!-- end share button -->

            <!-- apply button -->
            <?= $this->partial('jobs/partials/apply-button.phtml', [
                'preview' => $preview,
                'isExpired' => $isExpired,
                'job' => $this->job,
            ]); ?>
            <!-- end apply button -->

            <!-- favorite button -->
            <?= $this->partial('jobs/partials/favorite-button.phtml', [
                'jobId' => $job->getId(),
                'isExpired' => $isExpired,
                'buttonCss' => 'favorite-button',
            ]); ?>
            <!-- end favorite button -->
        </div>

        <!-- share buttons -->
        <div class="text-center">Diesen Job teilen: </div>
        <div id="share" class="text-center round-shares"></div>
        <div class="clearfix"></div>
        <!-- end share buttons -->

        <!-- similar jobs -->
        <?php if (!$preview && !$isExpired): ?>  
            <?php echo $this->partial('jobs/partials/similar-jobs.phtml', ['job' => $this->job]); ?>
         <?php endif; ?>
        <!-- end similar jobs -->

        <!-- similar company jobs -->
        <?php if (!$preview && !$isExpired): ?>
            <?php echo $this->partial('jobs/partials/similar-company-jobs.phtml', ['job' => $this->job]); ?>
        <?php endif; ?>
        <!-- end similar company jobs -->

      

   </div>
</div>

<!-- socials -->
<?php $this->configHeadScript()->appendScript('
    $("#share").jsSocials({
        showLabel: false,
        showCount: true,
        shares: ["email", "twitter", "facebook", "whatsapp"]
    });
    $("#shareMailTop").jsSocials({
        showCount: true,
        shares: ["email"]
    });
    $("#shareMailBottom").jsSocials({
        showCount: true,
        shares: ["email"]
    });
    $("#shareWhatsappTop").jsSocials({
        showLabel: false,
        showCount: true,
        shares: ["whatsapp"]
    });
    $("#shareWhatsappBottom").jsSocials({
        showLabel: false,
        showCount: true,
        shares: ["whatsapp"]
    });
'); ?>
<!-- end socials -->
