<?php
/**no-
* YAWIK - Anzeige für Preview & Ausgabe Einzelinserat / Job-Abo
*
* @filesource
* @license MIT
* @copyright  2013 - 2018 Cross Solution <http://cross-solution.de>
*/
// check for preview
$routeParams = $this->params()->fromRoute();
$preview = false;
if (isset($routeParams['isPreview']) && $routeParams['isPreview']) {
$preview = true;
}
/** @var \Gastro24\Entity\Template $template */
$template = $this->job->getAttachedEntity('gastro24-template');
$basePathHelper = $this->plugin('basePath');
$replaceImage = function($str) use ($template, $basePathHelper)
{
$image = $template ? $template->getImage() : null;
if ($image) {
$imageUri = $basePathHelper($image->getUri());
$imageHtml = '<img data-src="' . $imageUri . '">';
} else {
$imageHtml = '';
}
return str_replace('#image#', $imageHtml, $str);
};
$isExpired = ($this->job->getStatus()) ? $this->job->getStatus()->getName() == \Jobs\Entity\StatusInterface::EXPIRED : false;
$defaultLogoUrl = $this->basePath('modules/Gastro24/images/no-company-logo.png');
// organisation values
$organizationImageCache = $this->services('Organizations\ImageFileCache\Manager');
$org = $this->job->getOrganization();
$orgIsDisabled = false;
$orgName = $this->jobOrganizationName($this->job);
if ($org && (Organizations\Entity\Organization::PROFILE_DISABLED == $org->getProfileSetting() || is_null($org->getProfileSetting())) ) {
$orgIsDisabled = true;
}
// get org logo as default
if($org && $org->getImages()->notEmpty('images')) {
$defaultLogoUrl = $this->basePath($organizationImageCache->getUri($org->getImages()->get('thumbnail')));
}
// check for banner
$hasBanner = false;
// default banner
$imageServerUrl = $this->basePath('modules/Gastro24/images/bg_placeholder_gray.svg');
// banner from org
if ($org) {
$organizationAdditionalRepo = $this->services('repositories')->get(\Gastro24\Entity\OrganizationAdditional::class);
/** @var \Gastro24\Entity\OrganizationAdditional $organizationAdditional */
$organizationAdditional = $organizationAdditionalRepo->findOneByOrganizationId($org->getId());
if ($organizationAdditional && $organizationAdditional->getBanner()) {
$imageServerUrl = $this->basePath($organizationAdditional->getBanner()->getUri());
$hasBanner = true;
}
}
// banner from job
$jobBanner = $template && ($image = $template->getImage());
if ($jobBanner) {
$serverUrl = new \Laminas\View\Helper\ServerUrl();
/*$imageServerUrl = $serverUrl($this->basePath($image->getUri()));*/
$imageServerUrl = $this->basePath($image->getUri());
$hasBanner = true;
}
if ($template && $template->getHideBanner()) {
$hasBanner = false;
}
// check for newer than 24 hours
$newerThanDay = false;
// get date difference
$today = new DateTime();
$jobDate = $this->job->getDatePublishStart() ?? $this->job->getDateCreated();
// workaround - mongodb entity has difference in time
$time = strtotime($jobDate->format('y-m-d\TH:i:s.u'). '+02:00');
$jobDate->setTimestamp($time);
$dayDiff = $today->diff($jobDate);
if ($dayDiff->days < 1) {
$newerThanDay = true;
}
$industries = $this->job->getClassifications()->getIndustries();
$qualifications = $this->job->getClassifications()->getProfessions();
?>
<div class="company-description-wrapper">
  <div class="row">
    <div class="col-md-9">
      <div class="stand-alone-card company-info-wrapper">
        <div class="info-card">
          <div class="company-profile-image">
       
              <?php
$wrapperLogoUrl = $defaultLogoUrl;
if ($template && ($logo = $template->getLogo())) {
$wrapperLogoUrl = $this->basePath($logo->getUri());
}
else {
$wrapperLogoUrl = $defaultLogoUrl;
}
?>

<?php if (!$logo): ?>
<style>
  .job-info-wrapper {
    width:100%
  }
</style>

<?php endif; ?>
              <?php if ($logo): ?>
              <span class="job-logo-wrapper">
              <img data-gmlazy="false" class="job-logo " alt="<?= $this->organizationName ?>" src="https://gastrojob24.gumlet.net<?= $wrapperLogoUrl ?>?mode=fit&width=140&height=140&quality=75" />

              </span>
              <?php elseif ($preview) : ?>
              <?php else: ?>
               
              <?php endif; ?>
            
            <div class="job-info-wrapper">
              <h2 class="job-titel">
                <span>
                  <?= (!empty($this->organizationName)) ? $this->organizationName : $orgName ?>
                </span>
                <?=$this->job->getTitle()?>
              </h2>
              <?= $this->partial('jobs/partials/expired-info.phtml', ['isExpired' => $isExpired]); ?>
              <?php if ($newerThanDay): ?>
              <span class="apply-info-new">
                <i class="fa fa-clock-o">
                </i> Gehören Sie zu den ersten 3 Bewerbern.
              </span>
              <?php endif; ?>
              <ul class="details-list-horizontal">
                <li>
                  <i class="fa fa-angle-right">
                  </i>
                  <div class="details-list-content">
                    <span class="title">Veröffentlichung
                    </span>
                    <span class="value">
                      <?= $this->publishDateFormatter($this->job) ?>
                    </span>
                  </div>
                </li>
                <?php if ($industries->getItems()->count() && !$this->isCrawlerJob($org) && $industries->__toString() != ""): ?>
                <li>
                  <i class="fa fa-angle-right">
                  </i>
                  <div class="details-list-content">
                    <span class="title">Branche
                    </span>
                    <span class="value">
                      <?= $industries->__toString(); ?>
                    </span>
                  </div>
                </li>
                <?php else: ?>
                <li>
                  <i class="fa fa-angle-right">
                  </i>
                  <div class="details-list-content">
                    <span class="title">Branche
                    </span>
                    <span class="value">keine Angabe
                    </span>
                  </div>
                </li>
                <?php endif; ?>
                <?php if ($qualifications->getItems()->count() && !$this->isCrawlerJob($org) && $qualifications->__toString() != ""): ?>
                <li>
                  <i class="fa fa-angle-right">
                  </i>
                  <div class="details-list-content">
                    <span class="title">Erforderliche Qualifikation
                    </span>
                    <span class="value">
                      <?= $qualifications->__toString(); ?>
                    </span>
                  </div>
                </li>
                <?php endif; ?>
                <?php $typeOfContract = $this->job->getClassifications()->getEmploymentTypes()->__toString() ?:'Vollzeit' ?>
                <li>
                  <i class="fa fa-angle-right">
                  </i>
                  <div class="details-list-content">
                    <span class="title">Beschäftigungsart
                    </span>
                    <span class="value">
                      <?=$typeOfContract; ?>
                    </span>
                  </div>
                </li>
                </li>
              <li>
                <i class="fa fa-angle-right">
                </i>
                <div class="details-list-content">
                  <span class="title">Arbeitsort
                  </span>
                  <span class="value">
                    <?php
$location = $this->job->getLocations()->current();
if ($location == '') {
echo $this->translate('Swiss');
}
elseif ($location) {
echo $location->getCity() ? $location->getCity() : preg_replace('~\(.*?\)$~', '', (string) $this->job->getLocation());
}
else {
echo preg_replace('~\(.*?\)$~', '', (string) $this->job->getLocation());
}
?>
                  </span>
                </div>
              </li>
                  <?php if ($this->job->getAtsMode()->getMode() === 'none') : ?>

                  <li>
                      <i class="fa fa-angle-right">
                      </i>
                      <div class="details-list-content">
                  <span class="title">Bewerbung</span>
                          <span class="value">Keine Online-Bewerbung erwünscht</span>
                      </div>
                  </li>
                  <?php endif; ?>
              </ul>
          </div>
        </div>
        <div class="apply-wrapper button_container 
        <?php if ($this->job->getAtsMode()->getMode() === 'none') : ?>no-application<?php endif; ?> 
        <?php if (!$org): ?>no-company-profile<?php endif; ?>">
        
          <?php if (!$preview): ?>
          <?= $this->partial('jobs/partials/apply-button.phtml', [
'preview' => $preview,
'isExpired' => $isExpired,
'job' => $this->job,
]); 
?>
          <?php endif; ?>
          <?php if ($org && !$orgIsDisabled && !$preview): ?>
          <a class="btn btn-default" title="Firmenprofil <?= $this->organizationName ?>" href="<?= $this->orgProfileUrl($org)?>?clear=1">
            <span>Firmenprofil
            </span>
          </a>
          <?php endif; ?>
          <?php if (!$preview): ?>
          <?= $this->partial('jobs/partials/favorite-button.phtml', [
'jobId' => $this->job->getId(),
'isExpired' => $isExpired,
'buttonCss' => 'favorite-button',
]); 
?>
          <?php endif; ?>
        </div>
      </div>
    </div>
    <div class="stand-alone-card extra-shadow">
      <?php if ($hasBanner): ?>
      <img class="job-top-image" alt="<?=$this->job->getTitle()?>" data-src="https://gastrojob24.gumlet.net<?= $imageServerUrl ?>?mode=crop&amp;width=845&amp;quality=75" />
      <?php endif; ?>
      <div class="info-card info-card-job-body">
        <?php if ($this->html): ?>
        <div class="position">
          <?=$this->html?>
        </div>
        <?php else: ?>
        <div class="position">
          <?= $replaceImage($this->job->getTemplateValues()->get('position'));?>
        </div>
        <?php endif; ?>
        <?= $this->partial('jobs/partials/contact-sidebar-alternative', [
'job' =>  $this->job,
'orgName' => $orgName,
'preview' => $preview
]
); ?>
      </div>
      <div class="apply-box-footer">
        <?= $this->partial('jobs/partials/apply-button.phtml', [
'preview' => $preview,
'isExpired' => $isExpired,
'job' => $this->job,
]); 
?>
      </div>
        <?php
            $showCompanyJobsBox = false;
            if ($this->job->getTemplateValues()->get('companyDescription')) {
                $showCompanyJobsBox = true;
                $companyDescription = $this->job->getTemplateValues()->get('companyDescription');
            }
            if ($org && !$orgIsDisabled && $org->getDescription()) {
                $showCompanyJobsBox = true;
                $companyDescription = $org->getDescription();
            }
        ?>
    <?php if ($showCompanyJobsBox): ?>
      <div class="stand-alone-card company-info">
        <div class="info-card">
          <div class="container-fluid">
            <div class="row">
            
               <div class="col-md-3">
                  <?php
                    $wrapperLogoUrl = $defaultLogoUrl;
                    if ($template && ($logo = $template->getLogo())) {
                    $wrapperLogoUrl = $this->basePath($logo->getUri());
                    }
                    else {
                    $wrapperLogoUrl = $defaultLogoUrl;
                    }
?>
                  <?php if ($logo): ?>
                 
                     <span class="job-logo-wrapper">
                         <img data-gmlazy="false" class="job-logo " alt="<?= $this->organizationName ?>" data-src="https://gastrojob24.gumlet.net<?= $wrapperLogoUrl ?>?mode=fit&width=140&height=140&quality=75" />
                    </span>
                   
                  <?php elseif ($preview) : ?>
                  <?php else: ?>
                  <?php endif; ?>
         
                <div class="meta-adress">
                  <?php if ($org && !$orgIsDisabled && !$preview): ?>
                      <a class="fa fa-angle-right" title="Firmenprofil <?= $this->organizationName ?>"
                         href="<?= $this->orgProfileUrl($org)?>?clear=1">
                        <span>Firmenprofil</span>
                      </a>
                      <a class="fa fa-angle-right" href="<?= $this->orgProfileUrl($org)?>?clear=1" rel="nofollow"><span>Jobs: <?= $this->companyJobsCount($org->getId()); ?></span></a>
                  <?php elseif($this->job->getTemplateValues()->get('companyWebsite')): ?>
                      <a class="fa fa-angle-right" title="Firmenprofil <?= $this->organizationName ?>"
                         href="<?= $this->job->getTemplateValues()->get('companyWebsite')?>">
                        <span>Firmenprofil</span>
                      </a>
                  <?php endif; ?>
                </div>
              </div>
              <div class="col-md-9">
                <h2>
                  <?= (!empty($this->organizationName)) ? $this->organizationName : $orgName ?>
                </h2>
                <div class="more">
                  <?= nl2br($companyDescription); ?>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <?php endif; ?>
      <?php if (!$preview): ?>
      <?php echo $this->partial('jobs/partials/similar-company-jobs.phtml', ['job' => $this->job]); ?>
      <?php endif; ?>
      <?php if (!$preview && !$isExpired): ?>
      <?php echo $this->partial('jobs/partials/similar-jobs.phtml', ['job' => $this->job]); ?>
      <?php endif; ?>

<?php
/** @var \Gastro24\Options\Landingpages $landingpagesOptions */
$landingpagesOptions = $this->services(\Gastro24\Options\Landingpages::class);
$landingPageCategories = $this->job->getTemplateValues()->get('categories');
$contentProperty = 3;
$locationString = ' ' . \Gastro24\View\Helper\Jobs\JobLocationHelper::getLocationStringForBreadcrumb($this->job);
?>

       <?php if ($landingPageCategories && !$preview) : ?>
            
            <h2 style="font-weight:700;margin-bottom:15px;">Weitere Stellenangebote</h2>

               <div class="stand-alone-card">
                  <div class="info-card">

                        <!-- build parent breadcrumbs -->
                        <?php
                            foreach ($landingPageCategories as $category) {
                                $catText = $landingpagesOptions->getQueryParameters($category)['q'];

                                echo
                             '<a class="btn facet-active" title="' . $catText . ' Jobs" href="' . $this->url('lang/landingPage', ['q' => $category, 'format' => 'html' ], true) . '">' .$catText . ' Jobs</a>';

                                $contentProperty++;
                            }
                        ?>

                        </div>
                      </div>
  

      <?php endif; ?>






      <!-- end col-md-9 -->
    </div>
    <!-- sidebar contact and map -->
    <?= $this->partial('jobs/partials/contact-sidebar', [
'job' =>  $this->job,
'orgName' => $orgName,
'preview' => $preview
]
); ?>
    <!-- end col-md-3 -->
  </div>
  <!-- end company-description-wrapper -->
</div>
