<?php
/**
 * YAWIK - Anzeige für Vorschau & Ausgabe
 *
 * @filesource
 * @license MIT
 * @copyright  2013 - 2018 Cross Solution <http://cross-solution.de>
 */


// check for preview
$routeParams = $this->params()->fromRoute();
$preview = false;
if (isset($routeParams['isPreview']) && $routeParams['isPreview']) {
    $preview = true;
}
$isExpired = ($this->job->getStatus()) ? $this->job->getStatus()->getName() == \Jobs\Entity\StatusInterface::EXPIRED : false;
$template = $this->job->getAttachedEntity('gastro24-template');
$basePathHelper = $this->plugin('basePath');
$replaceImage = function($str) use ($template, $basePathHelper)
{
    $image = $template ? $template->getImage() : null;
    if ($image) {
        $imageUri = $basePathHelper($image->getUri());
        $imageHtml = '<img src="' . $imageUri . '">';
    } else {
        $imageHtml = '';
    }

    return str_replace('#image#', $imageHtml, $str);
};

$defaultLogoUrl = $this->basePath('modules/Gastro24/images/no-company-logo.png');

// organisation values
$organizationImageCache = $this->services('Organizations\ImageFileCache\Manager');
$org = $this->job->getOrganization();
$orgIsDisabled = false;
$orgName = $this->jobOrganizationName($this->job);
if ($org && (Organizations\Entity\Organization::PROFILE_DISABLED == $org->getProfileSetting() || is_null($org->getProfileSetting()) )) {
    $orgIsDisabled = true;
}

// get org logo as default
if($org && $org->getImages()->notEmpty('images')) {
    $defaultLogoUrl = $this->basePath($organizationImageCache->getUri($org->getImages()->get('thumbnail')));
}

// check for banner
$hasBanner = false;
// default banner
$imageServerUrl = $this->basePath('modules/Gastro24/images/bg_placeholder_gray.svg');
// banner from org
/*if ($org) {
    $organizationAdditionalRepo = $this->services('repositories')->get(\Gastro24\Entity\OrganizationAdditional::class);
    $organizationAdditional = $organizationAdditionalRepo->findOneByOrganizationId($org->getId());
    if ($organizationAdditional && $organizationAdditional->getBanner()) {
        $imageServerUrl = $this->basePath($organizationAdditional->getBanner()->getUri());
        $hasBanner = true;
    }
}*/
// banner from job
$jobBanner = $template && ($image = $template->getImage());
if ($jobBanner) {
    $serverUrl = new \Laminas\View\Helper\ServerUrl();
    $imageServerUrl = $serverUrl($this->basePath($image->getUri()));
    $hasBanner = true;
}

// check for newer than 24 hours
$newerThanDay = false;
// get date difference
$today = new DateTime();
$jobDate = $this->job->getDatePublishStart() ?? $this->job->getDateCreated();
// workaround - mongodb entity has difference in time
$time = strtotime($jobDate->format('y-m-d\TH:i:s.u'). '+02:00');
$jobDate->setTimestamp($time);
$dayDiff = $today->diff($jobDate);
if ($dayDiff->days < 1) {
    $newerThanDay = true;
}

$industries = $this->job->getClassifications()->getIndustries();

?>

<div class="company-description-wrapper">
  <div class="row">
    <div class="col-md-9">
      <div class="stand-alone-card company-info-wrapper">
        <div class="info-card">
          <div class="company-profile-image">
                  <?php
                            $wrapperLogoUrl = $defaultLogoUrl;
                            if ($template && ($logo = $template->getLogo())) {
                                $wrapperLogoUrl = $this->basePath($logo->getUri());
                            }
                            else {
                                $wrapperLogoUrl = $defaultLogoUrl;
                            }
                        ?>

            <?php if ($logo): ?>
              <span class="job-logo-wrapper">
                  <img 
                  data-gmlazy="false" 
                  class="job-logo" 
                  alt="<?= $this->organizationName ?>" 
                  data-src="https://gastrojob24.gumlet.net<?= $wrapperLogoUrl ?>?mode=fit&width=115&height=115&quality=75);" />
              </span>
            <?php endif; ?>
<div class="job-info-wrapper">
              <h2 class="job-titel">
                <span>
                  <?= (!empty($this->organizationName)) ? $this->organizationName : $orgName ?>
                </span>
               <?=ucfirst($this->job->getTitle())?>
              </h2>
              <?= $this->partial('jobs/partials/expired-info.phtml', ['isExpired' => $isExpired]); ?> 
              <?php if ($newerThanDay): ?>
              <span class="apply-info-new">
                <i class="fa fa-clock-o">
                </i> Gehören Sie zu den ersten 3 Bewerbern.
              </span>
              <?php endif; ?>

    <ul class="details-list-horizontal">


  <li ><i class="fa fa-angle-right"></i>
   <div class="details-list-content"><span class="title">Datum der Veröffentlichung</span><span class="value"><?= $this->publishDateFormatter($this->job) ?></span></div>
</li>
  <li ><i class="fa fa-angle-right"></i>
   <div class="details-list-content"><span class="title">Beschäftigungsart</span><span class="value"><?=$typeOfContract; ?></span></div>
</li>

</li>
  <li ><i class="fa fa-angle-right"></i>
   <div class="details-list-content"><span class="title">Arbeitsort</span><span class="value"><?php
                    $location = $this->job->getLocations()->current();
                    if ($location == '') {
                        echo $this->translate('Swiss');
                    }
                    elseif ($location) {
                        echo $location->getCity() ? $location->getCity() : preg_replace('~\(.*?\)$~', '', (string) $this->job->getLocation());
                    }
                    else {
                        echo preg_replace('~\(.*?\)$~', '', (string) $this->job->getLocation());
                    }
                    ?></span></div>
</li>

</ul>
 </div>
</div>















       
           
