<?php
/**
 * YAWIK - Anzeige für Vorschau & Ausgabe
 *
 * @filesource
 * @license MIT
 * @copyright  2013 - 2018 Cross Solution <http://cross-solution.de>
 */


// check for preview
$routeParams = $this->params()->fromRoute();
$preview = false;
if (isset($routeParams['isPreview']) && $routeParams['isPreview']) {
    $preview = true;
}
$isExpired = ($this->job->getStatus()) ? $this->job->getStatus()->getName() == \Jobs\Entity\StatusInterface::EXPIRED : false;
$template = $this->job->getAttachedEntity('gastro24-template');
$basePathHelper = $this->plugin('basePath');
$replaceImage = function($str) use ($template, $basePathHelper)
{
    $image = $template ? $template->getImage() : null;
    if ($image) {
        $imageUri = $basePathHelper($image->getUri());
        $imageHtml = '<img src="' . $imageUri . '">';
    } else {
        $imageHtml = '';
    }

    return str_replace('#image#', $imageHtml, $str);
};

$defaultLogoUrl = $this->basePath('modules/Gastro24/images/no-company-logo.png');

// organisation values
$organizationImageCache = $this->services('Organizations\ImageFileCache\Manager');
$org = $this->job->getOrganization();
$orgIsDisabled = false;
$orgName = $this->jobOrganizationName($this->job);
if ($org && (Organizations\Entity\Organization::PROFILE_DISABLED == $org->getProfileSetting() || is_null($org->getProfileSetting()) )) {
    $orgIsDisabled = true;
}

// get org logo as default
if($org && $org->getImages()->notEmpty('images')) {
    $defaultLogoUrl = $this->basePath($organizationImageCache->getUri($org->getImages()->get('thumbnail')));
}

// check for banner
$hasBanner = false;
// default banner
$imageServerUrl = $this->basePath('modules/Gastro24/images/bg_placeholder_gray.svg');
// banner from org
/*if ($org) {
    $organizationAdditionalRepo = $this->services('repositories')->get(\Gastro24\Entity\OrganizationAdditional::class);
    $organizationAdditional = $organizationAdditionalRepo->findOneByOrganizationId($org->getId());
    if ($organizationAdditional && $organizationAdditional->getBanner()) {
        $imageServerUrl = $this->basePath($organizationAdditional->getBanner()->getUri());
        $hasBanner = true;
    }
}*/
// banner from job
$jobBanner = $template && ($image = $template->getImage());
if ($jobBanner) {
    $serverUrl = new \Laminas\View\Helper\ServerUrl();
    $imageServerUrl = $serverUrl($this->basePath($image->getUri()));
    $hasBanner = true;
}

// check for newer than 24 hours
$newerThanDay = false;
// get date difference
$today = new DateTime();
$jobDate = $this->job->getDatePublishStart() ?? $this->job->getDateCreated();
// workaround - mongodb entity has difference in time
$time = strtotime($jobDate->format('y-m-d\TH:i:s.u'). '+02:00');
$jobDate->setTimestamp($time);
$dayDiff = $today->diff($jobDate);
if ($dayDiff->days < 1) {
    $newerThanDay = true;
}

$industries = $this->job->getClassifications()->getIndustries();

?>
<?php if ($preview): ?>
    <?php $this->headStyle()->captureStart() ?>
        .container {
            min-width: 100%;
            padding: 0;
        }
    <?php $this->headStyle()->captureEnd() ?>
<?php endif; ?>

<?php if ($hasBanner): ?>
  <style>
	.company-bg-image:before {
	    background-image: url(<?= $imageServerUrl ?>);
     }
  </style>
<?php endif; ?>

<div class="<?php if(!$hasBanner) echo 'no-banner' ?>" style="position:relative;">
   <div style="height:482.5px" class="company-bg-image"></div>
     <div class="<?php if(!$hasBanner) echo 'no-banner' ?> company-profile-wrapper">
        <div class="jgArSS" style="background-image: url(<?= $imageServerUrl ?>);"></div>
          <div class="company-profile-image">
              
                  <?php
                            $wrapperLogoUrl = $defaultLogoUrl;
                            if ($template && ($logo = $template->getLogo())) {
                                $wrapperLogoUrl = $this->basePath($logo->getUri());
                            }
                            else {
                                $wrapperLogoUrl = $defaultLogoUrl;
                            }
                        ?>
                   

             <span class="job-logo-wrapper">
                 <img class="job-logo" alt="<?= $this->organizationName ?>" src="<?= $wrapperLogoUrl ?>" />
              </span>
        
           
           
              
           <div class="job-info-wrapper">
                <h1><?=ucfirst($this->job->getTitle())?></h1>
                
                <?php $typeOfContract = $this->job->getClassifications()->getEmploymentTypes()->__toString() ?:'Vollzeit' ?>
                    
                <p><?=$typeOfContract; ?> bei <?php if ($org && !$orgIsDisabled && !$preview): ?>
                        <a title="<?= $this->organizationName ?> " href="<?= $this->orgProfileUrl($org)?>?clear=1"><?= $orgName ?></a>
                    <?php elseif (!$preview && $this->job->getTemplateValues()->get('companyWebsite')) : ?>
                        <a rel="nofollow" title="<?= $this->organizationName ?>" href="<?= $this->job->getTemplateValues()->get('companyWebsite') ?>"><?= $orgName ?></a>
                    <?php else: ?>
                        <?= (!empty($this->organizationName)) ? $this->organizationName : $orgName ?>
                    <?php endif ?> in <?php
                    $location = $this->job->getLocations()->current();
                    if ($location == '') {
                        echo $this->translate('Swiss');
                    }
                    elseif ($location) {
                        echo $location->getCity() ? $location->getCity() : preg_replace('~\(.*?\)$~', '', (string) $this->job->getLocation());
                    }
                    else {
                        echo preg_replace('~\(.*?\)$~', '', (string) $this->job->getLocation());
                    }
                    ?>
                </p>
                
                 <div class="apply-wrapper">
                      <?= $this->partial('jobs/partials/apply-button.phtml', [
                        'preview' => $preview,
                        'isExpired' => $isExpired,
                        'job' => $this->job,
                          ]); 
                        ?>
                      <?= $this->partial('jobs/partials/favorite-button.phtml', [
                        'preview' => $preview,
                        'jobId' => $this->job->getId(),
                        'isExpired' => $isExpired,
                        'buttonCss' => 'favorite-button',
                      ]); 
                      ?>
                  </div>
                
             <?php if ($newerThanDay): ?>
                 <span class="apply-info-new"><i class="fa fa-clock-o"></i> Gehören Sie zu den ersten 3 Bewerbern.</span>
            <?php endif; ?>
            
             <?= $this->partial('jobs/partials/expired-info.phtml', ['isExpired' => $isExpired]); ?>


      </div>
    </div>
  </div>
</div>

<div class="company-description-wrapper">
    <div class="row">
         <div class="col-md-12">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb" itemscope="" itemtype="http://schema.org/BreadcrumbList">
                        <li class="breadcrumb-item" itemprop="itemListElement" itemscope="" itemtype="http://schema.org/ListItem">
                            <a itemprop="item" href="/"> <span itemprop="name">Home</span></a>
                                   <meta itemprop="position" content="1">
                            </li>
                             <li class="breadcrumb-item" itemprop="itemListElement" itemscope="" itemtype="http://schema.org/ListItem">
                                <a itemprop="item" href="/de/jobs?clear=1"> <span itemprop="name">Jobs</span></a>
                                    <meta itemprop="position" content="2">
                            </li>
                            <li class="breadcrumb-item" itemprop="itemListElement" itemscope="" itemtype="http://schema.org/ListItem"> 
                                 <span itemprop="name"><?=ucfirst($this->job->getTitle())?></span>
                                 <meta itemprop="position" content="3">
                            </li>
                        </ol>
                  </nav>
            </div>
        

 <div class="col-md-9">
  <div class="info-card">
<h2>Kurz & knapp</h2>
 <ul class="details-list-horizontal">


  <li ><i class="fa fa-angle-right"></i>
   <div class="details-list-content"><span class="title">Datum der Veröffentlichung</span><span class="value"><?= $this->publishDateFormatter($this->job) ?></span></div>
</li>
  <li ><i class="fa fa-angle-right"></i>
   <div class="details-list-content"><span class="title">Branche</span><span class="value">Gastronomie / Lebensmittel / Tourismus</span></div>
</li>
  <li ><i class="fa fa-angle-right"></i>
   <div class="details-list-content"><span class="title">Beschäftigungsart</span><span class="value"><?=$typeOfContract; ?></span></div>
</li>

</li>
  <li ><i class="fa fa-angle-right"></i>
   <div class="details-list-content"><span class="title">Arbeitsort</span><span class="value"><?php
                    $location = $this->job->getLocations()->current();
                    if ($location == '') {
                        echo $this->translate('Swiss');
                    }
                    elseif ($location) {
                        echo $location->getCity() ? $location->getCity() : preg_replace('~\(.*?\)$~', '', (string) $this->job->getLocation());
                    }
                    else {
                        echo preg_replace('~\(.*?\)$~', '', (string) $this->job->getLocation());
                    }
                    ?></span></div>
</li>

</ul>




<h2>Stellenbeschreibung</h2>

 <?php if ($this->job->getTemplateValues()->get('companyDescription')): ?>
        <div class="position">
            <p><?= $this->job->getTemplateValues()->get('companyDescription'); ?></p> 
       </div>
  <?php endif;?>

<?php if ($this->html): ?>
        <div class="position">
              <?=strip_tags($this->html,"<p><ul><li><b><strong>")?>
       </div>
     <?php else: ?>
        <div class="position">
           <?= $replaceImage($this->job->getTemplateValues()->get('position'));?>
          </div>
 <?php endif; ?>
 
 <!-- end info-card -->
  </div>
  
  
     <?php if (!$preview): ?>
            <?php echo $this->partial('jobs/partials/similar-company-jobs.phtml', ['job' => $this->job]); ?>
      <?php endif; ?>
  
    <?php if (!$preview && !$isExpired): ?>  
            <?php echo $this->partial('jobs/partials/similar-jobs.phtml', ['job' => $this->job]); ?>
     <?php endif; ?>
  
<!-- end col-md-9 -->
 </div>


<!-- sidebar contact and map -->
<div class="col-md-3">
    <?= $this->partial('jobs/partials/contact-sidebar', [
            'job' =>  $this->job,
            'orgName' => $orgName,
            'preview' => $preview
        ]
    ); ?>
</div>
<!-- end col-md-3 -->


 </div>

<!-- end company-description-wrapper -->
</div>

<div class="to-top-link">
                    <a id="scroll-to-top" href="#top"><span class="fa fa-chevron-up"></span> nach oben</a>
                </div>
