<?php
/**
 * YAWIK - Anzeige für Preview & Ausgabe Einzelinserat / Job-Abo
 *
 * @filesource
 * @license MIT
 * @copyright  2013 - 2018 Cross Solution <http://cross-solution.de>
 */


// check for preview
$routeParams = $this->params()->fromRoute();
$preview = false;
if (isset($routeParams['isPreview']) && $routeParams['isPreview']) {
    $preview = true;
}

/** @var \Gastro24\Entity\Template $template */
$template = $this->job->getAttachedEntity('gastro24-template');
$basePathHelper = $this->plugin('basePath');
$replaceImage = function($str) use ($template, $basePathHelper)
{
    $image = $template ? $template->getImage() : null;
    if ($image) {
        $imageUri = $basePathHelper($image->getUri());
        $imageHtml = '<img src="' . $imageUri . '">';
    } else {
        $imageHtml = '';
    }

    return str_replace('#image#', $imageHtml, $str);
};

$isExpired = ($this->job->getStatus()) ? $this->job->getStatus()->getName() == \Jobs\Entity\StatusInterface::EXPIRED : false;
$defaultLogoUrl = $this->basePath('modules/Gastro24/images/no-company-logo.png');

// organisation values
$organizationImageCache = $this->services('Organizations\ImageFileCache\Manager');
$org = $this->job->getOrganization();
$orgIsDisabled = false;
$orgName = $this->jobOrganizationName($this->job);
if ($org && (Organizations\Entity\Organization::PROFILE_DISABLED == $org->getProfileSetting() || is_null($org->getProfileSetting())) ) {
    $orgIsDisabled = true;
}
// get org logo as default
if($org && $org->getImages()->notEmpty('images')) {
    $defaultLogoUrl = $this->basePath($organizationImageCache->getUri($org->getImages()->get('thumbnail')));
}

// check for banner
$hasBanner = false;
// default banner
$imageServerUrl = $this->basePath('modules/Gastro24/images/bg_placeholder_gray.svg');
// banner from org
if ($org) {
    $organizationAdditionalRepo = $this->services('repositories')->get(\Gastro24\Entity\OrganizationAdditional::class);
    /** @var \Gastro24\Entity\OrganizationAdditional $organizationAdditional */
    $organizationAdditional = $organizationAdditionalRepo->findOneByOrganizationId($org->getId());
    if ($organizationAdditional && $organizationAdditional->getBanner()) {
        $imageServerUrl = $this->basePath($organizationAdditional->getBanner()->getUri());
        $hasBanner = true;
    }
}
// banner from job
$jobBanner = $template && ($image = $template->getImage());
if ($jobBanner) {
    $serverUrl = new \Laminas\View\Helper\ServerUrl();
    $imageServerUrl = $serverUrl($this->basePath($image->getUri()));
    $hasBanner = true;
}
if ($template && $template->getHideBanner()) {
    $hasBanner = false;
}

// check for newer than 24 hours
$newerThanDay = false;
// get date difference
$today = new DateTime();
$jobDate = $job->getDatePublishStart() ?? $job->getDateCreated();
// workaround - mongodb entity has difference in time
$time = strtotime($jobDate->format('y-m-d\TH:i:s.u'). '+02:00');
$jobDate->setTimestamp($time);
$dayDiff = $today->diff($jobDate);
if ($dayDiff->days < 1) {
    $newerThanDay = true;
}

$industries = $job->getClassifications()->getIndustries();
?>

<?php if ($hasBanner): ?>
  <style>
	.company-bg-image:before {
	    background-image: url(<?= $imageServerUrl ?>);
     }
  </style>
<?php endif; ?>

<div class="<?php if(!$hasBanner) echo 'no-banner' ?>" style="position:relative;">
   <div style="height:482.5px" class="company-bg-image"></div>
     <div class="<?php if(!$hasBanner) echo 'no-banner' ?> company-profile-wrapper">
        <div class="jgArSS" style="background-image: url(<?= $imageServerUrl ?>);"></div>
          <div class="company-profile-image">
              
               <?php
                  $wrapperLogoUrl = $defaultLogoUrl;
                     if ($template && ($logo = $template->getLogo())) {
                            $wrapperLogoUrl = $this->basePath($logo->getUri());
                        }
                      else {
                             $wrapperLogoUrl = $defaultLogoUrl;
                        }
                   ?>
                   
                   
          <?php if ($logo): ?>             
             <span class="job-logo-wrapper">
                 <img class="job-logo" alt="<?= $this->organizationName ?>" src="<?= $wrapperLogoUrl ?>" />
              </span>
           <?php endif; ?>  
           
           
              
           <div class="job-info-wrapper">
                <h1><?=$this->job->getTitle()?></h1>
                
                <?php $typeOfContract = $job->getClassifications()->getEmploymentTypes()->__toString() ?:'Vollzeit' ?>
                    
                <p><?=$typeOfContract; ?> bei <?php if ($org && !$orgIsDisabled && !$preview): ?>
                        <a title="<?= $this->organizationName ?> " href="<?= $this->orgProfileUrl($org)?>?clear=1"><?= $orgName ?></a>
                    <?php elseif (!$preview && $job->getTemplateValues()->get('companyWebsite')) : ?>
                        <a rel="nofollow" title="<?= $this->organizationName ?>" href="<?= $job->getTemplateValues()->get('companyWebsite') ?>"><?= $orgName ?></a>
                    <?php else: ?>
                        <?= (!empty($this->organizationName)) ? $this->organizationName : $orgName ?>
                    <?php endif ?> in <?php
                    $location = $job->getLocations()->current();
                    if ($location == '') {
                        echo $this->translate('Swiss');
                    }
                    elseif ($location) {
                        echo $location->getCity() ? $location->getCity() : preg_replace('~\(.*?\)$~', '', (string) $job->getLocation());
                    }
                    else {
                        echo preg_replace('~\(.*?\)$~', '', (string) $job->getLocation());
                    }
                    ?>
                </p>
                
                 <div class="apply-wrapper">
                      <?= $this->partial('jobs/partials/apply-button.phtml', [
                        'preview' => $preview,
                        'isExpired' => $isExpired,
                        'job' => $this->job,
                          ]); 
                        ?>
                      <?= $this->partial('jobs/partials/favorite-button.phtml', [
                        'jobId' => $job->getId(),
                        'isExpired' => $isExpired,
                        'buttonCss' => 'favorite-button',
                      ]); 
                      ?>
                  </div>
                
             <?php if ($newerThanDay): ?>
                 <span class="apply-info-new"><i class="fa fa-clock-o"></i> Gehören Sie zu den ersten 3 Bewerbern.</span>
            <?php endif; ?>
            
             <?= $this->partial('jobs/partials/expired-info.phtml', ['isExpired' => $isExpired]); ?>


      </div>
    </div>
  </div>
</div>

<div class="company-description-wrapper">
    <div class="row">
         <div class="col-md-12">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb" itemscope="" itemtype="http://schema.org/BreadcrumbList">
                        <li class="breadcrumb-item" itemprop="itemListElement" itemscope="" itemtype="http://schema.org/ListItem">
                            <a itemprop="item" href="/"> <span itemprop="name">Home</span></a>
                                   <meta itemprop="position" content="1">
                            </li>
                             <li class="breadcrumb-item" itemprop="itemListElement" itemscope="" itemtype="http://schema.org/ListItem">
                                <a itemprop="item" href="/de/jobs?clear=1"> <span itemprop="name">Jobs</span></a>
                                    <meta itemprop="position" content="2">
                            </li>
                            <li class="breadcrumb-item" itemprop="itemListElement" itemscope="" itemtype="http://schema.org/ListItem"> 
                                 <span itemprop="name"><?=$this->job->getTitle()?></span>
                                 <meta itemprop="position" content="3">
                            </li>
                        </ol>
                  </nav>
            </div>
        

 <div class="col-md-9">
  <div class="info-card">
<h2>Kurz & knapp</h2>
 <ul class="details-list-horizontal">


  <li ><i class="fa fa-angle-right"></i>
   <div class="details-list-content"><span class="title">Datum der Veröffentlichung</span><span class="value"><?= $this->publishDateFormatter($job) ?></span></div>
</li>
  <li ><i class="fa fa-angle-right"></i>
   <div class="details-list-content"><span class="title">Branche</span><span class="value">Gastronomie / Lebensmittel / Tourismus</span></div>
</li>
  <li ><i class="fa fa-angle-right"></i>
   <div class="details-list-content"><span class="title">Beschäftigungsart</span><span class="value"><?=$typeOfContract; ?></span></div>
</li>

</li>
  <li ><i class="fa fa-angle-right"></i>
   <div class="details-list-content"><span class="title">Arbeitsort</span><span class="value"><?php
                    $location = $job->getLocations()->current();
                    if ($location == '') {
                        echo $this->translate('Swiss');
                    }
                    elseif ($location) {
                        echo $location->getCity() ? $location->getCity() : preg_replace('~\(.*?\)$~', '', (string) $job->getLocation());
                    }
                    else {
                        echo preg_replace('~\(.*?\)$~', '', (string) $job->getLocation());
                    }
                    ?></span></div>
</li>

</ul>

<?php if ($this->job->getTemplateValues()->get('companyDescription')): ?>
        <h2><?= (!empty($this->organizationName)) ? $this->organizationName : $orgName ?> als Arbeitgeber/in</h2>
        <div class="position intro">
            <p><?= nl2br($this->job->getTemplateValues()->get('companyDescription')); ?></p> 
       </div>
  <?php endif;?>

<h2>Stellenbeschreibung</h2>

<?php if ($this->html): ?>
        <div class="position">
             <?=$this->html?>
       </div>
     <?php else: ?>
        <div class="position">
           <?= $replaceImage($this->job->getTemplateValues()->get('position'));?>
          </div>
 <?php endif; ?>
 
 <!-- end info-card -->
  </div>
  
  
     <?php if (!$preview): ?>
            <?php echo $this->partial('jobs/partials/similar-company-jobs.phtml', ['job' => $this->job]); ?>
      <?php endif; ?>
  
    <?php if (!$preview && !$isExpired): ?>  
            <?php echo $this->partial('jobs/partials/similar-jobs.phtml', ['job' => $this->job]); ?>
     <?php endif; ?>
  
<!-- end col-md-9 -->
 </div>


<div class="col-md-3">
     <div class="info-card" style="margin-bottom:0px;">
                    <h2>Firmenadresse</h2>
                    <address>
                        <?= (!empty($this->organizationName)) ? $this->organizationName : $orgName ?> <br>
                        <?php
                            $location = $job->getLocations()->current();
                            if ($location == '') {
                                echo $this->translate('Swiss');
                            } elseif ($location->getCity() && $location->getStreetname() && $location->getPostalcode()) {
                                echo $location->getStreetname() . '<br>';
                                echo $location->getPostalcode() . ' ' . $location->getCity();
                            } else {
                                echo preg_replace('~\(.*?\)$~', '', (string)$job->getLocation());
                            }
                        ?>
                    </address>
                        
                    <?php if (!$preview && $job->getTemplateValues()->get('companyWebsite')) : ?>
                        <div class="meta-adress">
                        <a rel="nofollow" title="<?= $this->organizationName ?>" href="<?= $job->getTemplateValues()->get('companyWebsite') ?>">zur Website <i class="fa fa-external-link"></i></a>
                      </div>
                     <?php endif ?>
      </div>
  <div class="iframe-container">
      <?php
          $googleMapsString = '';
          $googleMapsString .= !empty($this->organizationName) ? $this->organizationName : $orgName ;
          $googleMapsString .= '+';

          $location = $job->getLocations()->current();
          if ($location == '') {
              $googleMapsString .= 'Schweiz';
          }
          elseif ($location->getCity() && $location->getStreetname() && $location->getPostalcode()) {
              $googleMapsString .= $location->getStreetname() . '+' . $location->getCity() . '+' . $location->getPostalcode() . '+Schweiz';
          }
          else {
              $googleMapsString .= preg_replace('~\(.*?\)$~', '', (string) $job->getLocation());
          }
      ?>

      <iframe src="https://maps.google.com/maps?width=100%&amp;height=450&amp;hl=de&amp;q=1%20<?= $googleMapsString ?>&amp;ie=UTF8&amp;t=&amp;z=16&amp;iwloc=B&amp;output=embed"
              frameborder="0" scrolling="no" marginheight="0" marginwidth="0"></iframe>
 </div>
<!-- end col-md-3 -->
</div>


 </div>

<!-- end company-description-wrapper -->
</div>