<?php
/**
 * YAWIK
 *
 * @filesource
 * @license MIT
 * @copyright  2013 - 2018 Cross Solution <http://cross-solution.de>
 *
 * Variables:
 *             $job         JobInterface    Job Entity
 *             $isVisited   bool            Has the user already visited this job in the current session
 */

// meta data
$this->headTitle($this->metaTitle);
$this->headMeta()->setName('description', $this->translate($this->metaDescription))
    ->setProperty('og:title', $this->metaOgTitle)
    ->setProperty('og:description', 'Jetzt bewerben auf die Stelle &quot;' . $job->getTitle() . '&quot; bei Gastrojob24.ch - der Gastronomie & Hotellerie Jobbörse der Schweiz.')
    ->setProperty('og:url', $this->jobUrl($job, ['linkOnly' => true, 'absolute' => true]))
    ->setProperty('og:image', 'https://www.gastrojob24.ch/modules/Gastro24/gastro-logo-fb.png')
    ->setProperty('og:locale', 'de_DE')
    ->setProperty('og:type', 'website')
    ->setAutoEscape(false);


// check for preview
$routeParams = $this->params()->fromRoute();
$preview = false;
if (isset($routeParams['isPreview']) && $routeParams['isPreview']) {
    $preview = true;
}

// WORKAROUND for coop crawler -> wrong link
$isCoopJobWithWrongLink = false;
if ($job->getOrganization() && $job->getOrganization()->getOrganizationName()->getName() == 'Coop' && strpos($job->getLink(), 'https://www.jobs.ch') !== false ) {
    $isCoopJobWithWrongLink = true;
}

$isSpruengli = false;
if ($job->getOrganization() && $job->getOrganization()->getOrganizationName()->getName() == 'Confiserie Sprüngli') {
    $isSpruengli = true;
}


$isJam = false;
if ($job->getOrganization() && $job->getOrganization()->getOrganizationName()->getName() == 'Jobs And More') {
    $isJam = true;
}








if ($this->isIntern):
     $this->headMeta()->setName('robots', 'index, follow, noarchive, noodp, max-snippet:-1, max-image-preview:large, max-video-preview:-1');
     // intern HTML
elseif(!$this->isIntern && !$this->isEmbeddable):
      $this->headMeta()->setName('robots', 'noindex,follow');
     // External Redirects
elseif($isCoopJobWithWrongLink):
    $this->headMeta()->setName('robots', 'noindex,follow');
elseif($isSpruengli):
    $this->headMeta()->setName('robots', 'noindex,follow');
elseif($isJam):
    $this->headMeta()->setName('robots', 'noindex,follow');

endif;



// organisation values
$org = $job->getOrganization();
$orgIsDisabled = false;
$orgName = $this->jobOrganizationName($this->job);
if ($org && (Organizations\Entity\Organization::PROFILE_DISABLED == $org->getProfileSetting() || is_null($org->getProfileSetting()) )) {
    $orgIsDisabled = true;
}

$isExpired = ($this->job->getStatus()) ? $this->job->getStatus()->getName() == \Jobs\Entity\StatusInterface::EXPIRED : false;

// pagination values
$container = new \Laminas\Session\Container('gastro24_jobboardcontainer');
$lastSearchQuery = $container->landingPageSearchQuery;
$searchTerm = $container->searchTerm;
$hasSession = count($container->getArrayCopy());

if($container->fromCompanyProfile && $container->companyName) {
    $backTitle = $container->companyName . ' Jobs';
    $lastSearchQueryUrl = $this->orgProfileUrl($org) . '?clear=1';
}
elseif (!$lastSearchQuery) {
    $lastSearchQueryUrl = ($container->fromCompanyProfile) ? '/de/jobs?clear=1' : $this->url('lang/jobboard', [], ['query'=> ['q' => $searchTerm]], true);
    $backTitle = $this->translate('Back to search');
}
else {
    $lastSearchQueryUrl = $this->url('lang/landingPage', ['q' => $container->landingPageTerm, 'format' => 'html' ], true);
    $backTitle = $this->translate($lastSearchQuery . ' Jobs');
}

// banner image
$hasBanner = false;
if (!$this->isIntern && $this->isEmbeddable) {
    // check for banner
    // default banner
    $imageServerUrl = $this->basePath('modules/Gastro24/images/bg_placeholder_blue.svg');
    // banner from org
    if ($org) {
        $organizationAdditionalRepo = $this->services('repositories')->get(\Gastro24\Entity\OrganizationAdditional::class);
        /** @var \Gastro24\Entity\OrganizationAdditional $organizationAdditional */
        $organizationAdditional = $organizationAdditionalRepo->findOneByOrganizationId($org->getId());
        if ($organizationAdditional && $organizationAdditional->getBanner()) {
           $imageServerUrl = $this->basePath($organizationAdditional->getBanner()->getUri());
            $hasBanner = true;
        }
    }
    // banner from job
    /** @var \Gastro24\Entity\Template $template */
    $template = $this->job->getAttachedEntity('gastro24-template');
    $jobBanner = $template && ($image = $template->getImage());
    if ($jobBanner) {
        $serverUrl = new \Laminas\View\Helper\ServerUrl();
       /* $imageServerUrl = $serverUrl($this->basePath($image->getUri()));*/
        $imageServerUrl = $this->basePath($image->getUri());
        $hasBanner = true;
    }
    if ($template && $template->getHideBanner()) {
        $hasBanner = false;
    }
}

// get logo url
$organizationImageCache = $this->services('Organizations\ImageFileCache\Manager');
$logoUrl = $this->basePath('modules/Gastro24/images/no-company-logo.png');
// get org logo as default
$org = $this->job->getOrganization();
if($org && $org->getImages()->notEmpty('images')) {
    $logoUrl = $this->basePath($organizationImageCache->getUri($org->getImages()->get('thumbnail')));
}
$jobLogoUrl = $this->gastroLogoUri($this->job);
if ($jobLogoUrl) {
    $logoUrl = $jobLogoUrl;
}

// check for newer than 24 hours
$newerThanDay = false;
// get date difference
$today = new DateTime();
$jobDate = $job->getDatePublishStart() ?? $job->getDateCreated();
// workaround - mongodb entity has difference in time
$time = strtotime($jobDate->format('y-m-d\TH:i:s.u'). '+02:00');
$jobDate->setTimestamp($time);
$dayDiff = $today->diff($jobDate);
if ($dayDiff->days < 1) {
    $newerThanDay = true;
}

$link = $this->job->getLink();
$pdfcompressLink = str_replace("https://www.gastrojob24.ch", "https://gastrojob24.gumlet.net",$link);
$industries = $job->getClassifications()->getIndustries();
$qualifications = $this->job->getClassifications()->getProfessions();

//if (!$link) {
//    $link = $this->jobUrl($job, ['preview' => true, 'linkOnly' => true]);
//    $this->isEmbeddable = true;
//}

if (!$this->isIntern && !$this->isVisited && !$this->isEmbeddable):
$this->headScript()->captureStart();?>
;(function($, w) {
    $(function() {
        w.setTimeout(
            function() { w.location.href='<?=$this->job->getLink()?>'; },
            3000
        );
    });
})(jQuery, window);
<?php $this->headScript()->captureEnd();
endif;

//$this->headScript()->appendFile($this->basePath($this->asset('modules/Gastro24/js/jobs.js')))
 //   ->appendFile($this->basePath('/dist/js/bootstrap-dialog.min.js'))
?>

<?php if ($preview): ?>
    <?php $this->headStyle()->captureStart() ?>
  .container {
    min-width: 100%;
    padding-left:0px!important;
    padding-right:0px!important;
    }
    <?php $this->headStyle()->captureEnd() ?>
<?php endif; ?>


<?php if (!$preview) : ?>

    <?php echo $this->partial('jobs/partials/navigation.phtml', [
        
        'hasBanner' => $this->hasBanner,
        'hasSession' => $hasSession,
        'backTitle' => $backTitle,
        'lastSearchQueryUrl' => $lastSearchQueryUrl,
        'prevJob' => $this->prevJob,
        'nextJob' => $this->nextJob,
        'job' => $this->job,
        'location' => $this->location

    ]);
    ?>
<?php endif; ?>

<div class="row">
    <div class="col-md-12">
       
       <!-- view-intern --> 
        <?php if ($this->isIntern):?>
            <?= $this->internalJob ?>
        <?php endif ?>

      <!-- end view-intern --> 
       
<!-- view PDF / External --> 
<?php if (!$this->isIntern && $this->isEmbeddable):?>

<div class="company-description-wrapper">
  <div class="row">
    <div class="col-md-9">


      <div class="stand-alone-card company-info-wrapper">
        <div class="info-card">

          <div class="company-profile-image">

<?php if (!$jobLogoUrl): ?>
<style>
  .job-info-wrapper {
    width:100%
  }
</style>

<?php endif; ?>

                <?php if ($jobLogoUrl): ?>
                  <span class="job-logo-wrapper">
                     <img data-gmlazy="false" 
                          class="job-logo " 
                          alt="<?= $orgName?>" 
                          src="https://gastrojob24.gumlet.net<?= $logoUrl ?>?mode=fit&width=140&height=140&quality=75" />
                   </span>
                 <?php endif; ?>

                  <div class="job-info-wrapper">

                   <h2 class="job-titel">
                    <span>
                     <?= (!empty($this->organizationName)) ? $this->organizationName : $orgName ?>
                    </span>
                    <?=ucfirst($this->job->getTitle())?>
                    </h2>

                    <?= $this->partial('jobs/partials/expired-info.phtml', ['isExpired' => $isExpired]); ?>
                   <?php if ($newerThanDay): ?>
                      <span class="apply-info-new"><i class="fa fa-clock-o"></i> Gehören Sie zu den ersten 3 Bewerbern</span>
                    <?php endif; ?>
  <ul class="details-list-horizontal">
      <li><i class="fa fa-angle-right"></i>
          <div class="details-list-content"><span class="title">Datum der Veröffentlichung</span><span class="value"><?= $this->publishDateFormatter($job) ?></span></div>
      </li>
      <?php if ($industries->getItems()->count() && !$this->isCrawlerJob($org) && $industries->__toString() != ""): ?>
      <li><i class="fa fa-angle-right"></i>
          <div class="details-list-content"><span class="title">Branche</span><span class="value"><?= $industries->__toString(); ?></span></div>
      </li>

      <?php else: ?>

      <li><i class="fa fa-angle-right"></i>
          <div class="details-list-content"><span class="title">Branche</span><span class="value">keine Angabe</span></div>
      </li>
      <?php endif; ?>

    <?php if ($qualifications->getItems()->count() && !$this->isCrawlerJob($org) && $qualifications->__toString() != ""): ?>
      <li><i class="fa fa-angle-right"></i>
          <div class="details-list-content"><span class="title">Erforderliche Qualifikation</span><span class="value"><?= $qualifications->__toString(); ?></span></div>
      </li>
    <?php else: ?>
     <li>
         <i class="fa fa-angle-right"></i>
          <div class="details-list-content"><span class="title">Erforderliche Qualifikation</span><span class="value">Keine angegeben</div>
      </li>
      <?php endif; ?>

      <?php $typeOfContract = $job->getClassifications()->getEmploymentTypes()->__toString() ?:'Vollzeit' ?>
      <li><i class="fa fa-angle-right"></i>
          <div class="details-list-content"><span class="title">Beschäftigungsart</span><span class="value"><?=$typeOfContract; ?></span></div>
      </li>
      <li>
          <i class="fa fa-angle-right"></i>
          <div class="details-list-content"><span class="title">Arbeitsort</span><span class="value"><?php
                    $location = $job->getLocations()->current();
                    if ($location == '') {
                        echo $this->translate('Swiss');
                    }
                    elseif ($location) {
                        echo $location->getCity() ? $location->getCity() : preg_replace('~\(.*?\)$~', '', (string) $job->getLocation());
                    }
                    else {
                        echo preg_replace('~\(.*?\)$~', '', (string) $job->getLocation());
                    }
                    ?></span></div>
      </li>
      <?php if ($this->job->getAtsMode()->getMode() === 'none') : ?>

          <li>
              <i class="fa fa-angle-right">
              </i>
              <div class="details-list-content">
                  <span class="title">Bewerbung</span>
                  <span class="value">Keine Online-Bewerbung erwünscht</span>
              </div>
          </li>
      <?php endif; ?>
  </ul>
  </div>
</div>
<div class="apply-wrapper button_container <?php if (!$org || $orgIsDisabled): ?>no-company-profile<?php endif; ?> ">
            <?php if (!$preview): ?>
                    <?= $this->partial('jobs/partials/apply-button.phtml', [
            'preview' => $preview,
            'isExpired' => $isExpired,
            'job' => $this->job,
            ]); 
            ?>
          <?php endif; ?>
          <?php if ($org && !$orgIsDisabled && !$preview): ?>
          <a class="btn btn-default" title="Firmenprofil <?= $this->organizationName ?>" href="<?= $this->orgProfileUrl($org)?>?clear=1">
            <span>Firmenprofil
            </span>
          </a>
          <?php endif; ?>
          <?php if (!$preview): ?>
          <?= $this->partial('jobs/partials/favorite-button.phtml', [
'jobId' => $this->job->getId(),
'isExpired' => $isExpired,
'buttonCss' => 'favorite-button',
]); 
?>
          <?php endif; ?>
        </div>
      </div>
    </div>



   <div class="stand-alone-card extra-shadow">
   <?php if ($hasBanner): ?>

      <img class="job-top-image" 
      alt="<?=ucfirst($this->job->getTitle())?>" 
      data-src="https://gastrojob24.gumlet.net<?= $imageServerUrl ?>?mode=crop&amp;width=845&amp;quality=75" />

    <?php endif; ?>
      


         <?php if(strpos($link, '.pdf') !== false): ?> 
           <style>
             .apply-wrapper .no-apply-link { display:none;}

                @media (max-width: 468px) {
                 .button_container .favorite-button {
                  float: none;
                   width: 100%;
                  }

                }
              
            </style>

            <img style="margin:0 auto;"
            alt="PDF-Stellenbeschreibung von <?= (!empty($this->organizationName)) ? $this->organizationName : $orgName ?>" 
            title="<?= (!empty($this->organizationName)) ? $this->organizationName : $orgName ?> sucht <?=ucfirst($this->job->getTitle())?> in <?php
                    $location = $job->getLocations()->current();
                    if ($location == '') {
                        echo $this->translate('Swiss');
                    }
                    elseif ($location) {
                        echo $location->getCity() ? $location->getCity() : preg_replace('~\(.*?\)$~', '', (string) $job->getLocation());
                    }
                    else {
                        echo preg_replace('~\(.*?\)$~', '', (string) $job->getLocation());
                    }
                    ?>
            " class="img-responsive" src="<?=$pdfcompressLink?>?page=1&quality=75&width=780&enlarge=true" />
           

          
              <?php else: ?>
                    
                    <iframe style="height:1500px;width:100%;background-color:#fff;" src="" data-src="<?=$link?>"></iframe>


    <script>
		function deferIframe() {
		  var iframeElem = document.getElementsByTagName('iframe');
		  for ( var i = 0; i < iframeElem.length; i++ ) {
			if(iframeElem[i].getAttribute('data-src')) {
			  iframeElem[i].setAttribute('src',iframeElem[i].getAttribute('data-src'));
			} 
		  } 
		}
		window.onload = deferIframe;
																											 
	
    </script>



<?php endif; ?>

 <?= $this->partial('jobs/partials/contact-sidebar-alternative-extern', [
'job' =>  $this->job,
'orgName' => $orgName,
'preview' => $preview
]
); ?>




 <div class="apply-box-footer">
    <?= $this->partial('jobs/partials/apply-button.phtml', [
        'preview' => $preview,
        'isExpired' => $isExpired,
        'job' => $this->job,
        ]); 
    ?>
 </div>

 <?php if ($this->job->getTemplateValues()->get('companyDescription') && !$orgIsDisabled ): ?>
      <div class="stand-alone-card company-info">
        <div class="info-card">
          <div class="container-fluid">
            <div class="row">
              <div class="col-md-3">
                
               <?php if ($jobLogoUrl): ?>
                  <span class="job-logo-wrapper">
                     <img data-gmlazy="false" 
                          class="job-logo " 
                          alt="<?= $orgName?>" 
                          data-src="https://gastrojob24.gumlet.net<?= $logoUrl ?>?mode=fit&width=140&height=140&quality=75);" />
                   </span>
                 <?php endif; ?>




                <div class="meta-adress">
                  <?php if ($org && !$orgIsDisabled && !$preview): ?>
                  <a class="fa fa-angle-right" title="Firmenprofil <?= $this->organizationName ?>" href="<?= $this->orgProfileUrl($org)?>?clear=1">
                    <span>Firmenprofil
                    </span>
                  </a>
                  <?php endif; ?>
                  <!--<a class="fa fa-angle-right" href="http://gastro.jobs" rel="nofollow"><span>Jobs: 4</span></a>-->
                </div>
              </div>
              <div class="col-md-9">
                <h2>
                  <?= (!empty($this->organizationName)) ? $this->organizationName : $orgName ?>
                </h2>
                <div class="more">
                  <?= nl2br($this->job->getTemplateValues()->get('companyDescription')); ?>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <?php endif; ?>
      <?php if (!$preview): ?>
      <?php echo $this->partial('jobs/partials/similar-company-jobs.phtml', ['job' => $this->job]); ?>
      <?php endif; ?>
      <?php if (!$preview && !$isExpired): ?>
      <?php echo $this->partial('jobs/partials/similar-jobs.phtml', ['job' => $this->job]); ?>
      <?php endif; ?>
      <!-- end col-md-9 -->
    </div>
    <!-- sidebar contact and map -->
        <?= $this->partial('jobs/partials/contact-sidebar', [
        'job' =>  $this->job,
        'orgName' => $orgName,
        'preview' => $preview
        ]
        ); ?>
    <!-- end col-md-3 -->
  </div>
  <!-- end company-description-wrapper -->
</div>



 
<?php endif ?>
<!-- end view PDF / External -->
        
                

    </div>
</div>


<!-- apply modal -->
<style>

#job-apply-modal {
  padding-right:0px!important;

}

</style>
<div class="modal fade" id="job-apply-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" >
    <div class="modal-dialog" style="width: 95%; max-width:1200px; height: 95%" role="document">
        <div class="modal-content" style="height: 100%">
            <div class="modal-body" style="padding:0px;height: calc(100% - 65px)"></div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Schliessen</button>
            </div>
        </div>
    </div>
</div>
<!-- end apply modal -->
