<?php
$this->headMeta()->setName('robots', 'noindex');
$this->headScript()->appendFile($this->basePath($this->asset('modules/Gastro24/js/jobs.js')))
    ->appendFile($this->basePath('/dist/js/bootstrap-dialog.min.js'));


$savedJobsContainer = new \Zend\Session\Container('gastro24_savedjobs');
$savedJobs = ($savedJobsContainer->jobs) ? $savedJobsContainer->jobs : [];

$jobsRepo = $this->services('repositories')->get('Jobs');
?>

<h1><?=$this->translate('Saved jobs')?></h1>

<?php if(count($savedJobs)) : ?>
    <div class="box__favorites">
        <p>
            <span>
                <?php
                    $counter = count($savedJobs);
                    $title = ($counter == 1) ? $this->translate('You have 1 saved job.') : sprintf($this->translate('You have %s saved jobs.'), $counter);
                ?>
                <i class="fa fa-star" aria-hidden="true"></i><?=$title?>
            </span>
            <a class="btn btn-default" href="<?= $this->url('lang/saved-jobs', [], ['query' => ['remove' => true]], true)?>">
                <?=$this->translate("Remove all")?>
            </a>
        </p>
        <?php foreach ($savedJobs as $id => $jobData) : ?>
            <?php
            $jobObject = $jobsRepo->find($jobData['id']);
            $isExpired = ($jobObject->getStatus()) ? $jobObject->getStatus()->getName() == \Jobs\Entity\StatusInterface::EXPIRED : false;
            ?>
            <div class="box__job <?= ($isExpired) ? 'expired' : '' ?>">
                <div class="header">
                    <?php if ($isExpired) : ?>
                        <h2 class="h3">
                            <?=$jobData['title']?>
                        </h2>
                    <?php else: ?>
                        <h2 class="h3">
                            <a href="<?=$jobData['url']?>" title="<?=$jobData['title']?>"><?=$jobData['title']?></a>
                        </h2>
                    <?php endif; ?>

                    <a class="close-link" href="<?= $this->url('lang/saved-jobs', [], ['query' => ['remove' => true, 'id' => $jobData['id']]], true)?>">x</a>
                </div>
                <div class="content">
                    <ul>
                        <li class="location">
                            <?=($jobData['location'] == '') ? $this->translate('Swiss') : $jobData['location']; ?>
                        </li>
                        <li class="company">
                            <?=$jobData['organizationName']; ?>
                        </li>
                        <li class="employmentType">
                            <?=$jobData['employmentType']; ?>
                        </li>
                        <li class="date">
                            <?=$jobData['createdAt']?>
                        </li>
                    </ul>
                    <?php if ($isExpired) : ?>
                        <span class="badge badge-expired"><?=$this->translate('Expired')?></span>
                    <?php else: ?>
                        <!-- apply button -->
                        <div class="button-job-apply text-center">
                            <?=$jobData['applyUrl']?>
                        </div>
                        <!-- end apply button -->
                    <?php endif; ?>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
<?php else : ?>
    <div class="text-center box__favorite-note">
        <p>
            <?php $buttonHtml = '<button type="button" class="btn btn-default btn__job-favorite">' .
                $this->translate("Mark") . '</button>'; ?>
            <?= sprintf($this->translate('To save a job, click the %s button on a job you like.'), $buttonHtml)?>
        </p>
        <p>
            <?=$this->translate('The jobs you save will be stored here.')?>
        </p>
    </div>
<?php endif; ?>


<div class="modal fade" id="job-apply-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
    <div class="modal-dialog" style="width: 90%; max-width:1200px; height: 90%" role="document">
        <div class="modal-content" style="height: 100%">
            <div class="modal-body" style="height: calc(100% - 65px)"></div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Schliessen</button>
            </div>
        </div>
    </div>
</div>
