<?php
/**
 * YAWIK
 *
 * @filesource
 * @author    Carsten Bleek <bleek@cross-solution.de>
 * @copyright 2013-2016 Cross Solution (http://cross-solution.de)
 * @version   GIT: $Id$
 * @license   https://yawik.org/LICENSE.txt MIT
 */

/**
 * @see http://php.net/manual/de/class.datetime.php#datetime.constants.types
 */
$dateFormat = 'd.m.Y';

/* @var Organizations\ImageFileCache\Manager $organizationImageCache */
$organizationImageCache = $this->services('Organizations\ImageFileCache\Manager');

/* @var \Laminas\Paginator\Paginator $paginator */
$paginator = $this->jobs;
$paginator->setItemCountPerPage(1000);
$basePathHelper = $this->plugin('basePath');

/* @todo move this into a view helper */
$linkNext = $paginator->getCurrentPageNumber() < $paginator->count() ?
    $this->serverUrl($this->basePath($this->url('lang/export',
        [
            'format' => 'xml',
            'channel' => $this->channel
        ],
        [
            'query' => [
                'page' => ($paginator->getCurrentPageNumber() + 1)
            ]
        ]))) : '';

$linkPrevious = $paginator->getCurrentPageNumber() > 1 ?
    $this->serverUrl($this->basePath($this->url('lang/export',
        [
            'format' => 'xml',
            'channel' => $this->channel
        ],
        [
            'query' => [
                'page' => ($paginator->getCurrentPageNumber() - 1)
            ]
        ]))) : '';

$xmlStr='<?xml version="1.0" encoding="utf-8"?><jobs>
    <head>
        <totalPagesCount>' . $paginator->count() .'</totalPagesCount>
        <currentPage>'.$paginator->getCurrentPageNumber() .'</currentPage>
        <link type="next">'.$linkNext.'</link>
        <link type="previous">'.$linkPrevious.'</link>
        <totalJobsCount>' . $paginator->getTotalItemCount() . '</totalJobsCount>
        <channel>'.$this->channel.'</channel>
    </head>
</jobs>';

/*$xmlStr='<?xml version="1.0" encoding="utf-8"?><jobs></jobs>';*/

$xml = simplexml_load_string($xmlStr);

foreach ($this->jobs as $jobObject) {
    /** @var \Gastro24\Entity\Template $template */
    $template = $jobObject->getAttachedEntity('gastro24-template');

    $replaceImage = function($str) use ($template, $basePathHelper)
    {
        $image = $template ? $template->getImage() : null;
        if ($image) {
            $imageUri = $basePathHelper($image->getUri());
            $imageHtml = '<img rel="preload" as="image" src="' . $imageUri . '">';
        } else {
            $imageHtml = '';
        }

        return str_replace('#image#', $imageHtml, $str);
    };

    /* @var \Jobs\Entity\Job $jobObject */
    $job = $xml->addChild('job');
    $job->addAttribute('id', $jobObject->getId());
    $job->addChild('link', '<![CDATA[' . htmlspecialchars($this->jobUrl($jobObject,['linkOnly'=>true, 'absolute' => true])) . ']]');
    $job->addChild('name', '<![CDATA[' . $jobObject->getTitle() . ']]');

    if ($jobObject->getSalary()->getCurrency()) {
        $job->addChild('salary', '<![CDATA[' . $jobObject->getSalary()->getValue() . $jobObject->getSalary()->getCurrency() .
            $jobObject->getSalary()->getUnit() . ']]');
    }
    $job->addChild('description', '<![CDATA[' . $replaceImage($jobObject->getTemplateValues()->get('position')) . ']]');
    $job->addChild('company', '<![CDATA[' . $jobObject->getCompany() . ']]');

    $jobTypes = $jobObject->getClassifications()->getEmploymentTypes()->getValues();
    $jobType = array_pop($jobTypes);
    $job->addChild('jobtype', '<![CDATA[' . $jobType . ']]');

    $job->addChild('pubdate', $jobObject->getDatePublishStart()?date_format($jobObject->getDatePublishStart(),$dateFormat):"");
    if ($jobObject->getDatePublishEnd()) {
        $job->addChild('expire', date_format($jobObject->getDatePublishEnd(),$dateFormat));
    }
    $job->addChild('updated', $jobObject->getDateModified()?date_format($jobObject->getDateModified(),$dateFormat):"");

    if ($jobObject->getAtsMode()->isEnabled()) {
        $job->addChild('email', '<![CDATA[' . $jobObject->getContactEmail() . ']]');
        $job->addChild('apply_url', '<![CDATA[' . $this->applyUrl($jobObject, ['linkOnly'=>true, 'absolute' => true]) . ']]');
    }
    if ($jobObject->getOrganization()) {
        $job->addChild('phone', '<![CDATA[' . $jobObject->getOrganization()->getContact()->getPhone() . ']]');
    }

    $regions = [];
    $countries = [];
    foreach ($jobObject->getLocations() as $locationObject) {
        /* @var \Jobs\Entity\Location $locationObject */
        $regions[] =  $locationObject->getRegion();
        $countries[] =  $locationObject->getCountry();
    }
    $job->addChild('region', '<![CDATA[' . implode(',', $regions) . ']]');
    $job->addChild('country', '<![CDATA[' . implode(',', $countries) . ']]');
}
echo $xml->saveXML();