<?php
/**
 * YAWIK
 *
 * @filesource
 * @author    Carsten Bleek <bleek@cross-solution.de>
 * @copyright 2013-2016 Cross Solution (http://cross-solution.de)
 * @version   GIT: $Id$
 * @license   https://yawik.org/LICENSE.txt MIT
 */


/**
 * @see http://php.net/manual/de/class.datetime.php#datetime.constants.types
 */
$dateFormat = 'd.m.Y';

/* @var Organizations\ImageFileCache\Manager $organizationImageCache */
$organizationImageCache = $this->services('Organizations\ImageFileCache\Manager');

/**
 * Feed for offene-stellen.ch
 * @see https://www.offene-stellen.ch/XMLInfo/
 */
if ($this->channel == 'offene-stellen') {
    $paginators = $this->services('Core/PaginatorService');
    $params = [
        'channel' => 'default'
    ];
    /* @var \Laminas\Paginator\Paginator $paginator */
    $jobsPaginator = $paginators->get('Jobs/Job', $params);
    $jobsPaginator->setItemCountPerPage(1000);
    $xml = \Gastro24\View\Helper\OffeneStellenXmlExportHelper::getOffeneStellenXml($jobsPaginator);

    echo $xml->saveXML();
}
elseif ($this->channel == 'neuvoo') {
    $paginators = $this->services('Core/PaginatorService');
    $params = [
        'channel' => 'default'
    ];
    /* @var \Laminas\Paginator\Paginator $paginator */
    $jobsPaginator = $paginators->get('Jobs/Job', $params);
    $jobsPaginator->setItemCountPerPage(1000);
    $basePathHelper = $this->plugin('basePath');

    $crawlerOrganizations = [
        '5a0809397bb2b582267c7a97', // Adecco
        '5bcf612fb6428b0b1008db60', // McDonalds
        '5bc6e561b6428b641322dbf9', // Gilde
        '5aa7e1d77bb2b57b5d3c03e4', // zfv
        '58a4a59d4e197f17047b23c6', // Sprüngli
        '5bcdfda2b6428ba17c5c9048', // Bürkenstock
        '59d7d04e7bb2b594121c1235', // Coop
        '5aaf724f7bb2b5233a03ed25', // Kramer
        '5bd21420b6428bfb4523562e', // gastrag.ch
        '5a970fea7bb2b5a578812d52', // Randstad
        '59e4b53e7bb2b553412f9be9', // Sv Group
        '5a054fa37bb2b593231413a0', // Migros
        '5dc120e93c050f419712a3b2', // Coople Schweiz
        '5db7f6bb3c050f1326103fc2', // Jobs And More
        '5d8e267b3c050f7ff12f75d2', // Active Gastro
        '5d8da3cb3c050f4563073b32', // Compass Group
        '602bd1ebdd454724e4444042', // New Economy GmbH  - offene-stellen.ch
    ];

    $xmlStr='<?xml version="1.0" encoding="UTF-8"?><jobs></jobs>';

    $xml = simplexml_load_string($xmlStr);

    /* @var \Jobs\Entity\Job $jobObject */
    foreach ($jobsPaginator as $jobObject) {
        // skip crawler jobs
        $org = $jobObject->getOrganization();
        if($org && in_array($crawlerOrganizations, $org->getId()) !== false ) {
            continue;
        }

        // skip PDF and external jobs
        if($jobObject->getLink() && !$jobObject->getTemplateValues()->getHtml()) {
            continue;
        }

        /** @var \Gastro24\Entity\Template $template */
        $template = $jobObject->getAttachedEntity('gastro24-template');

        $replaceImage = function($str) use ($template, $basePathHelper)
        {
            $image = $template ? $template->getImage() : null;
            if ($image) {
                $imageUri = $basePathHelper($image->getUri());
                $imageHtml = '<img rel="preload" as="image" src="' . $imageUri . '">';
            } else {
                $imageHtml = '';
            }

            return str_replace('#image#', $imageHtml, $str);
        };

        $job = $xml->addChild('job');
        $job->addAttribute('id', $jobObject->getId());
        $job->addChild('link', '<![CDATA[' . htmlspecialchars($this->jobUrl($jobObject,['linkOnly'=>true, 'absolute' => true])) . ']]>');
        $job->addChild('name', '<![CDATA[' . $jobObject->getTitle() . ']]>');

        if ($jobObject->getSalary()->getCurrency()) {
            $job->addChild('salary', '<![CDATA[' . $jobObject->getSalary()->getValue() . $jobObject->getSalary()->getCurrency() .
                $jobObject->getSalary()->getUnit() . ']]>');
        }
        $jobDescription = $jobObject->getTemplateValues()->getHtml() ?: $jobObject->getTemplateValues()->get('position');
        $job->addChild('description', '<![CDATA[' . htmlspecialchars($replaceImage($jobDescription)) . ']]>');
        $job->addChild('company', '<![CDATA[' . $jobObject->getCompany() . ']]>');

        $jobTypes = $jobObject->getClassifications()->getEmploymentTypes()->getValues();
        $jobType = array_pop($jobTypes);
        $job->addChild('jobtype', '<![CDATA[' . ($jobType ?: 'vollzeit') . ']]>');

        $job->addChild('pubdate', $jobObject->getDatePublishStart()?date_format($jobObject->getDatePublishStart(),$dateFormat):"");
        if ($jobObject->getDatePublishEnd()) {
            $job->addChild('expire', date_format($jobObject->getDatePublishEnd(),$dateFormat));
        }
        $job->addChild('updated', $jobObject->getDateModified()?date_format($jobObject->getDateModified(),$dateFormat):"");

        if ($jobObject->getAtsMode()->isEnabled()) {
            switch ($jobObject->getAtsMode()->getMode()) {
                case 'uri':
                    $job->addChild('apply_url', '<![CDATA[' . htmlspecialchars($jobObject->getAtsMode()->getUri()) . ']]>');
                    break;
                default:
                    $job->addChild('email', '<![CDATA[' . $jobObject->getContactEmail() . ']]>');
                    $job->addChild('apply_url', '<![CDATA[' . $this->applyUrl($jobObject, ['linkOnly'=>true, 'absolute' => true]) . ']]>');
                    break;
            }
        }
        else {
            $job->addChild('apply_url', '<![CDATA[' . htmlspecialchars($this->jobUrl($jobObject,['linkOnly'=>true, 'absolute' => true])) . ']]>');
        }
        if ($jobObject->getOrganization()) {
            $job->addChild('phone', '<![CDATA[' . $jobObject->getOrganization()->getContact()->getPhone() . ']]>');
        }

        $regions = [];
        $countries = [];
        foreach ($jobObject->getLocations() as $locationObject) {
            /* @var \Jobs\Entity\Location $locationObject */
            $regions[] =  $locationObject->getRegion();
            $countries[] =  $locationObject->getCountry();
        }
        $job->addChild('region', '<![CDATA[' . implode(',', $regions) . ']]>');
        $job->addChild('country', '<![CDATA[' . implode(',', $countries) . ']]>');
    }

    echo html_entity_decode($xml->saveXML());
}
else {
    /* @var \Laminas\Paginator\Paginator $paginator */
    $paginator = $this->jobs;
    $paginator->setItemCountPerPage(1000);
    $basePathHelper = $this->plugin('basePath');

    /* @todo move this into a view helper */
    $linkNext = $paginator->getCurrentPageNumber() < $paginator->count() ?
        $this->serverUrl($this->basePath($this->url('lang/export',
            [
                'format' => 'xml',
                'channel' => $this->channel
            ],
            [
                'query' => [
                    'page' => ($paginator->getCurrentPageNumber() + 1)
                ]
            ]))) : '';

    $linkPrevious = $paginator->getCurrentPageNumber() > 1 ?
        $this->serverUrl($this->basePath($this->url('lang/export',
            [
                'format' => 'xml',
                'channel' => $this->channel
            ],
            [
                'query' => [
                    'page' => ($paginator->getCurrentPageNumber() - 1)
                ]
            ]))) : '';

    $xmlStr='<?xml version="1.0" encoding="UTF-8"?><jobs>
        <head>
            <totalPagesCount>' . $paginator->count() .'</totalPagesCount>
            <currentPage>'.$paginator->getCurrentPageNumber() .'</currentPage>
            <link type="next">'.$linkNext.'</link>
            <link type="previous">'.$linkPrevious.'</link>
            <totalJobsCount>' . $paginator->getTotalItemCount() . '</totalJobsCount>
            <channel>'.$this->channel.'</channel>
        </head>
    </jobs>';

    /*$xmlStr='<?xml version="1.0" encoding="utf-8"?><jobs></jobs>';*/

    $xml = simplexml_load_string($xmlStr);

    foreach ($this->jobs as $jobObject) {

        /* @var \Jobs\Entity\Job $jobObject */
        // skip PDF and external jobs
        if($jobObject->getLink() && !$jobObject->getTemplateValues()->getHtml()) {
            continue;
        }

        /** @var \Gastro24\Entity\Template $template */
        $template = $jobObject->getAttachedEntity('gastro24-template');

        $replaceImage = function($str) use ($template, $basePathHelper)
        {
            $image = $template ? $template->getImage() : null;
            if ($image) {
                $imageUri = $basePathHelper($image->getUri());
                $imageHtml = '<img rel="preload" as="image" src="' . $imageUri . '">';
            } else {
                $imageHtml = '';
            }

            return str_replace('#image#', $imageHtml, $str);
        };

        $job = $xml->addChild('job');
        $job->addAttribute('id', $jobObject->getId());
        $job->addChild('link', '<![CDATA[' . htmlspecialchars($this->jobUrl($jobObject,['linkOnly'=>true, 'absolute' => true])) . ']]>');
        $job->addChild('name', '<![CDATA[' . $jobObject->getTitle() . ']]>');

        if ($jobObject->getSalary()->getCurrency()) {
            $job->addChild('salary', '<![CDATA[' . $jobObject->getSalary()->getValue() . $jobObject->getSalary()->getCurrency() .
                $jobObject->getSalary()->getUnit() . ']]>');
        }
        $jobDescription = $jobObject->getTemplateValues()->getHtml() ?: $jobObject->getTemplateValues()->get('position');
        $job->addChild('description', '<![CDATA[' . htmlspecialchars($replaceImage($jobDescription)) . ']]>');
        $job->addChild('company', '<![CDATA[' . $jobObject->getCompany() . ']]>');

        $jobTypes = $jobObject->getClassifications()->getEmploymentTypes()->getValues();
        $jobType = array_pop($jobTypes);
        $job->addChild('jobtype', '<![CDATA[' . ($jobType ?: 'vollzeit') . ']]>');

        $job->addChild('pubdate', $jobObject->getDatePublishStart()?date_format($jobObject->getDatePublishStart(),$dateFormat):"");
        if ($jobObject->getDatePublishEnd()) {
            $job->addChild('expire', date_format($jobObject->getDatePublishEnd(),$dateFormat));
        }
        $job->addChild('updated', $jobObject->getDateModified()?date_format($jobObject->getDateModified(),$dateFormat):"");

        if ($jobObject->getAtsMode()->isEnabled()) {
            switch ($jobObject->getAtsMode()->getMode()) {
                case 'uri':
                    $job->addChild('apply_url', '<![CDATA[' . htmlspecialchars($jobObject->getAtsMode()->getUri()) . ']]>');
                    break;
                default:
                    $job->addChild('email', '<![CDATA[' . $jobObject->getContactEmail() . ']]>');
                    $job->addChild('apply_url', '<![CDATA[' . $this->applyUrl($jobObject, ['linkOnly'=>true, 'absolute' => true]) . ']]>');
                    break;
            }
        }
        else {
            $job->addChild('apply_url', '<![CDATA[' . htmlspecialchars($this->jobUrl($jobObject,['linkOnly'=>true, 'absolute' => true])) . ']]>');
        }
        if ($jobObject->getOrganization()) {
            $job->addChild('phone', '<![CDATA[' . $jobObject->getOrganization()->getContact()->getPhone() . ']]>');
        }

        $regions = [];
        $countries = [];
        foreach ($jobObject->getLocations() as $locationObject) {
            /* @var \Jobs\Entity\Location $locationObject */
            $regions[] =  $locationObject->getRegion();
            $countries[] =  $locationObject->getCountry();
        }
        $job->addChild('region', '<![CDATA[' . implode(',', $regions) . ']]>');
        $job->addChild('country', '<![CDATA[' . implode(',', $countries) . ']]>');
    }

    echo html_entity_decode($xml->saveXML());
}
