<div class="row">

<?php foreach ($this->organizations as $organization): /* @var $organization \Organizations\Entity\Organization */?>

<?php
    $paginators = $this->services('Core/PaginatorService');
    $jobPaginator = $paginators->get('Jobs/Admin', ['companyId' => $organization->getId(), 'status' => \Jobs\Entity\Status::ACTIVE]);
    $activeJobCount = $jobPaginator->getTotalItemCount();
?>
<div class="col-xs-12 col-sm-6 col-md-4 ">
<div class=" card box__job-favorite">
    <a class="job-logo-link" title="<?php
        $nameEntity = $organization->getOrganizationName();
        echo isset($nameEntity)?$nameEntity->getName():'**** DRAFT ****';
        ?>" href="<?php echo $this->url('lang/organizations/profileDetail', array('id' => $organization->getId())); ?>?clear=1">
        <?php if ($organization->getImage() &&  $organization->getOrganizationName()): ?>
        <img class="job-logo" alt="" src="<?php echo $this->basePath($this->organizationImageCache->getUri($organization->getImage(true))) ?>">
        <?php endif ?>
    </a>
    <div class="card__job-content box__action-buttons">

        <!-- favorite button -->
        <!-- end favorite button -->

        <h2><a title="	<?php
        $nameEntity = $organization->getOrganizationName();
        echo isset($nameEntity)?$nameEntity->getName():'**** DRAFT ****';
        ?>" href="<?php echo $this->url('lang/organizations/profileDetail', array('id' => $organization->getId())); ?>?clear=1">
                <?php
        $nameEntity = $organization->getOrganizationName();
        echo isset($nameEntity)?$nameEntity->getName():'**** DRAFT ****';
        ?></a></h2>
        <div class="card__job-info">
            <div class="card__job-empname-label">
                <?php echo $organization->getContact()->getPostalcode();?> <?php echo $organization->getContact()->getCity();?>

            </div>
            <div class="card__job-location">
                <?php echo $organization->getContact()->getStreet();?> <?php echo $organization->getContact()->getHouseNumber();?>
            </div>
        </div>
        <div class="card__job-snippet-logo">
            <p class="card__job-snippet" dir="auto">



            </p>
        </div>
        <p><?= $activeJobCount == 1 ? $activeJobCount . ' aktiver Job' : $activeJobCount . ' aktive Jobs' ?></p>
    </div>
  </div>
</div>

<?php endforeach?>

</div>


<?php echo $this->paginationControl($this->organizations, 'Sliding', 'pagination-control',
                                    ['lang' => $this->params('lang'), 'route' => 'lang/organizations/profile']
);?>