<?php

$this->headTitle($this->translate("Register"));
$this->headScript()->appendFile($this->basePath('modules/Gastro24/js/registration.js'))

?>
<style>
    /*only for register page */
    
    .panel-footer a {
        
        text-decoration:underline;
    }
    h2 {
        
    margin-bottom: 10px;
    color: #0b2235;
    font-size: 24px;
    line-height: 30px;
    font-weight: bold;
    }
    
    .ecom-list {
    position: relative;
    list-style: none inside;
    padding: 0;
}

.ecom-list__item--checked {
    position: relative;
    padding-left: 19px;
}

.ecom-list__item--checked::before {
    content: '\f00c';
    display: block;
    font: normal normal normal 14px/1 FontAwesome;
    font-size: inherit;
    text-rendering: auto;
    -webkit-font-smoothing: antialiased;
    position: absolute;
    margin-left: -20px;
    color: #7aae1a;
    top: 3px;
    font-weight: 100;
}

  .panel-body {
      
      padding: 15px 15px 30px 15px;  
  }
  
  .panel-info {
    border: 0;
    box-shadow: 0px 1px 3px 0 rgba(44,43,35,0.3);
      -moz-box-shadow:  0px 1px 3px 0 rgba(44,43,35,0.3);
  -webkit-box-shadow: 0px 1px 3px 0 rgba(44,43,35,0.3);
  -webkit-border-radius: 4px;
-moz-border-radius: 4px;
border-radius: 4px;
}
.breadcrumb, main#content {
    background-color: #fff;
}

.advantage-box {
    
    color:#566578;
}
    @media (min-width: 768px) {
    .promote-container {
        max-width: 780px;
        padding: 40px 0;
    }
}

#promote-abos {
    background-color: #fff;
}

#promote-abos hr {
    background-color: #bac4da;
    height: 1px;
    margin: 60px auto;
}

#post-job-help {
    padding: 0 0 20px 0;
}

#promote-abos h3 {
    margin-top: 0px;
    font-size: 22px;
    font-weight: 300;
}
</style>


<div class="row">

        <div class="col-md-12">
     <nav aria-label="breadcrumb">
        <ol class="hidden-xs breadcrumb" itemscope="" itemtype="http://schema.org/BreadcrumbList" >
            <li class="breadcrumb-item" itemprop="itemListElement" itemscope="" itemtype="http://schema.org/ListItem">
                <a itemprop="item" href="/">
                    <span itemprop="name">Home</span>
                </a>
                <meta itemprop="position" content="1">
            </li>
            <li class="breadcrumb-item" itemprop="itemListElement" itemscope="" itemtype="http://schema.org/ListItem">
                 <span itemprop="name">Für Arbeitgeber</span>
                <meta itemprop="position" content="2">
            </li>
        </ol>
    </nav>
            <div class="page-title">
                <h1>Für Arbeitgeber</h1>
            </div>
        </div>
        
        <div class="col-md-6">
            <div class="panel panel-info">
              
              
              
                <div class="panel-body">
                    
                    <h2>Registrieren und Mitarbeiter finden!</h2>
                    
                    <?php echo $this->form($this->form);?>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="panel panel-info advantage-box">
              
                <div class="panel-body">
                   
                   <h2>Ihre Vorteile als registrierter Arbeitgeber</h2>
                  <p>Als registrierter Arbeitgeber erhalten Sie für <strong>nur CHF 595.-</strong> exklusiv Zugriff während 12 Monaten und können folgende 
                  Gastrojob24-Services voll in Anspruch nehmen:</p>

<ul class="ecom-list">
<li class="ecom-list__item ecom-list__item--checked">Sensationelles Preis-Leistungsverhältnis</li>
<li class="ecom-list__item ecom-list__item--checked">Enorme Reichweite</li>
<li class="ecom-list__item ecom-list__item--checked">Google Job Search und Mobile optimiert</li>
<li class="ecom-list__item ecom-list__item--checked">Unlimitiert Jobs schalten (Flatrate)</li>
<li class="ecom-list__item ecom-list__item--checked">Bewerberverwaltung</li>
<li class="ecom-list__item ecom-list__item--checked">Individuelle Inserate-Laufzeit</li>
<li class="ecom-list__item ecom-list__item--checked">Eigenes Firmenprofil</li>
<li class="ecom-list__item ecom-list__item--checked">Jobs direkt von Ihrer Webseite einbinden</li>
<li class="ecom-list__item ecom-list__item--checked">Permanente Logopräsenz auf der Startseite</li>
</ul>
                   
                </div>
               <div class="panel-footer">
                   
                   Fragen? <a href="mailto:info@gastrojob24.ch">Kontaktieren</a> Sie uns!
                   <div class="pull-right"> Es gelten unsere <a href="/de/agb.html">AGB</a></div>
                   
               </div>
               
    
            </div>
        </div>
        
        
        <div id="promote-abos">
        <div class="promote-container container">
            <div class="row">
                <div class="col-md-12">

                    <div class="text-center subTextMarginBottom full-width-titles">
                        <h2>Features für mehr Job-Sichtbarkeit</h2>

                        <p class="postJobSubTitle">Publizieren Sie schnell und unkompliziert Ihre Stellenanzeigen und erreichen Sie gezeilt Fachkräfte aus Gastronomie und Hotellerie -
                            am richtigen Ort und im richtigen Moment. Mit monatlich über 10'000 Inserate-Klicks sprechen wir Stellensuchende aus der Gastronomie-Branche gezielt an.
                            Wählen Sie jetzt das für Sie passende Angebot.
                        </p>

                    </div>
                 

                    <div class="row">


                        <div class="col-md-5 col-sm-5 col-xs-12">
                            <img class="img-responsive" src="/modules/Gastro24/images/crawler.png" alt="Job Crawler">

                        </div>
                        <div class="col-md-7 col-sm-7 col-xs-12">
                            <h3>Job-Crawler</h3>

                            <p>Verfügt Ihre Website über eine grössere Anzahl an Stellenanzeigen und möchten Sie diese in Ihrem individuellen Design automatisch bei Gastrojob24 integrieren?
                                Dann ist unser Job-Crawler die richtige Lösung für Sie.</p>



                            <ul class="ecom-list">
                                <li class="ecom-list__item ecom-list__item--checked">Keine Extra-Programmierung notwendig</li>
                                <li class="ecom-list__item ecom-list__item--checked">Bilder und Logos gemäss Ihren CD/CI-Vorgaben</li>
                                <li class="ecom-list__item ecom-list__item--checked">Individuelles HTML-Template nach Ihren Wünschen</li>
                            </ul>


                            <a href="/de/crawler" class="link-inverted-post">
                                Jetzt anfragen
                            </a>

                        </div>





                    </div>


                    <hr>


                    <div class="row">



                        <div class="col-md-7 col-sm-7 col-xs-12">
                            <h3>Branding &amp; Job-Boostings</h3>
                            <p>Sie möchten Fachkräfte noch schneller auf Ihre Stellenanzeigen, Dienstleistungen oder Produkte aufmerksam machen? Nutzen Sie
                                jetzt unsere diversen Online-Werbeflächen und Services für mehr Aufmerksamkeit und Klicks.</p>



                            <a href="/de/branding.html" class="link-inverted-post">
                                Mehr erfahren
                            </a>

                        </div>

                        <div class="col-md-5 col-sm-5 col-xs-12">
                            <img class="img-responsive" src="/modules/Gastro24/images/rocket.png" alt="Job Branding Pakete">

                        </div>




                    </div>




                </div>
            </div>
        </div>
    </div>
    </div>
