<?php

$this->headTitle($this->translate("Register"));
$this->headScript()->appendFile($this->basePath('modules/Gastro24/js/registration.js'))

?>
<div class="row">

        <div class="col-md-12">
     <nav aria-label="breadcrumb">
        <ol class="hidden-xs breadcrumb" itemscope="" itemtype="http://schema.org/BreadcrumbList" >
            <li class="breadcrumb-item" itemprop="itemListElement" itemscope="" itemtype="http://schema.org/ListItem">
                <a itemprop="item" href="/">
                    <span itemprop="name">Home</span>
                </a>
                <meta itemprop="position" content="1">
            </li>
            <li class="breadcrumb-item" itemprop="itemListElement" itemscope="" itemtype="http://schema.org/ListItem">
                 <span itemprop="name">Für Arbeitgeber</span>
                <meta itemprop="position" content="2">
            </li>
        </ol>
    </nav>
            <div class="page-title">
                <h1>Jetzt als Arbeitgeber registrieren</h1>
            </div>
            <p>Als registrierter Arbeitgeber erhalten Sie für nur CHF 595.- exklusiv Zugriff auf alle Services während 12 Monaten. </p>
        </div>
        
        <div class="col-md-6">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <?php echo $this->translate("I'm not yet a customer"); ?>
                </div>
                <div class="panel-body">
                    <?php echo $this->form($this->form);?>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <?php echo $this->translate("I am already a customer"); ?>
                </div>
                <div class="panel-body">
                    <?php echo $this->form($this->formLogin);?>
                </div>
                <div class="panel-footer">
                    <a href="<?php echo  $this->url('lang/forgot-password'); ?>" title="<?php echo  $this->translate('I forgot my password'); ?>" class="small">
                        <?php echo  $this->translate('I forgot my password'); ?>
                    </a>
                </div>
            </div>
        </div>
    </div>
