<?php
/**
 * YAWIK
 *
 * @filesource
 * @copyright (c) 2013 - 2016 Cross Solution (http://cross-solution.de)
 * @author        bleek@cross-solution.de
 * @license       MIT
 */
/*
 * Information Mail to the Approval Team
 */

// shared vars used in mails
include(__DIR__ . '/' . 'vars.inc.phtml');

?>
<?= $this->partial('mail/header', [
        'title'            => 'Ein neues Jahres-Abo wurde angelegt',
        'width'            => $width,
        'mail_blue_color'  => $mail_blue_color,
        'mail_white_color' => $mail_white_color
    ]
); ?>

<tr>
    <td align="center" valign="top">

        <!-- CENTERING TABLE // -->
        <table border="0" cellpadding="0" cellspacing="0" width="100%" bgcolor="#FFF">
            <tbody>
            <tr>
                <td align="center" valign="top">
                    <!-- FLEXIBLE CONTAINER // -->
                    <table border="0" cellpadding="0" cellspacing="0" width="500" class="flexibleContainer">
                        <tbody>
                        <tr>
                            <td align="center" valign="top" width="500" class="flexibleContainerCell">
                                <table border="0" cellpadding="30" cellspacing="0" width="100%">
                                    <tbody><tr>
                                        <td align="center" valign="top">

                                            <!-- CONTENT TABLE // -->
                                            <table border="0" cellpadding="0" cellspacing="0" width="100%">
                                                <tbody>
                                                <tr>
                                                    <td valign="top" class="textContent">

                                                        <div style="margin: 10px 0;">
                                                            <h2>Angaben zum Unternehmen</h2>
                                                            <table border="0" cellpadding="3" cellspacing="0" width="100%">
                                                                <tr>
                                                                    <td><?= $this->translate("Companyname") ?>:</td>
                                                                    <td><?= $organization->getName() ?></td>
                                                                </tr>
                                                                <tr>
                                                                    <td>Vertreter:</td>
                                                                    <td><?= $organization->getName() ?></td>
                                                                </tr>
                                                                <tr>
                                                                    <td>E-Mail Adresse:</td>
                                                                    <td><?= $user->getEmail() ?></td>
                                                                </tr>
                                                                <tr>
                                                                    <td>Telefon:</td>
                                                                    <td><?= $user->getInfo()->getPhone() ?></td>
                                                                </tr>
                                                                <tr>
                                                                    <td>USt-ID-Nr/UID:</td>
                                                                    <td><?= $user->getSettings('Orders')->getInvoiceAddress()->getVatId()  ?></td>
                                                                </tr>
                                                            </table>
                                                        </div>

                                                        <div style="margin: 10px 0;">
                                                            <h2>Benutzer</h2>
                                                            <table border="0" cellpadding="3" cellspacing="0" width="100%">
                                                                <tr>
                                                                    <td>Geschlecht:</td>
                                                                    <td><?= $this->translate($user->getInfo()->getGender()) ?></td>
                                                                </tr>
                                                                <tr>
                                                                    <td><?= $this->translate("Vorname") ?>:</td>
                                                                    <td><?= $user->getInfo()->getFirstName() ?></td>
                                                                </tr>
                                                                <tr>
                                                                    <td><?= $this->translate("Nachname") ?>:</td>
                                                                    <td><?= $user->getInfo()->getLastName() ?></td>
                                                                </tr>
                                                            </table>
                                                        </div>

                                                        <div style="margin: 10px 0;">
                                                            <h2>Rechnungsadresse</h2>
                                                            <table border="0" cellpadding="3" cellspacing="0" width="100%">
                                                                <tr>
                                                                    <td><?= $this->translate("street") ?>:</td>
                                                                    <td><?= $user->getInfo()->getStreet() ?></td>
                                                                </tr>
                                                                <tr>
                                                                    <td><?= $this->translate("addressSuffix") ?>:</td>
                                                                    <td><?= $user->getInfo()->getFirstName() ?></td>
                                                                </tr>
                                                                <tr>
                                                                    <td><?= $this->translate("Postalcode") ?>:</td>
                                                                    <td><?= $user->getInfo()->getPostalCode() ?></td>
                                                                </tr>
                                                                <tr>
                                                                    <td><?= $this->translate("City") ?>:</td>
                                                                    <td><?= $user->getInfo()->getCity() ?></td>
                                                                </tr>
                                                                <tr>
                                                                    <td><?= $this->translate("country") ?>:</td>
                                                                    <td><?= $user->getInfo()->getCountry() ?></td>
                                                                </tr>
                                                            </table>
                                                        </div>
                                                    </td>
                                                </tr>
                                                </tbody>
                                            </table>
                                            <!-- // CONTENT TABLE -->

                                        </td>
                                    </tr>
                                    </tbody></table>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                    <!-- // FLEXIBLE CONTAINER -->
                </td>
            </tr>
            </tbody>
        </table>
        <!-- // CENTERING TABLE -->




    </td>
</tr>

<?= $this->partial('mail/footer', ['width' => $width, 'mail_white_color' => $mail_white_color]); ?>
