<?php
/**
 * YAWIK
 *
 * @filesource
 * @copyright (c) 2013 - 2016 Cross Solution (http://cross-solution.de)
 * @author        bleek@cross-solution.de
 * @license       MIT
 */
/*
 * Information Mail to the Approval Team
 */

// shared vars used in mails
include(__DIR__ . '/' . 'vars.inc.phtml');

?>
<?= $this->partial('mail/header', [
        'title'            => 'Änderung Rechnungsadresse',
        'width'            => $width,
        'mail_blue_color'  => $mail_blue_color,
        'mail_white_color' => $mail_white_color
    ]
); ?>

<tr>
    <td align="center" valign="top">

        <!-- CENTERING TABLE // -->
        <table border="0" cellpadding="0" cellspacing="0" width="100%" bgcolor="#FFF">
            <tbody>
            <tr>
                <td align="center" valign="top">
                    <!-- FLEXIBLE CONTAINER // -->
                    <table border="0" cellpadding="0" cellspacing="0" width="500" class="flexibleContainer">
                        <tbody>
                        <tr>
                            <td align="center" valign="top" width="500" class="flexibleContainerCell">
                                <table border="0" cellpadding="30" cellspacing="0" width="100%">
                                    <tbody><tr>
                                        <td align="center" valign="top">

                                            <!-- CONTENT TABLE // -->
                                            <table border="0" cellpadding="0" cellspacing="0" width="100%">
                                                <tbody>
                                                <tr>
                                                    <td valign="top" class="textContent">

                                                        <div style="margin: 10px 0;">
                                                            <h2>Neue Angaben für <?= $user->getInfo()->getDisplayName() ?> (<?= $user->getEmail() ?>)</h2>
                                                            <table border="0" cellpadding="3" cellspacing="0" width="100%">
                                                                <tr>
                                                                    <td><?= $this->translate("Companyname") ?>:</td>
                                                                    <td><?= $invoiceAddress->getCompany() ?></td>
                                                                </tr>
                                                                <tr>
                                                                    <td><?= $this->translate("street") ?>:</td>
                                                                    <td><?= $invoiceAddress->getStreet() ?></td>
                                                                </tr>
                                                                <tr>
                                                                    <td><?= $this->translate("Postalcode") ?>:</td>
                                                                    <td><?= $invoiceAddress->getZipCode() ?></td>
                                                                </tr>
                                                                <tr>
                                                                    <td><?= $this->translate("City") ?>:</td>
                                                                    <td><?= $invoiceAddress->getCity() ?></td>
                                                                </tr>
                                                                <tr>
                                                                    <td><?= $this->translate("country") ?>:</td>
                                                                    <td><?= $invoiceAddress->getCountry() ?></td>
                                                                </tr>
<!--                                                                <tr>-->
<!--                                                                    <td>Geschlecht:</td>-->
<!--                                                                    <td>--><?//= $this->translate($user->getInfo()->getGender()) ?><!--</td>-->
<!--                                                                </tr>-->
                                                                <tr>
                                                                    <td>Vertreter:</td>
                                                                    <td><?= $invoiceAddress->getName() ?></td>
                                                                </tr>
                                                                <tr>
                                                                    <td>E-Mail Adresse:</td>
                                                                    <td><?= $invoiceAddress->getEmail() ?></td>
                                                                </tr>
                                                            </table>
                                                        </div>
                                                    </td>
                                                </tr>
                                                </tbody>
                                            </table>
                                            <!-- // CONTENT TABLE -->

                                        </td>
                                    </tr>
                                    </tbody></table>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                    <!-- // FLEXIBLE CONTAINER -->
                </td>
            </tr>
            </tbody>
        </table>
        <!-- // CENTERING TABLE -->




    </td>
</tr>

<?= $this->partial('mail/footer', ['width' => $width, 'mail_white_color' => $mail_white_color]); ?>
