<?php
/**
 * YAWIK
 *
 * @filesource
 * @copyright (c) 2013 - 2016 Cross Solution (http://cross-solution.de)
 * @author        bleek@cross-solution.de
 * @license       MIT
 */
/*
 * Information Mail to the Approval Team
 */

// shared vars used in mails
include(__DIR__ . '/' . 'vars.inc.phtml');

?>
<div style="background: #eee;width: 100%;height: 100vh;">
    <div class="size margin-auto"
         style="background-color:<?= $mail_white_color ?>;max-width:<?= $width ?>;width:100%;margin-left: auto;margin-right: auto;">
        <?= $this->partial('mail/header', [
            'title'            => 'Neue Stellenanzeige',
            'width'            => $width,
            'mail_blue_color'  => $mail_blue_color,
            'mail_white_color' => $mail_white_color
        ]
        ); ?>

        <tr>
            <td align="center" valign="top">
                <!-- CENTERING TABLE // -->
                <table border="0" cellpadding="0" cellspacing="0" width="100%" bgcolor="#FFF">
                    <tbody>
                    <tr>
                        <td align="center" valign="top">
                            <!-- FLEXIBLE CONTAINER // -->
                            <table border="0" cellpadding="0" cellspacing="0" width="500" class="flexibleContainer">
                                <tbody><tr>
                                    <td align="center" valign="top" width="500" class="flexibleContainerCell">
                                        <table border="0" cellpadding="30" cellspacing="0" width="100%">
                                            <tbody>
                                            <tr>
                                                <td align="center" valign="top">

                                                    <!-- CONTENT TABLE // -->
                                                    <table border="0" cellpadding="0" cellspacing="0" width="100%">
                                                        <tbody>
                                                        <tr>
                                                            <td valign="top" class="textContent">

                                                                <div class="seprate_footer" style="padding:10px;">
                                                                    <?php
                                                                    $channels = $this->services('Jobs/Options/Provider');
                                                                    /* @var Jobs\Options\ProviderOptions $channels */
                                                                    $options             = $this->services('Core/Options');
                                                                    $defaultCurrencyCode = $options->defaultCurrencyCode;
                                                                    $defaultTaxRate      = $options->defaultTaxRate;
                                                                    $job                 = $this->job; /* @var Jobs\Entity\Job $job */
                                                                    ?>
                                                                    <h2><?= $this->translate("Job details") ?></h2>
                                                                    <table>
                                                                        <tr>
                                                                            <td><?= $this->translate("Title of the job") ?></td>
                                                                            <td><?= $job->getTitle() ?></td>
                                                                        </tr>
                                                                        <tr>
                                                                            <td><?= $this->translate("Location") ?></td>
                                                                            <td><?= $job->getLocation() ?></td>
                                                                        </tr>
                                                                        <tr>
                                                                            <td><?= $this->translate("Companyname") ?></td>
                                                                            <td><?= $job->getCompany() ?></td>
                                                                        </tr>
                                                                    </table>

                                                                    <h2><?= $this->translate("Publisher details") ?></h2>

                                                                    <table>
                                                                        <tr>
                                                                            <td><?= $this->translate("Name") ?></td>
                                                                            <td><?= $job->getUser()->getInfo()->getDisplayName() ?></td>
                                                                        </tr>
                                                                        <tr>
                                                                            <td><?= $this->translate("Email") ?></td>
                                                                            <td><?= $job->getUser()->getInfo()->getEmail() ?></td>
                                                                        </tr>
                                                                    </table>

                                                                    <?php
                                                                    /**
                                                                     * following Variables are accessible
                                                                     * - template string
                                                                     * - job JobEntity
                                                                     */
                                                                    ?>

                                                                    <?php $total = 0; ?>

                                                                    <?php if (empty($job->getPortals())) : ?>
                                                                        <?php echo $this->translate('no Portal chosen') ?>
                                                                    <?php else: ?>
                                                                        <h2><?php echo $this->translate("Selected Channels") ?></h2>
                                                                        <p>
                                                                            <?php foreach ($job->getPortals() as $portalName): ?>

                                                                                <?php $channelData =
                                                                                    $channels->getChannel($portalName);  /* @var Jobs\Options\ChannelOptions $channelData */ ?>
                                                                                <?= $channelData->getLabel() ?>,

                                                                            <?php endforeach;
                                                                            $priceFilter = $this->services('FilterManager.Jobs/ChannelPrices');
                                                                            $total       = $priceFilter->filter($job->getPortals()); ?>
                                                                        </p>
                                                                        <table>
                                                                            <tr>
                                                                                <td><?php echo $this->translate("Price") ?>:</td>
                                                                                <td><?php echo $this->currencyFormat((round($total, 2)), $defaultCurrencyCode) ?></td>
                                                                            </tr>
                                                                            <tr>
                                                                                <td><?php echo $this->translate("plus VAT") ?> (<?php echo $defaultTaxRate ?>%)</td>
                                                                                <td><?php echo $this->currencyFormat((round($total * $defaultTaxRate / 100, 2)),
                                                                                        $defaultCurrencyCode
                                                                                    ) ?></td>
                                                                            </tr>
                                                                            <tr>
                                                                                <td><?php echo $this->translate("Invoice amount") ?>:</td>
                                                                                <td><?php echo $this->currencyFormat((round(($total * $defaultTaxRate / 100) + $total, 2)),
                                                                                        $defaultCurrencyCode
                                                                                    ) ?></td>
                                                                            </tr>
                                                                        </table>
                                                                    <?php endif; ?>

                                                                    <a href="<?php echo $this->serverUrl() . $this->url('lang/jobs/approval', array(), true
                                                                        ) ?>?id=<?php echo $this->job->getId() ?>">
                                                                        <?php echo $this->translate("Click here to accept or reject the job opening") ?>
                                                                    </a>
                                                                </div>

                                                            </td>
                                                        </tr>
                                                        </tbody>
                                                    </table>
                                                    <!-- // CONTENT TABLE -->

                                                </td>
                                            </tr>
                                            </tbody>
                                        </table>
                                    </td>
                                </tr>
                                </tbody>
                            </table>
                            <!-- // FLEXIBLE CONTAINER -->
                        </td>
                    </tr>
                    </tbody></table>
                <!-- // CENTERING TABLE -->
            </td>
        </tr>

            <?= $this->partial('mail/footer', ['width' => $width, 'mail_white_color' => $mail_white_color]); ?>
        </div>
    </div>
</div>
