<?php
/**
 * YAWIK
 *
 * @filesource
 * @copyright (c) 2013 - 2016 Cross Solution (http://cross-solution.de)
 * @author        bleek@cross-solution.de
 * @license       MIT
 */
/*
 * Information Mail to the Approval Team
 */

// shared vars used in mails
include(__DIR__ . '/' . 'vars.inc.phtml');

?>
<?= $this->partial('mail/header', [
        'title'            => 'Einzelinserat angelegt',
        'width'            => $width,
        'mail_blue_color'  => $mail_blue_color,
        'mail_white_color' => $mail_white_color
    ]
); ?>

<tr>
    <td align="center" valign="top">

        <!-- CENTERING TABLE // -->
        <table border="0" cellpadding="0" cellspacing="0" width="100%" bgcolor="#FFF">
            <tbody>
                <tr>
                    <td align="center" valign="top">
                        <!-- FLEXIBLE CONTAINER // -->
                        <table border="0" cellpadding="0" cellspacing="0" width="500" class="flexibleContainer">
                            <tbody>
                            <tr>
                                <td align="center" valign="top" width="500" class="flexibleContainerCell">
                                    <table border="0" cellpadding="30" cellspacing="0" width="100%">
                                        <tbody>
                                            <tr>
                                                <td align="center" valign="top">
                                                    <!-- CONTENT TABLE // -->
                                                    <table border="0" cellpadding="0" cellspacing="0" width="100%">
                                                        <tbody>
                                                            <tr>
                                                                <td valign="top" class="textContent">

                                                                    <div style="background: #eee;width: 100%;">
                                                                        <div class="size margin-auto"
                                                                             style="background-color:<?= $mail_white_color ?>;max-width:<?= $width ?>;width:100%;margin-left: auto;margin-right: auto;">


                                                                            <div class="seprate_footer" style="padding:10px;">
                                                                                <?php
                                                                                $channels = $this->services('Jobs/Options/Provider');
                                                                                /* @var Jobs\Options\ProviderOptions $channels */
                                                                                $options             = $this->services('Core/Options');
                                                                                $defaultCurrencyCode = $options->defaultCurrencyCode;
                                                                                $defaultTaxRate      = $options->defaultTaxRate;
                                                                                $job                 = $this->job; /* @var Jobs\Entity\Job $job */
                                                                                ?>
                                                                                <h2><?= $this->translate("Job details") ?></h2>
                                                                                <table>
                                                                                    <tr>
                                                                                        <td><?= $this->translate("Title of the job") ?></td>
                                                                                        <td><?= $job->getTitle() ?></td>
                                                                                    </tr>
                                                                                    <tr>
                                                                                        <td><?= $this->translate("Location") ?></td>
                                                                                        <td><?= $job->getLocation() ?></td>
                                                                                    </tr>
                                                                                    <tr>
                                                                                        <td><?= $this->translate("Companyname") ?></td>
                                                                                        <td><?= $job->getCompany() ?></td>
                                                                                    </tr>
                                                                                    <tr>
                                                                                        <td>Unternehmenswebsite</td>
                                                                                        <td><?= $this->companyWebsite ?></td>
                                                                                    </tr>
                                                                                    <tr>
                                                                                        <td>Unternehmensinformation</td>
                                                                                        <td><?= $this->companyDescription ?></td>
                                                                                    </tr>
                                                                                </table>

                                                                                <br><br>
                                                                                <h2>Bewerbungsoptionen</h2>
                                                                                <table>
                                                                                    <tr>
                                                                                        <td>gewählte Option: </td>
                                                                                        <td><?= $this->applicationOption ?></td>
                                                                                    </tr>
                                                                                    <?php foreach ($this->applicationOptionData as $key => $value) : ?>
                                                                                        <tr>
                                                                                            <td><?= $key ?></td>
                                                                                            <td><?= $value ?></td>
                                                                                        </tr>
                                                                                    <?php endforeach; ?>
                                                                                </table>

                                                                                <br><br>
                                                                                <h2>Publikation</h2>
                                                                                <table>
                                                                                    <tr>
                                                                                        <td>Gewünschtes Aufschaltdatum: </td>
                                                                                        <td><?php if ($job->getDatePublishStart()) echo $job->getDatePublishStart()->format('d.m.Y') ?></td>
                                                                                    </tr>
                                                                                </table>

                                                                                <br><br>
                                                                                <h2><?= $this->translate("Publisher details") ?><?php $invoice = $this->order->getInvoiceAddress(); ?></h2>

                                                                                <table>
                                                                                    <tr>
                                                                                        <td><?= $this->translate("Companyname") ?></td>
                                                                                        <td><?= $invoice->getCompany() ?></td>
                                                                                    </tr>
                                                                                    <tr>
                                                                                        <td><?= $this->translate("Name") ?></td>
                                                                                        <td><?= $this->invoice['name'] ?></td>
                                                                                    </tr>
                                                                                    <tr>
                                                                                        <td>Adresse</td>
                                                                                        <td><?= $this->invoice['street'] ?>
                                                                                            <br>
                                                                                            <?= $this->invoice['zipCode'] ?> <?= $this->invoice['city'] ?>
                                                                                            <br>
                                                                                            <?= $this->invoice['region'] . ', ' . $this->invoice['country'] ?>
                                                                                        </td>
                                                                                    </tr>
                                                                                    <tr>
                                                                                        <td>Email</td>
                                                                                        <td><?=$this->link($invoice->getEmail())?></td>
                                                                                    </tr>
                                                                                </table>

                                                                                <?php if ($this->otherAddress) : ?>
                                                                                    <br><br>
                                                                                    <h2>Abweichende Rechnungsanschrift</h2>

                                                                                    <table>
                                                                                        <tr>
                                                                                            <td><?= $this->translate("Name") ?></td>
                                                                                            <td><?= $this->otherAddress['name'] ?></td>
                                                                                        </tr>
                                                                                        <tr>
                                                                                            <td>Adresse</td>
                                                                                            <td><?= $this->otherAddress['street'] ?>
                                                                                                <br>
                                                                                                <?= $this->otherAddress['zipCode']?> <?= $this->otherAddress['city'] ?>
                                                                                                <br>
                                                                                                <?=$this->otherAddress['region'] . ', ' . $this->otherAddress['country'] ?>
                                                                                            </td>
                                                                                        </tr>
                                                                                    </table>
                                                                                <?php endif; ?>


                                                                                <?php
                                                                                /**
                                                                                 * following Variables are accessible
                                                                                 * - template string
                                                                                 * - job JobEntity
                                                                                 */
                                                                                ?>

                                                                                <?php $total = 0; ?>

                                                                                <?php if (empty($job->getPortals())) : ?>
                                                                                    <?php echo $this->translate('no Portal chosen') ?>
                                                                                <?php else: ?>
                                                                                    <h2><?php echo $this->translate("Selected Channels") ?></h2>
                                                                                    <p>
                                                                                        <?php foreach ($job->getPortals() as $portalName): ?>

                                                                                            <?php $channelData =
                                                                                                $channels->getChannel($portalName);  /* @var Jobs\Options\ChannelOptions $channelData */ ?>
                                                                                            <?= $channelData->getLabel() ?>,

                                                                                        <?php endforeach;
                                                                                        $priceFilter = $this->services('FilterManager.Jobs/ChannelPrices');
                                                                                        $total       = $priceFilter->filter($job->getPortals()); ?>
                                                                                    </p>
                                                                                    <table>
                                                                                        <tr>
                                                                                            <td><?php echo $this->translate("Price") ?>:</td>
                                                                                            <td><?php echo $this->currencyFormat((round($total, 2)), $defaultCurrencyCode) ?></td>
                                                                                        </tr>
                                                                                        <tr>
                                                                                            <td><?php echo $this->translate("plus VAT") ?> (<?php echo $defaultTaxRate ?>%)</td>
                                                                                            <td><?php echo $this->currencyFormat((round($total * $defaultTaxRate / 100, 2)),
                                                                                                    $defaultCurrencyCode
                                                                                                ) ?></td>
                                                                                        </tr>
                                                                                        <tr>
                                                                                            <td><?php echo $this->translate("Invoice amount") ?>:</td>
                                                                                            <td><?php echo $this->currencyFormat((round(($total * $defaultTaxRate / 100) + $total, 2)),
                                                                                                    $defaultCurrencyCode
                                                                                                ) ?></td>
                                                                                        </tr>
                                                                                    </table>
                                                                                <?php endif; ?>

                                                                                <br><br>

                                                                                <a href="<?php echo $this->serverUrl() . $this->url('lang/jobs/approval', array(), true
                                                                                    ) ?>?id=<?php echo $this->job->getId() ?>">
                                                                                    <?php echo $this->translate("Click here to accept or reject the job opening") ?>
                                                                                </a>

                                                                                <br><br>

                                                                                <a href="<?php echo $this->serverUrl() . $this->url('lang/orders-view', [], true) ?>?id=<?=$this->order->getId()?>">
                                                                                    Bestellung-Details ansehen
                                                                                </a>



                                                                            </div>
                                                                        </div>
                                                                    </div>

                                                                </td>
                                                            </tr>
                                                        </tbody>
                                                    </table>
                                                    <!-- // CONTENT TABLE -->
                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </td>
                            </tr>
                            </tbody>
                        </table>
                        <!-- // FLEXIBLE CONTAINER -->
                    </td>
                </tr>
            </tbody>
        </table>
        <!-- // CENTERING TABLE -->
    </td>
</tr>

<?= $this->partial('mail/footer', ['width' => $width, 'mail_white_color' => $mail_white_color]); ?>


