<?php
/**
 * YAWIK
 *
 * @filesource
 * @license    MIT
 * @copyright  2013 - 2015 Cross Solution <http://cross-solution.de>
 */

// shared vars used in mails
include(__DIR__ . '/' . 'vars.inc.phtml');
$this->setSubject('Stellenanzeige freigeschaltet');
?>

  <?= $this->partial('mail/header', [
            'title'            => 'Job wurde freigeschaltet',
            'width'            => $width,
            'mail_blue_color'  => $mail_blue_color,
            'mail_white_color' => $mail_white_color
        ]
        ); ?>
 <tr>
	 <td align="center" valign="top">
									<!-- CENTERING TABLE // -->
									<table border="0" cellpadding="0" cellspacing="0" width="100%" bgcolor="#FFF">
										<tbody><tr>
											<td align="center" valign="top">
												<!-- FLEXIBLE CONTAINER // -->
												<table border="0" cellpadding="0" cellspacing="0" width="500" class="flexibleContainer">
													<tbody><tr>
														<td align="center" valign="top" width="500" class="flexibleContainerCell">
															<table border="0" cellpadding="30" cellspacing="0" width="100%">
																<tbody><tr>
																	<td align="center" valign="top">

																		<!-- CONTENT TABLE // -->
																		<table border="0" cellpadding="0" cellspacing="0" width="100%">
																			<tbody><tr>
																				<td valign="top" class="textContent">
																					
<h3 mc:edit="header" style="color:#22436c;line-height:125%;font-family:Helvetica,Arial,sans-serif;font-size:20px;font-weight:bold;margin-top:0;margin-bottom:3px;text-align:left;">
 <?php
            /*
             * Available variables:
             * $this->job : The job entity
             * $this->siteName: The site name (from Core/AbstractOptions)
             */

            $job = $this->job;
            /* @var \Jobs\Entity\Job $job */

            ?>
          Hallo <?php echo $invoice->getName() ?></h3>
<div mc:edit="body" style="text-align:left;font-family:Helvetica,Arial,sans-serif;font-size:15px;margin-bottom:0;color:#5F5F5F;line-height:135%;">
Ihre Stellenanzeige "<?= $job->getTitle() ?>"
    <?php if ($job->getReference()): ?> mit der Referenz <?= $job->getReference() ?> <?php endif ?> wurde freigeschaltet.
																					    
																					    </div>
																				</td>
																			</tr>
																		</tbody></table>
																		<!-- // CONTENT TABLE -->

																	</td>
																</tr>
															</tbody></table>
														</td>
													</tr>
												</tbody></table>
												<!-- // FLEXIBLE CONTAINER -->
											</td>
										</tr>
									</tbody></table>
									<!-- // CENTERING TABLE -->
								</td>
							</tr>
<!-- MODULE ROW // -->
<tr>
    <td align="center" valign="top">
        <!-- CENTERING TABLE // -->
        <table border="0" cellpadding="0" cellspacing="0" width="100%">
            <tr style="padding-top:0;">
                <td align="center" valign="top">
                    <!-- FLEXIBLE CONTAINER // -->
                    <table border="0" cellpadding="30" cellspacing="0" width="500" class="flexibleContainer">
                        <tr>
                            <td style="padding-top:0;" align="center" valign="top" width="500" class="flexibleContainerCell">

                                <!-- CONTENT TABLE // -->
                                <table border="0" cellpadding="0" cellspacing="0" width="50%" class="emailButton" style="background-color: #243b84;">
                                    <tr>
                                        <td align="center" valign="middle" class="buttonContent" style="padding-top:15px;padding-bottom:15px;padding-right:15px;padding-left:15px;">
                                            <a style="color:#FFFFFF;text-decoration:none;font-family:Helvetica,Arial,sans-serif;font-size:20px;line-height:135%;" href="<?php echo $this->serverUrl() . $this->jobUrl($job, ['linkOnly' => true ]) ?>" target="_blank">zum Inserat</a>
                                        </td>
                                    </tr>
                                </table>
                                <!-- // CONTENT TABLE -->

                            </td>
                        </tr>
                    </table>
                    <!-- // FLEXIBLE CONTAINER -->
                </td>
            </tr>
        </table>
        <!-- // CENTERING TABLE -->
    </td>
</tr>
<!-- // MODULE ROW -->

 <?= $this->partial('mail/footer', ['width' => $width, 'mail_white_color' => $mail_white_color]); ?>
