<?php
/**
 * YAWIK
 *
 * @filesource
 * @license MIT
 * @copyright  2013 - 2017 Cross Solution <http://cross-solution.de>
 */
$this->headTitle($this->article->title->rendered);
?>

<div class="sub-navigation-wrapper">
   <nav class="job-detail-breadcrumb-nav" aria-label="breadcrumb">
    <ol class="breadcrumb" itemscope="" itemtype="http://schema.org/BreadcrumbList">
            <li class="breadcrumb-item" itemprop="itemListElement" itemscope="" itemtype="http://schema.org/ListItem">
                <a itemprop="item" href="/">
                    <span itemprop="name">Home</span>
                </a>
                <meta itemprop="position" content="1">
            </li>
            <li class="breadcrumb-item" itemprop="itemListElement" itemscope="" itemtype="http://schema.org/ListItem">
                 <span itemprop="name"><?=$this->article->title->rendered?></span>
                <meta itemprop="position" content="2">
            </li>
        </ol>
   </nav>
</div>
<div class="row">
<div class="col-md-3" style="padding-right:0px;">

<div class="stand-alone-card">
          <div class="info-card">
			<ul class="content-link">
                    <li><a title="Publikationsnetzwerk" href="/de/publikationsnetzwerk.html">Publikationsnetzwerk</a></li>
                    <li><a title="Kontakt" href="/de/contact.html">Kontakt</a></li>
                    <li><a title="Über uns" href="/de/ueber-uns.html">Über uns</a></li>
                    <li><a title="Impressum" href="/de/impressum.html">Impressum</a></li>
                    <li><a title="Datenschutz" href="/de/datenschutz.html">Datenschutz</a></li>
                    <li><a title="AGB" href="/de/agb.html">AGB</a></li>

            </ul>
			
			
		</div>
    </div>	



</div>

<div class="col-md-9">
    <div class="stand-alone-card">
          <div class="info-card">
			<h1><?=$this->article->title->rendered?></h1>
            <?=$this->article->content->rendered;?>
			
			
		</div>
    </div>	
</div>
<!-- end row -->
</div>
