<?php
/**
 * YAWIK
 *
 * @filesource
 * @license MIT
 * @copyright  2013 - 2017 Cross Solution <http://cross-solution.de>
 */
$this->headTitle($this->article->title->rendered);
?>

<div class="row">
  <div class="col-md-8 col-xs-12"
        <h1><?=$this->article->title->rendered?></h1>
        <div class="wp-content">
            <?=$this->article->content->rendered;?>
        </div>
  </div>
</div>
