<?php
/**
 * YAWIK
 *
 * @filesource
 * @license MIT
 * @copyright  2013 - 2017 Cross Solution <http://cross-solution.de>
 */
$this->headTitle($this->article->title->rendered);
?>

<div class="row">
  <div class="col-md-8 col-xs-12">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb" itemscope="" itemtype="http://schema.org/BreadcrumbList">
            <li class="breadcrumb-item" itemprop="itemListElement" itemscope="" itemtype="http://schema.org/ListItem">
                <a itemprop="item" href="/">
                    <span itemprop="name">Home</span>
                </a>
                <meta itemprop="position" content="1">
            </li>
            <li class="breadcrumb-item" itemprop="itemListElement" itemscope="" itemtype="http://schema.org/ListItem">
                 <span itemprop="name"><?=$this->article->title->rendered?></span>
                <meta itemprop="position" content="2">
            </li>
        </ol>
    </nav>
      <div class="page-title">
            <h1><?=$this->article->title->rendered?></h1>
        </div>
        
        <div class="wp-content">
            <?=$this->article->content->rendered;?>
        </div>
  </div>
</div>
