<style>
    #wrapper {
        text-align: center;
        min-height: 600px;
    }
    #wrapper #bg-full {
        position: absolute;
        width: 100%;
    }
    #wrapper .bg-static {
        background-image: url(/modules/Gastro24/background_gastrojob24_img.jpg);
        background-color: #999;
        background-size: cover;
        background-repeat: no-repeat;
        background-position: center center;
        display: block;
        min-height: 600px;
    }

    .jumbotron {
        margin-top: 40px;
        position: relative;
        margin-bottom: 25px;
        padding: 0;
        color: #fff;
        background-color: transparent;
    }
    .jumbotron h1 {
        color: #fff;
        font-size: 42px;
        font-weight: 700;
        margin: 0;
    }
    .jumbotron h2 {
        color: #f2f2f2;
        font-size: 24px;
        font-weight: 300;
        margin: 15px 0 35px 0;
    }
    .jumbotron a {
        color: #f2f2f2;
        text-decoration:underline;
    }

    @media(min-width: @screen-sm) {
        #main-navigation {
            font-weight: 600;
        }
        #main-navigation .navbar-nav > li > a {
            padding-top: 10px;
            padding-bottom: 10px;
            margin-top: 30px;
            font-weight: 300;
            font-size: 16px;
        }
        #main-navigation .navbar-nav > li > a.link__saved-jobs {
            padding-left: 0;
        }
    }
</style>