<?php
/** @var \Zend\View\Renderer\PhpRenderer $this */
/** @var \Zend\Form\Form $form */
$form = $this->element;
/** @var \Solr\Facets $facets */
$facets = $this->facets;
$modalId = 'job-by-mail-subscribe-modal';
?>

<div class="jobmail-listings">
    <h2 class="h4">Täglich neue Jobs per E-Mail erhalten?</h2>
    <p class="hidden-xs">
        Lassen Sie sich automatisch informieren, sobald neue Jobs vorhanden sind.
    </p>
    <button type="button" class="pull-right hidden visible-sm hidden-xs btn btn-secondary" aria-expanded="false"
            data-toggle="collapse" data-target=".panel-group">Filter anzeigen</button>
    <button class="btn btn-info" data-title="<?=$this->translate('Jobs By Mail')?>" data-toggle="modal" data-target="#<?=$modalId?>"
            title="<?=$this->translate('Jobs By Mail')?>">
        <i class="yk-icon yk-icon-envelope"></i>Suche abonnieren
    </button>
</div>

<!-- job-by-mail modal form -->
<?= $this->partial('jobs-by-mail/partials/jobs-by-mail-modal.phtml', [
        'form' => $form,
        'facets' => $facets,
        'modalId' => $modalId
]); ?>
<!-- end job-by-mail modal form -->

<?php $this->headScript()->captureStart()?>
(function(){
var $form,
$modal,
init = function () {
$form = $('#<?=$form->getAttribute('id')?>');
$modal = $('#<?=$modalId?>');
$form.on('yk:forms:success', function(event, data) {
if ('valid' in data.data && data.data.valid) {
$modal.find('.modal-body').html(data.data.content);
$modal.find('.modal-footer .btn-primary').remove();
}
});
};

$(function () {
init();
$('#jobs-list-container').on('yk-paginator-container:loaded', function() {
init();
$form.form().find('select').each($.fn.form.initSelect);
$form.find('select.geoselect').geoSelect();
});
});
})();
<?php $this->headScript()->captureEnd() ?>
<script>
    /* HINT: should actually work with yk-forms success event*/
    $(document).ready(function() {
        $("#jobsbymail-subscribe-form").submit(function(e) {
            e.preventDefault(); // avoid to execute the actual submit of the form.

            var form = $(this);
            var url = form.attr('action');
            var modal = $('#job-by-mail-subscribe-modal');

            $.ajax({
                type: "POST",
                dataType: 'json',
                url: url,
                data: form.serialize(),
                success: function(data)
                {
                    if (data.valid) {
                        modal.find('.modal-body').html(data.content);
                        modal.find('.modal-footer .btn-primary').remove();
                    }
                }
            });
        });
    })
</script>

