<?php
/** @var \Zend\View\Renderer\PhpRenderer $this */
/** @var \Zend\Form\Form $form */
$form = $this->element;
/** @var \Solr\Facets $facets */
$facets = $this->facets;
$modalId = 'job-by-mail-subscribe-modal';
?>

  <a class="btn gastro-btn-secondary job-alert pull-right" data-toggle="modal" data-target="#job-by-mail-subscribe-modal">
      <i class="fa fa-bell"></i> Job-Alarm erstellen
   </a>
                            
                            



<!-- job-by-mail modal form -->
<?= $this->partial('jobs-by-mail/partials/jobs-by-mail-modal.phtml', [
        'form' => $form,
        'facets' => $facets,
        'modalId' => $modalId
]); ?>
<!-- end job-by-mail modal form -->

<?php $this->headScript()->captureStart()?>
(function(){
var $form,
$modal,
init = function () {
$form = $('#<?=$form->getAttribute('id')?>');
$modal = $('#<?=$modalId?>');
$form.on('yk:forms:success', function(event, data) {
if ('valid' in data.data && data.data.valid) {
$modal.find('.modal-body').html(data.data.content);
$modal.find('.modal-footer .btn-primary').remove();
}
});
};

$(function () {
init();
$('#jobs-list-container').on('yk-paginator-container:loaded', function() {
init();
$form.form().find('select').each($.fn.form.initSelect);
$form.find('select.geoselect').geoSelect();
});
});
})();
<?php $this->headScript()->captureEnd() ?>
<?php $this->configHeadScript()->appendScript('
    /* HINT: should actually work with yk-forms success event */
    $(document).ready(function() {
        $("#jobsbymail-subscribe-form").submit(function(e) {
            e.preventDefault(); // avoid to execute the actual submit of the form.

            var form = $(this);
            var url = form.attr("action");
            var modal = $("#job-by-mail-subscribe-modal");

            $.ajax({
                type: "POST",
                dataType: "json",
                url: url,
                data: form.serialize(),
                success: function(data)
                {
                    if (data.valid) {
                        modal.find(".modal-body").html(data.content);
                        modal.find(".modal-footer .btn-primary").remove();
                    }
                }
            });
        });
    });
'); ?>

