<?php
/**
 * YAWIK
 *
 * @filesource
 * @license MIT
 * @copyright  2013 - 2016 Cross Solution <http://cross-solution.de>
 */

$this->headScript()->appendFile($this->basePath('/dist/js/iframeResizer.js'));

$job = $this->element->getObject(); /* @var \Jobs\Entity\JobInterface $job */
$snapshotId = null;

if ($job instanceOf \Jobs\Entity\JobSnapshot) {
    $snapshotId = $job->getSnapshotId();
    $query = ['snapshot' => $snapshotId];
} else {
    $query = ['id' => $job->getId()];
}

$viewLink = ($snapshotId) ? $this->url('lang/jobs/view') . '?id=' . $job->getId() . '&snapshot=' . $job->getSnapshotId() :
    $this->url('lang/jobs/view') . '?id=' . $job->getId();

$query['page'] = 0;
$multipostLink = $this->url(
    'lang/jobs/manage',
    array(),
    array(
        'query' => $query,
    )
);
$options = $this->services('Core/Options');
$defaultCurrencyCode = $options->defaultCurrencyCode;
$defaultTaxRate = $options->defaultTaxRate;

$template = $job->getAttachedEntity('gastro24-template');

$defaultLogoUrl = $this->basePath('modules/Gastro24/images/no-company-logo.png');
$imageServerUrl = $this->basePath('modules/Gastro24/images/bg_placeholder_gray.svg');
$hasBanner = $template && ($image = $template->getImage());
if ($hasBanner) {
    $serverUrl = new \Laminas\View\Helper\ServerUrl();
    $imageServerUrl = $serverUrl($this->basePath($image->getUri()));
}
else {
    if ($job->getLink()) {
        $imageServerUrl = $this->basePath('modules/Gastro24/images/bg_placeholder_blue.svg');
    }
}

// organisation values
$org = $job->getOrganization();
$orgIsDisabled = false;
$orgName = $this->jobOrganizationName($job);
if ($org && (Organizations\Entity\Organization::PROFILE_DISABLED == $org->getProfileSetting() || is_null($org->getProfileSetting()) )) {
    $orgIsDisabled = true;
}

?>
<style>
    #form-jobs-form-preview .panel__job-detail .panel-body{
        padding: 0 2rem!important;
    }
    iframe {
        background-color:#fff;
        height:1800px;
        overflow:auto;
        width: 1px;
        min-width: 100%;
    }
</style>
<h3><?=$this->translate("Preview of your job posting"); ?></h3>
<div class="row">
    <div class="col-md-8">
        <!-- HINT: $viewLink can be overwritten in jobpdfupload.js -->
        <iframe id="previewJob" src="<?= $viewLink ?>"></iframe>
    </div>
    <div class="col-md-4">
        <div class="alert alert-info">
            <script type="text/javascript">
                function printIframe(id)
                {
                    var iframe = document.frames ? document.frames[id] : document.getElementById(id);
                    var ifWin = iframe.contentWindow || iframe;
                    iframe.focus();
                    ifWin.yawikPrintJob();
                    return false;
                }
            </script>

            <!-- HINT: $viewLink can be overwritten in jobpdfupload.js -->
            <?php echo sprintf($this->translate('Please check the preview of your job position. Click %s to open the preview in a new window'),
                '<a class="preview-link" target="_blank" href="'. $viewLink .'">'.$this->translate("here").'</a>'); ?><br/>
            <a target="_blank" href="<?= $viewLink ?>" class="btn btn-info preview-link-button" role="button"><i class="fa fa-external-link"></i>
                <?=$this->translate('Open new Window')?>
            </a>
            <a href="#" onclick="javascript:printIframe('previewJob');return false;" class="btn btn-info" role="button"><i class="fa fa-print"></i>
                <?=$this->translate('Print')?>
            </a>
        </div>
    </div>
</div>

<script src="/modules/Gastro24/jssocials-1.4.0/dist/jssocials.js"></script>
<script>
    $("#share").jsSocials({
        showLabel: false,
        showCount: true,
        shares: ["email", "twitter", "facebook", "whatsapp"]
    });
</script>

<!-- iframe resizer -->
<?php $this->configHeadScript()->appendScript('iFrameResize({ log: false }, "#previewJob")'); ?>
<!-- end iframe resizer -->

<div id="product-list-wrapper">
    <?php if ($job->getPortals()): ?>
        <?= $this->partial('jobs/partials/channel-list', [
            'portals'             => $job->getPortals(),
            'channels'            => $this->services('Jobs/Options/Provider'),
            'defaultCurrencyCode' => $defaultCurrencyCode,
            'defaultTaxRate'      => $defaultTaxRate,
            'jobId'               => $job->getId(),
        ]);
        ?>

    <?php endif; // $this->job->portals ?>
</div>

<?= $this->formCollection($this->element); ?>
