<?php
/**
 * YAWIK
 *
 * @filesource
 * @license MIT
 * @copyright  2013 - 2018 Cross Solution <http://cross-solution.de>
 */

/* @var \Core\View\Helper\Proxy\HelperProxy $wp */
$wp = $this->proxy('wordpress');

$this->headTitle($wp->chain(['page' => 586, 'value' => ['title.rendered']], 'Kontakt'));

?>

      <nav aria-label="breadcrumb">
        <ol class="breadcrumb" itemscope="" itemtype="http://schema.org/BreadcrumbList">
            <li class="breadcrumb-item" itemprop="itemListElement" itemscope="" itemtype="http://schema.org/ListItem">
                <a itemprop="item" href="/">
                    <span itemprop="name">Home</span>
                </a>
                <meta itemprop="position" content="1">
            </li>
            <li class="breadcrumb-item" itemprop="itemListElement" itemscope="" itemtype="http://schema.org/ListItem">
                 <span itemprop="name"><?=$wp->call('value', ['title.rendered'])?></span>
                <meta itemprop="position" content="2">
            </li>
        </ol>
    </nav>

<div class="page-title">
<h1><?=$wp->call('value', ['title.rendered'])?></h1>
</div>
        
<?php if ($this->sent):?>
<div class="well well-lg">
    <p class="lead">Vielen Dank.</p>
    <p>Ihre Anfrage wurde erfolgreich an uns übermittelt.</p>
</div>
<?php else: ?>
    <div class="container">
        <?=$wp->call('value', ['content.rendered'])?>
    </div>
    <hr>
    <div class="">
        <?=$this->form($this->form)?>
    </div>
<?php endif ?>


