<?php
/**
 * YAWIK
 *
 * @filesource
 * @author    Carsten Bleek <bleek@cross-solution.de>
 * @copyright 2013-2017 Cross Solution (http://cross-solution.de)
 * @version   GIT: $Id$
 * @license   https://yawik.org/LICENSE.txt MIT
 */
?>
<footer id="footer">
<div class="container">
        
  <div class="row">
    <div class="col-md-3">
        <a class="text-center facebook" title="Gastrojob24.ch bei Facebook" href="https://www.facebook.com/gastrojob24.ch/" target="_blank" rel="ugc"><i class="fa fa-facebook"></i></a>
        <ul class="footer-link">
            <li>&copy; <?=date('Y')?> Alle Rechte vorbehalten</li>
            <li>Mit <i class="fa fa-heart"></i> im Thurgau entwickelt </li>
        </ul>
    </div>
    <div class="col-sm-12 col-md-9">
        <div class="col-xs-6 col-sm-4 col-md-4">
            <strong>Für Jobsuchende</strong>
            <ul class="footer-link">

                <li><a title="Küche Jobs" href="/de/jobs/kueche.html">Küche Jobs</a></li>
                <li><a title="Hauswirtschaft Jobs" href="/de/jobs/housekeeping.html">Hauswirtschaft Jobs</a></li>
                <li><a title="Service Jobs" href="/de/jobs/service.html">Service Jobs</a></li>
                <li><a title="Administration Jobs" href="/de/jobs/administration-verkauf.html">Administration Jobs</a></li>
                <li><a title="Hotel Jobs" href="/de/jobs/hotel.html">Hotel Jobs</a></li>
                <li><a title="Food Jobs" href="/de/jobs/food.html">Food Jobs</a></li>
                <li><a title="Teilzeit Jobs" href="/de/jobs/teilzeit.html">Teilzeit Jobs</a></li>
                <li><a title="Management Jobs" href="/de/jobs/manager.html">Management Jobs</a></li>
                <li><a title="Tourismus Jobs" href="/de/jobs/touristik.html">Tourismus Jobs</a></li>
            </ul>


        </div>

        <div class="col-xs-6 col-sm-4 col-md-4">

            <strong>Für Arbeitgeber</strong>
            <ul class="footer-link">
                <li><a title="Login" href="/de/login">Login</a></li>
                <li><a title="Einzelinserat schalten" href="/de/job/single">Einzelinserat schalten</a></li>
                <li><a title="Flatrate Job-Abo" href="/de/auth/register">Flatrate Job-Abo</a></li>
                <li><a title="Geld-zurück-Garantie" href="/de/geld-zurueck-garantie.html">60 Tage Geld-zurück-Garantie</a></li>
                <li><a title="Job-Crawler" href="/de/crawler">Job-Crawler</a></li>
                <li><a title="Employer Branding" href="/de/branding.html">Employer Branding</a></li>
            </ul>
        </div>
        <div class="col-xs-12 col-sm-4 col-md-4">

            <strong>Allgemein</strong>

            <ul class="footer-link">

                    <li><a title="Kontakt" href="<?= $this->url('lang/wordpress', ['id' => 'contact'], true)?>">Kontakt</a></li>
                    <li><a title="Über uns" href="<?= $this->url('lang/wordpress', ['id' => 'ueber-uns'], true)?>">Über uns</a></li>
                    <li><a title="Impressum" href="<?= $this->url('lang/wordpress', ['id' => 'impressum'], true)?>">Impressum</a></li>
                    <li><a title="Datenschutz" href="<?= $this->url('lang/wordpress', ['id' => 'datenschutz'], true)?>">Datenschutz</a></li>
                    <li><a title="AGB" href="<?= $this->url('lang/wordpress', ['id' => 'agb'], true)?>">AGB</a></li>

            </ul>


        </div>
    </div>
  </div>
        
</div>
</footer>