<?php
/**
 * YAWIK
 *
 * @filesource
 * @author    Carsten Bleek <bleek@cross-solution.de>
 * @copyright 2013-2017 Cross Solution (http://cross-solution.de)
 * @version   GIT: $Id$
 * @license   https://yawik.org/LICENSE.txt MIT
 */
?>
<footer id="footer">
    <div class="container">
        <div class="row">
            <div class="col-xs-6 col-md-2">
                <strong style="color:#fff" class="h5">Über Gastrojob24</strong>
                <nav>
                    <ul class="list-unstyled">
                        <li><a title="Über Gastrojob24" href="<?= $this->url('lang/wordpress', ['id' => 'ueber-uns'], true)?>">Über uns</a></li>
                        <li><a title="Impressum" href="<?= $this->url('lang/wordpress', ['id' => 'impressum'], true)?>">Impressum</a></li>
                        <li><a title="AGB" href="<?= $this->url('lang/wordpress', ['id' => 'agb'], true)?>">AGB</a></li>
                        <!--<li><a title="Jobs durchsuchen" href="<?= $this->url('lang/wordpress', ['id' => 'jobs-durchsuchen'], true)?>">Jobs durchsuchen</a></li>-->
                        <li><a title="Jobs im Gastro" href="/de/jobs?clear=1">Jobs im Gastro</a></li>
                        
                    </ul>
                </nav>
            </div>
            <div class="col-xs-6 col-md-2">
                <strong style="color:#fff" class="h5">Social Media</strong>
                <nav>
                    <ul class="list-unstyled">
                        <li><a title="Gastrojob24.ch bei Facebook" href="https://www.facebook.com/gastrojob24.ch/" target="_blank" rel="ugc">Facebook</a></li>

                    </ul>
                </nav>
            </div>
            <div class="col-xs-6 col-md-2">
                <strong style="color:#fff" class="h5">Für Arbeitgeber</strong>
                <nav>
                    <ul class="list-unstyled">
                        
                         <li><a title="Kontakt" href="<?= $this->url('lang/wordpress', ['id' => 'contact'], true)?>">Kontakt</a></li>
                         <li><a title="Häufige Fragen & Antworten" href="<?= $this->url('lang/wordpress', ['id' => 'faq'], true)?>">Hilfe</a></li>
                        <?php if (!$this->auth()->isLoggedIn()):?>
                        <li><a title="Login für Arbeitgeber" href="<?=$this->url('lang/auth', [], true)?>?ref=<?= urlencode($this->url('lang/dashboard', [], true)) ?>">Einloggen</a></li>
                        <?php endif ?>
                        <?php if (!$this->auth()->isLoggedIn()):?> <li><a title="Inserieren" href="<?= $this->url('lang/wordpress', ['id' => 'stellenanzeigen-schalten'], true)?>">Inserieren</a></li>   <?php endif ?>
                    </ul>
                </nav>
            </div>
            <!--<div class="col-md-offset-3 col-md-3">
                <?php #$this->languageSwitcher()?>
            </div>-->
        </div>

        <hr style="border-top: 1px solid #b6bed6">
        <div class="row">
            <div class="col-md-12 text-center">
               <p>&copy; <?=date('Y')?> Alle Rechte vorbehalten <strong>Gastrojob24 Schweiz</strong> </p>
            </div>
        </div>
</footer>