<?php
/**
 * Gastrojobs24
 *
 * General layout template file. Defines the general layout.
 *
 * @copyright (c) 2013 - 2016 Cross Solution (http://cross-solution.de)
 * @license   Gastrojobs
 */

/* @var $options \Core\Options\ModuleOptions */
$options = $this->services('Core/Options');
$lang = $this->params('lang');

$routeParams = $this->params()->fromRoute();
$routeClass = '';
if (isset($routeParams['controller']) && isset($routeParams['action'])) {
    $routeClass = strtolower(str_replace(['/', '\\'], '-', $routeParams['controller'] . '-' . $routeParams['action']));
}

// check for preview
$preview = false;
if (isset($routeParams['isPreview']) && $routeParams['isPreview']) {
    $preview = true;
}

// See: http://yawik.readthedocs.org/en/latest/modules/core/notifications.html
$notifications = $this->partial('core/notifications');
// set default page title
$this->headTitle($this->translate('Gastrojob24'))->setSeparator(' - ')->setAutoEscape(false);

// set default keywords
$this->headMeta()->setCharset("utf-8");
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0')->setAutoEscape(false);

$this->headLink()->prependStylesheet($this->basePath($this->asset('modules/Gastro24/Gastro24.css')))->setAutoEscape(false);
$this->headLink()->prependStylesheet($this->basePath($this->asset('dist/css/jquery-ui-1-12.min.css')))
    ->prependStylesheet($this->basePath('dist/css/core.min.css'));
$this->headLink()->appendStylesheet($this->basePath('/modules/Gastro24/jssocials-1.4.0/dist/jssocials.css'))
    ->appendStylesheet($this->basePath('/modules/Gastro24/jssocials-1.4.0/dist/jssocials-theme-flat.css'));

$savedJobsContainer = new \Zend\Session\Container('gastro24_savedjobs');
$savedJobsCount = ($savedJobsContainer->jobs) ? count($savedJobsContainer->jobs) : 0;
?>

<?php echo $this->doctype(); ?>
<html lang="<?php echo $this->params('lang') ?>">
<head prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# website: http://ogp.me/ns/website#">
    <link rel="icon" type="image/png" sizes="32x32" href="<?=$this->basepath('modules/Gastro24/favicons/favicon-32x32_1_.png')?>">
    <link rel="icon" type="image/png" sizes="16x16" href="<?=$this->basepath('modules/Gastro24/favicons/favicon-16x16_1_.png')?>">
    <link rel="shortcut icon" type="image/ico" href="<?=$this->basepath('modules/Gastro24/favicons/favicon_1_.ico')?>">
    <meta name="msapplication-TileColor" content="#2e5b93">
    <meta name="theme-color" content="#2e5b93">
    <?php echo $this->headTitle() ?>
    <?php echo $this->headMeta() ?>
    <?php echo $this->headLink() ?>
    <?php echo $this->headStyle() ?>
    <meta name="msvalidate.01" content="2A03FA2A5360A355DD3ECEB3DF29DFA3" />

    <?php if ($this->params()->fromRoute('isLandingPage')):?>
      
    <?php endif ?>

    <script>
        var lang="<?= $this->params('lang') ?>"; var basePath="<?= $this->basePath() ?>";
    </script>
    
    <link rel="preconnect" href="https://www.facebook.com" crossorigin>
    <link rel="dns-prefetch" href="https://www.facebook.com">
    <link rel="preconnect" href="https://connect.facebook.net" crossorigin>
    <link rel="dns-prefetch" href="https://connect.facebook.net">
    <link rel="preconnect" href="https://static.ak.facebook.com" crossorigin>
    <link rel="dns-prefetch" href="https://static.ak.facebook.com">
    <link rel="preconnect" href="https://static.ak.fbcdn.net" crossorigin>
    <link rel="dns-prefetch" href="https://static.ak.fbcdn.net">
    <link rel="preconnect" href="https://s-static.ak.facebook.com" crossorigin>
    <link rel="dns-prefetch" href="https://s-static.ak.facebook.com">
    <link rel="preconnect" href="https://www.google.com" crossorigin>
    <link rel="dns-prefetch" href="https://www.google.com">
    <link rel="preconnect" href="https://www.googletagmanager.com" crossorigin>
    <link rel="dns-prefetch" href="https://www.googletagmanager.com">
    <link rel="preconnect" href="https://www.google-analytics.com" crossorigin>
    <link rel="dns-prefetch" href="https://www.google-analytics.com">
    
    <!-- Google Tag Manager -->
    <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
            new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
            j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
            'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
        })(window,document,'script','dataLayer','GTM-MCDJ26Q');</script>
    <!-- End Google Tag Manager -->
    
<style>
    .featured-image-box {
        padding: 12px 12px 19px 12px;
        overflow: hidden
    }

    .box__job-favorite .h3 {
        font-size: 19px;
        line-height: 1.3;
        font-weight: 300;
        margin-bottom: 5px
    }

    .box__job-short-info .wrapper__right .wrapper__logo img {
        width: 100%;
        padding: 10px
    }

    .featured-image-box .box__job-short-info ul li {
        font-size: 12px !important;
        margin-bottom: 2px;
        line-height: 2rem
    }

    .featured-image-box .box__job-short-info {
        margin: 0
    }

    .navbar-search-container-mobile form .input-group:nth-child(2) {
        width: 66.66666667%;
        float: left
    }

    .navbar-search-container-mobile form .input-group:nth-child(3) {
        width: 33.33333333%;
        float: left
    }

    .navbar-search-container-mobile form .select2-selection {
        border-radius: 0
    }

    .navbar-search-container-mobile .form-control {
        -webkit-border-radius: 0 !important;
        -moz-border-radius: 0 !important;
        border-radius: 0 !important;
        height: 36px !important
    }

    .teaser__job-detail .corner {
        right: -100px !important;
        top: 55px !important
    }

    .navbar-header .menu-logo {
        width: 200px
    }

    .featured-image-box, .panel__job-detail {
        position: relative
    }

    .featured-image-box .corner {
        width: 0;
        height: 0;
        border-top: 40px solid #60a5d1;
        border-bottom: 40px solid transparent;
        border-left: 40px solid transparent;
        position: absolute;
        right: 0;
        top: -1px
    }

    .featured-image-box .corner span {
        color: #fff;
        position: absolute;
        top: -33px;
        width: 40px;
        left: -35px;
        text-align: center;
        font-size: 10px;
        font-family: arial;
        transform: rotate(45deg);
        display: block
    }

    .panel__job-detail .corner {
        width: 0;
        height: 0;
        border-top: 60px solid #60a5d1;
        border-bottom: 60px solid transparent;
        border-left: 60px solid transparent;
        position: absolute;
        right: 0
    }

    .panel__job-detail .corner span {
        color: #fff;
        position: absolute;
        top: -47px;
        width: 75px;
        left: -60px;
        text-align: center;
        font-size: 12px;
        font-family: arial;
        transform: rotate(45deg);
        display: block
    }

    .fa-search:before {
        font-family: FontAwesome
    }

    .navbar-search-container-mobile {
        background-color: #0b2235
    }

    .navbar-search-container-mobile .btn-default {
        display: none
    }

    .navbar-search-container-mobile .search-form {
        padding: 15px 0
    }

    .navbar-search-container-mobile .input-group:first-child {
        margin-bottom: 15px
    }

    .navbar-search-container-mobile .btn-group {
        margin-top: 15px
    }

    .navbar-search-container-mobile .btn-group, .navbar-search-container-mobile .btn-group .btn-primary {
        width: 100%
    }

    #wizardcontainer-jobs-form-categoriescontainer .nav .active a, #wizardcontainer-jobs-form-job .nav .active a, #yk-login .nav .active a {
        color: #fff
    }

    #jobsbymail-subscribe-form .row {
        margin-bottom: 10px
    }

    iframe {
        border: 0
    }

    #form-jobs-form-preview .panel-body {
        padding: 0 !important
    }

    #main-navigation ul li a.inverted {
        background-color: #fff;
        color: #243b84
    }

    #main-navigation ul li a.inverted:hover {
        color: #fff
    }

    .navbar-toggle {
        border-color: #242424 !important;
        background-color: #243b84 !important
    }

    .navbar-toggle .icon-bar {
        background-color: #fff
    }

    main#content {
        background-color: #f2f2f2;
        margin-bottom: 0;
        padding-bottom: 50px;
        min-height: 65vh;
        padding-top: 10px;
        position: relative
    }

    .panel__job-detail {
        margin-bottom: -50px !important
    }

    #rpt_pricr .btn {
        border-color: #dcdfe2;
        color: #243b84;
        background-color: #fff;
        padding: 8px 0;
        border-radius: 3px
    }

    .rpt_3_plans .rpt_plan_1 {
        box-shadow: 1px 5px 9px 2px #ddd
    }

    .rpt_3_plans .rpt_plan_1 .btn {
        color: #fff !important;
        background-color: #d9534f !important;
        border-color: #d9534f
    }

    .rpt_3_plans .rpt_plan_1::before {
        content: "Bestseller";
        background-color: #d9534f;
        color: #fff;
        line-height: 42px;
        display: block;
        font-size: 15px;
        text-decoration: none;
        cursor: pointer;
        position: absolute;
        left: 15px;
        top: -41px;
        text-transform: uppercase;
        right: 15px;
        font-weight: 700;
        height: 41px;
        border-top-left-radius: 3px;
        border-top-right-radius: 3px
    }

    #rpt_pricr {
        margin-top: 75px
    }

    main ul.column {
        padding-left: 0;
        list-style-type: none;
        -webkit-column-count: 3;
        -moz-column-count: 3;
        column-count: 3
    }

    main ul.column li a {
        text-decoration: underline;
        color: #22436c
    }

    .wp-block-columns.has-2-columns.contact-column .wp-block-column:first-child {
        float: left;
        width: 70%;
        border-right: 1px solid #ccc
    }

    .wp-block-columns.has-2-columns.contact-column .wp-block-column:last-child {
        float: left;
        width: 30%;
        padding: 0 15px
    }

    .wp-block-column li {
        list-style-type: none
    }

    .wp-block-column a {
        text-decoration: underline;
        color: #22436c
    }

    .navbar {
        border: none
    }

    #meta-navigation .dropdown-menu > li > a {
        display: block;
        width: 100%;
        padding: 10px 12px 12px
    }

    .search-form-container {
        padding: 0
    }

    .breadcrumb > li + li:before {
        color: #000;
        content: ">"
    }

    #job_content p {
        margin-bottom: 25px
    }

    #job_content p a {
        color: #243b84;
        text-decoration: underline
    }

    #job_content ul {
        margin-left: 20px;
        margin-bottom: 25px
    }

    #job_content ul li {
        margin-bottom: 5px
    }

    #job_content h1 {
        font-size: 24px;
        line-height: 36px;
        font-weight: 600;
        color: #000
    }

    #job_content h3 {
        font-size: 16px;
        color: #000
    }

    #job_content h2 {
        font-size: 24px;
        line-height: 36px;
        color: #000;
        font-weight: 600
    }

  
    .bg-wp-content hr {
        margin-bottom: 50px !important
    }

    .bg-wp-content li, .bg-wp-content p {
        font-size: 16px;
        line-height: 24px
    }

    .bg-wp-content h1 {
        font-size: 34px
    }

    .bg-wp-content img {
        width: 100%
    }

    #footer {
        position: absolute;
        left: 0;
        right: 0
    }

    @media (max-width: 768px) {
        .apply-button-group .favorite-button {
            width: 40px
        }

        .apply-button-group .favorite-button:before {
            padding-right: 0
        }

        .teaser__job-detail .corner {
            right: -25px !important
        }

        .search-form-container.search-form-container__header .container .search-form {
            display: none;
        }

        .search-form-container {
            padding: 15px 0
        }

        .page-title h1, .page-title span {
            display: inline;
            font-size: 24px;
            font-weight: 300
        }

        .page-title {
            margin-top: 0;
            margin-bottom: 10px
        }

        .jobmail-listings {
            margin-bottom: 20px
        }

        .navbar-collapse {
            border-top: none
        }

        .navbar-brand > img {
            width: 122px;
            position: absolute;
            left: 45px;
            top: 15px
        }

        .search-form-container {
            padding: 0 !important
        }

        .nav > li {
            border-bottom: none !important
        }

        .badge {
            margin: 0 !important
        }

        .search-form-container.search-form-container__header .container form {
            width: 100%
        }

        .search-form-container__header form.search-form .row > div:first-child {
            margin-bottom: 10px
        }

        .search-form-container__header form.search-form .row div:nth-child(2) {
            width: 66.66666667%;
            margin-bottom: 10px
        }

        .search-form-container__header form.search-form .row div:nth-child(3) {
            width: 33.33333333%;
            margin-bottom: 10px
        }


        main ul.column {
            -webkit-column-count: 1;
            -moz-column-count: 1;
            column-count: 1
        }

        .navbar-nav2 {
            margin: 0;
            width: 100%
        }

        .navbar-nav > li > a:hover {
            color: #fff
        }

        #main-navigation .dropdown-menu > li > a:hover, #main-navigation a:hover {
            color: #fff !important
        }

        #main-navigation ul li a.inverted:hover {
            color: #000 !important
        }

        .navbar-collapse {
            box-shadow: none !important
        }

        #main-navigation .dropdown-menu > li > a {
            color: #000 !important
        }

        .navbar-nav .open .dropdown-menu .dropdown-header, .navbar-nav .open .dropdown-menu > li > a {
            padding: 8px 15px 8px 45px !important
        }

        .nav > li {
            border-bottom: 1px solid #ddd
        }
    }

    #meta-navigation .navbar-nav2 > .dropdown {
        display: table
    }

    #meta-navigation .navbar-nav2 > .dropdown > .dropdown-toggle {
        padding: 0 !important;
        height: 52px;
        width: 48px;
        display: table-cell;
        vertical-align: middle
    }

    .navbar-nav2 > .dropdown > .dropdown-toggle:hover {
        background-color: #0b2235
    }

    .navbar-nav2 > .dropdown.open > .dropdown-toggle {
        background-color: #0b2235
    }

    #meta-navigation {
        padding: 0
    }

    #meta-navigation .dropdown-submenu {
        position: relative
    }

    #meta-navigation .dropdown-submenu > .dropdown-menu {
        top: 0;
        left: 100%;
        margin-top: -6px;
        margin-left: -1px;
        -webkit-border-radius: 0 6px 6px 6px;
        -moz-border-radius: 0 6px 6px;
        border-radius: 0 6px 6px 6px
    }

    #meta-navigation .dropdown-submenu > .dropdown-menu {
        left: 0;
        margin-top: 40px;
        margin-left: 0;
        -webkit-border-radius: 0;
        -moz-border-radius: 0 6px 6px;
        border-radius: 0
    }

    #meta-navigation .dropdown.dropdown-submenu.open, #meta-navigation .dropdown.dropdown-submenu.open > .dropdown-menu {
        width: 400px
    }

    #meta-navigation .dropdown .reveal:not(.open) {
        max-height: 0;
        opacity: 0;
        overflow: hidden
    }

    .dropdown-menu > li > a:focus, .dropdown-menu > li > a:hover {
        background: #e5e5e5;
        color: #0b2235
    }

    #meta-navigation .dropdown > li > .reveal {
        box-shadow: none
    }

    #meta-navigation .dropdown-submenu > a:after {
        display: block;
        content: " ";
        float: right;
        width: 0;
        height: 0;
        border-color: transparent;
        border-style: solid;
        border-width: 5px 0 5px 5px;
        border-left-color: #ccc;
        margin-top: 5px;
        margin-right: -10px
    }

    #meta-navigation .dropdown-submenu:hover > a:after {
        border-left-color: #fff
    }

    #meta-navigation .dropdown-submenu.pull-left {
        float: none
    }

    #meta-navigation .divider.reveal {
        display: none
    }

    #meta-navigation .navbar-nav2 > li > .dropdown-menu {
        margin-top: 3px;
        left: 3px;
        min-width: 200px;
        background-color: #0b2235
    }

    #meta-navigation .dropdown-menu .divider {
        margin: 0
    }

    #meta-navigation .navbar-nav2 > li > .dropdown-menu > li > a {
        color: #fff
    }

    #meta-navigation .dropdown-submenu.pull-left > .dropdown-menu {
        left: -100%;
        margin-left: 10px;
        -webkit-border-radius: 6px 0 6px 6px;
        -moz-border-radius: 6px 0 6px 6px;
        border-radius: 6px 0 6px 6px
    }

    #meta-navigation .dropdown.dropdown-submenu.open .dropdown-menu {
        -webkit-column-count: 2;
        -moz-column-count: 2;
        column-count: 2;
        -webkit-column-gap: 0;
        -moz-column-gap: 0;
        column-gap: 0;
        max-height: none;
        box-shadow: rgba(0, 0, 0, .2) 0 1px 2px;
        -webkit-perspective: 1;
        width: 400px
    }

    #meta-navigation .dropdown.dropdown-submenu.open .dropdown-menu li {
        display: -webkit-inline-box;
        display: -ms-inline-flexbox;
        display: inline-flex;
        width: 200px;
        padding: 0
    }

    #meta-navigation .dropdown-submenu.open > a:before {
        display: block;
        content: " ";
        float: left;
        width: 0;
        height: 0;
        border-color: transparent;
        border-style: solid;
        border-width: 5px 0 5px 5px;
        border-left-color: #fff;
        margin-top: 5px;
        margin-right: 10px;
        transform: rotate(180deg)
    }

    #meta-navigation .dropdown-submenu.open > a:after {
        display: none
    }

    #meta-navigation .open .dropdown-menu {
        padding: 0;
        border: none;
        border-radius: 0
    }

    #meta-navigation .open.dropdown-submenu {
        padding: 0;
        border: none;
        border-radius: 0;
        box-shadow: none;
        background: #0b2235 !important
    }

    #meta-navigation li.open .dropdown-menu .dropdown-submenu {
        padding: 0
    }

    #meta-navigation .open.dropdown-submenu > a.dropdown-toggle {
        color: #fff;
        line-height: 20px;
        height: 40px
    }

    .icon-bar {
        background-color: #fff
    }

    .icon-bar {
        display: block;
        margin-bottom: 3px;
        width: 22px;
        height: 2px;
        margin-left: 12px;
        border-radius: 1px;
        -webkit-transition-duration: .35s;
        -moz-transition-duration: .35s;
        -o-transition-duration: .35s;
        transition-duration: .35s
    }

    .middle-bar {
        opacity: 1
    }

    #meta-navigation .navbar-nav2 > .dropdown.open > .dropdown-toggle .middle-bar {
        opacity: 0;
        margin-top: 2px
    }

    #meta-navigation .navbar-nav2 > .dropdown.open > .dropdown-toggle .top-bar {
        -ms-transform: rotate(45deg);
        -ms-transform-origin: 15% 10%;
        -webkit-transform: rotate(45deg);
        -webkit-transform-origin: 15% 10%;
        transform: rotate(45deg);
        transform-origin: 15% 10%;
        -webkit-transition-duration: .35s;
        -moz-transition-duration: .35s;
        -o-transition-duration: .35s;
        transition-duration: .35s;
        margin-left: 15px
    }

    #meta-navigation .navbar-nav2 > .dropdown.open > .dropdown-toggle .bottom-bar {
        -webkit-transform: rotate(-45deg);
        -webkit-transform-origin: 15% 90%;
        -ms-transform: rotate(-45deg);
        -ms-transform-origin: 15% 90%;
        transform: rotate(-45deg);
        transform-origin: 15% 90%;
        -webkit-transition-duration: .35s;
        -moz-transition-duration: .35s;
        -o-transition-duration: .35s;
        transition-duration: .35s;
        margin-top: 2px;
        margin-left: 15px
    }

    #meta-navigation .dropdown .jobs {
        display: block
    }

    #meta-navigation .dropdown-submenu > a:after {
        display: block;
        content: " ";
        float: right;
        width: 0;
        height: 0;
        border-color: transparent;
        border-style: solid;
        border-width: 5px 0 5px 5px;
        border-left-color: #fff;
        margin-top: 5px;
        margin-right: 0
    }

    #meta-navigation .dropdown-login:not(.reveal) {
        padding: 5px
    }

    #meta-navigation .dropdown-login > a {
        background: #e5e5e5;
        color: #0b2235 !important
    }

    #meta-navigation .dropdown-submenu:not(.open) > a:focus, #meta-navigation .dropdown-submenu:not(.open) > a:hover {
        background: #e5e5e5;
        color: #0b2235 !important
    }

    @media only screen and (max-width: 768px) {
        .dropdown-menu-mobile {
            margin-top: 0;
        }
    }

    @media (max-width: 480px) {
        .embed-container {
            margin-left: -15px;
            margin-right: -15px
        }

        .panel__job-detail h1.no-banner {
            max-width: 90%
        }

        .row {
            margin-right: -12px;
            margin-left: -12px
        }

        .panel__job-detail .panel-body {
            padding: 0 1.5rem 1.5rem 1.5rem
        }

        .panel__job-detail h1.no-banner {
            margin-top: 15px;
            font-size: 22px;
            margin-bottom: 35px;
            line-height: 1.1
        }

        .panel__job-detail .job-short-info.no-banner {
            align-items: flex-start;
            margin-top: 15px
        }

        .container {
            padding-right: 12px;
            padding-left: 12px;
            margin-right: auto;
            margin-left: auto
        }

        .jssocials {
            padding-bottom: 0
        }

        .panel__job-detail .panel-body .button-job-apply {
            margin-bottom: 2px
        }

        .teaser__job-detail .corner {
            top: 40px !important;
            right: -16px !important
        }

        .apply-button-group button {
            margin-bottom: 4px
        }

        .col-lg-1, .col-lg-10, .col-lg-11, .col-lg-12, .col-lg-2, .col-lg-3, .col-lg-4, .col-lg-5, .col-lg-6, .col-lg-7, .col-lg-8, .col-lg-9, .col-md-1, .col-md-10, .col-md-11, .col-md-12, .col-md-2, .col-md-3, .col-md-4, .col-md-5, .col-md-6, .col-md-7, .col-md-8, .col-md-9, .col-sm-1, .col-sm-10, .col-sm-11, .col-sm-12, .col-sm-2, .col-sm-3, .col-sm-4, .col-sm-5, .col-sm-6, .col-sm-7, .col-sm-8, .col-sm-9, .col-xs-1, .col-xs-10, .col-xs-11, .col-xs-12, .col-xs-2, .col-xs-3, .col-xs-4, .col-xs-5, .col-xs-6, .col-xs-7, .col-xs-8, .col-xs-9 {
            padding-right: 12px;
            padding-left: 12px
        }

        #menu {
            padding-left: 3px
        }
    }
</style>
  
</head>
<body class="<?= $routeClass ?>">
<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-MCDJ26Q"
                  height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->
<?php if (!$this->noHeader):?>
    <header id="header" role="banner" class="hidden-xs" data-saved-jobs="<?=$savedJobsCount?>">
        <div class="container">
            <?php if ($this->auth('role') === Auth\Entity\User::ROLE_RECRUITER) : ?>
                <div class="row">
                    <div class="col-12 text-right header-link">
                        <a class="link--inverted"
                           href="<?php echo $this->url('lang/jobs/manage', array('action' => 'edit'), true) ?>">
                            Stellenanzeige anlegen
                        </a>
                    </div>
                </div>
            <?php endif ?>
            <div class="row">
                <div class="navbar-header col-md-4">
                    <a class="logo" title="Gastrojob24" href="<?php echo $this->basepath('/' . $this->params('lang')) ?>">
                        <img src="<?php echo $this->basepath('/modules/Gastro24/gastrojob24_blue.svg') ?>" alt="Gastrojob24 Logo">
                    </a>
                </div>
                <div class="col-md-8">
                    <?php if ('guest' == $this->auth('role')): ?>
                        <ul class="pull-right navbar-nav nav-recruiting">
                            <li class="nav-item">
                                <?php if ($this->auth('role') === Auth\Entity\User::ROLE_RECRUITER) : ?>
                                    <a title="Stellenanzeige anlegen" href="<?php echo $this->url('lang/jobs/manage', array('action' => 'edit'), true) ?>"
                                       class="px-md-2 px-lg-3 px-xl-4 btn btn-danger nav-link text-white text-decoration-none">Stellenanzeige anlegen</a>
                                <?php else : ?>
                                    <a title="Anzeige schalten" href="<?= $this->url('lang/wordpress', ['id' => 'stellenanzeigen-schalten'], true)?>"
                                       class="px-md-2 px-lg-3 px-xl-4 btn btn-danger nav-link text-white text-decoration-none">Anzeige schalten</a>
                                <?php endif ?>
                            </li>
                            <li class="nav-item dropdown">
                                <a title="Anmelden" href="#" class="login-link nav-link text-reset _dropdown-toggle text-decoration-none" data-toggle="dropdown" aria-expanded="false"><i class="fa fa-user"></i></a>
                                <ul class="dropdown-menu dropdown-menu-right">
                                    <li class="nav-item">
                                        <?= $this->partial('partials/login-popup.phtml', ['device' => 'desktop']); ?>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    <?php else: ?>
                        <nav id="main-navigation" class="navbar-collapse collapse navbar-collapse" role="navigation">
                            <?= $this->loginInfo(array('lang' => $lang ));?>
                            <?= $this->navigation('Core/Navigation')
                                ->setAcl($this->services('acl'))
                                ->setRole($this->auth('role'))
                                ->menu()
                                ->setMaxDepth(0) // only show the top level entries
                                ->renderPartial(null, 'main-navigation');
                            ?>
                        </nav>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </header>
<?php endif ?>

<!-- search form container -->
<?= $this->partial('partials/search-form-container.phtml', [
    'jobs' => $this->jobs,
    'filterForm' => $this->filterForm,
    'cssClass' => $preview ? 'searchform-preview' : '',
]); ?>
<!-- end search form container -->

<main id="content" class="<?= $routeClass ?>">
   <div class="container">
    <?php echo $notifications?>
     <?php echo $this->content;?>
  </div>
</main>

<?php if (!$this->noFooter): echo $this->partial("footer"); endif; ?>
<!-- lazy loaded javascript -->
<?php
    $langScript = 'dist/locales/' . $lang . '.js';
    echo $this->inlineScript()->setAutoEscape(false)->appendFile($this->basepath($this->asset('dist/js/core.min.js')))
        ->appendFile($this->basePath('/dist/js/jquery-ui-1-12.min.js'))
        ->appendFile($this->basePath($this->asset('modules/Gastro24/js/index-main.min.js')))
        ->appendFile($this->basePath($langScript))
        ->appendFile($this->basePath($this->asset('modules/Gastro24/js/jobs.search.js')));

    echo $this->configHeadScript()->setAutoEscape(false);
?>
<!-- end lazy loaded javascript -->
<script>
    $(document).ready(function() {
        $('ul.dropdown-menu [data-toggle=dropdown2]').on('click', function(event) {
            event.preventDefault();
            event.stopPropagation();

            $(this).parent().siblings().removeClass('open');
            $(this).parent().siblings().toggleClass('reveal');
            $(this).parent().toggleClass('open');
        });
    });

    (function( $ ) {
        'use strict';

        /**
         * FAQs Toggles
         */
        $(function() {
            $('.qe-toggle-title').click(function () {
                var parent_toggle = $(this).closest('.qe-faq-toggle');
                if ( parent_toggle.hasClass( 'active' ) ) {
                    $(this).find('i.fa').removeClass( 'fa-minus-circle' ).addClass( 'fa-plus-circle' );
                    parent_toggle.removeClass( 'active' ).find( '.qe-toggle-content' ).slideUp( 'fast' );
                } else {
                    $(this).find('i.fa').removeClass( 'fa-plus-circle' ).addClass( 'fa-minus-circle' );
                    parent_toggle.addClass( 'active' ).find( '.qe-toggle-content' ).slideDown( 'fast' );
                }
            });
        });

        /**
         * FAQs Filter
         */
        $(function() {
            $('.qe-faqs-filter').click( function ( event ) {
                event.preventDefault();
                $(this).parents('li').addClass('active').siblings().removeClass('active');
                var filterSelector = $(this).attr( 'data-filter' );
                var allFAQs = $( '.qe-faq-toggle' );
                if ( filterSelector == '*' ) {
                    allFAQs.show();
                } else {
                    allFAQs.not( filterSelector ).hide().end().filter( filterSelector ).show();
                }
            });
        });
	
	 
	
        window.addEventListener('scroll', function(e) {
            if( isOnScreen( jQuery( '.apply-button-group' ).not('.first') ) ) {
                $('.apply-button-group.first').hide();
            }
            else {
                $('.apply-button-group.first').show();
            }
        });

        function isOnScreen(elem) {
            // if the element doesn't exist, abort
            if( elem.length == 0 ) {
                return;
            }
            var $window = jQuery(window)
            var viewport_top = $window.scrollTop()
            var viewport_height = $window.height()
            var viewport_bottom = viewport_top + viewport_height
            var $elem = jQuery(elem)
            var top = $elem.offset().top
            var height = $elem.height()
            var bottom = top + height

            return (top >= viewport_top && top < viewport_bottom) ||
                (bottom > viewport_top && bottom <= viewport_bottom) ||
                (height > viewport_height && top <= viewport_top && bottom >= viewport_bottom)
        };

        $('#jobs-list-container').on('yk-paginator-container:loaded.gastro24 g24-jobs:init', function(ev) {
            $(".shareMail").each(function() {
                var link = $(this).data("url");
                var title = $(this).data("title");
                $(this).jsSocials({
                    url: link,
                    text: title,
                    showCount: true,
                    shares: ["email"]
                });
            });
            $(".shareWhatsapp").each(function() {
                var link = $(this).data("url");
                var title = $(this).data("title");
                $(this).jsSocials({
                    url: link,
                    text: title,
                    showLabel: false,
                    showCount: true,
                    shares: ["whatsapp"]
                });
            });
        });
    })( jQuery );
</script>
</body>
</html>
