<?php
/**
 * Gastrojobs24
 *
 * General layout template file. Defines the general layout.
 *
 * @copyright (c) 2013 - 2016 Cross Solution (http://cross-solution.de)
 * @license   Gastrojobs
 */

/* @var $options \Core\Options\ModuleOptions */
$options = $this->services('Core/Options');
$lang = $this->params('lang');

$routeParams = $this->params()->fromRoute();
$routeClass = '';
if (isset($routeParams['controller']) && isset($routeParams['action'])) {
    $routeClass = strtolower(str_replace(['/', '\\'], '-', $routeParams['controller'] . '-' . $routeParams['action']));
}

// check for preview
$preview = false;
if (isset($routeParams['isPreview']) && $routeParams['isPreview']) {
    $preview = true;
}

// See: http://yawik.readthedocs.org/en/latest/modules/core/notifications.html
$notifications = $this->partial('core/notifications');
// set default page title
$this->headTitle($this->translate('Gastrojob24'))->setSeparator(' - ')->setAutoEscape(false);

// set default keywords
$this->headMeta()->setCharset("utf-8");
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0')->setAutoEscape(false);

$this->headLink()->prependStylesheet($this->basePath($this->asset('modules/Gastro24/Gastro24.css')))->setAutoEscape(false);
$this->headLink()->prependStylesheet($this->basePath($this->asset('dist/css/jquery-ui-1-12.min.css')))
    ->prependStylesheet($this->basePath('dist/css/core.min.css'));

$savedJobsContainer = new \Laminas\Session\Container('gastro24_savedjobs');
$savedJobsCount = ($savedJobsContainer->jobs) ? count($savedJobsContainer->jobs) : 0;

// check for preview
$routeParams = $this->params()->fromRoute();
$preview = false;
if (isset($routeParams['isPreview']) && $routeParams['isPreview']) {
    $preview = true;
}
?>

<?php echo $this->doctype(); ?>
<html lang="<?php echo $this->params('lang') ?>">
<head prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# website: http://ogp.me/ns/website#">
    
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">
    
    <?php echo $this->headTitle() ?>
    <?php echo $this->headMeta() ?>
    <?php echo $this->headLink() ?>
    <?php echo $this->headStyle() ?>

    <!-- job json ld -->
    <?php if($this->job): ?>
        <?= $this->jsonLd($this->job); ?>
    <?php endif; ?>
    <!-- job json ld -->

    <meta name="msvalidate.01" content="2A03FA2A5360A355DD3ECEB3DF29DFA3" />

    <?php if ($this->params()->fromRoute('isLandingPage')):?>
      
    <?php endif ?>

    <script>
        var lang="<?= $this->params('lang') ?>"; var basePath="<?= $this->basePath() ?>";
    </script>
    
    <link rel="preconnect" href="https://www.google.com" crossorigin>
    <link rel="dns-prefetch" href="https://www.google.com">
    <link rel="preconnect" href="https://www.googletagmanager.com" crossorigin>
    <link rel="dns-prefetch" href="https://www.googletagmanager.com">
    <link rel="preconnect" href="https://www.google-analytics.com" crossorigin>
    <link rel="dns-prefetch" href="https://www.google-analytics.com">
    
<!-- Google Tag Manager -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-125791873-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'UA-125791873-1');
  gtag('config', 'AW-980688466');

</script>
  
    <!-- End Google Tag Manager -->
    
<?php if ($this->auth()->isLoggedIn() && !$preview):?>
    <!-- Start of  Zendesk Widget script -->
    <script id="ze-snippet" src="https://static.zdassets.com/ekr/snippet.js?key=2d241515-52bd-4381-8955-1cd82d61cf71"> </script>
    <!-- End of  Zendesk Widget script -->
<?php endif ?>
    
</head>
<body class="<?= $routeClass ?>" id="top">

<?php if (!$this->noHeader):?>
    <header id="header" role="banner" class="hidden-xs" data-saved-jobs="<?=$savedJobsCount?>">
        <div class="container">
            <div class="row">
                <div class="navbar-header col-md-2">
                    <a class="logo" title="Gastrojob24" href="<?php echo $this->basepath('/' . $this->params('lang')) ?>">
                        <img src="<?php echo $this->basepath('/modules/Gastro24/gastrojob24_white.svg') ?>" alt="Gastrojob24">
                    </a>
                </div>
                <div class="col-md-10">
                    <?php if ('guest' == $this->auth('role')): ?>
                        <ul class="pull-right navbar-nav nav-recruiting">
                            
                          <li class="nav-item">
                              <a title="Jobs" href="/de/jobs?clear=1" class="navigation-link-norm text-white">Jobs</a>
                            </li>
                             <li class="nav-item">
                              <a title="Firmen" href="/de/organizations/profile" class="navigation-link-norm text-white">Firmen</a>
                            </li>
                           <li class="nav-item">	   
                              <a title="Abo für Firmen" href="/de/auth/register" class="navigation-link-norm text-white">Abo für Firmen</a>
                           </li>
                           
                            <li class="nav-item">
                                <?php
                                $tooltip = ($savedJobsCount) ? (($savedJobsCount == 1) ? $this->translate('1 saved job') :
                                    sprintf($this->translate('%s saved jobs'), $savedJobsCount)) : $this->translate('No saved jobs');
                                ?>
                              <a title="Merkliste" href="<?= $this->url('lang/saved-jobs', [], true) ?>"
                                 class="navigation-link-norm text-white">Merkliste
                                  <?php if($savedJobsCount): ?>
                                  <div class="link__saved-jobs">
                                      <span class="badge badge-light" data-toggle="tooltip" data-placement="bottom" title="<?= $tooltip ?>">
                                          <?= $savedJobsCount ?>
                                      </span>
                                  </div>
                                  <?php else: ?>
                                      <div class="link__saved-jobs empty"></div>
                                  <?php endif; ?>
                              </a>
                           </li>
                           
                            <li class="nav-item">
                                <?php if ($this->auth('role') !== Auth\Entity\User::ROLE_RECRUITER) : ?>
                                    <a title="Inserieren" href="<?= $this->url('stellenanzeigen-schalten') ?>"
                                       class="px-md-2 px-lg-3 px-xl-4 btn btn-danger nav-link text-white text-decoration-none">Inserieren</a>
                                <?php endif ?>
                            </li>
                            <li class="nav-item dropdown">
                                <a title="Anmelden" href="#" class="login-link nav-link text-reset _dropdown-toggle text-decoration-none" data-toggle="dropdown" aria-expanded="false"><i class="login-icon-top"></i>
                                  <span>Login</span>
                                </a>
                                <ul class="dropdown-menu dropdown-menu-right">
                                    <li class="nav-item">
                                        <?= $this->partial('partials/login-popup.phtml', ['device' => 'desktop']); ?>
                                        <?= $this->partial('partials/password-reset.phtml', [
                                            'style' => 'display: none;',
                                            'device' => 'desktop'
                                        ]) ?>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    <?php else: ?>
                        <nav id="main-navigation" class="navbar-collapse collapse navbar-collapse" role="navigation">
                            <?= $this->loginInfo(array('lang' => $lang ));?>
                            <?= $this->navigation('Core/Navigation')
                                ->setAcl($this->services('acl'))
                                ->setRole($this->auth('role'))
                                ->menu()
                                ->setMaxDepth(0) // only show the top level entries
                                ->renderPartial(null, 'main-navigation');
                            ?>
                        </nav>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </header>
<?php endif ?>

<!-- search form container -->
<?= $this->partial('partials/search-form-container.phtml', [
    'jobs' => $this->jobs,
    'filterForm' => $this->filterForm,
    'cssClass' => $preview ? 'searchform-preview' : '',
]); ?>
<!-- end search form container -->

<main id="content" class="<?= $routeClass ?>">
   <div class="container">
    <?php echo $notifications?>
     <?php echo $this->content;?>
  </div>
</main>

<?php if (!$this->noFooter): echo $this->partial("footer"); endif; ?>
<!-- lazy loaded javascript-->
<?php
    $langScript = 'dist/locales/' . $lang . '.js';
    echo $this->inlineScript()->setAutoEscape(false)
        ->appendFile($this->basepath($this->asset('dist/js/core.min.js')))
        ->appendFile($this->basePath('/dist/js/jquery-ui-1-12.min.js'))
        ->appendFile($this->basePath($this->asset('modules/Gastro24/js/index-main.min.js')))
        ->appendFile($this->basePath($langScript))
        ->appendFile($this->basePath('dist/js/tinymce.js'))
        ->appendFile($this->basePath($this->asset('modules/Gastro24/js/jobs.search.js')));

    echo $this->configHeadScript()->setAutoEscape(false);
?>
<!-- end lazy loaded javascript -->
<script>
    $(document).ready(function() {
        $(document).on('click', function(e) {
            var $trigger = $('.dropdown-menu');
            if($trigger !== e.target && !$trigger.has(e.target).length) {
                $('.login-form-desktop').css('display', 'block');
                $('.reset-form-desktop').css('display', 'none');
                $('.login-form-mobile').css('display', 'block');
                $('.reset-form-mobile').css('display', 'none');
            }
        });

        $('a.link--reset-password').click(function(e) {
            e.stopPropagation();
            $('.login-form-desktop').css('display', 'none');
            $('.reset-form-desktop').css('display', 'block');
            $('.login-form-mobile').css('display', 'none');
            $('.reset-form-mobile').css('display', 'block');
        });
    });
</script>
</body>
</html>
