<?php
/**
 * YAWIK
 *
 * View template for the login status box.
 *
 * @copyright (c) 2013 - 2016 Cross Solution (http://cross-solution.de)
 * @license   MIT
 */
?>
<?php $switchUserSession = new \Zend\Session\Container(\Auth\Controller\Plugin\UserSwitcher::SESSION_NAMESPACE);
$lang = isset($this->lang)?$this->lang:$this->params('lang'); ?>
<ul id="yk-login-info" style="margin-left:-15px;" class="nav navbar-nav  navbar-collapse collapse navbar-right">
    <li class="dropdown">

        <?php if ($this->auth()->isLoggedIn()):?>

            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <?php if ($switchUserSession->isSwitchedUser): ?> [<?=$this->translate('switched')?>]<?php endif ?>
                (<?= $this->translate($this->acl()->getUser()->getRole())?>)
                <strong><?= $this->auth('info')->getDisplayName()?></strong>
                <b class="caret"></b>
            </a>

            <!-- submenu logged in -->
            <?= $this->partial('partials/logged-in-submenu.phtml'); ?>
            <!-- end submenu logged in -->
        <?php else: ?>
            <a href="<?php
            $ref = $this->url('lang/dashboard', [], true);
            echo $this->url('lang/auth', array(), array(
                'query' => array(
                    'ref' => urlencode($ref),
                )), true)?>">
               <!-- <span class="yk-icon yk-icon-login fa-fw"></span>--> <?= $this->translate('Login')?>
            </a>
        <?php endif ?>
    </li>
</ul>


<div id="su-select-dialog" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <strong class="modal-title"><?=$this->translate('Select the user to switch to')?>:
                <button type="button" class="close pull-right" data-dismiss="modal">
                    <span>&times;</span>
                </button></strong>
            </div>
            <div class="modal-body">
                <form id="su-form" action="<?=$this->url('lang/user-switch', [], [], true)?>" method="get" class="form-horizontal"><select id="su-user-list" name="id" class="form-control"></select></form>

                <?php $this->headScript()->captureStart() ?>
                    $('#su-form').submit(function(e) {
                    var $form = $(e.target);
                    $.get($form.attr('action'), $form.serialize(), function() { window.location.reload(); });
                    return false;
                    });

                    $('#su-user-list').select2({
                        theme: "bootstrap",
                        width: '100%',
                        minimumInputLength: 0,
                        ajax: {
                            url: basePath + '/' + lang + '/user/switch',
                            dataType: 'json',
                            delay: 200,
                            data: function(params) {
                            return { "do": "list", q: params.term, page: params.page };
                        },
                        processResults: function(data, params) {
                            params.page = params.page || 1;
                            return {
                                results: data.items,
                                pagination: {
                                    more: params.page * 20 < data.total
                                }
                            };
                            }
                        },
                        templateResult: function(data) {
                            if (data.loading) { return data.text; }
                                return data.name + (data.email ? ' <' + data.email + '>' : '') + (data.login ? ' [' + data.login + ']' : '');
                        },
                        templateSelection: function(data) {
                            if (!data.id) { return data.text; }
                                return data.login;
                        },
                        escapeMarkup: function (m) { return m; }
                    });
                <?php $this->headScript()->captureEnd() ?>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" onclick="$('#su-form').submit()"><?=$this->translate('Switch user')?></button>
                <button type="button" class="btn btn-default" data-dismiss="modal"><?=$this->translate('Cancel')?></button>
            </div>
        </div>
    </div>
</div>
