<?php
/**
 * YAWIK
 *
 * @filesource
 * @copyright (c) 2013 - 2016 Cross Solution (http://cross-solution.de)
 * @license       MIT
 */
/**
 * {{rtd: Renders paginations}}
 */

if ($this->pageCount > 1):

    //$this->headScript()->appendFile($this->basepath('/Core/js/core.pagination.js'));

    $query = $this->params()->fromQuery();

    $enableNextButton = true;
    $enablePrevButton = true;

    $currentPage = (isset($query['page']) && !is_null($query['page'])) ? $query['page'] : '1';
    ?>
    <div class="row">
        <div class="col-md-10 pagination-pages-span">
            <?php $pagesContent = '<strong>'. $currentPage . '</strong> von <strong>' . $this->pageCount . ' </strong>'; ?>
            <span class="pull-left"><?= $pagesContent ?></span>
        </div>
        <div class="col-md-2">
            <!-- First page link -->
            <ul class="pagination pull-right">
                <!-- Previous page link -->
                <?php if ($enablePrevButton): ?>
                    <?php if (isset($this->previous)): $query['page'] = $this->previous; ?>
                        <?php

                        if ($this->params()->fromRoute('isLandingPage') && !$this->params()->fromRoute('isFilteredLandingPage')) {
                            $url = $this->url("lang/landingPage", ['q' => $this->params()->fromRoute('term'), 'format' => 'html'], true);
                            if ($this->previous != 1) { $url .= '?page=' . $this->previous; }
                        } else {
                        $url = $this->url($this->route, ['lang' => $this->lang], ['query' => $query], true); }
                        ?>
                        <li class="prev-link"><a title="<?= $this->translate('Back') ?>" href="<?php echo $url ?>"><span fill="currentColor" class="pagination-previous">
<svg fill="currentColor" data-icon="caret-left" data-container-transform="translate(4 0)" viewBox="0 0 16 16" width="14px" height="14px"><path d="M12 0L4 8l8 8V0z"></path></svg></span>
                                <?php $this->headLink(array('rel' => 'prev', 'href' => $url), 'PREPEND'); ?>
                            </a></li>
                    <?php else: ?>
                        <li class="disabled" id="prev-link">
                            <a title="<?=$this->translate('Back') ?>">
                                <span fill="currentColor" class="pagination-previous">
<svg fill="currentColor" data-icon="caret-left" data-container-transform="translate(4 0)" viewBox="0 0 16 16" width="14px" height="14px"><path d="M12 0L4 8l8 8V0z"></path></svg>
                                </span>
                            </a>
                        </li>
                    <?php endif; ?>
                <?php endif;?>

                <!-- Next page link -->
                <?php if ($enableNextButton): ?>
                <?php if (isset($this->next)): $query['page'] = $this->next; ?>
                    <?php
                    if ($this->params()->fromRoute('isLandingPage') && !$this->params()->fromRoute('isFilteredLandingPage')) {
                        $url = $this->url("lang/landingPage", ['q' => $this->params()->fromRoute('term'), 'format' => 'html'], true);
                        if ($this->next != 1) { $url .= '?page=' . $this->next; }
                    } else { $url                 =
                        $this->url($this->route, array('lang' => $this->lang), array('query' => $query), true);
                    } ?>

                    <li class="next-link"><a title="<?=$this->translate('Next') ?>" href="<?php echo $url ?>"><span fill="currentColor" class="pagination-next">
<svg fill="currentColor"
data-icon="caret-right" data-container-transform="translate(4 0)" viewBox="0 0 16 16" width="14px" height="14px"><path d="M4 0v16l8-8-8-8z"></path></svg></span>

                            <?php $this->headLink(array('rel' => 'next', 'href' => $url), 'PREPEND'); ?>
                        </a></li>
                <?php else: ?>
                    <li class="disabled" id="next-link"><a title="<?=$this->translate('Next') ?>"><span fill="currentColor" class="pagination-next">
<svg fill="currentColor"
data-icon="caret-right" data-container-transform="translate(4 0)" viewBox="0 0 16 16" width="14px" height="14px"><path d="M4 0v16l8-8-8-8z"></path></svg></span>
</a></li>
                <?php endif; ?>
                <?php endif; ?>

            </ul>
        </div>
    </div>
<?php endif; ?>
