<?php
/**
 * YAWIK
 *
 * @filesource
 * @copyright (c) 2013 - 2016 Cross Solution (http://cross-solution.de)
 * @license       MIT
 */

if ($this->pageCount > 1):

    //$this->headScript()->appendFile($this->basepath('/Core/js/core.pagination.js'));

    $query = $this->params()->fromQuery();

    $currentPage = (isset($query['page']) && $query['page']>0) ? $query['page'] : '1';
    $enableNextButton = $currentPage < $this->pageCount;
    $enablePrevButton = $currentPage > 1;

    if ($this->params()->fromRoute('isLandingPage')) {
        $canonicalUri = $this->url('lang/landingPage', ['q' => $this->params()->fromRoute('term'), 'format' => 'html'], true);
        if ($currentPage > 1) { $canonicalUri .= '?page=' . $currentPage; }
        $this->headLink(array('rel' => 'canonical', 'href' => $canonicalUri), 'PREPEND');
    }
    ?>
    <div class="row">
        <div class="col-md-10 pagination-pages-span">
            <?php $pagesContent = '<strong>'. $currentPage . '</strong> von <strong>' . $this->pageCount . ' </strong>'; ?>
            <span class="pull-left"><?= $pagesContent ?></span>
        </div>
        <div class="col-md-2">
            <!-- First page link -->
            <ul class="pagination pull-right">
                <!-- Previous page link -->
                <?php if ($enablePrevButton): ?>
                        <?php

                        if ($this->params()->fromRoute('isLandingPage')) {
                            $previousUri = $this->url("lang/landingPage", ['q' => $this->params()->fromRoute('term'), 'format' => 'html'], true);
                            if ($this->previous > 1) { $previousUri .= '?page=' . $this->previous; }
                        } else {
                        $previousUri = $this->url($this->route, ['lang' => $this->lang], ['query' => $query], true); }
                        ?>
                        <li class="prev-link"><a title="<?= $this->translate('Back') ?>" href="<?php echo $previousUri ?>"><span fill="currentColor" class="pagination-previous">
<svg fill="currentColor" data-icon="caret-left" data-container-transform="translate(4 0)" viewBox="0 0 16 16" width="14px" height="14px"><path d="M12 0L4 8l8 8V0z"></path></svg></span>
                                <?php $this->headLink(array('rel' => 'prev', 'href' => $previousUri), 'PREPEND'); ?>
                            </a></li>
                    <?php else: ?>
                        <li class="disabled" id="prev-link">
                            <a title="<?=$this->translate('Back') ?>">
                                <span fill="currentColor" class="pagination-previous">
<svg fill="currentColor" data-icon="caret-left" data-container-transform="translate(4 0)" viewBox="0 0 16 16" width="14px" height="14px"><path d="M12 0L4 8l8 8V0z"></path></svg>
                                </span>
                            </a>
                        </li>
                <?php endif;?>

                <!-- Next page link -->
                <?php if ($enableNextButton): ?>
                    <?php
                    if ($this->params()->fromRoute('isLandingPage')) {
                        $nextUri = $this->url("lang/landingPage", ['q' => $this->params()->fromRoute('term'), 'format' => 'html'], true);
                        if ($this->next != 1) { $nextUri .= '?page=' . $this->next; }
                    } else { $nextUri                 =
                        $this->url($this->route, array('lang' => $this->lang), array('query' => $query), true);
                    } ?>

                    <li class="next-link"><a title="<?=$this->translate('Next') ?>" href="<?php echo $nextUri ?>"><span fill="currentColor" class="pagination-next">
<svg fill="currentColor"
data-icon="caret-right" data-container-transform="translate(4 0)" viewBox="0 0 16 16" width="14px" height="14px"><path d="M4 0v16l8-8-8-8z"></path></svg></span>

                            <?php $this->headLink(array('rel' => 'next', 'href' => $url), 'PREPEND'); ?>
                        </a></li>
                <?php else: ?>
                    <li class="disabled" id="next-link"><a title="<?=$this->translate('Next') ?>"><span fill="currentColor" class="pagination-next">
<svg fill="currentColor"
data-icon="caret-right" data-container-transform="translate(4 0)" viewBox="0 0 16 16" width="14px" height="14px"><path d="M4 0v16l8-8-8-8z"></path></svg></span>
</a></li>
                <?php endif; ?>

            </ul>
        </div>
    </div>
<?php endif; ?>
<pre>
<?php
var_dump([
    "canonical" => $canonicalUri,
    "next" => $nextUri,
    "prev" => $previousUri,
    "pageCount" => $this->pageCount,
    "currentPage" => $currentPage,
    "query" => $query,
    'previousPage' => $this->previous,
    'nextPage' => $this->next,
    ]);
?>
</pre>
