<?php
/**
 * YAWIK
 *
 * @filesource
 * @copyright (c) 2013 - 2016 Cross Solution (http://cross-solution.de)
 * @license       MIT
 */
/**
 * {{rtd: Renders paginations}}
 */

if ($this->pageCount):

    //$this->headScript()->appendFile($this->basepath('/Core/js/core.pagination.js'));

    $query = $this->params()->fromQuery();

    $enableNextButton = true;
    $enablePrevButton = true;

    ?>
    <div class="row yk-pagination">
        <div class="col-md-12">
            <!-- First page link -->
            <ul class="pagination">
                <!-- Previous page link -->
                <?php if ($enablePrevButton): ?>
                    <?php if (isset($this->previous)): $query['page'] = $this->previous; ?>
                        <?php $url = $this->url($this->route, ['lang' => $this->lang], ['query' => $query], true); ?>
                        <li><a title="<?= $this->translate('Back') ?>" href="<?php echo $url ?>"><i class="fa fa-angle-left"></i>
                                <?php $this->headLink(array('rel' => 'prev', 'href' => $url), 'PREPEND'); ?>
                            </a></li>
                    <?php else: ?>
                        <li class="disabled"><a title="<?=$this->translate('Back') ?>"><i class="fa fa-angle-left"></i></a></li>
                    <?php endif; ?>
                <?php endif;?>

                <!-- Next page link -->
                <?php if ($enableNextButton): ?>
                <?php if (isset($this->next)): $query['page'] = $this->next; ?>
                    <?php $url                 =
                        $this->url($this->route, array('lang' => $this->lang), array('query' => $query), true); ?>
                    <li><a title="<?=$this->translate('Next') ?>" href="<?php echo $url ?>"><i class="fa fa-angle-right"></i>
                            <?php $this->headLink(array('rel' => 'next', 'href' => $url), 'PREPEND'); ?>
                        </a></li>
                <?php else: ?>
                    <li class="disabled"><a title="<?=$this->translate('Next') ?>"><i class="fa fa-angle-right"></i></a></li>
                <?php endif; ?>
                <?php endif; ?>

            </ul>
        </div>
    </div>
<?php endif; ?>
