<?php
/**
 * Gastrojobs24
 *
 * General layout template file. Defines the general layout.
 *
 * @copyright (c) 2013 - 2016 Cross Solution (http://cross-solution.de)
 * @license   Gastrojobs
 */

/* @var $options \Core\Options\ModuleOptions */
$options = $this->services('Core/Options');
$languages = $options->getSupportedLanguages();
$lang = $this->params('lang');

// See: http://yawik.readthedocs.org/en/latest/modules/core/notifications.html
$notifications = $this->partial('core/notifications');

// set default page title
$this->headTitle($this->translate('Gastrojob24'))->setSeparator(' | ')->setAutoEscape(false);

// set default keywords
$this->headMeta()->setCharset("utf-8");
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0')->setAutoEscape(false);

$this->headLink()->prependStylesheet($this->basePath($this->asset('modules/Gastro24/Gastro24.css')))->setAutoEscape(false);
$this->headLink()->prependStylesheet($this->basePath('/dist/css/jquery-ui-1-12.min.css'));
$this->headLink()->prependStylesheet($this->basePath('dist/css/core.min.css'));

$savedJobsContainer = new \Zend\Session\Container('gastro24_savedjobs');
$savedJobsCount = ($savedJobsContainer->jobs) ? count($savedJobsContainer->jobs) : 0;
?>

<?php echo $this->doctype(); ?>
<html lang="<?php echo $this->params('lang') ?>">
<head>
    <link rel="icon" type="image/png" sizes="32x32" href="<?=$this->basepath('modules/Gastro24/favicons/favicon-32x32_1_.png')?>">
    <link rel="icon" type="image/png" sizes="16x16" href="<?=$this->basepath('modules/Gastro24/favicons/favicon-16x16_1_.png')?>">
    <link rel="shortcut icon" type="image/ico" href="<?=$this->basepath('modules/Gastro24/favicons/favicon_1_.ico')?>">
    <meta name="msapplication-TileColor" content="#2e5b93">
    <link rel="canonical" href="https://www.gastrojob24.ch" />
    <meta name="theme-color" content="#2e5b93"> 

    <title>Gastrojob24: Jobbörse für Gastro Jobs & Hotel Jobs</title>  
    <meta name="description" content="Gastronomie Jobbörse mit <?= $this->gastroJobCount() ?> top-aktuellen Gastro Jobs, Hotel Jobs und mehr. Jetzt Traumjob finden - auf einen Klick!">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">


    <script type="text/javascript" src="<?= $this->basepath('dist/js/core.min.js') ?>"></script>
    <script>
        var lang="<?= $this->params('lang') ?>"; var basePath="<?= $this->basePath() ?>";
    </script>
    
    <link rel="dns-prefetch" href="//fbstatic-a.akamaihd.net">
    <link rel="dns-prefetch" href="//www.facebook.com">
    <link rel="dns-prefetch" href="//connect.facebook.net">
    <link rel="dns-prefetch" href="//static.ak.facebook.com">
    <link rel="dns-prefetch" href="//static.ak.fbcdn.net">
    <link rel="dns-prefetch" href="//s-static.ak.facebook.com">
    <link rel="dns-prefetch" href="//www.google.com">
    <link rel="dns-prefetch" href="//www.googletagmanager.com">
    <link rel="dns-prefetch" href="//www.google-analytics.com">
    <?php echo $this->headLink() ?>
    <?php echo $this->headStyle() ?>  
    <!-- Google Tag Manager -->
    <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
            new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
            j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
            'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
        })(window,document,'script','dataLayer','GTM-MCDJ26Q');</script>
    <!-- End Google Tag Manager -->
<style>
           .flex-block {
          
          display:flex;
      }
  @media (max-width: 768px){
      
      .flex-block {
          
          display:block;
      }
      .homepage-links li a {
    margin: 0px 5px 5px 0px;
   
   }
     .navbar-nav {
         margin: 0;
    }
     .navbar-collapse {
         box-shadow: none!important;
    }
     .navbar-toggle {
         background-color:#fff;
    }
     .navbar-toggle .icon-bar {
         background-color: #243b84;
    }
     .navbar-toggle.collapsed .icon-bar {
         background-color: #fff;
    }
     .navbar-default {
         width: 100%;
         text-align: left;
    }
}
 .homepage-links {
     padding-left: 0;
     list-style-type: none;
}
 .homepage-links li {
     display: inline-block;
     margin: 0;

}
 .homepage-links li a {
      margin:0px 0px 5px 5px;
    background-color: #dcdfe2;
    color: #566578;
    padding: 3px 12px;
    line-height: 24px;
    display: block;
    font-size: 14px;

    text-decoration: none;
}
.hide {
    display:none!important;
}
.separator::before {
    content: "Alle Berufe anzeigen ...";
      margin: 0px 0PX 5px 5px;
    background-color: #dcdfe2;
    color: #566578;
    padding: 3px 12px;
    line-height: 24px;
    display: block;
    font-size: 14px;
    text-decoration: none;
	 cursor:pointer
}
.separator2::before {
    content: "Alle Regionen anzeigen ... ";
    margin: 0px 0PX 5px 5px;
    background-color: #dcdfe2;
    color: #566578;
    padding: 3px 12px;
    line-height: 24px;
    display: block;
    font-size: 14px;
    text-decoration: none;
	 cursor:pointer
}

div p a {
    
    text-decoration:underline;
}

.jumbotron h1 {
color: #fff;
font-size: 42px;
font-weight: 700;
margin: 0;
}
.jumbotron h2 {
color: #f2f2f2;
font-size: 24px;
font-weight: 300;
margin: 15px 0 35px 0;
}

.jumbotron h2 a {
   color: #f2f2f2;
    text-decoration:underline;
}

</style>

    
    <script type="application/ld+json">
        {
            "@context": "http://schema.org",
            "@type": "WebSite",
            "url": "https://www.gastrojob24.ch",
            "potentialAction": {
                "@type": "SearchAction",
                "target": "https://www.gastrojob24.ch/de/jobs?q={search_term_string}",
                "query-input": "required name=search_term_string"
            }
        }
    </script>


</head>
<body class="home startpage.phtml">
    <!-- Google Tag Manager (noscript) -->
    <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-MCDJ26Q" height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
    <!-- End Google Tag Manager (noscript) -->

<div id="wrapper" style="margin-bottom:100px">
    <div id="bg-full">
        <span class="bg-static"></span>
    </div>
    <header id="header" role="banner">
        <div class="container navbar">
		     <div class="row">
               <div class="navbar-header">
                <button class="navbar-toggle collapsed" data-target="#main-navigation" data-toggle="collapse" type="button">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand menu-logo" href="<?php echo $this->basepath('/' . $this->params('lang')) ?>">
                    <img src="<?php echo $this->basepath('/modules/Gastro24/gastrojob24_white.svg') ?>" alt="Gastrojob24 Schweiz" class="menu-logo">
                </a>
            </div>
            <nav id="main-navigation" class="navbar-collapse collapse navbar-collapse" role="navigation" data-saved-jobs="<?=$savedJobsCount?>">
                <?=$this->loginInfo(array('lang' => $lang ));?>
                <?= $this->navigation('Core/Navigation')
                         ->setAcl($this->services('acl'))
                         ->setRole($this->auth('role'))
                         ->menu()
                         ->setMaxDepth(0) // only show the top level entries
                         ->renderPartial(null, 'main-navigation');
                ?>
            </nav>
            <!-- /main-navigation -->
        </div>
        <?php
        /* @todo Probably, we should create a dedicated IndexController to inject this dependencies. */
        $form = $this->services('forms.Jobs/JobboardSearch');
        $form->setButtonElement('q');
        $form->setAttribute('action', $this->url('lang/jobboard', [], true));

        ?>
        <div class="row jumbotron text-center">
            <h1>Jobs für Gastrohelden</h1>
            <h2><?= $this->gastroJobCount() ?> Gastrojobs für die Schweiz verfügbar</h2>
            <nav class="navbar yk-toolbar" id="jobs-list-filter-wrapper">
                <div class="search-form-container">
                    <?=$this->searchForm($form);?>
                </div>
            </nav>
        </div>
      </div>
    </header>
</div>

<?php

$queries = $this->services(\Gastro24\Options\Landingpages::class);
$this->headTitle($this->translate('Home'));
?>

<main id="content">
    
    <?php echo $notifications?>

    <div class="container" style="max-width:950px">
        
        <h2 style="font-size: 34px;margin-bottom: 40px;margin-top:0">Jetzt Traumjob in der Gastronomie finden - auf einen Klick</h2>
        
    <div style="margin-bottom:40px">
       <p>Sie arbeiten bereits in der Gastronomie und Hotellerie oder möchten gerne in diese Branche einsteigen? Gastrojob24.ch unterstützt Arbeitnehmer bei ihrer beruflichen Veränderung mit einer riesigen Auswahl an top-aktuellen 
       Gastrostellen in der Schweiz. Arbeitgeber werden mit innovativen Services und einer grossen Reichweite bei der Suche nach Wunschkandidaten unterstützt. </p>
       <p>Wir glauben daran, dass erstklassige Online-Rekrutierung nicht teuer sein muss. Darum bietet unsere Jobbörse grossartige Funktionen zu einem vernünftigen Preis.</p>
    </div>
        
        <?php

        $tabs = [];
        $sections = [];
        $active = ' active';
        $sectionHtml = '';
        foreach ($queries->getTabs() as $tab => $sections):
            $tabSlug = strtolower(str_replace(' ', '', $tab));
            $tabs[$tabSlug] = $tab;
            $sectionHtml .= '  <div style="margin-bottom:40px"><div class="flex-block"><h3 class="h2" style="font-weight:300;color: #22436c;min-width:190px;margin-top:0">' . $tab . '</h3>';
            $active='';
            foreach ($sections as $section => $links):
                    if ($tab == 'Jobs nach Kanton') {
                   $sectionHtml .= '<ul class="homepage-links regionlist">';
                }else {
                   // $sectionHtml .= '<div class="col-md-4_x"><h3>'. $section .'</h3><ul class="homepage-links">';
                   $sectionHtml .= '<ul class="homepage-links berufe">';
                }
                foreach ($links as $spec):
                    $sectionHtml .= '<li><a title="' .
                                    $spec[1] .'" href="' .
                                    $this->url('lang/landingPage', ['q' => $spec[0], 'format' => 'html' ], true) . '">' .
                                    $spec[1] .'</a></li>';
                endforeach;
                $sectionHtml .= '</ul>';
            endforeach;
            $sectionHtml .= '</div></div>';
        endforeach;

        ?>

            <?=$sectionHtml?>
<div style="margin-bottom:40px">
     <div class="flex-block">
       <h3 class="h2" style="font-weight:300;color: #22436c;min-width:190px; margin-top:0">Top-Arbeitgeber</h3>
         <ul class="homepage-links">
             <li><a title="Jobs ZFV" href="/de/profile-zfv-Die-Gastronomiegruppe-5aa7e1d77bb2b57b5d3c03e4?clear=1">ZFV</a></li>
             <li><a title="Jobs McDonalds Schweiz" href="/de/profile-McDonald--s-Suisse-Restaurants-S%C3-rl-5bcf612fb6428b0b1008db60?clear=1">McDonalds Schweiz</a></li>
             <li><a title="Jobs Migros" href="/de/profile-Migros-5a054fa37bb2b593231413a0?clear=1">Migros</a></li>
             <li><a title="Jobs Randstad Schweiz" href="/de/profile-Randstad-Schweiz-AG-5a970fea7bb2b5a578812d52?clear=1">Randstad Schweiz</a></li>
             <li><a title="Jobs Sprüngli" href="/de/profile-Spr%C3%BCngli-58a4a59d4e197f17047b23c6?clear=1">Sprüngli</a></li>
             <li><a title="Jobs Bürgenstock Resort" href="/de/profile-B%C3%9CRGENSTOCK-HOTELS--RESORT-5bcdfda2b6428ba17c5c9048?clear=1">Bürgenstock Resort</a></li>
         </ul>
      </div>  
    </div> 


        <div class="row">
            <div class="text-center">
         
                <div class="col-md-4 text-left">
                    <h2>Google for Job Optimierung</h2>
                    <p>Ihr Inserat ist automatisch <a title="Google for Jobs" href="/de/wp/page/ratgeber-google-jobs">Google for Jobs</a> optimiert. Ausserdem erscheint Ihr Inserat automatisch im Jobmail-Newsletter.</p>

                </div>
                <div class="col-md-4 text-left">
                    <h2>Bewerbermanagement</h2>
                    <p>Umfangreiches Bewerbermanagement mit E-Mail Vorlagen für Zu- und Absagen, Job-Templates und Vielem mehr. </p>

                </div>
                <div class="col-md-4 text-left">
                    <h2>Einfach & günstig</h2>
                    <p>Unkompliziert und günstig Jobs inserieren -<br /> Bequem mit Rechnung bezahlen.</p>

                </div>
            </div>
        </div>
    </div>
</main>
<!-- /container -->
    <?php echo $this->partial("footer") ?>
    <!-- lazy loaded javascript -->
    <?php
        $langScript = 'dist/locales/' . $lang . '.js';
        echo $this->inlineScript()->setAutoEscape(false)->appendFile($this->basePath('/dist/js/jquery-ui-1-12.min.js'))
            ->appendFile($this->basePath($this->asset('modules/Gastro24/js/index-main.min.js')))
            ->appendFile($this->basePath($this->asset('modules/Gastro24/js/jobs.search.js')))
            ->appendFile($this->basePath($langScript));
        echo $this->configHeadScript()->setAutoEscape(false);
    ?>
    <!-- end lazy loaded javascript -->
    <?php echo $this->partial("piwik") ?>
    <script>
        $( document ).ready(function() {

          $('.berufe > li:nth-child(4)').after("<li class='separator' />");


            var i = 0;
              $(".berufe > li ").each(function(i, k) {
                 if(++i > 10) $(k).addClass("hide");

              });

             $(".separator").click(function() {
               $('.berufe > li').removeClass("hide");
                 $('.berufe > li.separator').addClass("hide");

             });

            $('.regionlist > li:nth-child(4)').after("<li class='separator2' />");


            var i = 0;
            $(".regionlist > li ").each(function(i, k) {
                if(++i > 15) $(k).addClass("hide");

            });

            $(".separator2").click(function() {
                $('.regionlist > li').removeClass("hide");
                $('.regionlist > li.separator2').addClass("hide");
            });
        });
    </script>
</body>
</html>
